import type { TemplateMeta } from "../types";

export const secretHerbariumTemplate: TemplateMeta = {
  slug: "secret-herbarium",
  name: "Secret Herbarium",
  category: "romantic",
  description:
    "Arsip botani cinta abad ke-19 bergaya rumah kaca kaca patri. Dilengkapi sertifikat konservatori, surat di kertas serat tumbuhan, 4 spesimen bunga floriografi kering, 3 ramuan elixir apoteker, dan 4 ikrar pemelihara kebun abadi.",
  tagline: "L'Herbier d'Amour: Koleksi Botani Abadi Kisah Cinta Kita",
  cardAccent: "border-emerald-700/40 bg-gradient-to-br from-emerald-950/20 via-stone-900 to-amber-950/20",
  highlights: [
    "Sertifikat Arsip Botani & Rumah Kaca Klasik Abad ke-19",
    "Surat Kuratorial di Atas Kertas Serat Bunga Bersegel Botani",
    "4 Spesimen Bunga Kering & Bahasa Rahasia Bunga (Floriography)",
    "3 Botol Ramuan Herbal Cinta Khas Apoteker Kuno",
    "4 Ikrar Pemeliharaan Kebun Perenial Abadi",
    "Interaksi Penyiraman Embun Terarium & Alunan Harpa Akustik",
  ],
  fields: [
    // Section 1: Registri Konservatori
    {
      name: "recipientName",
      label: "Nama Penjaga Bunga (Penerima)",
      type: "text",
      placeholder: "Clarissa Aurelia",
      required: true,
      isRecipient: true,
      section: "Registri Herbarium",
    },
    {
      name: "senderName",
      label: "Nama Botanis (Pengirim)",
      type: "text",
      placeholder: "Julian Arkananta",
      required: true,
      section: "Registri Herbarium",
    },
    {
      name: "archiveNo",
      label: "Nomor Arsip Herbarium",
      type: "text",
      placeholder: "HB-AMOUR-2024-09",
      defaultValue: "HB-AMOUR-2024-09",
      section: "Registri Herbarium",
    },
    {
      name: "conservatoryWing",
      label: "Sayap / Paviliun Rumah Kaca",
      type: "text",
      placeholder: "Pavilion des Roses & Orangerie d'Hiver",
      defaultValue: "Pavilion des Roses & Orangerie d'Hiver",
      section: "Registri Herbarium",
    },
    {
      name: "plantingDate",
      label: "Tanggal Bibit Pertama Bersemi",
      type: "text",
      placeholder: "14 September 2022",
      defaultValue: "14 September 2022",
      section: "Registri Herbarium",
    },
    {
      name: "certificateTitle",
      label: "Judul Piagam Konservatori",
      type: "text",
      placeholder: "Arsip Botani Cinta Abadi",
      defaultValue: "Arsip Botani Cinta Abadi",
      section: "Registri Herbarium",
    },
    {
      name: "registryNotes",
      label: "Catatan Kurator Konservatori",
      type: "textarea",
      placeholder: "Catatan resmi arsip botani...",
      defaultValue:
        "Telah diklasifikasikan sebagai spesies cinta perenial yang langka dan berharga, dipelihara dengan ketulusan hati dan perlindungan tanpa henti.",
      rows: 2,
      section: "Registri Herbarium",
    },

    // Section 2: Surat Kuratorial Tumbuhan
    {
      name: "salutation",
      label: "Salam Pembuka",
      type: "text",
      placeholder: "Untuk Penjaga Hatiku yang Terindah,",
      defaultValue: "Untuk Penjaga Hatiku yang Terindah,",
      section: "Surat Botanis",
    },
    {
      name: "message",
      label: "Isi Surat Botanis (Pesan Cinta)",
      type: "textarea",
      placeholder: "Tuliskan surat cinta terdalammu...",
      rows: 6,
      required: true,
      defaultValue:
        "Jika seluruh semesta adalah belantara luas, pertemuan kita adalah benih kecil yang jatuh di tanah paling subur. Setiap hari bersamamu terasa seperti embun pagi yang menyegarkan dedaunan yang sempat layu.\n\nAku belajar bahwa mencintaimu bukanlah tentang bunga yang selalu bermekaran tanpa musim gugur, melainkan tentang kesediaan dua pasang tangan untuk tetap menyiram, menjaga akar, dan melindungi kuncup dari badai yang dingin.\n\nDi dalam lembaran herbarium ini, kuabadikan setiap aroma tawa, keheningan hangat di malam larut, dan janji bahwa perasaanku padamu akan selalu menjadi tanaman perenial—tumbuh lebih hijau dan harum seiring berjalannya waktu.",
      section: "Surat Botanis",
    },
    {
      name: "signoff",
      label: "Salam Penutup",
      type: "text",
      placeholder: "Dengan segenap kehangatan kelopak mekar,",
      defaultValue: "Dengan segenap kehangatan kelopak mekar,",
      section: "Surat Botanis",
    },
    {
      name: "sealInitials",
      label: "Inisial Segel Lilin Botani",
      type: "text",
      placeholder: "J & C",
      defaultValue: "J & C",
      maxLength: 10,
      section: "Surat Botanis",
    },

    // Section 3: 4 Spesimen Floriografi
    {
      name: "specimen1_name",
      label: "Spesimen 1: Nama Binomial (Latin)",
      type: "text",
      defaultValue: "Rosa Aeterna",
      section: "Spesimen Botani",
    },
    {
      name: "specimen1_common",
      label: "Spesimen 1: Nama Populer / Gelar Bunga",
      type: "text",
      defaultValue: "The Awakening Rose",
      section: "Spesimen Botani",
    },
    {
      name: "specimen1_floriography",
      label: "Spesimen 1: Makna Floriografi (Bahasa Bunga)",
      type: "text",
      defaultValue: "Kagum yang bersemi perlahan namun mengakar kuat",
      section: "Spesimen Botani",
    },
    {
      name: "specimen1_location",
      label: "Spesimen 1: Lokasi Temuan",
      type: "text",
      defaultValue: "Sudut Kedai Kopi di Bawah Gerimis Senja",
      section: "Spesimen Botani",
    },
    {
      name: "specimen1_date",
      label: "Spesimen 1: Tanggal Penyerbukan / Temu",
      type: "text",
      defaultValue: "14 September 2022",
      section: "Spesimen Botani",
    },
    {
      name: "specimen1_story",
      label: "Spesimen 1: Catatan Kenangan Spesimen",
      type: "textarea",
      defaultValue:
        "Pertama kali matamu menatapku di balik cangkir teh hangat, seluruh kebisingan kota mereda seketika. Mawar pertama yang mekar di dadaku.",
      rows: 2,
      section: "Spesimen Botani",
    },

    {
      name: "specimen2_name",
      label: "Spesimen 2: Nama Binomial (Latin)",
      type: "text",
      defaultValue: "Myosotis Amoris",
      section: "Spesimen Botani",
    },
    {
      name: "specimen2_common",
      label: "Spesimen 2: Nama Populer / Gelar Bunga",
      type: "text",
      defaultValue: "Forget-Me-Not of Whispers",
      section: "Spesimen Botani",
    },
    {
      name: "specimen2_floriography",
      label: "Spesimen 2: Makna Floriografi (Bahasa Bunga)",
      type: "text",
      defaultValue: "Kenangan manis larut malam yang abadi di ingatan",
      section: "Spesimen Botani",
    },
    {
      name: "specimen2_location",
      label: "Spesimen 2: Lokasi Temuan",
      type: "text",
      defaultValue: "Balkon Apartemen Menatap Lampu-Lampu Kota",
      section: "Spesimen Botani",
    },
    {
      name: "specimen2_date",
      label: "Spesimen 2: Tanggal Penyerbukan / Temu",
      type: "text",
      defaultValue: "03 Desember 2022",
      section: "Spesimen Botani",
    },
    {
      name: "specimen2_story",
      label: "Spesimen 2: Catatan Kenangan Spesimen",
      type: "textarea",
      defaultValue:
        "Obrolan panjang hingga pukul tiga dini hari tentang ketakutan terdalam dan mimpi masa kecil. Di situlah aku tahu jiwamu adalah rumahku.",
      rows: 2,
      section: "Spesimen Botani",
    },

    {
      name: "specimen3_name",
      label: "Spesimen 3: Nama Binomial (Latin)",
      type: "text",
      defaultValue: "Lavandula Serenitatis",
      section: "Spesimen Botani",
    },
    {
      name: "specimen3_common",
      label: "Spesimen 3: Nama Populer / Gelar Bunga",
      type: "text",
      defaultValue: "The Calming Lavender",
      section: "Spesimen Botani",
    },
    {
      name: "specimen3_floriography",
      label: "Spesimen 3: Makna Floriografi (Bahasa Bunga)",
      type: "text",
      defaultValue: "Ketenangan jiwa dan perlindungan di tengah badai",
      section: "Spesimen Botani",
    },
    {
      name: "specimen3_location",
      label: "Spesimen 3: Lokasi Temuan",
      type: "text",
      defaultValue: "Perjalanan Pulang Saat Hari Paling Melelahkan",
      section: "Spesimen Botani",
    },
    {
      name: "specimen3_date",
      label: "Spesimen 3: Tanggal Penyerbukan / Temu",
      type: "text",
      defaultValue: "19 Juni 2023",
      section: "Spesimen Botani",
    },
    {
      name: "specimen3_story",
      label: "Spesimen 3: Catatan Kenangan Spesimen",
      type: "textarea",
      defaultValue:
        "Saat hari-hari terasa berat dan dunia menuntut terlalu banyak, genggaman tanganmu adalah aroma lavender yang menentramkan seluruh badai batinku.",
      rows: 2,
      section: "Spesimen Botani",
    },

    {
      name: "specimen4_name",
      label: "Spesimen 4: Nama Binomial (Latin)",
      type: "text",
      defaultValue: "Jasminum Perpetuum",
      section: "Spesimen Botani",
    },
    {
      name: "specimen4_common",
      label: "Spesimen 4: Nama Populer / Gelar Bunga",
      type: "text",
      defaultValue: "The Everlasting Jasmine",
      section: "Spesimen Botani",
    },
    {
      name: "specimen4_floriography",
      label: "Spesimen 4: Makna Floriografi (Bahasa Bunga)",
      type: "text",
      defaultValue: "Keharuman ketulusan dan komitmen tanpa syarat",
      section: "Spesimen Botani",
    },
    {
      name: "specimen4_location",
      label: "Spesimen 4: Lokasi Temuan",
      type: "text",
      defaultValue: "Dermaga Tepi Danau di Bawah Langit Berbintang",
      section: "Spesimen Botani",
    },
    {
      name: "specimen4_date",
      label: "Spesimen 4: Tanggal Penyerbukan / Temu",
      type: "text",
      defaultValue: "14 Februari 2024",
      section: "Spesimen Botani",
    },
    {
      name: "specimen4_story",
      label: "Spesimen 4: Catatan Kenangan Spesimen",
      type: "textarea",
      defaultValue:
        "Janji sunyi yang kita ucapkan tanpa banyak kata: melangkah berdua, merawat hari esok, dan tetap saling memilih di setiap helaan napas.",
      rows: 2,
      section: "Spesimen Botani",
    },

    // Section 4: 3 Ramuan Apoteker Romantis
    {
      name: "elixir1_title",
      label: "Elixir 1: Nama Ramuan Apoteker",
      type: "text",
      defaultValue: "Tincture of Midnight Solace",
      section: "Apoteker Herbal",
    },
    {
      name: "elixir1_aroma",
      label: "Elixir 1: Catatan Aroma",
      type: "text",
      defaultValue: "Kelopak chamomile kering, uap teh madu, dan hembusan angin malam",
      section: "Apoteker Herbal",
    },
    {
      name: "elixir1_ingredients",
      label: "Elixir 1: Komposisi Bahan Cinta",
      type: "text",
      defaultValue: "70% pelukan hening tanpa penghakiman, 30% tatapan teduh penenang cemas",
      section: "Apoteker Herbal",
    },
    {
      name: "elixir1_effect",
      label: "Elixir 1: Khasiat untuk Hati",
      type: "text",
      defaultValue: "Menguraikan ketegangan batin dan menyelimuti hati dengan rasa aman mutlak",
      section: "Apoteker Herbal",
    },

    {
      name: "elixir2_title",
      label: "Elixir 2: Nama Ramuan Apoteker",
      type: "text",
      defaultValue: "Cordial of Pure Laughter",
      section: "Apoteker Herbal",
    },
    {
      name: "elixir2_aroma",
      label: "Elixir 2: Catatan Aroma",
      type: "text",
      defaultValue: "Kulit jeruk bergamot segar, sinar matahari sore, dan remah pastry manis",
      section: "Apoteker Herbal",
    },
    {
      name: "elixir2_ingredients",
      label: "Elixir 2: Komposisi Bahan Cinta",
      type: "text",
      defaultValue: "Gurauan spontan yang absurd, tawa terpingkal-pingkal di dalam mobil",
      section: "Apoteker Herbal",
    },
    {
      name: "elixir2_effect",
      label: "Elixir 2: Khasiat untuk Hati",
      type: "text",
      defaultValue: "Seketika menerangi hari-hari kelabu dengan kegembiraan yang tulus dan menular",
      section: "Apoteker Herbal",
    },

    {
      name: "elixir3_title",
      label: "Elixir 3: Nama Ramuan Apoteker",
      type: "text",
      defaultValue: "Essence of Unwavering Devotion",
      section: "Apoteker Herbal",
    },
    {
      name: "elixir3_aroma",
      label: "Elixir 3: Catatan Aroma",
      type: "text",
      defaultValue: "Kayu cendana hangat, getah pinus perenial, dan kelopak melati suci",
      section: "Apoteker Herbal",
    },
    {
      name: "elixir3_ingredients",
      label: "Elixir 3: Komposisi Bahan Cinta",
      type: "text",
      defaultValue: "Kejujuran tanpa topeng, kesabaran melewati masa sulit, komitmen setiap fajar",
      section: "Apoteker Herbal",
    },
    {
      name: "elixir3_effect",
      label: "Elixir 3: Khasiat untuk Hati",
      type: "text",
      defaultValue: "Membentuk perlindungan abadi dari dinginnya dunia luar dan memperdalam akar kasih",
      section: "Apoteker Herbal",
    },

    // Section 5: 4 Ikrar Kebun Abadi
    {
      name: "vow1_title",
      label: "Ikrar 1: Judul",
      type: "text",
      defaultValue: "Nurturing the Roots (Merawat Akar)",
      section: "Ikrar Kebun Abadi",
    },
    {
      name: "vow1_desc",
      label: "Ikrar 1: Kalimat Janji",
      type: "textarea",
      defaultValue: "Aku berjanji merawat fondasi kejujuran dan rasa saling percaya kita setiap hari, memastikan akar cinta kita tetap terhidrasi kehangatan.",
      rows: 2,
      section: "Ikrar Kebun Abadi",
    },
    {
      name: "vow2_title",
      label: "Ikrar 2: Judul",
      type: "text",
      defaultValue: "Pruning the Doubts (Memangkas Keraguan)",
      section: "Ikrar Kebun Abadi",
    },
    {
      name: "vow2_desc",
      label: "Ikrar 2: Kalimat Janji",
      type: "textarea",
      defaultValue: "Aku berjanji segera memangkas praduga dan prasangka buruk lewat dialog lembut, tak membiarkan duri kesalahpahaman melukai ranting kasih kita.",
      rows: 2,
      section: "Ikrar Kebun Abadi",
    },
    {
      name: "vow3_title",
      label: "Ikrar 3: Judul",
      type: "text",
      defaultValue: "Sheltering the Bloom (Melindungi Mekar)",
      section: "Ikrar Kebun Abadi",
    },
    {
      name: "vow3_desc",
      label: "Ikrar 3: Kalimat Janji",
      type: "textarea",
      defaultValue: "Aku berjanji menjadi atap kaca yang kokoh di tengah terpaan hujan deras dan embun beku, agar senyummu tetap terjaga hangat.",
      rows: 2,
      section: "Ikrar Kebun Abadi",
    },
    {
      name: "vow4_title",
      label: "Ikrar 4: Judul",
      type: "text",
      defaultValue: "Perennial Bloom (Mekar Abadi)",
      section: "Ikrar Kebun Abadi",
    },
    {
      name: "vow4_desc",
      label: "Ikrar 4: Kalimat Janji",
      type: "textarea",
      defaultValue: "Aku berjanji terus memilihmu, jatuh cinta lagi dan lagi, mekar bersama melintasi setiap musim kehidupan hingga akhir masa.",
      rows: 2,
      section: "Ikrar Kebun Abadi",
    },

    // Warna & Audio
    {
      name: "primaryColor",
      label: "Warna Dominan Konservatori",
      type: "color",
      defaultValue: "#1a382b",
      colorPresets: [
        { label: "Deep Forest Evergreen", value: "#1a382b" },
        { label: "Botanical Olive", value: "#2c3e2d" },
        { label: "Vintage Amber Herb", value: "#3a2c1f" },
        { label: "Midnight Fern", value: "#142c22" },
      ],
      section: "Palet Warna & Audio",
    },
    {
      name: "secondaryColor",
      label: "Warna Aksen Emas Botani",
      type: "color",
      defaultValue: "#c59b58",
      colorPresets: [
        { label: "Antique Botanical Gold", value: "#c59b58" },
        { label: "Warm Brass Leaf", value: "#d4af37" },
        { label: "Dried Copper Petal", value: "#b87333" },
      ],
      section: "Palet Warna & Audio",
    },
    {
      name: "accentColor",
      label: "Warna Aksen Bunga Kering",
      type: "color",
      defaultValue: "#9b435a",
      colorPresets: [
        { label: "Pressed Rose Burgundy", value: "#9b435a" },
        { label: "Lavender Dusk", value: "#6e5d84" },
        { label: "Wild Poppy Crimson", value: "#a83232" },
      ],
      section: "Palet Warna & Audio",
    },
    {
      name: "audioUrl",
      label: "URL Musik Latar (Harpa & Hujan)",
      type: "text",
      placeholder: "https://example.com/botanical-acoustic.mp3",
      defaultValue: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=acoustic-guitars-ambient-112318.mp3",
      helperText: "Format MP3 publik. Otomatis dimatikan di katalog template.",
      section: "Palet Warna & Audio",
    },
  ],
  sample: {
    recipientName: "Clarissa Aurelia",
    senderName: "Julian Arkananta",
    archiveNo: "HB-AMOUR-2024-09",
    conservatoryWing: "Pavilion des Roses & Orangerie d'Hiver",
    plantingDate: "14 September 2022",
    certificateTitle: "Arsip Botani Cinta Abadi",
    registryNotes:
      "Telah diklasifikasikan sebagai spesies cinta perenial yang langka dan berharga, dipelihara dengan ketulusan hati dan perlindungan tanpa henti di bawah naungan kaca konservatori abadi.",
    salutation: "Untuk Penjaga Hatiku yang Terindah,",
    message:
      "Jika seluruh semesta adalah belantara luas, pertemuan kita adalah benih kecil yang jatuh di tanah paling subur. Setiap hari bersamamu terasa seperti embun pagi yang menyegarkan dedaunan yang sempat layu.\n\nAku belajar bahwa mencintaimu bukanlah tentang bunga yang selalu bermekaran tanpa musim gugur, melainkan tentang kesediaan dua pasang tangan untuk tetap menyiram, menjaga akar, dan melindungi kuncup dari badai yang dingin.\n\nDi dalam lembaran herbarium ini, kuabadikan setiap aroma tawa, keheningan hangat di malam larut, dan janji bahwa perasaanku padamu akan selalu menjadi tanaman perenial—tumbuh lebih hijau dan harum seiring berjalannya waktu.",
    signoff: "Dengan segenap kehangatan kelopak mekar,",
    sealInitials: "J & C",

    specimen1_name: "Rosa Aeterna",
    specimen1_common: "The Awakening Rose",
    specimen1_floriography: "Kagum yang bersemi perlahan namun mengakar kuat",
    specimen1_location: "Sudut Kedai Kopi di Bawah Gerimis Senja",
    specimen1_date: "14 September 2022",
    specimen1_story:
      "Pertama kali matamu menatapku di balik cangkir teh hangat, seluruh kebisingan kota mereda seketika. Mawar pertama yang mekar di dadaku.",

    specimen2_name: "Myosotis Amoris",
    specimen2_common: "Forget-Me-Not of Whispers",
    specimen2_floriography: "Kenangan manis larut malam yang abadi di ingatan",
    specimen2_location: "Balkon Apartemen Menatap Lampu-Lampu Kota",
    specimen2_date: "03 Desember 2022",
    specimen2_story:
      "Obrolan panjang hingga pukul tiga dini hari tentang ketakutan terdalam dan mimpi masa kecil. Di situlah aku tahu jiwamu adalah rumahku.",

    specimen3_name: "Lavandula Serenitatis",
    specimen3_common: "The Calming Lavender",
    specimen3_floriography: "Ketenangan jiwa dan perlindungan di tengah badai",
    specimen3_location: "Perjalanan Pulang Saat Hari Paling Melelahkan",
    specimen3_date: "19 Juni 2023",
    specimen3_story:
      "Saat hari-hari terasa berat dan dunia menuntut terlalu banyak, genggaman tanganmu adalah aroma lavender yang menentramkan seluruh badai batinku.",

    specimen4_name: "Jasminum Perpetuum",
    specimen4_common: "The Everlasting Jasmine",
    specimen4_floriography: "Keharuman ketulusan dan komitmen tanpa syarat",
    specimen4_location: "Dermaga Tepi Danau di Bawah Langit Berbintang",
    specimen4_date: "14 Februari 2024",
    specimen4_story:
      "Janji sunyi yang kita ucapkan tanpa banyak kata: melangkah berdua, merawat hari esok, dan tetap saling memilih di setiap helaan napas.",

    elixir1_title: "Tincture of Midnight Solace",
    elixir1_aroma: "Kelopak chamomile kering, uap teh madu, dan hembusan angin malam",
    elixir1_ingredients: "70% pelukan hening tanpa penghakiman, 30% tatapan teduh penenang cemas",
    elixir1_effect: "Menguraikan ketegangan batin dan menyelimuti hati dengan rasa aman mutlak",

    elixir2_title: "Cordial of Pure Laughter",
    elixir2_aroma: "Kulit jeruk bergamot segar, sinar matahari sore, dan remah pastry manis",
    elixir2_ingredients: "Gurauan spontan yang absurd, tawa terpingkal-pingkal di dalam mobil",
    elixir2_effect: "Seketika menerangi hari-hari kelabu dengan kegembiraan yang tulus dan menular",

    elixir3_title: "Essence of Unwavering Devotion",
    elixir3_aroma: "Kayu cendana hangat, getah pinus perenial, dan kelopak melati suci",
    elixir3_ingredients: "Kejujuran tanpa topeng, kesabaran melewati masa sulit, komitmen setiap fajar",
    elixir3_effect: "Membentuk perlindungan abadi dari dinginnya dunia luar dan memperdalam akar kasih",

    vow1_title: "Nurturing the Roots (Merawat Akar)",
    vow1_desc:
      "Aku berjanji merawat fondasi kejujuran dan rasa saling percaya kita setiap hari, memastikan akar cinta kita tetap terhidrasi kehangatan.",
    vow2_title: "Pruning the Doubts (Memangkas Keraguan)",
    vow2_desc:
      "Aku berjanji segera memangkas praduga dan prasangka buruk lewat dialog lembut, tak membiarkan duri kesalahpahaman melukai ranting kasih kita.",
    vow3_title: "Sheltering the Bloom (Melindungi Mekar)",
    vow3_desc:
      "Aku berjanji menjadi atap kaca yang kokoh di tengah terpaan hujan deras dan embun beku, agar senyummu tetap terjaga hangat.",
    vow4_title: "Perennial Bloom (Mekar Abadi)",
    vow4_desc:
      "Aku berjanji terus memilihmu, jatuh cinta lagi dan lagi, mekar bersama melintasi setiap musim kehidupan hingga akhir masa.",

    primaryColor: "#1a382b",
    secondaryColor: "#c59b58",
    accentColor: "#9b435a",
    audioUrl:
      "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=acoustic-guitars-ambient-112318.mp3",
  },
};
