import type { TemplateMeta } from "../types";
import {
  BIRTHDAY_COLOR_PRESETS,
  BACKGROUND_COLOR_PRESETS,
  CARD_COLOR_PRESETS,
  TEXT_COLOR_PRESETS,
} from "../color-presets";

export const ultimateBirthdayTemplate: TemplateMeta = {
  slug: "ultimate-birthday",
  name: "Ultimate Joyful Birthday",
  category: "Perayaan",
  tagline: "Template perayaan ulang tahun ceria dengan animasi meriah, fitur interaktif, dan penuh keceriaan.",
  description:
    "Merayakan ulang tahun dengan penuh warna, keceriaan, dan animasi yang memukau. Dilengkapi dengan latar belakang animasi balon melayang, foto interaktif, statistik perjalanan usia, kue tiup lilin, dan memori tak terlupakan.",
  cardAccent: "bg-pink-50 text-pink-700 ring-1 ring-pink-300",
  highlights: [
    "Animasi ambient ceria: Bintang & balon melayang",
    "Hero interaktif dengan lencana usia",
    "Statistik usia & pencapaian (Fun Facts)",
    "4 Sifat terbaik yang sangat disayangi",
    "Kue bolu interaktif dengan efek tiup lilin memukau",
    "Jejak perjalanan usia (Timeline milestones)",
    "Galeri foto gaya polaroid dengan efek tilt",
    "Grid harapan terbaik & kutipan menyentuh",
  ],
  fields: [
    { name: "recipientName", label: "Nama Penerima", type: "text", required: true, section: "hero", isRecipient: true },
    { name: "senderName", label: "Nama Pengirim", type: "text", required: true, section: "hero" },
    { name: "age", label: "Usia", type: "number", required: true, section: "hero" },
    { name: "greeting", label: "Sapaan", type: "text", section: "hero" },
    { name: "heroBadge", label: "Lencana / Badge", type: "text", section: "hero" },
    { name: "title", label: "Judul", type: "text", required: true, section: "hero" },
    { name: "tagline", label: "Tagline", type: "textarea", section: "hero" },
    { name: "heroImage", label: "Foto Utama", type: "text", section: "hero" },

    { name: "messageTitle", label: "Judul Surat", type: "text", section: "letter" },
    { name: "message", label: "Isi Surat", type: "textarea", required: true, section: "letter" },
    
    { name: "qualityTitle", label: "Judul Kualitas Diri", type: "text", section: "story" },
    { name: "quality1", label: "Kualitas 1", type: "text", section: "story" },
    { name: "quality1Desc", label: "Deskripsi Kualitas 1", type: "text", section: "story" },
    { name: "quality2", label: "Kualitas 2", type: "text", section: "story" },
    { name: "quality2Desc", label: "Deskripsi Kualitas 2", type: "text", section: "story" },
    { name: "quality3", label: "Kualitas 3", type: "text", section: "story" },
    { name: "quality3Desc", label: "Deskripsi Kualitas 3", type: "text", section: "story" },
    { name: "quality4", label: "Kualitas 4", type: "text", section: "story" },
    { name: "quality4Desc", label: "Deskripsi Kualitas 4", type: "text", section: "story" },

    { name: "milestoneTitle", label: "Judul Milestones", type: "text", section: "milestone" },
    { name: "milestone1Year", label: "Tahun 1", type: "text", section: "milestone" },
    { name: "milestone1Title", label: "Judul 1", type: "text", section: "milestone" },
    { name: "milestone1Desc", label: "Cerita 1", type: "textarea", section: "milestone" },
    { name: "milestone2Year", label: "Tahun 2", type: "text", section: "milestone" },
    { name: "milestone2Title", label: "Judul 2", type: "text", section: "milestone" },
    { name: "milestone2Desc", label: "Cerita 2", type: "textarea", section: "milestone" },
    { name: "milestone3Year", label: "Tahun 3", type: "text", section: "milestone" },
    { name: "milestone3Title", label: "Judul 3", type: "text", section: "milestone" },
    { name: "milestone3Desc", label: "Cerita 3", type: "textarea", section: "milestone" },
    { name: "milestone4Year", label: "Tahun 4", type: "text", section: "milestone" },
    { name: "milestone4Title", label: "Judul 4", type: "text", section: "milestone" },
    { name: "milestone4Desc", label: "Cerita 4", type: "textarea", section: "milestone" },

    { name: "cakeTitle", label: "Judul Kue", type: "text", section: "cake" },
    { name: "cakeWishPrompt", label: "Panduan Tiup Lilin", type: "text", section: "cake" },
    { name: "secretWishMessage", label: "Pesan Kejutan", type: "textarea", section: "cake" },

    { name: "galleryTitle", label: "Judul Galeri", type: "text", section: "gallery" },
    { name: "gallerySubtitle", label: "Subjudul Galeri", type: "text", section: "gallery" },
    { name: "galleryImg1", label: "Foto 1", type: "text", section: "gallery" },
    { name: "galleryCaption1", label: "Keterangan 1", type: "text", section: "gallery" },
    { name: "galleryImg2", label: "Foto 2", type: "text", section: "gallery" },
    { name: "galleryCaption2", label: "Keterangan 2", type: "text", section: "gallery" },
    { name: "galleryImg3", label: "Foto 3", type: "text", section: "gallery" },
    { name: "galleryCaption3", label: "Keterangan 3", type: "text", section: "gallery" },
    { name: "galleryImg4", label: "Foto 4", type: "text", section: "gallery" },
    { name: "galleryCaption4", label: "Keterangan 4", type: "text", section: "gallery" },
    { name: "galleryImg5", label: "Foto 5", type: "text", section: "gallery" },
    { name: "galleryCaption5", label: "Keterangan 5", type: "text", section: "gallery" },
    { name: "galleryImg6", label: "Foto 6", type: "text", section: "gallery" },
    { name: "galleryCaption6", label: "Keterangan 6", type: "text", section: "gallery" },

    { name: "wishesTitle", label: "Judul Doa", type: "text", section: "wishes" },
    { name: "wish1", label: "Doa 1", type: "text", section: "wishes" },
    { name: "wish2", label: "Doa 2", type: "text", section: "wishes" },
    { name: "wish3", label: "Doa 3", type: "text", section: "wishes" },
    { name: "wish4", label: "Doa 4", type: "text", section: "wishes" },

    { name: "quote", label: "Kutipan Penutup", type: "text", section: "letter" },
    { name: "signature", label: "Tanda Tangan", type: "text", section: "letter" },
    { name: "musicTitle", label: "Judul Musik", type: "text", section: "theme" },
    { name: "bgMusicUrl", label: "URL Musik", type: "text", section: "theme" },

    { name: "primaryColor", label: "Warna Utama", type: "color", colorPresets: BIRTHDAY_COLOR_PRESETS, section: "theme" },
    { name: "backgroundColor", label: "Warna Latar", type: "color", colorPresets: BACKGROUND_COLOR_PRESETS, section: "theme" },
    { name: "cardColor", label: "Warna Kartu", type: "color", colorPresets: CARD_COLOR_PRESETS, section: "theme" },
    { name: "textColor", label: "Warna Teks Judul", type: "color", colorPresets: TEXT_COLOR_PRESETS, section: "theme" },
    { name: "bodyTextColor", label: "Warna Teks Isi", type: "color", colorPresets: TEXT_COLOR_PRESETS, section: "theme" },
  ],
  sample: {
    primaryColor: "#FF5E7E",
    backgroundColor: "#FFF5F7",
    cardColor: "#FFFFFF",
    textColor: "#2D3748",
    bodyTextColor: "#4A5568",
    recipientName: "Dinda Anandita",
    senderName: "Keluarga & Sahabat",
    age: 24,
    greeting: "Selamat Ulang Tahun! 🎉",
    heroBadge: "✨ Hari Paling Spesial di Tahun Ini",
    title: "Merayakan Hari Kelahiranmu",
    tagline: "Hari ini semesta ikut bersukacita merayakan bertambahnya usiamu. Terima kasih telah menjadi sosok yang luar biasa bagi kami semua.",
    heroImage: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1000&q=80",
    messageTitle: "Surat Kecil Untukmu",
    message: "Selamat ulang tahun! Di hari yang sangat istimewa ini, kami ingin mengungkapkan betapa berharganya dirimu bagi kami. Kamu selalu bisa membuat suasana menjadi lebih ceria dan hangat.\n\nSemoga di usia yang baru ini, kamu semakin dewasa, semakin bijaksana, dan segala yang kamu cita-citakan dapat segera tercapai.",
    qualityTitle: "Alasan Kami Menyayangimu",
    quality1: "Senyum Manismu",
    quality1Desc: "Selalu bisa menularkan energi positif.",
    quality2: "Hati yang Tulus",
    quality2Desc: "Pendengar yang baik dan selalu peduli.",
    quality3: "Ketangguhanmu",
    quality3Desc: "Tidak pernah menyerah.",
    quality4: "Keceriaanmu",
    quality4Desc: "Membawa tawa di setiap suasana.",
    milestoneTitle: "Perjalanan Luar Biasamu",
    milestone1Year: "Masa Kecil",
    milestone1Title: "Awal yang Ceria",
    milestone1Desc: "Membawa kebahagiaan.",
    milestone2Year: "Remaja",
    milestone2Title: "Mencari Jati Diri",
    milestone2Desc: "Semakin semangat.",
    milestone3Year: "Dewasa Muda",
    milestone3Title: "Mengejar Mimpi",
    milestone3Desc: "Berani ambil langkah.",
    milestone4Year: "Sekarang",
    milestone4Title: "Semakin Bersinar",
    milestone4Desc: "Inspiratif.",
    cakeTitle: "Tiup Lilin Impianmu!",
    cakeWishPrompt: "Ucapkan doa terbaikmu dalam hati, lalu tiup lilinnya!",
    secretWishMessage: "Semoga tahun ini membawa banyak kejutan indah!",
    galleryTitle: "Memori Indah Kita",
    gallerySubtitle: "Setiap momen bersamamu adalah kenangan berharga.",
    galleryImg1: "https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=800&q=80",
    galleryCaption1: "Pesta Kejutan",
    galleryImg2: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=800&q=80",
    galleryCaption2: "Liburan",
    galleryImg3: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80",
    galleryCaption3: "Kue Manis",
    galleryImg4: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=800&q=80",
    galleryCaption4: "Tawa Bersama",
    galleryImg5: "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=800&q=80",
    galleryCaption5: "Senja Santai",
    galleryImg6: "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?auto=format&fit=crop&w=800&q=80",
    galleryCaption6: "Malam Syukuran",
    wishesTitle: "Doa & Harapan Kami",
    wish1: "Kesehatan yang sempurna dan umur panjang.",
    wish2: "Kesuksesan luar biasa.",
    wish3: "Kebahagiaan yang melimpah.",
    wish4: "Cinta dan kasih sayang tiada henti.",
    quote: "Count your age by friends, not years.",
    signature: "Keluarga & Sahabat",
    bgMusicUrl: "",
    musicTitle: "Happy Birthday Melody",
  }
};
