import type { TemplateMeta } from "../types";
import {
  WEDDING_COLOR_PRESETS,
  BACKGROUND_COLOR_PRESETS,
  CARD_COLOR_PRESETS,
  TEXT_COLOR_PRESETS,
} from "../color-presets";

export const weddingTemplate: TemplateMeta = {
  slug: "wedding",
  name: "Royal Wedding Invitation",
  category: "Undangan",
  tagline:
    "Undangan pernikahan digital eksklusif dengan nama tamu kustom via URL (?to=Nama), hitung mundur, audio, dan amplop digital.",
  description:
    "Solusi undangan pernikahan digital modern dan elegan. Mendukung kustomisasi nama tamu personal lewat query URL (?to=NamaTamu), cover amplop pembuka interaktif, pemutar musik romantis latar, hitung mundur hari H, navigasi Google Maps, galeri foto, kisah cinta, dan amplop digital.",
  cardAccent: "bg-amber-50 text-amber-800 ring-1 ring-amber-300",
  highlights: [
    "Dukungan nama tamu undangan kustom via URL (?to=NamaTamu)",
    "Cover amplop digital interaktif dengan pembuka surat & musik latar",
    "Countdown timer realtime menuju hari bahagia",
    "Profil mempelai pria & wanita beserta informasi keluarga",
    "Detail akad nikah & resepsi lengkap dengan Google Maps",
    "Amplop digital & nomor rekening hadiah dengan tombol salin 1-klik",
    "Alat generator tautan & pesan WhatsApp khusus per tamu",
  ],
  fields: [
    // --- SECTION: COVER & INFORMASI UTAMA ---
    {
      name: "recipientName",
      label: "Nama tamu undangan default",
      type: "text",
      placeholder: "Bapak / Ibu / Saudara/i",
      helperText: "Dipakai jika undangan dibuka tanpa parameter query URL (?to=Nama).",
      required: true,
      maxLength: 100,
      isRecipient: true,
      section: "hero",
    },
    {
      name: "weddingTitle",
      label: "Judul cover undangan",
      type: "text",
      placeholder: "The Wedding of Dimas & Annisa",
      required: true,
      maxLength: 120,
      section: "hero",
    },
    {
      name: "groomNickname",
      label: "Nama panggilan mempelai pria",
      type: "text",
      placeholder: "Dimas",
      required: true,
      maxLength: 40,
      section: "hero",
    },
    {
      name: "brideNickname",
      label: "Nama panggilan mempelai wanita",
      type: "text",
      placeholder: "Annisa",
      required: true,
      maxLength: 40,
      section: "hero",
    },
    {
      name: "weddingDate",
      label: "Tanggal pernikahan (untuk countdown)",
      type: "date",
      helperText: "Format YYYY-MM-DD untuk menghitung otomatis sisa waktu hari H.",
      required: true,
      section: "hero",
    },
    {
      name: "heroImage",
      label: "Foto cover utama (URL)",
      type: "text",
      placeholder: "https://images.unsplash.com/photo-1519741497674-611481863552",
      maxLength: 1000,
      section: "hero",
    },
    {
      name: "weddingQuote",
      label: "Kutipan ayat suci atau kata mutiara",
      type: "textarea",
      placeholder:
        "Dan di antara tanda-tanda kekuasaan-Nya ialah Dia menciptakan untukmu isteri-isteri dari jenismu sendiri, supaya kamu cenderung dan merasa tenteram kepadanya, dan dijadikan-Nya di antaramu rasa kasih dan sayang.",
      maxLength: 500,
      rows: 3,
      section: "hero",
    },
    {
      name: "quoteSource",
      label: "Sumber kutipan",
      type: "text",
      placeholder: "QS. Ar-Rum: 21",
      maxLength: 80,
      section: "hero",
    },

    // --- SECTION: PROFIL MEMPELAI ---
    {
      name: "groomFullName",
      label: "Nama lengkap mempelai pria",
      type: "text",
      placeholder: "Dimas Arya Prasetya, S.T.",
      required: true,
      maxLength: 100,
      section: "couple",
    },
    {
      name: "groomParents",
      label: "Keterangan orang tua pria",
      type: "text",
      placeholder: "Putra pertama dari Bpk. Ir. Bambang Prasetya & Ibu Hj. Sri Wahyuni",
      maxLength: 160,
      section: "couple",
    },
    {
      name: "groomPhoto",
      label: "Foto mempelai pria (URL)",
      type: "text",
      placeholder: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d",
      maxLength: 1000,
      section: "couple",
    },
    {
      name: "groomInstagram",
      label: "Instagram pria (opsional)",
      type: "text",
      placeholder: "@dimasarya",
      maxLength: 50,
      section: "couple",
    },
    {
      name: "brideFullName",
      label: "Nama lengkap mempelai wanita",
      type: "text",
      placeholder: "Annisa Putri Larasati, S.Ds.",
      required: true,
      maxLength: 100,
      section: "couple",
    },
    {
      name: "brideParents",
      label: "Keterangan orang tua wanita",
      type: "text",
      placeholder: "Putri kedua dari Bpk. Drs. Hendro Larasati & Ibu Dra. Ratna Dewi",
      maxLength: 160,
      section: "couple",
    },
    {
      name: "bridePhoto",
      label: "Foto mempelai wanita (URL)",
      type: "text",
      placeholder: "https://images.unsplash.com/photo-1534528741775-53994a69daeb",
      maxLength: 1000,
      section: "couple",
    },
    {
      name: "brideInstagram",
      label: "Instagram wanita (opsional)",
      type: "text",
      placeholder: "@annisalarasati",
      maxLength: 50,
      section: "couple",
    },

    // --- SECTION: ACARA (AKAD & RESEPSI) ---
    {
      name: "akadTitle",
      label: "Nama acara 1",
      type: "text",
      placeholder: "Akad Nikah",
      maxLength: 60,
      section: "events",
    },
    {
      name: "akadDate",
      label: "Hari & tanggal acara 1",
      type: "text",
      placeholder: "Sabtu, 24 Oktober 2026",
      maxLength: 60,
      section: "events",
    },
    {
      name: "akadTime",
      label: "Waktu acara 1",
      type: "text",
      placeholder: "08.00 - 10.00 WIB",
      maxLength: 60,
      section: "events",
    },
    {
      name: "akadLocation",
      label: "Nama tempat / gedung acara 1",
      type: "text",
      placeholder: "Masjid Agung Al-Barkah",
      maxLength: 100,
      section: "events",
    },
    {
      name: "akadAddress",
      label: "Alamat lengkap acara 1",
      type: "textarea",
      placeholder: "Jl. Veteran No. 45, Kebayoran Baru, Jakarta Selatan",
      maxLength: 250,
      rows: 2,
      section: "events",
    },
    {
      name: "akadMapsUrl",
      label: "Tautan Google Maps acara 1",
      type: "text",
      placeholder: "https://maps.google.com/?q=Jakarta",
      maxLength: 1000,
      section: "events",
    },

    {
      name: "resepsiTitle",
      label: "Nama acara 2",
      type: "text",
      placeholder: "Resepsi Pernikahan",
      maxLength: 60,
      section: "events",
    },
    {
      name: "resepsiDate",
      label: "Hari & tanggal acara 2",
      type: "text",
      placeholder: "Sabtu, 24 Oktober 2026",
      maxLength: 60,
      section: "events",
    },
    {
      name: "resepsiTime",
      label: "Waktu acara 2",
      type: "text",
      placeholder: "11.00 - 15.00 WIB",
      maxLength: 60,
      section: "events",
    },
    {
      name: "resepsiLocation",
      label: "Nama tempat / gedung acara 2",
      type: "text",
      placeholder: "Grand Ballroom Hotel Horison",
      maxLength: 100,
      section: "events",
    },
    {
      name: "resepsiAddress",
      label: "Alamat lengkap acara 2",
      type: "textarea",
      placeholder: "Jl. Jenderal Sudirman Kav. 18, Jakarta Pusat",
      maxLength: 250,
      rows: 2,
      section: "events",
    },
    {
      name: "resepsiMapsUrl",
      label: "Tautan Google Maps acara 2",
      type: "text",
      placeholder: "https://maps.google.com/?q=Jakarta",
      maxLength: 1000,
      section: "events",
    },

    // --- SECTION: KISAH KITA (LOVE STORY) ---
    {
      name: "storyTitle",
      label: "Judul linimasa kisah cinta",
      type: "text",
      placeholder: "Perjalanan Kisah Kita",
      maxLength: 80,
      section: "story",
    },
    {
      name: "story1Date",
      label: "Tanggal momen 1",
      type: "text",
      placeholder: "12 Januari 2021",
      maxLength: 40,
      section: "story",
    },
    {
      name: "story1Title",
      label: "Judul momen 1",
      type: "text",
      placeholder: "Pertemuan Pertama",
      maxLength: 80,
      section: "story",
    },
    {
      name: "story1Desc",
      label: "Cerita singkat momen 1",
      type: "textarea",
      placeholder: "Bertemu tanpa sengaja dalam sebuah seminar kampus, berlanjut obrolan hangat tentang mimpi dan harapan.",
      maxLength: 350,
      rows: 2,
      section: "story",
    },
    {
      name: "story2Date",
      label: "Tanggal momen 2",
      type: "text",
      placeholder: "18 Juni 2023",
      maxLength: 40,
      section: "story",
    },
    {
      name: "story2Title",
      label: "Judul momen 2",
      type: "text",
      placeholder: "Komitmen Bersama",
      maxLength: 80,
      section: "story",
    },
    {
      name: "story2Desc",
      label: "Cerita singkat momen 2",
      type: "textarea",
      placeholder: "Memutuskan untuk melangkah bersama melewati suka dan duka, saling menguatkan di setiap langkah.",
      maxLength: 350,
      rows: 2,
      section: "story",
    },
    {
      name: "story3Date",
      label: "Tanggal momen 3",
      type: "text",
      placeholder: "15 Januari 2026",
      maxLength: 40,
      section: "story",
    },
    {
      name: "story3Title",
      label: "Judul momen 3",
      type: "text",
      placeholder: "Menuju Ikatan Suci",
      maxLength: 80,
      section: "story",
    },
    {
      name: "story3Desc",
      label: "Cerita singkat momen 3",
      type: "textarea",
      placeholder: "Dengan restu kedua orang tua dan keluarga besar, kami memantapkan hati untuk menyatukan janji sehidup semati.",
      maxLength: 350,
      rows: 2,
      section: "story",
    },

    // --- SECTION: GALERI FOTO ---
    {
      name: "galleryTitle",
      label: "Judul galeri foto",
      type: "text",
      placeholder: "Galeri Kenangan Indah",
      maxLength: 80,
      section: "gallery",
    },
    {
      name: "galleryImg1",
      label: "Foto galeri 1 (URL)",
      type: "text",
      placeholder: "https://images.unsplash.com/photo-1511285560929-80b456fea0bc",
      maxLength: 1000,
      section: "gallery",
    },
    {
      name: "galleryImg2",
      label: "Foto galeri 2 (URL)",
      type: "text",
      placeholder: "https://images.unsplash.com/photo-1520854221256-17451cc331bf",
      maxLength: 1000,
      section: "gallery",
    },
    {
      name: "galleryImg3",
      label: "Foto galeri 3 (URL)",
      type: "text",
      placeholder: "https://images.unsplash.com/photo-1583939003579-730e3918a45a",
      maxLength: 1000,
      section: "gallery",
    },
    {
      name: "galleryImg4",
      label: "Foto galeri 4 (URL)",
      type: "text",
      placeholder: "https://images.unsplash.com/photo-1519225421980-715cb0215aed",
      maxLength: 1000,
      section: "gallery",
    },

    // --- SECTION: HADIAH & AMPLOP DIGITAL ---
    {
      name: "giftTitle",
      label: "Judul amplop digital / kado",
      type: "text",
      placeholder: "Tanda Kasih & Hadiah Pernikahan",
      maxLength: 80,
      section: "gift",
    },
    {
      name: "giftNote",
      label: "Catatan pengantar hadiah",
      type: "textarea",
      placeholder: "Doa restu Anda adalah karunia terindah bagi kami. Namun jika ingin memberikan tanda kasih secara digital, Anda dapat menggunakan nomor rekening berikut.",
      maxLength: 350,
      rows: 2,
      section: "gift",
    },
    {
      name: "bankName1",
      label: "Nama bank / e-wallet 1",
      type: "text",
      placeholder: "BCA",
      maxLength: 40,
      section: "gift",
    },
    {
      name: "bankAccount1",
      label: "Nomor rekening 1",
      type: "text",
      placeholder: "8271928374",
      maxLength: 40,
      section: "gift",
    },
    {
      name: "bankHolder1",
      label: "Atas nama rekening 1",
      type: "text",
      placeholder: "Dimas Arya Prasetya",
      maxLength: 80,
      section: "gift",
    },
    {
      name: "bankName2",
      label: "Nama bank / e-wallet 2",
      type: "text",
      placeholder: "Mandiri",
      maxLength: 40,
      section: "gift",
    },
    {
      name: "bankAccount2",
      label: "Nomor rekening 2",
      type: "text",
      placeholder: "1370019283746",
      maxLength: 40,
      section: "gift",
    },
    {
      name: "bankHolder2",
      label: "Atas nama rekening 2",
      type: "text",
      placeholder: "Annisa Putri Larasati",
      maxLength: 80,
      section: "gift",
    },
    {
      name: "giftAddress",
      label: "Alamat pengiriman kado fisik (opsional)",
      type: "textarea",
      placeholder: "Jl. Veteran No. 45, Kebayoran Baru, Jakarta Selatan (Penerima: Dimas & Annisa)",
      maxLength: 300,
      rows: 2,
      section: "gift",
    },

    // --- SECTION: TEMA & AUDIO ---
    {
      name: "primaryColor",
      label: "Warna aksen utama",
      type: "color",
      defaultValue: "#b48c36",
      helperText: "Warna tombol, monogram, lis bingkai, dan ornamen mewah.",
      colorPresets: WEDDING_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "backgroundColor",
      label: "Warna latar belakang undangan",
      type: "color",
      defaultValue: "#faf7f2",
      helperText: "Warna kanvas dasar halaman undangan.",
      colorPresets: BACKGROUND_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "cardColor",
      label: "Warna kartu & wadah acara",
      type: "color",
      defaultValue: "#ffffff",
      helperText: "Latar kotak acara, kartu rekening, dan bingkai mempelai.",
      colorPresets: CARD_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "textColor",
      label: "Warna teks judul",
      type: "color",
      defaultValue: "#2a241e",
      helperText: "Warna nama mempelai dan judul seksi.",
      colorPresets: TEXT_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "bodyTextColor",
      label: "Warna teks narasi & alamat",
      type: "color",
      defaultValue: "#524b43",
      helperText: "Warna teks keterangan, doa, dan alamat acara.",
      colorPresets: TEXT_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "musicTitle",
      label: "Judul audio musik latar",
      type: "text",
      placeholder: "A Thousand Years (Piano Romantic)",
      maxLength: 80,
      section: "theme",
    },
    {
      name: "bgMusicUrl",
      label: "Tautan audio latar (.mp3)",
      type: "text",
      placeholder: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3",
      helperText: "File audio .mp3 yang diputar otomatis saat tamu menekan tombol Buka Undangan.",
      maxLength: 1000,
      section: "theme",
    },
  ],
  sample: {
    recipientName: "Bapak / Ibu / Saudara/i",
    weddingTitle: "The Wedding of Dimas & Annisa",
    groomNickname: "Dimas",
    brideNickname: "Annisa",
    weddingDate: "2026-10-24",
    heroImage:
      "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80",
    weddingQuote:
      "Dan di antara tanda-tanda kebesaran-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, agar kamu cenderung dan merasa tenteram kepadanya, dan Dia menjadikan di antaramu rasa kasih dan sayang.",
    quoteSource: "QS. Ar-Rum: 21",

    groomFullName: "Dimas Arya Prasetya, S.T.",
    groomParents:
      "Putra pertama dari Bpk. Ir. Bambang Prasetya & Ibu Hj. Sri Wahyuni",
    groomPhoto:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80",
    groomInstagram: "@dimasarya",

    brideFullName: "Annisa Putri Larasati, S.Ds.",
    brideParents:
      "Putri kedua dari Bpk. Drs. Hendro Larasati & Ibu Dra. Ratna Dewi",
    bridePhoto:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80",
    brideInstagram: "@annisalarasati",

    akadTitle: "Akad Nikah",
    akadDate: "Sabtu, 24 Oktober 2026",
    akadTime: "08.00 - 10.00 WIB",
    akadLocation: "Masjid Agung Al-Barkah",
    akadAddress: "Jl. Veteran No. 45, Kebayoran Baru, Jakarta Selatan",
    akadMapsUrl: "https://maps.google.com/?q=Jakarta",

    resepsiTitle: "Resepsi Pernikahan",
    resepsiDate: "Sabtu, 24 Oktober 2026",
    resepsiTime: "11.00 - 15.00 WIB",
    resepsiLocation: "Grand Ballroom Hotel Horison",
    resepsiAddress: "Jl. Jenderal Sudirman Kav. 18, Jakarta Pusat",
    resepsiMapsUrl: "https://maps.google.com/?q=Jakarta",

    storyTitle: "Perjalanan Kisah Kita",
    story1Date: "12 Januari 2021",
    story1Title: "Pertemuan Pertama",
    story1Desc:
      "Bertemu tanpa sengaja dalam sebuah seminar kampus, berlanjut obrolan hangat tentang mimpi dan harapan masa depan.",
    story2Date: "18 Juni 2023",
    story2Title: "Komitmen Bersama",
    story2Desc:
      "Memutuskan untuk melangkah bersama melewati suka dan duka, saling menguatkan di setiap tahapan kehidupan.",
    story3Date: "15 Januari 2026",
    story3Title: "Menuju Ikatan Suci",
    story3Desc:
      "Dengan restu kedua orang tua dan keluarga besar, kami memantapkan hati untuk mengikat janji suci sehidup semati.",

    galleryTitle: "Galeri Kenangan Indah",
    galleryImg1:
      "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=800&q=80",
    galleryImg2:
      "https://images.unsplash.com/photo-1520854221256-17451cc331bf?auto=format&fit=crop&w=800&q=80",
    galleryImg3:
      "https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=800&q=80",
    galleryImg4:
      "https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=800&q=80",

    giftTitle: "Tanda Kasih & Hadiah Pernikahan",
    giftNote:
      "Doa restu Anda adalah karunia terindah bagi kami. Namun jika Anda bermaksud memberikan tanda kasih secara digital, Anda dapat menyalurkannya melalui nomor rekening di bawah ini.",
    bankName1: "BCA",
    bankAccount1: "8271928374",
    bankHolder1: "Dimas Arya Prasetya",
    bankName2: "Mandiri",
    bankAccount2: "1370019283746",
    bankHolder2: "Annisa Putri Larasati",
    giftAddress:
      "Jl. Veteran No. 45, RT 02/RW 04, Kebayoran Baru, Jakarta Selatan 12120 (Penerima: Dimas & Annisa)",

    primaryColor: "#b48c36",
    backgroundColor: "#faf7f2",
    cardColor: "#ffffff",
    textColor: "#2a241e",
    bodyTextColor: "#524b43",
    musicTitle: "A Thousand Years (Piano Instrumental)",
    bgMusicUrl:
      "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
  },
};
