import type { TemplateMeta } from "../types";

export const amalfiWeddingTemplate: TemplateMeta = {
  slug: "amalfi-wedding",
  name: "Villa d'Amore: Amalfi Wedding",
  category: "Undangan",
  description:
    "Undangan pernikahan mewah bertema keanggunan pesisir Mediterania dan villa tebing Amalfi Coast Italia (The Amalfi Coast Villa d'Amore Celebration). Menampilkan bingkai keramik lukis tangan Italian Majolica tile, monogram inisial mempelai bergaya Romanesque arch, kisah cinta di bawah mentari Riviera, rundown 4 babak acara interaktif (Pemberkatan Tebing, Aperitivo Senja, Jamuan Pergola Lemon, & Pesta Kembang Api), petunjuk lokasi dan peta navigasi villa, panduan dress code swatch warna Riviera Chic, form simulasi RSVP interaktif, rekening tanda kasih digital dengan tombol salin instan, serta alunan melodi mandolin serenade Italia yang memikat.",
  tagline: "Villa d'Amore: Janji Suci Abadi di Bawah Mentari dan Birunya Laut Mediterania",
  cardAccent: "border-amber-500/40 bg-gradient-to-br from-[#0a192f] via-[#0f2b48] to-[#091e33] text-amber-200",
  highlights: [
    "Konsep Pesisir Mediterania & Villa Tebing Amalfi Coast dengan Ornamen Majolica Tile",
    "Monogram Pengantin Berbingkai Romanesque Arch & Maklumat Undangan Kehormatan",
    "Kisah Cinta Dua Hati di Bawah Pohon Lemon Ravello & Ayat Suci Pernikahan",
    "4 Babak Acara Interaktif (Pemberkatan Tebing, Aperitivo Senja, Jamuan Pergola, Pesta Dansa)",
    "Panduan Busana Tamu Riviera Chic dengan 4 Swatch Warna Pesisir Mediterania",
    "Rekening Tanda Kasih Digital dengan Tombol Satu-Klik Salin No. Rekening & Melodi Mandolin",
  ],
  fields: [
    // Section 1: Monogram Villa d'Amore & Maklumat Undangan Suci
    {
      name: "coupleMonogram",
      label: "Monogram Inisial Mempelai",
      type: "text",
      placeholder: "A & L",
      defaultValue: "A & L",
      section: "Monogram & Maklumat Undangan",
    },
    {
      name: "weddingTitle",
      label: "Judul Perayaan Pernikahan",
      type: "text",
      placeholder: "The Wedding Celebration of Alessandro & Lucia",
      defaultValue: "The Wedding Celebration of Alessandro & Lucia",
      section: "Monogram & Maklumat Undangan",
    },
    {
      name: "invitationSubtitle",
      label: "Subjudul Undangan Resmi",
      type: "text",
      placeholder: "Con Amore e Gioia • Bersama Berkah Kasih & Rahmat Illahi",
      defaultValue: "Con Amore e Gioia • Bersama Berkah Kasih & Rahmat Illahi",
      section: "Monogram & Maklumat Undangan",
    },
    {
      name: "recipientName",
      label: "Nama Tamu Undangan Terhormat",
      type: "text",
      placeholder: "Bapak / Ibu / Sahabat Terkasih",
      required: true,
      isRecipient: true,
      section: "Monogram & Maklumat Undangan",
    },
    {
      name: "weddingDate",
      label: "Hari & Tanggal Pernikahan",
      type: "text",
      placeholder: "Sabtu, 24 Oktober 2026",
      defaultValue: "Sabtu, 24 Oktober 2026",
      section: "Monogram & Maklumat Undangan",
    },
    {
      name: "weddingTime",
      label: "Rentang Waktu Acara",
      type: "text",
      placeholder: "Pukul 09.00 - 23.00 CEST",
      defaultValue: "Pukul 09.00 - 23.00 CEST",
      section: "Monogram & Maklumat Undangan",
    },
    {
      name: "groomName",
      label: "Nama Mempelai Pria",
      type: "text",
      placeholder: "Alessandro Matteo Moretti",
      required: true,
      defaultValue: "Alessandro Matteo Moretti",
      section: "Monogram & Maklumat Undangan",
    },
    {
      name: "groomParents",
      label: "Orang Tua Mempelai Pria",
      type: "text",
      placeholder: "Putra pertama dari Bpk. Lorenzo Moretti & Ibu Isabella Rossi",
      defaultValue: "Putra pertama dari Bpk. Lorenzo Moretti & Ibu Isabella Rossi",
      section: "Monogram & Maklumat Undangan",
    },
    {
      name: "brideName",
      label: "Nama Mempelai Wanita",
      type: "text",
      placeholder: "Lucia Caterina De Luca",
      required: true,
      defaultValue: "Lucia Caterina De Luca",
      section: "Monogram & Maklumat Undangan",
    },
    {
      name: "brideParents",
      label: "Orang Tua Mempelai Wanita",
      type: "text",
      placeholder: "Putri kedua dari Bpk. Marco De Luca & Ibu Sofia Bianchi",
      defaultValue: "Putri kedua dari Bpk. Marco De Luca & Ibu Sofia Bianchi",
      section: "Monogram & Maklumat Undangan",
    },
    {
      name: "sacredVerse",
      label: "Ayat Suci / Kutipan Janji Pernikahan",
      type: "textarea",
      placeholder: "Kutipan ayat suci atau janji...",
      defaultValue:
        "“Dan di antara tanda-tanda kebesaran-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, agar kamu cenderung dan merasa tenteram kepadanya, dan Dia menjadikan di antaramu rasa kasih dan sayang.”",
      section: "Monogram & Maklumat Undangan",
    },

    // Section 2: Kisah Cinta di Bawah Mentari Riviera (The Romance Chronicle)
    {
      name: "storyTitle",
      label: "Judul Kisah Cinta Mempelai",
      type: "text",
      placeholder: "Kisah Dua Hati di Pesisir Mediterania",
      defaultValue: "Kisah Dua Hati di Pesisir Mediterania",
      section: "Kisah Cinta Dua Hati",
    },
    {
      name: "storySubtitle",
      label: "Subjudul Kisah Cinta",
      type: "text",
      placeholder: "Bagaimana semesta menautkan langkah kami di bawah keteduhan pohon lemon Ravello",
      defaultValue: "Bagaimana semesta menautkan langkah kami di bawah keteduhan pohon lemon Ravello",
      section: "Kisah Cinta Dua Hati",
    },
    {
      name: "mainMessage",
      label: "Narasi Perjalanan Cinta (Warkah Utama)",
      type: "textarea",
      placeholder: "Tuliskan perjalanan cinta kedua mempelai...",
      required: true,
      defaultValue:
        "Pertemuan kami bermula dari obrolan sederhana di sebuah kafe tepi tebing di Positano saat matahari perlahan membasahi laut dengan warna keemasan. Dari secangkir espresso dan tawa lepas tentang impian masa depan, kami menyadari bahwa langkah kami diciptakan untuk berjalan beriringan.\n\nMelewati berbagai musim kehidupan, tawa bahagia, dan ujian yang menguatkan, kami belajar bahwa cinta bukan sekadar memandang satu sama lain, melainkan menatap ke arah yang sama dengan keyakinan yang utuh. Kini, di hadapan keluarga dan sahabat tercinta, kami memohon doa restu untuk mengikat janji suci seumur hidup kami di bawah naungan langit biru Mediterania.",
      section: "Kisah Cinta Dua Hati",
    },
    {
      name: "coupleQuote",
      label: "Kutipan Romantis Mempelai",
      type: "text",
      placeholder: "Kutipan cinta...",
      defaultValue: "Di antara deburan ombak dan hangatnya mentari, kami menemukan rumah satu sama lain untuk selamanya.",
      section: "Kisah Cinta Dua Hati",
    },
    {
      name: "senderName",
      label: "Nama Tanda Tangan Pasangan Pengantin",
      type: "text",
      placeholder: "Alessandro & Lucia",
      defaultValue: "Alessandro & Lucia",
      section: "Kisah Cinta Dua Hati",
    },

    // Section 3: 4 Babak Acara Hari Bahagia (L'Itinerario della Celebrazione)
    {
      name: "act1Time",
      label: "Babak 1: Waktu Acara",
      type: "text",
      placeholder: "09:00 - 11:00 CEST",
      defaultValue: "09:00 - 11:00 CEST",
      section: "4 Babak Acara Pernikahan",
    },
    {
      name: "act1Title",
      label: "Babak 1: Nama Prosesi",
      type: "text",
      placeholder: "Atto I: Pemberkatan Suci di Tebing Laut",
      defaultValue: "Atto I: Pemberkatan Suci di Tebing Laut",
      section: "4 Babak Acara Pernikahan",
    },
    {
      name: "act1Location",
      label: "Babak 1: Lokasi Area",
      type: "text",
      placeholder: "Terrazza dell'Infinito, Villa d'Amore",
      defaultValue: "Terrazza dell'Infinito, Villa d'Amore",
      section: "4 Babak Acara Pernikahan",
    },
    {
      name: "act1Desc",
      label: "Babak 1: Keterangan Prosesi",
      type: "textarea",
      placeholder: "Deskripsi prosesi...",
      defaultValue:
        "Pengucapan janji suci dan pertukaran cincin pernikahan di atas altar marmer terbuka dengan pemandangan 180 derajat birunya laut Tyrrhenian.",
      section: "4 Babak Acara Pernikahan",
    },

    {
      name: "act2Time",
      label: "Babak 2: Waktu Acara",
      type: "text",
      placeholder: "16:30 - 18:00 CEST",
      defaultValue: "16:30 - 18:00 CEST",
      section: "4 Babak Acara Pernikahan",
    },
    {
      name: "act2Title",
      label: "Babak 2: Nama Prosesi",
      type: "text",
      placeholder: "Atto II: Aperitivo Mentari Senja & Live Mandolin",
      defaultValue: "Atto II: Aperitivo Mentari Senja & Live Mandolin",
      section: "4 Babak Acara Pernikahan",
    },
    {
      name: "act2Location",
      label: "Babak 2: Lokasi Area",
      type: "text",
      placeholder: "Giardino dei Limoni",
      defaultValue: "Giardino dei Limoni",
      section: "4 Babak Acara Pernikahan",
    },
    {
      name: "act2Desc",
      label: "Babak 2: Keterangan Prosesi",
      type: "textarea",
      placeholder: "Deskripsi prosesi...",
      defaultValue:
        "Menyambut tamu dengan Limoncello Spritz segar, kudapan canapé khas pesisir Italia, dan alunan melodi serenade petik akustik saat matahari mulai terbenam.",
      section: "4 Babak Acara Pernikahan",
    },

    {
      name: "act3Time",
      label: "Babak 3: Waktu Acara",
      type: "text",
      placeholder: "18:30 - 20:30 CEST",
      defaultValue: "18:30 - 20:30 CEST",
      section: "4 Babak Acara Pernikahan",
    },
    {
      name: "act3Title",
      label: "Babak 3: Nama Prosesi",
      type: "text",
      placeholder: "Atto III: Jamuan Makan Malam di Bawah Pergola",
      defaultValue: "Atto III: Jamuan Makan Malam di Bawah Pergola",
      section: "4 Babak Acara Pernikahan",
    },
    {
      name: "act3Location",
      label: "Babak 3: Lokasi Area",
      type: "text",
      placeholder: "Pergola delle Rose e Limoni",
      defaultValue: "Pergola delle Rose e Limoni",
      section: "4 Babak Acara Pernikahan",
    },
    {
      name: "act3Desc",
      label: "Babak 3: Keterangan Prosesi",
      type: "textarea",
      placeholder: "Deskripsi prosesi...",
      defaultValue:
        "Makan malam romantis dengan sajian hidangan pasta buatan tangan dan hidangan laut Mediterania di bawah naungan pergola dedaunan lemon dan lilin temaram.",
      section: "4 Babak Acara Pernikahan",
    },

    {
      name: "act4Time",
      label: "Babak 4: Waktu Acara",
      type: "text",
      placeholder: "20:30 - Selesai",
      defaultValue: "20:30 - Selesai",
      section: "4 Babak Acara Pernikahan",
    },
    {
      name: "act4Title",
      label: "Babak 4: Nama Prosesi",
      type: "text",
      placeholder: "Atto IV: Pesta Dansa & Kembang Api Teluk",
      defaultValue: "Atto IV: Pesta Dansa & Kembang Api Teluk",
      section: "4 Babak Acara Pernikahan",
    },
    {
      name: "act4Location",
      label: "Babak 4: Lokasi Area",
      type: "text",
      placeholder: "Belvedere sul Mare",
      defaultValue: "Belvedere sul Mare",
      section: "4 Babak Acara Pernikahan",
    },
    {
      name: "act4Desc",
      label: "Babak 4: Keterangan Prosesi",
      type: "textarea",
      placeholder: "Deskripsi prosesi...",
      defaultValue:
        "Dansa pertama kedua mempelai, pemotongan kue pengantin Millefoglie tradisional, serta selebrasi kembang api spektakuler yang menerangi teluk malam.",
      section: "4 Babak Acara Pernikahan",
    },

    // Section 4: Panduan Lokasi & Navigasi Villa
    {
      name: "venueName",
      label: "Nama Lokasi Villa Pernikahan",
      type: "text",
      placeholder: "Villa d'Amore Cliffside Estate",
      defaultValue: "Villa d'Amore Cliffside Estate",
      section: "Lokasi & Navigasi Villa",
    },
    {
      name: "venueSubname",
      label: "Wilayah & Kota Lokasi",
      type: "text",
      placeholder: "Ravello, Costiera Amalfitana, Italia",
      defaultValue: "Ravello, Costiera Amalfitana, Italia",
      section: "Lokasi & Navigasi Villa",
    },
    {
      name: "venueAddress",
      label: "Alamat Lengkap Venue",
      type: "textarea",
      placeholder: "Alamat lengkap...",
      defaultValue: "Via San Giovanni del Toro, 28, 84010 Ravello SA, Italy",
      section: "Lokasi & Navigasi Villa",
    },
    {
      name: "venueNotes",
      label: "Catatan Akses & Transportasi Tamu",
      type: "text",
      placeholder: "Catatan penjemputan shuttle...",
      defaultValue: "Disediakan layanan shuttle van privat dan perahu boat dari dermaga utama Amalfi mulai pukul 08.00 pagi.",
      section: "Lokasi & Navigasi Villa",
    },
    {
      name: "mapsUrl",
      label: "URL Google Maps Lokasi",
      type: "text",
      placeholder: "https://maps.google.com/?q=Ravello+Amalfi+Coast",
      defaultValue: "https://maps.google.com/?q=Ravello+Amalfi+Coast",
      section: "Lokasi & Navigasi Villa",
    },

    // Section 5: Etiket Tamu & Riviera Dress Code Swatches
    {
      name: "dressCodeTheme",
      label: "Tema Busana Tamu Undangan",
      type: "text",
      placeholder: "Amalfi Riviera Elegance • Formal Summer Chic",
      defaultValue: "Amalfi Riviera Elegance • Formal Summer Chic",
      section: "Etiket & Riviera Dress Code",
    },
    {
      name: "dressCodeDesc",
      label: "Deskripsi Panduan Busana",
      type: "textarea",
      placeholder: "Penjelasan dress code...",
      defaultValue:
        "Pria disarankan mengenakan setelan jas linen atau kemeja rapi bernuansa terang. Wanita disarankan mengenakan gaun midi/maxi cocktail berpotongan elegan bernuansa floral atau warna pesisir Mediterania.",
      section: "Etiket & Riviera Dress Code",
    },
    {
      name: "colorSwatch1",
      label: "Swatch Warna 1: Limoncello Gold",
      type: "text",
      placeholder: "Limoncello Gold (#eab308)",
      defaultValue: "Limoncello Gold (#eab308)",
      section: "Etiket & Riviera Dress Code",
    },
    {
      name: "colorSwatch2",
      label: "Swatch Warna 2: Mediterranean Azure",
      type: "text",
      placeholder: "Mediterranean Azure (#0284c7)",
      defaultValue: "Mediterranean Azure (#0284c7)",
      section: "Etiket & Riviera Dress Code",
    },
    {
      name: "colorSwatch3",
      label: "Swatch Warna 3: Olive Sage Green",
      type: "text",
      placeholder: "Olive Sage Green (#65a30d)",
      defaultValue: "Olive Sage Green (#65a30d)",
      section: "Etiket & Riviera Dress Code",
    },
    {
      name: "colorSwatch4",
      label: "Swatch Warna 4: Terracotta Linen",
      type: "text",
      placeholder: "Terracotta Linen (#c2410c)",
      defaultValue: "Terracotta Linen (#c2410c)",
      section: "Etiket & Riviera Dress Code",
    },
    {
      name: "guestEtiquetteNotes",
      label: "Catatan Tambahan untuk Kenyamanan Tamu",
      type: "textarea",
      placeholder: "Catatan alas kaki atau etiket...",
      defaultValue:
        "Karena sebagian prosesi berlangsung di atas teras batu marmer dan taman tebing bertingkat, para tamu wanita sangat disarankan menggunakan sepatu berhak kokoh (block heels atau wedges) untuk kenyamanan melangkah.",
      section: "Etiket & Riviera Dress Code",
    },

    // Section 6: Digital RSVP, Tanda Kasih & Musik Serenade
    {
      name: "bank1Name",
      label: "Bank 1: Nama Bank",
      type: "text",
      placeholder: "BCA (Bank Central Asia)",
      defaultValue: "BCA (Bank Central Asia)",
      section: "RSVP & Tanda Kasih",
    },
    {
      name: "bank1AccountNo",
      label: "Bank 1: Nomor Rekening",
      type: "text",
      placeholder: "8820194821",
      defaultValue: "8820194821",
      section: "RSVP & Tanda Kasih",
    },
    {
      name: "bank1Holder",
      label: "Bank 1: Atas Nama Rekening",
      type: "text",
      placeholder: "Alessandro Matteo Moretti",
      defaultValue: "Alessandro Matteo Moretti",
      section: "RSVP & Tanda Kasih",
    },
    {
      name: "bank2Name",
      label: "Bank 2: Nama Bank",
      type: "text",
      placeholder: "Bank Mandiri",
      defaultValue: "Bank Mandiri",
      section: "RSVP & Tanda Kasih",
    },
    {
      name: "bank2AccountNo",
      label: "Bank 2: Nomor Rekening",
      type: "text",
      placeholder: "1370029481023",
      defaultValue: "1370029481023",
      section: "RSVP & Tanda Kasih",
    },
    {
      name: "bank2Holder",
      label: "Bank 2: Atas Nama Rekening",
      type: "text",
      placeholder: "Lucia Caterina De Luca",
      defaultValue: "Lucia Caterina De Luca",
      section: "RSVP & Tanda Kasih",
    },
    {
      name: "giftMessage",
      label: "Pesan Pengantar Tanda Kasih (Wedding Gift)",
      type: "textarea",
      placeholder: "Pesan pengantar...",
      defaultValue:
        "Doa restu dan kehadiran Anda adalah hadiah terindah dalam babak baru hidup kami. Namun jika Anda bermaksud memberikan tanda kasih berupa kado pernikahan, kami menyediakan amplop digital di atas dengan rasa terima kasih yang tulus.",
      section: "RSVP & Tanda Kasih",
    },
    {
      name: "rsvpDeadline",
      label: "Batas Waktu Konfirmasi RSVP",
      type: "text",
      placeholder: "Mohon konfirmasi kehadiran sebelum 1 Oktober 2026",
      defaultValue: "Mohon konfirmasi kehadiran sebelum 1 Oktober 2026",
      section: "RSVP & Tanda Kasih",
    },

    // Palette & Music
    {
      name: "primaryColor",
      label: "Warna Utama (Limoncello Gold)",
      type: "color",
      defaultValue: "#eab308",
      section: "Pengaturan Tampilan & Musik",
    },
    {
      name: "secondaryColor",
      label: "Warna Sekunder (Mediterranean Azure)",
      type: "color",
      defaultValue: "#0284c7",
      section: "Pengaturan Tampilan & Musik",
    },
    {
      name: "accentColor",
      label: "Warna Aksen (Tyrrhenian Deep Blue)",
      type: "color",
      defaultValue: "#0f2b48",
      section: "Pengaturan Tampilan & Musik",
    },
    {
      name: "musicTrack",
      label: "URL Musik Latar (Mandolin Serenade Italia)",
      type: "text",
      placeholder: "https://cdn.pixabay.com/download/audio/...",
      defaultValue: "https://cdn.pixabay.com/download/audio/2022/03/15/audio_c89b7b9cf4.mp3?filename=celestial-music-box-waltz-10928.mp3",
      section: "Pengaturan Tampilan & Musik",
    },
  ],
  sample: {
    coupleMonogram: "A & L",
    weddingTitle: "The Wedding Celebration of Alessandro & Lucia",
    invitationSubtitle: "Con Amore e Gioia • Bersama Berkah Kasih & Rahmat Illahi",
    recipientName: "Bapak / Ibu / Sahabat Terkasih",
    weddingDate: "Sabtu, 24 Oktober 2026",
    weddingTime: "Pukul 09.00 - 23.00 CEST",
    groomName: "Alessandro Matteo Moretti",
    groomParents: "Putra pertama dari Bpk. Lorenzo Moretti & Ibu Isabella Rossi",
    brideName: "Lucia Caterina De Luca",
    brideParents: "Putri kedua dari Bpk. Marco De Luca & Ibu Sofia Bianchi",
    sacredVerse:
      "“Dan di antara tanda-tanda kebesaran-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, agar kamu cenderung dan merasa tenteram kepadanya, dan Dia menjadikan di antaramu rasa kasih dan sayang.”",
    storyTitle: "Kisah Dua Hati di Pesisir Mediterania",
    storySubtitle: "Bagaimana semesta menautkan langkah kami di bawah keteduhan pohon lemon Ravello",
    mainMessage:
      "Pertemuan kami bermula dari obrolan sederhana di sebuah kafe tepi tebing di Positano saat matahari perlahan membasahi laut dengan warna keemasan. Dari secangkir espresso dan tawa lepas tentang impian masa depan, kami menyadari bahwa langkah kami diciptakan untuk berjalan beriringan.\n\nMelewati berbagai musim kehidupan, tawa bahagia, dan ujian yang menguatkan, kami belajar bahwa cinta bukan sekadar memandang satu sama lain, melainkan menatap ke arah yang sama dengan keyakinan yang utuh. Kini, di hadapan keluarga dan sahabat tercinta, kami memohon doa restu untuk mengikat janji suci seumur hidup kami di bawah naungan langit biru Mediterania.",
    coupleQuote: "Di antara deburan ombak dan hangatnya mentari, kami menemukan rumah satu sama lain untuk selamanya.",
    senderName: "Alessandro & Lucia",
    act1Time: "09:00 - 11:00 CEST",
    act1Title: "Atto I: Pemberkatan Suci di Tebing Laut",
    act1Location: "Terrazza dell'Infinito, Villa d'Amore",
    act1Desc:
      "Pengucapan janji suci dan pertukaran cincin pernikahan di atas altar marmer terbuka dengan pemandangan 180 derajat birunya laut Tyrrhenian.",
    act2Time: "16:30 - 18:00 CEST",
    act2Title: "Atto II: Aperitivo Mentari Senja & Live Mandolin",
    act2Location: "Giardino dei Limoni",
    act2Desc:
      "Menyambut tamu dengan Limoncello Spritz segar, kudapan canapé khas pesisir Italia, dan alunan melodi serenade petik akustik saat matahari mulai terbenam.",
    act3Time: "18:30 - 20:30 CEST",
    act3Title: "Atto III: Jamuan Makan Malam di Bawah Pergola",
    act3Location: "Pergola delle Rose e Limoni",
    act3Desc:
      "Makan malam romantis dengan sajian hidangan pasta buatan tangan dan hidangan laut Mediterania di bawah naungan pergola dedaunan lemon dan lilin temaram.",
    act4Time: "20:30 - Selesai",
    act4Title: "Atto IV: Pesta Dansa & Kembang Api Teluk",
    act4Location: "Belvedere sul Mare",
    act4Desc:
      "Dansa pertama kedua mempelai, pemotongan kue pengantin Millefoglie tradisional, serta selebrasi kembang api spektakuler yang menerangi teluk malam.",
    venueName: "Villa d'Amore Cliffside Estate",
    venueSubname: "Ravello, Costiera Amalfitana, Italia",
    venueAddress: "Via San Giovanni del Toro, 28, 84010 Ravello SA, Italy",
    venueNotes: "Disediakan layanan shuttle van privat dan perahu boat dari dermaga utama Amalfi mulai pukul 08.00 pagi.",
    mapsUrl: "https://maps.google.com/?q=Ravello+Amalfi+Coast",
    dressCodeTheme: "Amalfi Riviera Elegance • Formal Summer Chic",
    dressCodeDesc:
      "Pria disarankan mengenakan setelan jas linen atau kemeja rapi bernuansa terang. Wanita disarankan mengenakan gaun midi/maxi cocktail berpotongan elegan bernuansa floral atau warna pesisir Mediterania.",
    colorSwatch1: "Limoncello Gold (#eab308)",
    colorSwatch2: "Mediterranean Azure (#0284c7)",
    colorSwatch3: "Olive Sage Green (#65a30d)",
    colorSwatch4: "Terracotta Linen (#c2410c)",
    guestEtiquetteNotes:
      "Karena sebagian prosesi berlangsung di atas teras batu marmer dan taman tebing bertingkat, para tamu wanita sangat disarankan menggunakan sepatu berhak kokoh (block heels atau wedges) untuk kenyamanan melangkah.",
    bank1Name: "BCA (Bank Central Asia)",
    bank1AccountNo: "8820194821",
    bank1Holder: "Alessandro Matteo Moretti",
    bank2Name: "Bank Mandiri",
    bank2AccountNo: "1370029481023",
    bank2Holder: "Lucia Caterina De Luca",
    giftMessage:
      "Doa restu dan kehadiran Anda adalah hadiah terindah dalam babak baru hidup kami. Namun jika Anda bermaksud memberikan tanda kasih berupa kado pernikahan, kami menyediakan amplop digital di atas dengan rasa terima kasih yang tulus.",
    rsvpDeadline: "Mohon konfirmasi kehadiran sebelum 1 Oktober 2026",
    primaryColor: "#eab308",
    secondaryColor: "#0284c7",
    accentColor: "#0f2b48",
    musicTrack: "https://cdn.pixabay.com/download/audio/2022/03/15/audio_c89b7b9cf4.mp3?filename=celestial-music-box-waltz-10928.mp3",
  },
};
