import type { TemplateMeta } from "../types";

export const neonBashTemplate: TemplateMeta = {
  slug: "neon-bash",
  name: "Neon Birthday Bash & VIP Music Night",
  category: "Undangan",
  tagline:
    "Undangan pesta ulang tahun neon & synthwave — tiket VIP backstage, countdown digital, 3 foto polaroid glow, dress code cyberpunk, dan audio DJ party.",
  description:
    "Undangan pesta ulang tahun malam bertema Cyberpunk & 90s Retro Synthwave yang spektakuler. Menampilkan tiket konser VIP All-Access interaktif, sapaan tamu kustom via URL (?to=Nama), live digital countdown timer menuju jam pesta, preview 3 foto polaroid beraksen neon glow, timeline 4 sesi acara pesta & DJ rave, panduan dress code neon glow-in-the-dark, hadiah digital e-wallet, integrasi Google Maps, dan pemutar audio synthwave energik.",
  cardAccent: "bg-fuchsia-950 text-fuchsia-200 ring-1 ring-fuchsia-500/50",
  highlights: [
    "Tiket konser VIP All-Access pass dengan barcode dan stempel neon hologram interaktif",
    "Sapaan tamu kehormatan dinamis via parameter tautan (?to=NamaTamu)",
    "Widget Live Digital Countdown Timer menghitung mundur menuju pesta malam",
    "Galeri 3 foto polaroid retro dengan efek neon glow dan caption seru",
    "Timeline 4 sesi acara (Red Carpet, DJ Set, Candle Toast, Midnight Rave)",
    "Panduan dress code Y2K Cyberpunk dengan 4 swatch warna neon terang",
    "Amplop kado digital / e-wallet dengan tombol salin instan",
    "Integrasi peta lokasi venue langsung ke Google Maps",
    "Pemutar musik retro synthwave berputar melayang",
  ],
  fields: [
    // --- SECTION: TIKET VIP & COVER ---
    {
      name: "recipientName",
      label: "Nama tamu undangan (penerima)",
      type: "text",
      placeholder: "Sahabat Terdekat / VIP Guest",
      required: true,
      maxLength: 60,
      isRecipient: true,
      section: "ticket",
    },
    {
      name: "ticketCode",
      label: "Kode tiket VIP pass",
      type: "text",
      placeholder: "NEON-PASS-2026-VIP",
      maxLength: 30,
      section: "ticket",
    },
    {
      name: "vipBadge",
      label: "Lencana stempel VIP",
      type: "text",
      placeholder: "ALL ACCESS VIP // LEVEL 17",
      maxLength: 40,
      section: "ticket",
    },
    {
      name: "partySub",
      label: "Subjudul pesta / Tagline",
      type: "text",
      placeholder: "Sweet 17 Cyberpunk Odyssey & Rooftop Rave",
      maxLength: 80,
      section: "ticket",
    },

    // --- SECTION: ULANG TAHUN & PESAN ---
    {
      name: "partyTitle",
      label: "Judul utama pesta ulang tahun",
      type: "text",
      placeholder: "NEON ODYSSEY: Natasha's 17th Birthday",
      required: true,
      maxLength: 100,
      section: "party",
    },
    {
      name: "celebrantName",
      label: "Nama yang berulang tahun",
      type: "text",
      placeholder: "Natasha Aurelia",
      required: true,
      maxLength: 60,
      section: "party",
    },
    {
      name: "ageCelebration",
      label: "Usia yang dirayakan",
      type: "text",
      placeholder: "Sweet Seventeen (17th)",
      maxLength: 40,
      section: "party",
    },
    {
      name: "partyMessage",
      label: "Pesan undangan pesta",
      type: "textarea",
      placeholder:
        "Satu malam penuh cahaya neon, dentuman beat terbaik, dan momen tak terlupakan! Bergabunglah bersamaku untuk merayakan babak baru ke-17 di bawah gemerlap langit malam kota...",
      required: true,
      maxLength: 1000,
      section: "party",
    },
    {
      name: "senderName",
      label: "Nama pengundang (tuan rumah)",
      type: "text",
      placeholder: "Natasha & The Crew",
      required: true,
      maxLength: 60,
      section: "party",
    },

    // --- SECTION: WAKTU & VENUE ---
    {
      name: "eventDate",
      label: "Hari & tanggal pesta",
      type: "text",
      placeholder: "Jumat, 13 November 2026",
      required: true,
      maxLength: 50,
      section: "event",
    },
    {
      name: "eventTime",
      label: "Waktu pesta",
      type: "text",
      placeholder: "19.00 WIB s.d. Tengah Malam",
      required: true,
      maxLength: 50,
      section: "event",
    },
    {
      name: "targetDateIso",
      label: "Waktu ISO untuk Countdown Timer",
      type: "text",
      placeholder: "2026-11-13T19:00:00",
      maxLength: 30,
      helperText: "Format: YYYY-MM-DDTHH:mm:ss (contoh: 2026-11-13T19:00:00).",
      section: "event",
    },
    {
      name: "venueName",
      label: "Nama venue / rooftop lounge",
      type: "text",
      placeholder: "Skyline Neon Lounge & Rooftop",
      required: true,
      maxLength: 80,
      section: "event",
    },
    {
      name: "venueFloor",
      label: "Lantai / Area khusus",
      type: "text",
      placeholder: "32nd Floor Sky Deck & Poolside Foyer",
      maxLength: 60,
      section: "event",
    },
    {
      name: "venueAddress",
      label: "Alamat lengkap venue",
      type: "text",
      placeholder: "Jl. Jend. Sudirman Kav. 52-53, Kawasan SCBD, Jakarta Selatan",
      required: true,
      maxLength: 200,
      section: "event",
    },
    {
      name: "mapsUrl",
      label: "Tautan Google Maps",
      type: "text",
      placeholder: "https://maps.google.com/?q=SCBD+Jakarta",
      maxLength: 300,
      section: "event",
    },

    // --- SECTION: RUNDOWN PESTA (4 SESI) ---
    {
      name: "session1Time",
      label: "Waktu Sesi 1",
      type: "text",
      placeholder: "19.00 – 19.45 WIB",
      maxLength: 30,
      section: "rundown",
    },
    {
      name: "session1Title",
      label: "Judul Sesi 1",
      type: "text",
      placeholder: "VIP Red Carpet & Neon Face Art",
      maxLength: 60,
      section: "rundown",
    },
    {
      name: "session1Desc",
      label: "Keterangan Sesi 1",
      type: "text",
      placeholder: "Registrasi tamu VIP, glow face-painting booth, pembagian gelang LED, dan welcome drink.",
      maxLength: 150,
      section: "rundown",
    },
    {
      name: "session2Time",
      label: "Waktu Sesi 2",
      type: "text",
      placeholder: "19.45 – 20.45 WIB",
      maxLength: 30,
      section: "rundown",
    },
    {
      name: "session2Title",
      label: "Judul Sesi 2",
      type: "text",
      placeholder: "Warm-Up DJ Set & Finger Food Feast",
      maxLength: 60,
      section: "rundown",
    },
    {
      name: "session2Desc",
      label: "Keterangan Sesi 2",
      type: "text",
      placeholder: "Iringan musik synthwave chill, santap gourmet mini-burgers & mocktail bar, serta photo session.",
      maxLength: 150,
      section: "rundown",
    },
    {
      name: "session3Time",
      label: "Waktu Sesi 3",
      type: "text",
      placeholder: "20.45 – 21.30 WIB",
      maxLength: 30,
      section: "rundown",
    },
    {
      name: "session3Title",
      label: "Judul Sesi 3",
      type: "text",
      placeholder: "17th Birthday Toast & Laser Show",
      maxLength: 60,
      section: "rundown",
    },
    {
      name: "session3Desc",
      label: "Keterangan Sesi 3",
      type: "text",
      placeholder: "Momen tiup lilin utama ke-17, video kenangan sahabat, dan spektakel laser hologram.",
      maxLength: 150,
      section: "rundown",
    },
    {
      name: "session4Time",
      label: "Waktu Sesi 4",
      type: "text",
      placeholder: "21.30 – 23.30 WIB",
      maxLength: 30,
      section: "rundown",
    },
    {
      name: "session4Title",
      label: "Judul Sesi 4",
      type: "text",
      placeholder: "Midnight Rave & Dance Floor Finale",
      maxLength: 60,
      section: "rundown",
    },
    {
      name: "session4Desc",
      label: "Keterangan Sesi 4",
      type: "text",
      placeholder: "Pesta dansa bersama guest star DJ, confetti party, dan pembagian hadiah best outfit.",
      maxLength: 150,
      section: "rundown",
    },

    // --- SECTION: FOTO POLAROID RETRO GLOW ---
    {
      name: "photo1Title",
      label: "Keterangan Singkat Foto 1",
      type: "text",
      placeholder: "Neon Cyber Rebel",
      maxLength: 50,
      section: "photos",
    },
    {
      name: "photo1Caption",
      label: "Caption Foto 1",
      type: "text",
      placeholder: "Ready to rock the 17th chapter with full energy and vibrant lights!",
      maxLength: 120,
      section: "photos",
    },
    {
      name: "photo1Url",
      label: "URL Foto Polaroid 1",
      type: "image",
      placeholder: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1000&q=80",
      section: "photos",
    },
    {
      name: "photo2Title",
      label: "Keterangan Singkat Foto 2",
      type: "text",
      placeholder: "City Skyline Glow",
      maxLength: 50,
      section: "photos",
    },
    {
      name: "photo2Caption",
      label: "Caption Foto 2",
      type: "text",
      placeholder: "Midnight conversations under the neon towers of the capital.",
      maxLength: 120,
      section: "photos",
    },
    {
      name: "photo2Url",
      label: "URL Foto Polaroid 2",
      type: "image",
      placeholder: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1000&q=80",
      section: "photos",
    },
    {
      name: "photo3Title",
      label: "Keterangan Singkat Foto 3",
      type: "text",
      placeholder: "The Best Squad",
      maxLength: 50,
      section: "photos",
    },
    {
      name: "photo3Caption",
      label: "Caption Foto 3",
      type: "text",
      placeholder: "Good vibes only! Can't wait to dance the night away with you all.",
      maxLength: 120,
      section: "photos",
    },
    {
      name: "photo3Url",
      label: "URL Foto Polaroid 3",
      type: "image",
      placeholder: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1000&q=80",
      section: "photos",
    },

    // --- SECTION: DRESS CODE & KADO DIGITAL ---
    {
      name: "dressCodeTitle",
      label: "Tema Busana (Dress Code)",
      type: "text",
      placeholder: "Y2K Cyberpunk / Neon Glow in the Dark",
      maxLength: 60,
      section: "guide",
    },
    {
      name: "dressCodeNotes",
      label: "Catatan Pedoman Busana",
      type: "text",
      placeholder: "Kenakan busana gelap dengan sentuhan warna neon terang yang bersinar di bawah lampu UV ultraviolet.",
      maxLength: 200,
      section: "guide",
    },
    {
      name: "paletteColor1",
      label: "Kode Hex Swatch 1",
      type: "color",
      placeholder: "#00f2fe",
      section: "guide",
    },
    {
      name: "paletteName1",
      label: "Nama Warna Swatch 1",
      type: "text",
      placeholder: "Electric Cyan",
      maxLength: 30,
      section: "guide",
    },
    {
      name: "paletteColor2",
      label: "Kode Hex Swatch 2",
      type: "color",
      placeholder: "#ff007f",
      section: "guide",
    },
    {
      name: "paletteName2",
      label: "Nama Warna Swatch 2",
      type: "text",
      placeholder: "Hot Magenta",
      maxLength: 30,
      section: "guide",
    },
    {
      name: "paletteColor3",
      label: "Kode Hex Swatch 3",
      type: "color",
      placeholder: "#39ff14",
      section: "guide",
    },
    {
      name: "paletteName3",
      label: "Nama Warna Swatch 3",
      type: "text",
      placeholder: "Laser Lime",
      maxLength: 30,
      section: "guide",
    },
    {
      name: "paletteColor4",
      label: "Kode Hex Swatch 4",
      type: "color",
      placeholder: "#12121e",
      section: "guide",
    },
    {
      name: "paletteName4",
      label: "Nama Warna Swatch 4",
      type: "text",
      placeholder: "Pitch Noir",
      maxLength: 30,
      section: "guide",
    },

    // Hadiah Digital E-Wallet
    {
      name: "giftWalletType",
      label: "Metode / Nama Bank / E-Wallet",
      type: "text",
      placeholder: "BCA / GoPay / Dana",
      maxLength: 50,
      section: "guide",
    },
    {
      name: "giftAccountNo",
      label: "Nomor Rekening / Ponsel E-Wallet",
      type: "text",
      placeholder: "081298765432",
      maxLength: 40,
      section: "guide",
    },
    {
      name: "giftAccountName",
      label: "Nama Pemilik Akun",
      type: "text",
      placeholder: "Natasha Aurelia",
      maxLength: 60,
      section: "guide",
    },
    {
      name: "giftNote",
      label: "Keterangan Kado Ulang Tahun",
      type: "text",
      placeholder: "Kehadiran dan kebersamaan kalian adalah kado paling berharga!",
      maxLength: 200,
      section: "guide",
    },

    // --- SECTION: TEMA WARNA & SYNTHWAVE AUDIO ---
    {
      name: "backgroundColor",
      label: "Warna Latar Belakang Pesta",
      type: "color",
      placeholder: "#090910",
      section: "theme",
    },
    {
      name: "cardColor",
      label: "Warna Kartu & Deck",
      type: "color",
      placeholder: "#12121e",
      section: "theme",
    },
    {
      name: "textColor",
      label: "Warna Teks Utama",
      type: "color",
      placeholder: "#f8fafc",
      section: "theme",
    },
    {
      name: "musicUrl",
      label: "URL Audio Synthwave (.mp3)",
      type: "text",
      placeholder: "https://cdn.pixabay.com/download/audio/2022/10/14/audio_9939f792cb.mp3?filename=synthwave-80s-110045.mp3",
      maxLength: 500,
      section: "theme",
    },
    {
      name: "musicTitle",
      label: "Judul Musik Party",
      type: "text",
      placeholder: "Synthwave Cyber Odyssey Beat",
      maxLength: 60,
      section: "theme",
    },
  ],
  sample: {
    recipientName: "Sahabat Terdekat & VIP Guest",
    ticketCode: "NEON-PASS-2026-VIP",
    vipBadge: "ALL ACCESS VIP // LEVEL 17",
    partySub: "Sweet 17 Cyberpunk Odyssey & Rooftop Rave",
    partyTitle: "NEON ODYSSEY: Natasha's 17th Birthday",
    celebrantName: "Natasha Aurelia",
    ageCelebration: "Sweet Seventeen (17th)",
    partyMessage:
      "Satu malam penuh cahaya neon, dentuman beat synthwave terbaik, dan momen tak terlupakan! Bergabunglah bersamaku untuk merayakan babak baru ke-17 di bawah gemerlap langit malam kota.\n\nMari menari, tertawa, dan abadikan kenangan terbaik bersama sahabat tercinta. Get your VIP pass ready and light up the dance floor with me!",
    senderName: "Natasha & The Crew",
    eventDate: "Jumat, 13 November 2026",
    eventTime: "19.00 WIB s.d. Tengah Malam",
    targetDateIso: "2026-11-13T19:00:00",
    venueName: "Skyline Neon Lounge & Rooftop",
    venueFloor: "32nd Floor Sky Deck & Poolside Foyer",
    venueAddress: "Jl. Jend. Sudirman Kav. 52-53, Kawasan SCBD, Jakarta Selatan",
    mapsUrl: "https://maps.google.com/?q=SCBD+Jakarta",

    session1Time: "19.00 – 19.45 WIB",
    session1Title: "VIP Red Carpet & Neon Face Art",
    session1Desc: "Registrasi tamu VIP, glow face-painting booth, pembagian gelang LED, dan welcome drink.",
    session2Time: "19.45 – 20.45 WIB",
    session2Title: "Warm-Up DJ Set & Finger Food Feast",
    session2Desc: "Iringan musik synthwave chill, santap gourmet mini-burgers & mocktail bar, serta photo session.",
    session3Time: "20.45 – 21.30 WIB",
    session3Title: "17th Birthday Toast & Laser Show",
    session3Desc: "Momen tiup lilin utama ke-17, video kenangan sahabat, dan spektakel laser hologram.",
    session4Time: "21.30 – 23.30 WIB",
    session4Title: "Midnight Rave & Dance Floor Finale",
    session4Desc: "Pesta dansa bersama guest star DJ, confetti party, dan pembagian hadiah best outfit.",

    photo1Title: "Neon Cyber Rebel",
    photo1Caption: "Ready to rock the 17th chapter with full energy and vibrant lights!",
    photo1Url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1000&q=80",

    photo2Title: "City Skyline Glow",
    photo2Caption: "Midnight conversations under the neon towers of the capital.",
    photo2Url: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1000&q=80",

    photo3Title: "The Best Squad",
    photo3Caption: "Good vibes only! Can't wait to dance the night away with you all.",
    photo3Url: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1000&q=80",

    dressCodeTitle: "Y2K Cyberpunk / Neon Glow in the Dark",
    dressCodeNotes: "Kenakan busana gelap dengan sentuhan warna neon terang yang bersinar di bawah lampu UV ultraviolet.",
    paletteColor1: "#00f2fe",
    paletteName1: "Electric Cyan",
    paletteColor2: "#ff007f",
    paletteName2: "Hot Magenta",
    paletteColor3: "#39ff14",
    paletteName3: "Laser Lime",
    paletteColor4: "#12121e",
    paletteName4: "Pitch Noir",

    giftWalletType: "BCA / GoPay / Dana",
    giftAccountNo: "081298765432",
    giftAccountName: "Natasha Aurelia",
    giftNote: "Kehadiran dan kebersamaan kalian adalah kado paling berharga!",

    backgroundColor: "#090910",
    cardColor: "#12121e",
    textColor: "#f8fafc",
    musicUrl: "https://cdn.pixabay.com/download/audio/2022/10/14/audio_9939f792cb.mp3?filename=synthwave-80s-110045.mp3",
    musicTitle: "Synthwave Cyber Odyssey Beat",
  },
};
