import type { TemplateMeta } from "../types";
import {
  SCRAPBOOK_COLOR_PRESETS,
  BACKGROUND_COLOR_PRESETS,
  CARD_COLOR_PRESETS,
  TEXT_COLOR_PRESETS,
} from "../color-presets";

export const loveScrapbookTemplate: TemplateMeta = {
  slug: "love-scrapbook",
  name: "Photobooth Love Scrapbook",
  category: "Romansa",
  tagline:
    "Buku jurnal scrapbook cinta — strip foto photobooth 4-cut, washi tape pastel, memo sticky notes, dan surat tulisan tangan.",
  description:
    "Pengalaman romantis bernuansa buku jurnal kenangan cinta (aesthetic scrapbook journal). Menampilkan strip foto photobooth 4-cut vertikal ala Life4Cuts, hiasan selotip washi tape pastel, lembaran surat di atas kertas kotak-kotak (grid paper), dan 4 kartu memo sticky notes hal-hal kecil favorit tentang pasangan.",
  cardAccent: "bg-pink-50 text-pink-700 ring-1 ring-pink-300",
  highlights: [
    "Strip foto photobooth vertikal 4-frame realistis (Life4Cuts style)",
    "Sampul jurnal scrapbook interaktif dengan efek membuka buku",
    "Lembar surat cinta di atas kertas jurnal grid dengan hiasan washi tape",
    "Empat kartu memo sticky notes pastel (Hal-hal kecil favoritku)",
    "Aksen stiker cinta, klip kertas, dan perangko scrapbook",
    "Pemutar audio akustik lo-fi lembut bergaya pin enamel",
  ],
  fields: [
    // --- SECTION: SAMPUL JURNAL & IDENTITAS ---
    {
      name: "recipientName",
      label: "Nama kekasih (penerima)",
      type: "text",
      placeholder: "Alya Zahra",
      required: true,
      maxLength: 60,
      isRecipient: true,
      section: "cover",
    },
    {
      name: "senderName",
      label: "Nama kamu (pengirim)",
      type: "text",
      placeholder: "Arka Pratama",
      required: true,
      maxLength: 60,
      section: "cover",
    },
    {
      name: "journalTitle",
      label: "Judul jurnal scrapbook",
      type: "text",
      placeholder: "Our Little Moments & Sweet Memories",
      maxLength: 80,
      helperText: "Judul yang tertera pada stiker sampul buku jurnal.",
      section: "cover",
    },
    {
      name: "editionBadge",
      label: "Badge edisi jurnal",
      type: "text",
      placeholder: "Vol. 2 • Captured with Love 📸",
      maxLength: 60,
      section: "cover",
    },
    {
      name: "coverPhotoUrl",
      label: "Foto sampul polaroid jurnal",
      type: "text",
      placeholder:
        "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=600&q=80",
      maxLength: 1000,
      helperText: "Foto mini polaroid yang tertempel dengan washi tape di sampul depan buku jurnal.",
      section: "cover",
    },

    // --- SECTION: STRIP FOTO PHOTOBOOTH 4-CUT ---
    {
      name: "photoboothTitle",
      label: "Judul cetak strip photobooth",
      type: "text",
      placeholder: "Life4Cuts With You • 2024",
      maxLength: 80,
      section: "photobooth",
    },
    {
      name: "photoboothDate",
      label: "Tanggal / Lokasi strip foto",
      type: "text",
      placeholder: "14.07.2024 • Seoul Photobox",
      maxLength: 60,
      section: "photobooth",
    },
    {
      name: "photo1Url",
      label: "Foto 1 (Frame Atas)",
      type: "text",
      placeholder:
        "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=600&q=80",
      maxLength: 1000,
      section: "photobooth",
    },
    {
      name: "photo2Url",
      label: "Foto 2 (Frame Kedua)",
      type: "text",
      placeholder:
        "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=600&q=80",
      maxLength: 1000,
      section: "photobooth",
    },
    {
      name: "photo3Url",
      label: "Foto 3 (Frame Ketiga)",
      type: "text",
      placeholder:
        "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=600&q=80",
      maxLength: 1000,
      section: "photobooth",
    },
    {
      name: "photo4Url",
      label: "Foto 4 (Frame Bawah)",
      type: "text",
      placeholder:
        "https://images.unsplash.com/photo-1513279922550-250c2129b13a?auto=format&fit=crop&w=600&q=80",
      maxLength: 1000,
      section: "photobooth",
    },
    {
      name: "photoboothCaption",
      label: "Catatan kecil di bawah strip foto",
      type: "text",
      placeholder: "Empat pose konyol, sejuta rasa bahagia bersamamu.",
      maxLength: 140,
      section: "photobooth",
    },

    // --- SECTION: FOTO POLAROID EKSTRA & TIKET KENANGAN ---
    {
      name: "polaroidMemoryUrl",
      label: "Foto kenangan polaroid lembar jurnal",
      type: "text",
      placeholder:
        "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=800&q=80",
      maxLength: 1000,
      helperText: "Foto polaroid kenangan manis yang ditempel di lembaran scrapbook.",
      section: "memories",
    },
    {
      name: "polaroidMemoryCaption",
      label: "Keterangan foto polaroid scrapbook",
      type: "text",
      placeholder: "Hari kita jalan berdua seharian penuh tawa.",
      maxLength: 120,
      section: "memories",
    },
    {
      name: "ticketEvent",
      label: "Nama tiket kencan berdua",
      type: "text",
      placeholder: "Tiket Nonton Bioskop & Es Krim Strawberry 🍦",
      maxLength: 80,
      helperText: "Klip tiket kencan manis yang disematkan di jurnal scrapbook.",
      section: "memories",
    },
    {
      name: "ticketDate",
      label: "Tanggal / Detail tiket",
      type: "text",
      placeholder: "Sabtu Sore, 14 Juli 2024 • Kursi D1 & D2",
      maxLength: 60,
      section: "memories",
    },

    // --- SECTION: LEMBAR SURAT GRID JOURNAL ---
    {
      name: "title",
      label: "Judul surat cinta",
      type: "text",
      placeholder: "Halaman Khusus Untuk Pemilik Senyum Manis",
      required: true,
      maxLength: 100,
      section: "letter",
    },
    {
      name: "message",
      label: "Isi surat cinta",
      type: "textarea",
      placeholder:
        "Tuliskan isi surat cintamu di sini...\n\nPisahkan setiap paragraf dengan baris kosong untuk kerapian format kertas kotak-kotak.",
      required: true,
      maxLength: 4000,
      rows: 10,
      section: "letter",
    },
    {
      name: "closingStatement",
      label: "Kalimat penutup",
      type: "text",
      placeholder: "Dengan sejuta peluk dan sayang,",
      maxLength: 80,
      section: "letter",
    },
    {
      name: "signature",
      label: "Tanda tangan",
      type: "text",
      placeholder: "Arka Pratama",
      maxLength: 60,
      section: "letter",
    },

    // --- SECTION: HAL-HAL KECIL FAVORIT (STICKY NOTES) ---
    {
      name: "stickyNotesTitle",
      label: "Judul seksi memo favorit",
      type: "text",
      placeholder: "Hal-Hal Kecil Favoritku Tentangmu 📌",
      maxLength: 80,
      section: "stickynotes",
    },
    {
      name: "memo1",
      label: "Memo 1: Senyuman / Wajah",
      type: "text",
      placeholder: "Caramu tersenyum malu-malu saat kupuji, matamu selalu menyipit gemas.",
      maxLength: 150,
      section: "stickynotes",
    },
    {
      name: "memo2",
      label: "Memo 2: Momen Berdua",
      type: "text",
      placeholder: "Duduk berdampingan di kafe favorit sambil mendengarkan satu earphone berdua.",
      maxLength: 150,
      section: "stickynotes",
    },
    {
      name: "memo3",
      label: "Memo 3: Kebiasaan Lucu",
      type: "text",
      placeholder: "Bagaimana kamu selalu memesan es matcha lalu mencuri kentang gorengku.",
      maxLength: 150,
      section: "stickynotes",
    },
    {
      name: "memo4",
      label: "Memo 4: Harapan Manis",
      type: "text",
      placeholder: "Menciptakan lebih banyak halaman scrapbook kenangan manis bersamamu di masa depan.",
      maxLength: 150,
      section: "stickynotes",
    },

    // --- SECTION: TEMA & AUDIO ---
    {
      name: "primaryColor",
      label: "Warna aksen washi tape & pita",
      type: "color",
      defaultValue: "#f472b6",
      helperText: "Warna selotip washi tape, stiker cinta, dan tombol interaktif.",
      colorPresets: SCRAPBOOK_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "backgroundColor",
      label: "Warna meja / kanvas luar",
      type: "color",
      defaultValue: "#faf7f2",
      helperText: "Warna meja kayu atau kanvas di luar buku jurnal.",
      colorPresets: BACKGROUND_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "cardColor",
      label: "Warna kertas jurnal (Grid Sheet)",
      type: "color",
      defaultValue: "#ffffff",
      helperText: "Warna lembaran kertas jurnal kotak-kotak.",
      colorPresets: CARD_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "textColor",
      label: "Warna teks judul",
      type: "color",
      defaultValue: "#27272a",
      helperText: "Warna teks judul jurnal dan surat.",
      colorPresets: TEXT_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "bodyTextColor",
      label: "Warna teks isi surat",
      type: "color",
      defaultValue: "#4b5563",
      helperText: "Warna tulisan paragraf surat.",
      colorPresets: TEXT_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "musicTitle",
      label: "Judul audio scrapbook (opsional)",
      type: "text",
      placeholder: "Acoustic Ukulele & Coffee Morning",
      maxLength: 80,
      section: "theme",
    },
    {
      name: "bgMusicUrl",
      label: "Tautan audio scrapbook (.mp3)",
      type: "text",
      placeholder: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3",
      maxLength: 1000,
      helperText: "Tautan langsung ke file audio mp3 akustik romantis.",
      section: "theme",
    },
  ],
  sample: {
    recipientName: "Alya Zahra",
    senderName: "Arka Pratama",
    journalTitle: "Our Little Moments & Sweet Memories",
    editionBadge: "Vol. 2 • Captured with Love 📸",
    coverPhotoUrl:
      "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=600&q=80",
    photoboothTitle: "Life4Cuts With You • 2024",
    photoboothDate: "14.07.2024 • Seoul Photobox",
    photo1Url:
      "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=600&q=80",
    photo2Url:
      "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=600&q=80",
    photo3Url:
      "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=600&q=80",
    photo4Url:
      "https://images.unsplash.com/photo-1513279922550-250c2129b13a?auto=format&fit=crop&w=600&q=80",
    photoboothCaption: "Empat pose konyol, sejuta rasa bahagia bersamamu.",
    polaroidMemoryUrl:
      "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=800&q=80",
    polaroidMemoryCaption: "Hari kita jalan berdua seharian penuh tawa dan senyuman manis.",
    ticketEvent: "Tiket Nonton Bioskop & Es Krim Strawberry 🍦",
    ticketDate: "Sabtu Sore, 14 Juli 2024 • Kursi D1 & D2",
    title: "Halaman Khusus Untuk Pemilik Senyum Manis",
    message:
      "Alya,\n\nAda banyak hal di dunia ini yang cepat pudar, tapi caramu membuatku tertawa selalu terekam abadi di kepalaku. Jurnal ini adalah kumpulan remah-remah kebahagiaan yang kita kumpulkan bersama: dari photobooth acak di mall, tawa di tengah kemacetan kota, sampai obrolan larut malam yang tak pernah ingin kita akhiri.\n\nSetiap foto di strip samping membuktikan bahwa hal-hal sederhana bisa berubah menjadi momen paling berharga jika kulalui bersamamu. Kamu adalah warna paling cerah di buku catatanku yang tadinya biasa saja.\n\nTerima kasih sudah menjadi teman bertualang, pendengar terbaik, dan kekasih paling menyenangkan. Mari isi lembaran-lembaran berikutnya dengan lebih banyak petualangan seru berdua!",
    closingStatement: "Dengan sejuta peluk dan sayang,",
    signature: "Arka Pratama",
    stickyNotesTitle: "Hal-Hal Kecil Favoritku Tentangmu 📌",
    memo1: "Caramu tersenyum malu-malu saat kupuji, matamu selalu menyipit gemas.",
    memo2: "Duduk berdampingan di kafe favorit sambil mendengarkan satu earphone berdua.",
    memo3: "Bagaimana kamu selalu memesan es matcha lalu mencuri kentang gorengku.",
    memo4: "Menciptakan lebih banyak halaman scrapbook kenangan manis bersamamu di masa depan.",
    primaryColor: "#f472b6",
    backgroundColor: "#faf7f2",
    cardColor: "#ffffff",
    textColor: "#27272a",
    bodyTextColor: "#4b5563",
    musicTitle: "Acoustic Ukulele & Coffee Morning",
    bgMusicUrl: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3",
  },
};
