import type { TemplateMeta } from "../types";

export const solsticeThawTemplate: TemplateMeta = {
  slug: "solstice-thaw",
  name: "Solstice Thaw",
  category: "Permintaan Maaf",
  description:
    "Surat permohonan maaf dan rekonsiliasi bertema pergantian musim dari dinginnya badai es menuju kehangatan musim semi (Winter Solstice to Spring Thaw). Menampilkan catatan suhu beku titik nol, surat pengakuan di atas kaca berembun (frosted glass), 4 kristal es kesalahan & refleksi jujur, 3 api perapian hangat komitmen perbaikan, 4 tunas bunga salju (snowdrops) kenangan berharga, serta tombol interaktif hembusan kehangatan pelebur es dengan alunan musik piano musim semi yang damai.",
  tagline: "Solstice Thaw: Melelehkan Kebekuan Hati & Menyulut Kembali Api Perapian Kita",
  cardAccent: "border-sky-400/40 bg-gradient-to-br from-slate-950 via-slate-900 to-sky-950 text-sky-200",
  highlights: [
    "Metafora Perubahan Musim: Dari Bekunya Badai Menuju Kehangatan Musim Semi",
    "Catatan Suhu Beku & Piagam Tanggung Jawab Penjaga Perapian Tanpa Alasan",
    "Surat Pengakuan di Balik Kaca Berembun (Frosted Glassmorphism Epistle)",
    "4 Kristal Es Kesalahan (Crystalized Frosts) & Analisis Dampak Luka Batin",
    "3 Api Perapian Perdamaian (Hearthfires of Reparation) sebagai Komitmen Nyata",
    "4 Tunas Bunga Salju (Snowdrops) & Interaksi Hembusan Kehangatan Pelebur Es",
  ],
  fields: [
    // Section 1: Catatan Suhu Beku & Titik Nol
    {
      name: "recipientName",
      label: "Nama Penerima Maaf (The Soul Left in the Cold)",
      type: "text",
      placeholder: "Clarissa Amanda",
      required: true,
      isRecipient: true,
      section: "Catatan Suhu Beku",
    },
    {
      name: "senderName",
      label: "Nama Pemohon Maaf (The Remorseful Hearthkeeper)",
      type: "text",
      placeholder: "Arkananta",
      required: true,
      section: "Catatan Suhu Beku",
    },
    {
      name: "freezeRecordNo",
      label: "Nomor Catatan Beku",
      type: "text",
      placeholder: "SOLSTICE-THAW-2024",
      defaultValue: "SOLSTICE-THAW-2024",
      section: "Catatan Suhu Beku",
    },
    {
      name: "coldestHour",
      label: "Waktu Terjadinya Kebekuan",
      type: "text",
      placeholder: "Malam Terdingin Saat Keheningan Membeku",
      defaultValue: "Malam Terdingin Saat Keheningan Membeku",
      section: "Catatan Suhu Beku",
    },
    {
      name: "frostLocation",
      label: "Ranah / Tempat Terjadinya Kebekuan",
      type: "text",
      placeholder: "The Frozen Valley of Misunderstandings",
      defaultValue: "The Frozen Valley of Misunderstandings",
      section: "Catatan Suhu Beku",
    },
    {
      name: "frostSeverity",
      label: "Tingkat Keparahan Suhu Beku",
      type: "text",
      placeholder: "Sub-Zero Bitter Frost (-18°C) • Lingering Silence",
      defaultValue: "Sub-Zero Bitter Frost (-18°C) • Lingering Silence",
      section: "Catatan Suhu Beku",
    },
    {
      name: "hearthkeeperPledge",
      label: "Ikrar Tanggung Jawab Penjaga Perapian",
      type: "textarea",
      placeholder: "Pengakuan jujur tanpa mencari alasan pembenaran diri...",
      defaultValue:
        "Bukan badai musim dingin di luar yang membekukan ruang ini, melainkan keangkuhan, kata-kata ceroboh, dan keheninganku yang memadamkan nyala perapian. Aku bertanggung jawab penuh atas dinginnya rasa sakit yang kamu rasakan, dan aku hadir di sini dengan tulus membawa kayu bakar kehangatan untuk meleburkannya kembali.",
      section: "Catatan Suhu Beku",
    },

    // Section 2: Surat di Kaca Berembun
    {
      name: "letterTitle",
      label: "Judul Surat Pengakuan",
      type: "text",
      placeholder: "Menghapus Embun Dingin di Antara Kita",
      defaultValue: "Menghapus Embun Dingin di Antara Kita",
      section: "Surat di Kaca Berembun",
    },
    {
      name: "letterDate",
      label: "Tanggal Surat Ditulis",
      type: "text",
      placeholder: "Fajar Titik Balik Musim Dingin",
      defaultValue: "Fajar Titik Balik Musim Dingin",
      section: "Surat di Kaca Berembun",
    },
    {
      name: "mainMessage",
      label: "Isi Surat Pengakuan & Penyesalan",
      type: "textarea",
      placeholder: "Tuliskan surat pengakuan dan penyesalan terdalammu...",
      defaultValue:
        "Clarissa yang terkasih,\n\nKetika jendela di antara kita tertutup rapat dan udara berubah membeku, aku sadar betapa mengerikannya kesunyian yang kuciptakan. Betapa dinginnya jarak yang kurajut ketika aku membiarkan egoku berbicara lebih keras daripada rasa peduliku.\n\nAku melihat bagaimana matamu yang biasanya hangat meredup karena kalimat-kalimat kasarku. Aku melihat bagaimana kamu merapatkan pelukanmu sendiri di sudut dingin karena aku gagal menjadi tempat bernaung yang aman. Tidak ada alasan lelah, tidak ada dalih situasi; yang ada hanyalah kelalaianku menjaga kehangatan yang telah kita rawat bersama selama ini.\n\nMalam ini, aku duduk di dekat abu perapian yang sempat padam. Melalui surat ini, aku ingin mengusap embun beku di kaca pembatas kita dengan telapak tanganku yang penuh penyesalan. Aku tidak menuntutmu untuk langsung tersenyum hangat seperti sedia kala, namun aku ingin kamu tahu: aku bersedia duduk di udara dingin ini selama yang kamu butuhkan, menjaga nyala api kecil ini sampai hatimu kembali merasa aman dan musim semi kita kembali bersemi.",
      section: "Surat di Kaca Berembun",
    },
    {
      name: "letterSignoff",
      label: "Kalimat Penutup Surat",
      type: "text",
      placeholder: "Dengan jemari hangat yang selalu menantimu di dekat perapian,",
      defaultValue: "Dengan jemari hangat yang selalu menantimu di dekat perapian,",
      section: "Surat di Kaca Berembun",
    },

    // Section 3: 4 Kristal Es Kesalahan & Refleksi Jujur
    {
      name: "frost1Title",
      label: "Kristal Es 1: Nama Kesalahan",
      type: "text",
      placeholder: "The Blizzard of Piercing Words",
      defaultValue: "The Blizzard of Piercing Words",
      section: "4 Kristal Es Kesalahan",
    },
    {
      name: "frost1Temp",
      label: "Kristal Es 1: Derajat Suhu Beku",
      type: "text",
      placeholder: "-15°C Sharp Frost",
      defaultValue: "-15°C Sharp Frost",
      section: "4 Kristal Es Kesalahan",
    },
    {
      name: "frost1Confession",
      label: "Kristal Es 1: Pengakuan Kesalahan",
      type: "textarea",
      placeholder: "Pengakuan detail kesalahan...",
      defaultValue:
        "Aku melontarkan kata-kata tajam dengan intonasi meninggi di saat aku seharusnya menurunkan ego dan mendengarkan. Kalimatku melesat bagai pecahan es tajam yang melukai hatimu yang lembut.",
      section: "4 Kristal Es Kesalahan",
    },
    {
      name: "frost1Impact",
      label: "Kristal Es 1: Dampak Luka Batin",
      type: "text",
      placeholder: "Dampak yang dirasakan penerima maaf...",
      defaultValue: "Membuatmu merasa tidak dihargai, takut berbicara jujur, dan terpaksa menarik diri ke dalam kesedihan.",
      section: "4 Kristal Es Kesalahan",
    },

    {
      name: "frost2Title",
      label: "Kristal Es 2: Nama Kesalahan",
      type: "text",
      placeholder: "The Permafrost of Broken Attentiveness",
      defaultValue: "The Permafrost of Broken Attentiveness",
      section: "4 Kristal Es Kesalahan",
    },
    {
      name: "frost2Temp",
      label: "Kristal Es 2: Derajat Suhu Beku",
      type: "text",
      placeholder: "-22°C Frozen Presence",
      defaultValue: "-22°C Frozen Presence",
      section: "4 Kristal Es Kesalahan",
    },
    {
      name: "frost2Confession",
      label: "Kristal Es 2: Pengakuan Kesalahan",
      type: "textarea",
      placeholder: "Pengakuan detail kesalahan...",
      defaultValue:
        "Aku terlalu tenggelam dalam layar gadget dan kesibukan duniaku sendiri. Saat kamu ingin menceritakan kerapuhan harimu, aku hanya merespons dingin tanpa tatapan mata dan tanpa kehangatan empati.",
      section: "4 Kristal Es Kesalahan",
    },
    {
      name: "frost2Impact",
      label: "Kristal Es 2: Dampak Luka Batin",
      type: "text",
      placeholder: "Dampak yang dirasakan penerima maaf...",
      defaultValue: "Membuatmu merasa kesepian di tengah kebersamaan kita dan merasa bebanmu tidak penting bagiku.",
      section: "4 Kristal Es Kesalahan",
    },

    {
      name: "frost3Title",
      label: "Kristal Es 3: Nama Kesalahan",
      type: "text",
      placeholder: "The Glacial Wall of Defensive Pride",
      defaultValue: "The Glacial Wall of Defensive Pride",
      section: "4 Kristal Es Kesalahan",
    },
    {
      name: "frost3Temp",
      label: "Kristal Es 3: Derajat Suhu Beku",
      type: "text",
      placeholder: "-28°C Impenetrable Glacier",
      defaultValue: "-28°C Impenetrable Glacier",
      section: "4 Kristal Es Kesalahan",
    },
    {
      name: "frost3Confession",
      label: "Kristal Es 3: Pengakuan Kesalahan",
      type: "textarea",
      placeholder: "Pengakuan detail kesalahan...",
      defaultValue:
        "Saat kamu mengutarakan kekecewaanmu, naluri pertamaku justru memasang dinding pembelaan diri. Aku membantah dan mencari-cari pembenaran, bukannya langsung merangkul dan memahami lukamu.",
      section: "4 Kristal Es Kesalahan",
    },
    {
      name: "frost3Impact",
      label: "Kristal Es 3: Dampak Luka Batin",
      type: "text",
      placeholder: "Dampak yang dirasakan penerima maaf...",
      defaultValue: "Menghancurkan rasa aman untuk berkomunikasi dan membuat lukamu berlipat ganda karena merasa dihakimi.",
      section: "4 Kristal Es Kesalahan",
    },

    {
      name: "frost4Title",
      label: "Kristal Es 4: Nama Kesalahan",
      type: "text",
      placeholder: "The Long Polar Night of Silence",
      defaultValue: "The Long Polar Night of Silence",
      section: "4 Kristal Es Kesalahan",
    },
    {
      name: "frost4Temp",
      label: "Kristal Es 4: Derajat Suhu Beku",
      type: "text",
      placeholder: "-35°C Polar Freeze",
      defaultValue: "-35°C Polar Freeze",
      section: "4 Kristal Es Kesalahan",
    },
    {
      name: "frost4Confession",
      label: "Kristal Es 4: Pengakuan Kesalahan",
      type: "textarea",
      placeholder: "Pengakuan detail kesalahan...",
      defaultValue:
        "Aku memilih membisu berjam-jam (silent treatment) dan membiarkan ketegangan menggantung tanpa kepastian. Aku sadar sikap membisu ini adalah bentuk keegoisan terdingin yang menyiksa perasaanmu.",
      section: "4 Kristal Es Kesalahan",
    },
    {
      name: "frost4Impact",
      label: "Kristal Es 4: Dampak Luka Batin",
      type: "text",
      placeholder: "Dampak yang dirasakan penerima maaf...",
      defaultValue: "Menimbulkan kecemasan berlebih, rasa terasing, dan ketidakpastian batin yang melelahkan.",
      section: "4 Kristal Es Kesalahan",
    },

    // Section 4: 3 Api Perapian Pelebur Es
    {
      name: "hearthfire1Title",
      label: "Api Perapian 1: Nama Janji",
      type: "text",
      placeholder: "The Flame of Gentle Tenderness",
      defaultValue: "The Flame of Gentle Tenderness",
      section: "3 Api Perapian Pelebur Es",
    },
    {
      name: "hearthfire1Subtitle",
      label: "Api Perapian 1: Subjudul",
      type: "text",
      placeholder: "Komitmen Kelembutan Nada Bicara",
      defaultValue: "Komitmen Kelembutan Nada Bicara",
      section: "3 Api Perapian Pelebur Es",
    },
    {
      name: "hearthfire1Promise",
      label: "Api Perapian 1: Ikrar Komitmen",
      type: "textarea",
      placeholder: "Komitmen nyata yang dijanjikan...",
      defaultValue:
        "Aku bersumpah tidak akan pernah lagi melontarkan kalimat dengan intonasi tinggi atau nada mencemooh. Bila ada emosi yang memuncak, aku akan mengambil napas dalam-dalam dan hanya berbicara dengan nada lembut yang merangkul.",
      section: "3 Api Perapian Pelebur Es",
    },
    {
      name: "hearthfire1Action",
      label: "Api Perapian 1: Bukti Tindakan Nyata",
      type: "text",
      placeholder: "Tindakan konkret harian...",
      defaultValue: "Menurunkan nada bicara, menatap matamu dengan penuh kasih, dan selalu memvalidasi perasaanmu.",
      section: "3 Api Perapian Pelebur Es",
    },

    {
      name: "hearthfire2Title",
      label: "Api Perapian 2: Nama Janji",
      type: "text",
      placeholder: "The Flame of Prompt Warmth",
      defaultValue: "The Flame of Prompt Warmth",
      section: "3 Api Perapian Pelebur Es",
    },
    {
      name: "hearthfire2Subtitle",
      label: "Api Perapian 2: Subjudul",
      type: "text",
      placeholder: "Pantangan Sikap Membisu (No Silent Treatment)",
      defaultValue: "Pantangan Sikap Membisu (No Silent Treatment)",
      section: "3 Api Perapian Pelebur Es",
    },
    {
      name: "hearthfire2Promise",
      label: "Api Perapian 2: Ikrar Komitmen",
      type: "textarea",
      placeholder: "Komitmen nyata yang dijanjikan...",
      defaultValue:
        "Aku berjanji tidak akan pernah membiarkan matahari terbenam dengan kesunyian yang membeku. Jika butuh waktu menenangkan diri, aku akan menyatakannya secara terbuka dan segera kembali untuk berbicara hangat tanpa menghilang.",
      section: "3 Api Perapian Pelebur Es",
    },
    {
      name: "hearthfire2Action",
      label: "Api Perapian 2: Bukti Tindakan Nyata",
      type: "text",
      placeholder: "Tindakan konkret harian...",
      defaultValue: "Komunikasi transparan dalam waktu maksimal 60 menit, memeluk duluan, dan membuka ruang dialog jujur.",
      section: "3 Api Perapian Pelebur Es",
    },

    {
      name: "hearthfire3Title",
      label: "Api Perapian 3: Nama Janji",
      type: "text",
      placeholder: "The Flame of Patient Thawing",
      defaultValue: "The Flame of Patient Thawing",
      section: "3 Api Perapian Pelebur Es",
    },
    {
      name: "hearthfire3Subtitle",
      label: "Api Perapian 3: Subjudul",
      type: "text",
      placeholder: "Kesabaran Memulihkan Kepercayaan",
      defaultValue: "Kesabaran Memulihkan Kepercayaan",
      section: "3 Api Perapian Pelebur Es",
    },
    {
      name: "hearthfire3Promise",
      label: "Api Perapian 3: Ikrar Komitmen",
      type: "textarea",
      placeholder: "Komitmen nyata yang dijanjikan...",
      defaultValue:
        "Aku mengerti bahwa es di hatimu membutuhkan waktu untuk meleleh secara alami. Aku tidak akan mendesakmu untuk langsung melupakan apa yang terjadi. Aku akan konsisten membuktikan ketulusanku melalui tindakan setiap hari.",
      section: "3 Api Perapian Pelebur Es",
    },
    {
      name: "hearthfire3Action",
      label: "Api Perapian 3: Bukti Tindakan Nyata",
      type: "text",
      placeholder: "Tindakan konkret harian...",
      defaultValue: "Menghargai tempo pemulihan hatimu tanpa keluhan, selalu hadir mendampingi, dan konsisten merawat rasa nyaman.",
      section: "3 Api Perapian Pelebur Es",
    },

    // Section 5: 4 Tunas Bunga Salju
    {
      name: "snowdrop1Title",
      label: "Tunas Salju 1: Nama Kenangan Hangat",
      type: "text",
      placeholder: "The Radiance of Your Warm Smile",
      defaultValue: "The Radiance of Your Warm Smile",
      section: "4 Tunas Bunga Salju",
    },
    {
      name: "snowdrop1Memory",
      label: "Tunas Salju 1: Narasi Kenangan",
      type: "textarea",
      placeholder: "Ceritakan kenangan hangat...",
      defaultValue: "Saat kita tertawa lepas di kedai kopi hangat di tengah rintik hujan, melihat binar matamu yang tulus tanpa beban kecemasan.",
      section: "4 Tunas Bunga Salju",
    },
    {
      name: "snowdrop1Meaning",
      label: "Tunas Salju 1: Alasan Layak Diperjuangkan",
      type: "text",
      placeholder: "Makna penting kenangan...",
      defaultValue: "Senyumanmu adalah nyala api perapian terindah yang tidak rela kubiarkan padam karena kecerobohanku.",
      section: "4 Tunas Bunga Salju",
    },

    {
      name: "snowdrop2Title",
      label: "Tunas Salju 2: Nama Kenangan Hangat",
      type: "text",
      placeholder: "The Safe Haven of Our Honest Talks",
      defaultValue: "The Safe Haven of Our Honest Talks",
      section: "4 Tunas Bunga Salju",
    },
    {
      name: "snowdrop2Memory",
      label: "Tunas Salju 2: Narasi Kenangan",
      type: "textarea",
      placeholder: "Ceritakan kenangan hangat...",
      defaultValue: "Momen larut malam saat kita bisa menceritakan ketakutan terdalam kita masing-masing tanpa takut dihakimi atau disudutkan.",
      section: "4 Tunas Bunga Salju",
    },
    {
      name: "snowdrop2Meaning",
      label: "Tunas Salju 2: Alasan Layak Diperjuangkan",
      type: "text",
      placeholder: "Makna penting kenangan...",
      defaultValue: "Ruang saling percaya seperti itu terlalu suci dan langka untuk dihancurkan oleh dinding ego sesaat.",
      section: "4 Tunas Bunga Salju",
    },

    {
      name: "snowdrop3Title",
      label: "Tunas Salju 3: Nama Kenangan Hangat",
      type: "text",
      placeholder: "The Frosts We Overcame Before",
      defaultValue: "The Frosts We Overcame Before",
      section: "4 Tunas Bunga Salju",
    },
    {
      name: "snowdrop3Memory",
      label: "Tunas Salju 3: Narasi Kenangan",
      type: "textarea",
      placeholder: "Ceritakan kenangan hangat...",
      defaultValue: "Tahun lalu saat kita diuji oleh jarak dan ketidakpastian, namun kita berhasil melewatinya karena kita saling memilih untuk bertahan.",
      section: "4 Tunas Bunga Salju",
    },
    {
      name: "snowdrop3Meaning",
      label: "Tunas Salju 3: Alasan Layak Diperjuangkan",
      type: "text",
      placeholder: "Makna penting kenangan...",
      defaultValue: "Ikatan kita memiliki akar yang dalam, dan aku percaya kita bisa tumbuh lebih kuat dan lebih dewasa dari peristiwa ini.",
      section: "4 Tunas Bunga Salju",
    },

    {
      name: "snowdrop4Title",
      label: "Tunas Salju 4: Nama Kenangan Hangat",
      type: "text",
      placeholder: "The Blooming Meadow Ahead",
      defaultValue: "The Blooming Meadow Ahead",
      section: "4 Tunas Bunga Salju",
    },
    {
      name: "snowdrop4Memory",
      label: "Tunas Salju 4: Narasi Kenangan",
      type: "textarea",
      placeholder: "Ceritakan kenangan hangat...",
      defaultValue: "Semua rencana perjalanan, mimpi rumah dengan jendela menghadap fajar, dan tujuan hidup yang ingin kita capai berdampingan.",
      section: "4 Tunas Bunga Salju",
    },
    {
      name: "snowdrop4Meaning",
      label: "Tunas Salju 4: Alasan Layak Diperjuangkan",
      type: "text",
      placeholder: "Makna penting kenangan...",
      defaultValue: "Masa depan indah itu menanti kita di balik musim dingin ini, dan aku ingin menggenggam jemarimu berjalan ke sana.",
      section: "4 Tunas Bunga Salju",
    },

    // Section 6: Warna, Suasana & Musik Pelebur Es
    {
      name: "meltButtonText",
      label: "Teks Tombol Interaktif Kehangatan",
      type: "text",
      placeholder: "Hembuskan Kehangatan Pelebur Es",
      defaultValue: "Hembuskan Kehangatan Pelebur Es",
      section: "Suasana & Musik",
    },
    {
      name: "meltSuccessMessage",
      label: "Pesan Interaksi Sukses",
      type: "text",
      placeholder: "Kehangatan dihantarkan... kristal es mulai meleleh menjadi tetesan embun musim semi.",
      defaultValue: "Kehangatan dihantarkan... kristal es mulai meleleh menjadi tetesan embun musim semi.",
      section: "Suasana & Musik",
    },
    {
      name: "primaryColor",
      label: "Warna Utama Kristal Es",
      type: "color",
      defaultValue: "#38bdf8",
      section: "Suasana & Musik",
    },
    {
      name: "secondaryColor",
      label: "Warna Api Perapian Hangat",
      type: "color",
      defaultValue: "#fbbf24",
      section: "Suasana & Musik",
    },
    {
      name: "accentColor",
      label: "Warna Tunas Musim Semi",
      type: "color",
      defaultValue: "#86efac",
      section: "Suasana & Musik",
    },
    {
      name: "musicTrack",
      label: "URL Musik Latar (Opsional)",
      type: "text",
      placeholder: "https://example.com/audio/spring-thaw-piano.mp3",
      defaultValue: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=winter-solstice-peaceful-piano-112190.mp3",
      section: "Suasana & Musik",
    },
  ],
  sample: {
    recipientName: "Clarissa Amanda",
    senderName: "Arkananta",
    freezeRecordNo: "SOLSTICE-THAW-2024",
    coldestHour: "Malam Terdingin Saat Keheningan Membeku",
    frostLocation: "The Frozen Valley of Misunderstandings",
    frostSeverity: "Sub-Zero Bitter Frost (-18°C) • Lingering Silence",
    hearthkeeperPledge:
      "Bukan badai musim dingin di luar yang membekukan ruang ini, melainkan keangkuhan, kata-kata ceroboh, dan keheninganku yang memadamkan nyala perapian. Aku bertanggung jawab penuh atas dinginnya rasa sakit yang kamu rasakan, dan aku hadir di sini dengan tulus membawa kayu bakar kehangatan untuk meleburkannya kembali.",
    letterTitle: "Menghapus Embun Dingin di Antara Kita",
    letterDate: "Fajar Titik Balik Musim Dingin",
    mainMessage:
      "Clarissa yang terkasih,\n\nKetika jendela di antara kita tertutup rapat dan udara berubah membeku, aku sadar betapa mengerikannya kesunyian yang kuciptakan. Betapa dinginnya jarak yang kurajut ketika aku membiarkan egoku berbicara lebih keras daripada rasa peduliku.\n\nAku melihat bagaimana matamu yang biasanya hangat meredup karena kalimat-kalimat kasarku. Aku melihat bagaimana kamu merapatkan pelukanmu sendiri di sudut dingin karena aku gagal menjadi tempat bernaung yang aman. Tidak ada alasan lelah, tidak ada dalih situasi; yang ada hanyalah kelalaianku menjaga kehangatan yang telah kita rawat bersama selama ini.\n\nMalam ini, aku duduk di dekat abu perapian yang sempat padam. Melalui surat ini, aku ingin mengusap embun beku di kaca pembatas kita dengan telapak tanganku yang penuh penyesalan. Aku tidak menuntutmu untuk langsung tersenyum hangat seperti sedia kala, namun aku ingin kamu tahu: aku bersedia duduk di udara dingin ini selama yang kamu butuhkan, menjaga nyala api kecil ini sampai hatimu kembali merasa aman dan musim semi kita kembali bersemi.",
    letterSignoff: "Dengan jemari hangat yang selalu menantimu di dekat perapian,",
    frost1Title: "The Blizzard of Piercing Words",
    frost1Temp: "-15°C Sharp Frost",
    frost1Confession:
      "Aku melontarkan kata-kata tajam dengan intonasi meninggi di saat aku seharusnya menurunkan ego dan mendengarkan. Kalimatku melesat bagai pecahan es tajam yang melukai hatimu yang lembut.",
    frost1Impact: "Membuatmu merasa tidak dihargai, takut berbicara jujur, dan terpaksa menarik diri ke dalam kesedihan.",
    frost2Title: "The Permafrost of Broken Attentiveness",
    frost2Temp: "-22°C Frozen Presence",
    frost2Confession:
      "Aku terlalu tenggelam dalam layar gadget dan kesibukan duniaku sendiri. Saat kamu ingin menceritakan kerapuhan harimu, aku hanya merespons dingin tanpa tatapan mata dan tanpa kehangatan empati.",
    frost2Impact: "Membuatmu merasa kesepian di tengah kebersamaan kita dan merasa bebanmu tidak penting bagiku.",
    frost3Title: "The Glacial Wall of Defensive Pride",
    frost3Temp: "-28°C Impenetrable Glacier",
    frost3Confession:
      "Saat kamu mengutarakan kekecewaanmu, naluri pertamaku justru memasang dinding pembelaan diri. Aku membantah dan mencari-cari pembenaran, bukannya langsung merangkul dan memahami lukamu.",
    frost3Impact: "Menghancurkan rasa aman untuk berkomunikasi dan membuat lukamu berlipat ganda karena merasa dihakimi.",
    frost4Title: "The Long Polar Night of Silence",
    frost4Temp: "-35°C Polar Freeze",
    frost4Confession:
      "Aku memilih membisu berjam-jam (silent treatment) dan membiarkan ketegangan menggantung tanpa kepastian. Aku sadar sikap membisu ini adalah bentuk keegoisan terdingin yang menyiksa perasaanmu.",
    frost4Impact: "Menimbulkan kecemasan berlebih, rasa terasing, dan ketidakpastian batin yang melelahkan.",
    hearthfire1Title: "The Flame of Gentle Tenderness",
    hearthfire1Subtitle: "Komitmen Kelembutan Nada Bicara",
    hearthfire1Promise:
      "Aku bersumpah tidak akan pernah lagi melontarkan kalimat dengan intonasi tinggi atau nada mencemooh. Bila ada emosi yang memuncak, aku akan mengambil napas dalam-dalam dan hanya berbicara dengan nada lembut yang merangkul.",
    hearthfire1Action: "Menurunkan nada bicara, menatap matamu dengan penuh kasih, dan selalu memvalidasi perasaanmu.",
    hearthfire2Title: "The Flame of Prompt Warmth",
    hearthfire2Subtitle: "Pantangan Sikap Membisu (No Silent Treatment)",
    hearthfire2Promise:
      "Aku berjanji tidak akan pernah membiarkan matahari terbenam dengan kesunyian yang membeku. Jika butuh waktu menenangkan diri, aku akan menyatakannya secara terbuka dan segera kembali untuk berbicara hangat tanpa menghilang.",
    hearthfire2Action: "Komunikasi transparan dalam waktu maksimal 60 menit, memeluk duluan, dan membuka ruang dialog jujur.",
    hearthfire3Title: "The Flame of Patient Thawing",
    hearthfire3Subtitle: "Kesabaran Memulihkan Kepercayaan",
    hearthfire3Promise:
      "Aku mengerti bahwa es di hatimu membutuhkan waktu untuk meleleh secara alami. Aku tidak akan mendesakmu untuk langsung melupakan apa yang terjadi. Aku akan konsisten membuktikan ketulusanku melalui tindakan setiap hari.",
    hearthfire3Action: "Menghargai tempo pemulihan hatimu tanpa keluhan, selalu hadir mendampingi, dan konsisten merawat rasa nyaman.",
    snowdrop1Title: "The Radiance of Your Warm Smile",
    snowdrop1Memory: "Saat kita tertawa lepas di kedai kopi hangat di tengah rintik hujan, melihat binar matamu yang tulus tanpa beban kecemasan.",
    snowdrop1Meaning: "Senyumanmu adalah nyala api perapian terindah yang tidak rela kubiarkan padam karena kecerobohanku.",
    snowdrop2Title: "The Safe Haven of Our Honest Talks",
    snowdrop2Memory: "Momen larut malam saat kita bisa menceritakan ketakutan terdalam kita masing-masing tanpa takut dihakimi atau disudutkan.",
    snowdrop2Meaning: "Ruang saling percaya seperti itu terlalu suci dan langka untuk dihancurkan oleh dinding ego sesaat.",
    snowdrop3Title: "The Frosts We Overcame Before",
    snowdrop3Memory: "Tahun lalu saat kita diuji oleh jarak dan ketidakpastian, namun kita berhasil melewatinya karena kita saling memilih untuk bertahan.",
    snowdrop3Meaning: "Ikatan kita memiliki akar yang dalam, dan aku percaya kita bisa tumbuh lebih kuat dan lebih dewasa dari peristiwa ini.",
    snowdrop4Title: "The Blooming Meadow Ahead",
    snowdrop4Memory: "Semua rencana perjalanan, mimpi rumah dengan jendela menghadap fajar, dan tujuan hidup yang ingin kita capai berdampingan.",
    snowdrop4Meaning: "Masa depan indah itu menanti kita di balik musim dingin ini, dan aku ingin menggenggam jemarimu berjalan ke sana.",
    meltButtonText: "Hembuskan Kehangatan Pelebur Es",
    meltSuccessMessage: "Kehangatan dihantarkan... kristal es mulai meleleh menjadi tetesan embun musim semi.",
    primaryColor: "#38bdf8",
    secondaryColor: "#fbbf24",
    accentColor: "#86efac",
    musicTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=winter-solstice-peaceful-piano-112190.mp3",
  },
};
