import type { TemplateMeta } from "../types";

export const galaAwardTemplate: TemplateMeta = {
  slug: "gala-award",
  name: "The Grand Gala & Annual Award Night",
  category: "Undangan",
  tagline:
    "Undangan malam penganugerahan penghargaan & gala dinner mewah — segel lambang emas, countdown art-deco, galeri red carpet, dan audio orkestra simfoni.",
  description:
    "Undangan resmi prestisius bertema Black-Tie & Champagne Gold bernuansa kemewahan klasik abad ke-20. Menampilkan kartu undangan beludru hitam bersegel emas timbul (*embossed crest*), sapaan tamu kehormatan personal (?to=Nama), live golden countdown timer menuju malam penganugerahan, galeri 3 foto berbingkai emas (piala penghargaan & kemegahan ballroom), rundown 4 sesi gala dinner formal, panduan busana Black-Tie, donasi amal yayasan, dan alunan melodi orkestra waltz simfoni.",
  cardAccent: "bg-amber-950/60 text-amber-200 ring-1 ring-amber-500/40",
  highlights: [
    "Kartu beludru hitam pekat dengan bordir Art Deco & segel lambang emas timbul interaktif",
    "Sapaan tamu kehormatan dinamis melalui tautan (?to=NamaTamu)",
    "Widget Live Golden Countdown Timer menghitung mundur menuju malam penghargaan",
    "Galeri 3 foto red carpet berbingkai emas mewah lengkap dengan takarir resmi",
    "Timeline 4 sesi acara gala (Red Carpet, Imperial Dinner, Awarding, Charity Soirée)",
    "Panduan busana Strictly Black Tie dengan 4 rekomendasi palet warna busana",
    "Dukungan donasi yayasan amal / reservasi meja dengan tombol salin instan",
    "Integrasi peta venue grand ballroom langsung ke Google Maps",
    "Pemutar melodi orkestra waltz simfoni klasik mengambang",
  ],
  fields: [
    // --- SECTION: SAMPUL & SEGEL EMAS ---
    {
      name: "recipientName",
      label: "Nama tamu kehormatan (penerima)",
      type: "text",
      placeholder: "Yang Terhormat Bapak / Ibu Pemimpin & Kolega",
      required: true,
      maxLength: 60,
      isRecipient: true,
      section: "cover",
    },
    {
      name: "invitationNo",
      label: "Nomor resmi undangan gala",
      type: "text",
      placeholder: "INV-GALA-2026-009",
      maxLength: 30,
      section: "cover",
    },
    {
      name: "goldenCrestTitle",
      label: "Teks lambang segel emas",
      type: "text",
      placeholder: "HONORIS CAUSA // EXCELLENCE",
      maxLength: 40,
      section: "cover",
    },
    {
      name: "galaTagline",
      label: "Subjudul acara / Tagline penganugerahan",
      type: "text",
      placeholder: "The 12th Annual Distinction Awards & Charity Gala",
      maxLength: 80,
      section: "cover",
    },

    // --- SECTION: KOMITE & SAMBUTAN ---
    {
      name: "galaTitle",
      label: "Nama resmi malam gala",
      type: "text",
      placeholder: "THE GOLDEN PINNACLE GALA 2026",
      required: true,
      maxLength: 100,
      section: "committee",
    },
    {
      name: "hostCommittee",
      label: "Dewan penyelenggara / Institusi",
      type: "text",
      placeholder: "The Board of Trustees & Foundation Council",
      required: true,
      maxLength: 80,
      section: "committee",
    },
    {
      name: "chairpersonName",
      label: "Ketua Dewan Kehormatan / Tuan Rumah",
      type: "text",
      placeholder: "Lord Arthur Vance & Elizabeth Sterling",
      maxLength: 80,
      section: "committee",
    },
    {
      name: "invitationLetter",
      label: "Naskah surat undangan resmi",
      type: "textarea",
      placeholder:
        "Merupakan suatu kehormatan agung bagi kami untuk mengundang Anda hadir dalam Malam Penganugerahan Penghargaan Tahunan dan Gala Amal Eksklusif...",
      required: true,
      maxLength: 1200,
      section: "committee",
    },
    {
      name: "senderName",
      label: "Nama penutup pengundang",
      type: "text",
      placeholder: "Dewan Pembina Yayasan & Komite Acara",
      required: true,
      maxLength: 60,
      section: "committee",
    },

    // --- SECTION: WAKTU & BALLROOM ---
    {
      name: "eventDate",
      label: "Hari & tanggal malam gala",
      type: "text",
      placeholder: "Sabtu, 19 Desember 2026",
      required: true,
      maxLength: 50,
      section: "event",
    },
    {
      name: "eventTime",
      label: "Waktu pelaksanaan",
      type: "text",
      placeholder: "18.30 – 23.00 WIB",
      required: true,
      maxLength: 50,
      section: "event",
    },
    {
      name: "targetDateIso",
      label: "Waktu ISO untuk Countdown Timer",
      type: "text",
      placeholder: "2026-12-19T18:30:00",
      maxLength: 30,
      helperText: "Format: YYYY-MM-DDTHH:mm:ss (contoh: 2026-12-19T18:30:00).",
      section: "event",
    },
    {
      name: "venueName",
      label: "Nama ballroom / hotel bintang lima",
      type: "text",
      placeholder: "The Grand Ballroom, The Langham Jakarta",
      required: true,
      maxLength: 80,
      section: "event",
    },
    {
      name: "venueFloor",
      label: "Sayap / Lantai ballroom",
      type: "text",
      placeholder: "Main Tower Grand Ballroom & Crystal Foyer",
      maxLength: 60,
      section: "event",
    },
    {
      name: "venueAddress",
      label: "Alamat lengkap venue",
      type: "text",
      placeholder: "District 8, SCBD Lot 28, Senayan, Jakarta Selatan",
      required: true,
      maxLength: 200,
      section: "event",
    },
    {
      name: "mapsUrl",
      label: "Tautan Google Maps",
      type: "text",
      placeholder: "https://maps.google.com/?q=The+Langham+Jakarta",
      maxLength: 300,
      section: "event",
    },

    // --- SECTION: PROGRAM ACARA (4 SESI) ---
    {
      name: "session1Time",
      label: "Waktu Sesi 1",
      type: "text",
      placeholder: "18.30 – 19.30 WIB",
      maxLength: 30,
      section: "rundown",
    },
    {
      name: "session1Title",
      label: "Judul Sesi 1",
      type: "text",
      placeholder: "Red Carpet Arrival & Vintage Champagne Soirée",
      maxLength: 60,
      section: "rundown",
    },
    {
      name: "session1Desc",
      label: "Keterangan Sesi 1",
      type: "text",
      placeholder: "Penyambutan tamu kehormatan, pemotretan di karpet merah, dan toast pembuka di foyer kristal.",
      maxLength: 150,
      section: "rundown",
    },
    {
      name: "session2Time",
      label: "Waktu Sesi 2",
      type: "text",
      placeholder: "19.30 – 20.45 WIB",
      maxLength: 30,
      section: "rundown",
    },
    {
      name: "session2Title",
      label: "Judul Sesi 2",
      type: "text",
      placeholder: "Five-Course Imperial Dinner & Keynote Address",
      maxLength: 60,
      section: "rundown",
    },
    {
      name: "session2Desc",
      label: "Keterangan Sesi 2",
      type: "text",
      placeholder: "Santap malam megah kurasi Master Chef dilanjutkan pidato kehormatan oleh Dewan Pembina.",
      maxLength: 150,
      section: "rundown",
    },
    {
      name: "session3Time",
      label: "Waktu Sesi 3",
      type: "text",
      placeholder: "20.45 – 21.45 WIB",
      maxLength: 30,
      section: "rundown",
    },
    {
      name: "session3Title",
      label: "Judul Sesi 3",
      type: "text",
      placeholder: "The Annual Excellence Awards Conferment",
      maxLength: 60,
      section: "rundown",
    },
    {
      name: "session3Desc",
      label: "Keterangan Sesi 3",
      type: "text",
      placeholder: "Penganugerahan trofi emas piala penghargaan bagi para inovator dan tokoh filantropi bangsa.",
      maxLength: 150,
      section: "rundown",
    },
    {
      name: "session4Time",
      label: "Waktu Sesi 4",
      type: "text",
      placeholder: "21.45 – 23.00 WIB",
      maxLength: 30,
      section: "rundown",
    },
    {
      name: "session4Title",
      label: "Judul Sesi 4",
      type: "text",
      placeholder: "Charity Auction & Symphony Orchestra Waltz",
      maxLength: 60,
      section: "rundown",
    },
    {
      name: "session4Desc",
      label: "Keterangan Sesi 4",
      type: "text",
      placeholder: "Lelang karya seni filantropi dan malam ramah tamah elegan diiringi alunan simfoni klasik.",
      maxLength: 150,
      section: "rundown",
    },

    // --- SECTION: FOTO RED CARPET & BALLROOM (3 FOTO) ---
    {
      name: "photo1Title",
      label: "Keterangan Foto 1",
      type: "text",
      placeholder: "The Golden Pinnacle Trophy",
      maxLength: 60,
      section: "photos",
    },
    {
      name: "photo1Caption",
      label: "Takarir Foto 1",
      type: "text",
      placeholder: "Simbol keagungan dedikasi tanpa henti bagi kemajuan peradaban dan kemanusiaan.",
      maxLength: 120,
      section: "photos",
    },
    {
      name: "photo1Url",
      label: "URL Foto 1",
      type: "image",
      placeholder: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1200&q=80",
      section: "photos",
    },
    {
      name: "photo2Title",
      label: "Keterangan Foto 2",
      type: "text",
      placeholder: "The Crystal Grand Ballroom",
      maxLength: 60,
      section: "photos",
    },
    {
      name: "photo2Caption",
      label: "Takarir Foto 2",
      type: "text",
      placeholder: "Kemegahan lampu gantung kristal yang siap menyambut kehadiran para tokoh terkemuka.",
      maxLength: 120,
      section: "photos",
    },
    {
      name: "photo2Url",
      label: "URL Foto 2",
      type: "image",
      placeholder: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1200&q=80",
      section: "photos",
    },
    {
      name: "photo3Title",
      label: "Keterangan Foto 3",
      type: "text",
      placeholder: "A Prestigious Gathering",
      maxLength: 60,
      section: "photos",
    },
    {
      name: "photo3Caption",
      label: "Takarir Foto 3",
      type: "text",
      placeholder: "Momen perayaan kebersamaan para pemimpin visioner dan sahabat filantropi tanah air.",
      maxLength: 120,
      section: "photos",
    },
    {
      name: "photo3Url",
      label: "URL Foto 3",
      type: "image",
      placeholder: "https://images.unsplash.com/photo-1469371670807-013ccf25f16a?auto=format&fit=crop&w=1200&q=80",
      section: "photos",
    },

    // --- SECTION: DRESS CODE & DONASI AMAL ---
    {
      name: "dressCodeTitle",
      label: "Pedoman Busana (Dress Code)",
      type: "text",
      placeholder: "Strictly Black Tie & Golden Glamour",
      maxLength: 60,
      section: "guide",
    },
    {
      name: "dressCodeNotes",
      label: "Catatan Pedoman Busana",
      type: "text",
      placeholder: "Tuxedo hitam dasi kupu-kupu bagi pria dan gaun malam panjang (formal evening gown) bagi wanita.",
      maxLength: 200,
      section: "guide",
    },
    {
      name: "paletteColor1",
      label: "Kode Hex Swatch 1",
      type: "color",
      placeholder: "#d4af37",
      section: "guide",
    },
    {
      name: "paletteName1",
      label: "Nama Warna Swatch 1",
      type: "text",
      placeholder: "24K Champagne",
      maxLength: 30,
      section: "guide",
    },
    {
      name: "paletteColor2",
      label: "Kode Hex Swatch 2",
      type: "color",
      placeholder: "#0a0a0c",
      section: "guide",
    },
    {
      name: "paletteName2",
      label: "Nama Warna Swatch 2",
      type: "text",
      placeholder: "Midnight Obsidian",
      maxLength: 30,
      section: "guide",
    },
    {
      name: "paletteColor3",
      label: "Kode Hex Swatch 3",
      type: "color",
      placeholder: "#581c25",
      section: "guide",
    },
    {
      name: "paletteName3",
      label: "Nama Warna Swatch 3",
      type: "text",
      placeholder: "Imperial Burgundy",
      maxLength: 30,
      section: "guide",
    },
    {
      name: "paletteColor4",
      label: "Kode Hex Swatch 4",
      type: "color",
      placeholder: "#fbfbf7",
      section: "guide",
    },
    {
      name: "paletteName4",
      label: "Nama Warna Swatch 4",
      type: "text",
      placeholder: "Starlight Pearl",
      maxLength: 30,
      section: "guide",
    },

    // Rekening Donasi Amal
    {
      name: "charityBankName",
      label: "Nama Bank / Lembaga Amal",
      type: "text",
      placeholder: "BCA / The Langham Philanthropy Fund",
      maxLength: 50,
      section: "guide",
    },
    {
      name: "charityAccountNo",
      label: "Nomor Rekening Donasi",
      type: "text",
      placeholder: "8820192837",
      maxLength: 40,
      section: "guide",
    },
    {
      name: "charityAccountName",
      label: "Nama Pemilik Rekening",
      type: "text",
      placeholder: "Yayasan Peduli Nusantara Mandiri",
      maxLength: 60,
      section: "guide",
    },
    {
      name: "charityNote",
      label: "Tujuan Program Donasi",
      type: "text",
      placeholder: "Seluruh donasi dialokasikan untuk beasiswa pendidikan dan program sanitasi desa terpencil.",
      maxLength: 200,
      section: "guide",
    },

    // --- SECTION: TEMA WARNA & ORKESTRA ---
    {
      name: "backgroundColor",
      label: "Warna Latar Belakang (Obsidian)",
      type: "color",
      placeholder: "#0a0a0e",
      section: "theme",
    },
    {
      name: "cardColor",
      label: "Warna Kartu & Frame",
      type: "color",
      placeholder: "#14141c",
      section: "theme",
    },
    {
      name: "textColor",
      label: "Warna Teks Utama",
      type: "color",
      placeholder: "#fdfcf7",
      section: "theme",
    },
    {
      name: "musicUrl",
      label: "URL Audio Orkestra (.mp3)",
      type: "text",
      placeholder: "https://cdn.pixabay.com/download/audio/2022/11/06/audio_c3c3167123.mp3?filename=a-thousand-years-cello-and-piano-orchestra-124991.mp3",
      maxLength: 500,
      section: "theme",
    },
    {
      name: "musicTitle",
      label: "Judul Musik Orkestra",
      type: "text",
      placeholder: "Grand Imperial Waltz Symphony",
      maxLength: 60,
      section: "theme",
    },
  ],
  sample: {
    recipientName: "Yang Terhormat Bapak & Ibu Kolega",
    invitationNo: "INV-GALA-2026-009",
    goldenCrestTitle: "HONORIS CAUSA // EXCELLENCE",
    galaTagline: "The 12th Annual Distinction Awards & Charity Gala",
    galaTitle: "THE GOLDEN PINNACLE GALA 2026",
    hostCommittee: "The Board of Trustees & Foundation Council",
    chairpersonName: "Lord Arthur Vance & Elizabeth Sterling",
    invitationLetter:
      "Merupakan suatu kehormatan agung bagi Dewan Pembina dan Panitia Pelaksana untuk mengundang kehadiran Anda dalam Malam Penganugerahan Penghargaan Tahunan dan Gala Amal Eksklusif.\n\nSebuah malam perayaan yang didedikasikan untuk mengapresiasi dedikasi luar biasa para visioner bangsa, sekaligus menghimpun komitmen filantropi demi masa depan pendidikan generasi penerus.",
    senderName: "Dewan Pembina Yayasan & Komite Acara",
    eventDate: "Sabtu, 19 Desember 2026",
    eventTime: "18.30 – 23.00 WIB",
    targetDateIso: "2026-12-19T18:30:00",
    venueName: "The Grand Ballroom, The Langham Jakarta",
    venueFloor: "Main Tower Grand Ballroom & Crystal Foyer",
    venueAddress: "District 8, SCBD Lot 28, Senayan, Jakarta Selatan",
    mapsUrl: "https://maps.google.com/?q=The+Langham+Jakarta",

    session1Time: "18.30 – 19.30 WIB",
    session1Title: "Red Carpet Arrival & Vintage Champagne Soirée",
    session1Desc: "Penyambutan tamu kehormatan, pemotretan di karpet merah, dan toast pembuka di foyer kristal.",
    session2Time: "19.30 – 20.45 WIB",
    session2Title: "Five-Course Imperial Dinner & Keynote Address",
    session2Desc: "Santap malam megah kurasi Master Chef dilanjutkan pidato kehormatan oleh Dewan Pembina.",
    session3Time: "20.45 – 21.45 WIB",
    session3Title: "The Annual Excellence Awards Conferment",
    session3Desc: "Penganugerahan trofi emas piala penghargaan bagi para inovator dan tokoh filantropi bangsa.",
    session4Time: "21.45 – 23.00 WIB",
    session4Title: "Charity Auction & Symphony Orchestra Waltz",
    session4Desc: "Lelang karya seni filantropi dan malam ramah tamah elegan diiringi alunan simfoni klasik.",

    photo1Title: "The Golden Pinnacle Trophy",
    photo1Caption: "Simbol keagungan dedikasi tanpa henti bagi kemajuan peradaban dan kemanusiaan.",
    photo1Url: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1200&q=80",

    photo2Title: "The Crystal Grand Ballroom",
    photo2Caption: "Kemegahan lampu gantung kristal yang siap menyambut kehadiran para tokoh terkemuka.",
    photo2Url: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1200&q=80",

    photo3Title: "A Prestigious Gathering",
    photo3Caption: "Momen perayaan kebersamaan para pemimpin visioner dan sahabat filantropi tanah air.",
    photo3Url: "https://images.unsplash.com/photo-1469371670807-013ccf25f16a?auto=format&fit=crop&w=1200&q=80",

    dressCodeTitle: "Strictly Black Tie & Golden Glamour",
    dressCodeNotes: "Tuxedo hitam dasi kupu-kupu bagi pria dan gaun malam panjang (formal evening gown) bagi wanita.",
    paletteColor1: "#d4af37",
    paletteName1: "24K Champagne",
    paletteColor2: "#0a0a0c",
    paletteName2: "Midnight Obsidian",
    paletteColor3: "#581c25",
    paletteName3: "Imperial Burgundy",
    paletteColor4: "#fbfbf7",
    paletteName4: "Starlight Pearl",

    charityBankName: "BCA / The Langham Philanthropy Fund",
    charityAccountNo: "8820192837",
    charityAccountName: "Yayasan Peduli Nusantara Mandiri",
    charityNote: "Seluruh donasi dialokasikan untuk beasiswa pendidikan dan program sanitasi desa terpencil.",

    backgroundColor: "#0a0a0e",
    cardColor: "#14141c",
    textColor: "#fdfcf7",
    musicUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    musicTitle: "Grand Imperial Waltz Symphony",
  },
};
