import type { TemplateMeta } from "../types";

export const heritageWeddingTemplate: TemplateMeta = {
  slug: "heritage-wedding",
  name: "The Royal Javanese Heritage Wedding",
  category: "Undangan",
  tagline:
    "Undangan pernikahan agung adat Jawa & Nusantara luhur — gapura gunungan wayang interaktif, segel monogram surya, tata lampah adat 4 prosesi, dan gending syahdu.",
  description:
    "Undangan digital pernikahan adat Jawa Keraton modern dengan nuansa Deep Midnight Indigo dan ukiran emas pusaka Nusantara. Dilengkapi pembuka Gapura Gunungan Wayang kembar interaktif, sapaan uleman tamu dinamis (?to=Nama), kutipan serat suci Ar-Rum, profil agung kedua mempelai Raden Mas & Raden Ajeng dengan foto berbingkai kayu jati, kronometer surya Majapahit, jadwal 4 rangkaian tata lampah adat (Siraman, Midodareni, Ijab Qabul, Upacara Panggih), galeri pasinaon tresna, navigasi peta Sasana Pendopo Agung, panduan busana batik sogan, amplop digital tandha tresna, serta alunan gending gamelan penganten mengambang.",
  cardAccent: "bg-[#0b1320] text-amber-100 ring-1 ring-amber-500/40",
  highlights: [
    "Sampul Gapura Gunungan Wayang kembar interaktif dengan segel lilin monogram surya 3D",
    "Sapaan uleman tamu kehormatan dinamis melalui parameter tautan (?to=NamaTamu)",
    "Pernyataan suci kaluhuran & kutipan ayat sakinah QS. Ar-Rum: 21",
    "Profil agung kedua mempelai berbusana adat keraton dengan silsilah keluarga luhur",
    "Kronometer Surya Majapahit berornamen ukiran cincin emas antik",
    "Jadwal 4 rangkaian tata lampah adat sakral: Siraman, Midodareni, Akad, & Panggih Ageng",
    "Galeri potret prewedding etnik Nusantara dengan pigura ukiran kayu klasik",
    "Petunjuk lokasi Sasana Pawiwahan terintegrasi langsung ke navigasi Google Maps",
    "Panduan busana tamu (Batik Sogan & Beskap/Kebaya) lengkap dengan 4 swatch warna adat",
    "Amplop digital tandha tresna (BCA & Mandiri) dengan tombol salin nomor rekening instan",
    "Alunan gending penganten gamelan Jawa kontemporer mengambang yang syahdu",
  ],
  fields: [
    // --- SECTION: COVER & ULEMAN KEHORMATAN ---
    {
      name: "recipientName",
      label: "Nama tamu uleman kehormatan (penerima)",
      type: "text",
      placeholder: "Bapak / Ibu / Sahabat Ingkang Kinurmatan",
      required: true,
      maxLength: 70,
      isRecipient: true,
      section: "cover",
    },
    {
      name: "waxSealMonogram",
      label: "Inisial segel monogram surya",
      type: "text",
      placeholder: "D & S",
      maxLength: 10,
      helperText: "Inisial nama kedua mempelai (contoh: D & S).",
      section: "cover",
    },
    {
      name: "weddingTagline",
      label: "Tagline acara / Serat Pawiwahan",
      type: "text",
      placeholder: "Pawiwahan Ageng & The Sacred Nusantara Matrimony",
      maxLength: 90,
      section: "cover",
    },
    {
      name: "gununganSubtitle",
      label: "Subjudul gapura adat",
      type: "text",
      placeholder: "Serat Uleman Palakrama Adat Jawi Keraton",
      maxLength: 80,
      section: "cover",
    },

    // --- SECTION: SERAT SUCI & DOA PAMBUKA ---
    {
      name: "holyVerseQuote",
      label: "Kutipan ayat suci / Serat piwulang",
      type: "textarea",
      placeholder:
        "\"Dan di antara tanda-tanda kebesaran-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, agar kamu cenderung dan merasa tenteram kepadanya, dan Dia menjadikan di antaramu rasa kasih dan sayang.\" (QS. Ar-Rum: 21)",
      required: true,
      maxLength: 500,
      section: "blessing",
    },
    {
      name: "invitationMessage",
      label: "Serat uleman pambuka (Pesan undangan)",
      type: "textarea",
      placeholder:
        "Kanthi nyenyuwun lumunturing sih wilasa Dalem Gusti Ingkang Maha Agung, kaparenga kula sakeluwarga ngaturi rawuh panjenengan ing pawiwahan dhauping putra-putri kula...",
      required: true,
      maxLength: 1000,
      section: "blessing",
    },
    {
      name: "eventDate",
      label: "Hari & tanggal utama pawiwahan",
      type: "text",
      placeholder: "Setu Pahing, 12 Desember 2026",
      required: true,
      maxLength: 60,
      section: "blessing",
    },
    {
      name: "targetIsoDate",
      label: "Target ISO countdown (YYYY-MM-DDTHH:mm)",
      type: "text",
      placeholder: "2026-12-12T08:00",
      helperText: "Format tanggal target hitung mundur, contoh: 2026-12-12T08:00.",
      section: "blessing",
    },
    {
      name: "senderFamily",
      label: "Tuan rumah / Keluarga besar pengundang",
      type: "text",
      placeholder: "Keluarga Ageng Bpk. K.R.T. Dananjaya & Bpk. H. Suryonegoro",
      maxLength: 90,
      section: "blessing",
    },

    // --- SECTION: MEMPELAI KAKUNG (PRIA) ---
    {
      name: "groomTitle",
      label: "Sebutan mempelai pria",
      type: "text",
      placeholder: "Mempelai Kakung",
      maxLength: 40,
      section: "couple",
    },
    {
      name: "groomName",
      label: "Nama lengkap mempelai pria & gelar",
      type: "text",
      placeholder: "Raden Mas Dananjaya Bismantara, S.T., M.Sc.",
      required: true,
      maxLength: 80,
      section: "couple",
    },
    {
      name: "groomParents",
      label: "Putra dari (Nama orang tua)",
      type: "text",
      placeholder: "Putra kaping kalih saking Bpk. K.R.T. Dananjaya & Ibu Hj. Ratna Ningsih",
      maxLength: 120,
      section: "couple",
    },
    {
      name: "groomPhotoUrl",
      label: "URL foto mempelai pria (adat)",
      type: "text",
      placeholder: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80",
      section: "couple",
    },

    // --- SECTION: MEMPELAI PUTRI (WANITA) ---
    {
      name: "brideTitle",
      label: "Sebutan mempelai wanita",
      type: "text",
      placeholder: "Mempelai Putri",
      maxLength: 40,
      section: "couple",
    },
    {
      name: "brideName",
      label: "Nama lengkap mempelai wanita & gelar",
      type: "text",
      placeholder: "Raden Ajeng Sekar Kusumaningrum, B.A., M.Des.",
      required: true,
      maxLength: 80,
      section: "couple",
    },
    {
      name: "brideParents",
      label: "Putri dari (Nama orang tua)",
      type: "text",
      placeholder: "Putri pambayun saking Bpk. Dr. H. Suryonegoro & Ibu Hj. Endang Sri Lestari",
      maxLength: 120,
      section: "couple",
    },
    {
      name: "bridePhotoUrl",
      label: "URL foto mempelai wanita (adat)",
      type: "text",
      placeholder: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80",
      section: "couple",
    },

    // --- SECTION: TATA LAMPAH ADAT (4 SESI PROSESI) ---
    {
      name: "session1Time",
      label: "Waktu sesi 1 (Siraman & Bleketepe)",
      type: "text",
      placeholder: "Kemis Kliwon, 10 Des 2026 • 09.00 - 12.00 WIB",
      section: "itinerary",
    },
    {
      name: "session1Title",
      label: "Judul sesi 1",
      type: "text",
      placeholder: "Upacara Siraman & Pasang Bleketepe Tuwuhan",
      section: "itinerary",
    },
    {
      name: "session1Desc",
      label: "Deskripsi sesi 1",
      type: "textarea",
      placeholder: "Prosesi sesuci lair batin ngresiki raga, panyuwunan keselamatan dhumateng Gusti Kang Akarya Jagad.",
      maxLength: 300,
      section: "itinerary",
    },

    {
      name: "session2Time",
      label: "Waktu sesi 2 (Malam Midodareni)",
      type: "text",
      placeholder: "Jemuah Legi, 11 Des 2026 • 19.00 - 21.30 WIB",
      section: "itinerary",
    },
    {
      name: "session2Title",
      label: "Judul sesi 2",
      type: "text",
      placeholder: "Malam Midodareni & Nyantri Penganten",
      section: "itinerary",
    },
    {
      name: "session2Desc",
      label: "Deskripsi sesi 2",
      type: "textarea",
      placeholder: "Malam panyuwunan turunipun bidadari kahyangan, seserahan kancing gelung, lan wejangan catur wedha.",
      maxLength: 300,
      section: "itinerary",
    },

    {
      name: "session3Time",
      label: "Waktu sesi 3 (Akad Nikah)",
      type: "text",
      placeholder: "Setu Pahing, 12 Des 2026 • 08.00 - 10.00 WIB",
      section: "itinerary",
    },
    {
      name: "session3Title",
      label: "Judul sesi 3",
      type: "text",
      placeholder: "Ijab Qabul Khidmat (Akad Nikah)",
      section: "itinerary",
    },
    {
      name: "session3Desc",
      label: "Deskripsi sesi 3",
      type: "textarea",
      placeholder: "Ikrar suci prasetyaning katresnan ing ngarsaning penghulu, wali, lan para saksi pinunjul.",
      maxLength: 300,
      section: "itinerary",
    },

    {
      name: "session4Time",
      label: "Waktu sesi 4 (Panggih & Resepsi)",
      type: "text",
      placeholder: "Setu Pahing, 12 Des 2026 • 11.00 - 14.30 WIB",
      section: "itinerary",
    },
    {
      name: "session4Title",
      label: "Judul sesi 4",
      type: "text",
      placeholder: "Upacara Panggih Penganten & Resepsi Ageng",
      section: "itinerary",
    },
    {
      name: "session4Desc",
      label: "Deskripsi sesi 4",
      type: "textarea",
      placeholder: "Balangan suruh, wijidadi, sinduran, kacar-kucur, dhahar klimah, dilajengaken ramah tamah dhahar sesarengan.",
      maxLength: 300,
      section: "itinerary",
    },

    // --- SECTION: GALERI PASINAON TRESNA ---
    {
      name: "photo1Url",
      label: "URL Foto Galeri 1 (Adat Keraton)",
      type: "text",
      placeholder: "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80",
      section: "gallery",
    },
    {
      name: "photo1Caption",
      label: "Keterangan Foto 1",
      type: "text",
      placeholder: "Rukuning katresnan ingkang kuncara manggala wilasa.",
      section: "gallery",
    },
    {
      name: "photo2Url",
      label: "URL Foto Galeri 2 (Busana Adat)",
      type: "text",
      placeholder: "https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=1200&q=80",
      section: "gallery",
    },
    {
      name: "photo2Caption",
      label: "Keterangan Foto 2",
      type: "text",
      placeholder: "Lumampah sesarengan hanggayuh kasampurnaning gesang.",
      section: "gallery",
    },
    {
      name: "photo3Url",
      label: "URL Foto Galeri 3 (Kebersamaan)",
      type: "text",
      placeholder: "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1200&q=80",
      section: "gallery",
    },
    {
      name: "photo3Caption",
      label: "Keterangan Foto 3",
      type: "text",
      placeholder: "Nyawiji ing rasa, guyub rukun salaminya.",
      section: "gallery",
    },

    // --- SECTION: SASANA PAWIWAHAN (VENUE) ---
    {
      name: "venueName",
      label: "Nama Sasana / Gedung Pawiwahan",
      type: "text",
      placeholder: "Sasana Handrawina Ballroom & Pendopo Ageng Keraton",
      required: true,
      maxLength: 90,
      section: "venue",
    },
    {
      name: "venueHall",
      label: "Nama aula / Paviliun pendopo",
      type: "text",
      placeholder: "Grand Royal Atrium & Courtyard Taman Asri",
      maxLength: 80,
      section: "venue",
    },
    {
      name: "venueAddress",
      label: "Alamat lengkap gedung sasana",
      type: "textarea",
      placeholder: "Kawasan Candi Keraton, Jl. Mayor Kusmanto No. 99, Surakarta, Jawa Tengah 57111",
      required: true,
      maxLength: 250,
      section: "venue",
    },
    {
      name: "mapsUrl",
      label: "Tautan rute Google Maps",
      type: "text",
      placeholder: "https://maps.google.com/?q=Solo+Grand+Ballroom",
      section: "venue",
    },

    // --- SECTION: TATA BUSANA (DRESS CODE) ---
    {
      name: "dressCodeTitle",
      label: "Judul panduan busana tamu",
      type: "text",
      placeholder: "Busana Tradisional Ageng / Batik Formal Nusantara",
      maxLength: 80,
      section: "dresscode",
    },
    {
      name: "dressCodeNote",
      label: "Catatan panduan busana tamu",
      type: "textarea",
      placeholder: "Katuran rawuh ngagem busana Beskap Jawi / Kebaya Nasional utawi Batik Tulis Lengan Panjang kanthi nuansa sogan, navy, lan emas.",
      maxLength: 350,
      section: "dresscode",
    },

    // --- SECTION: TANDHA TRESNA (AMPLOP DIGITAL) ---
    {
      name: "giftInfoTitle",
      label: "Judul seksi tandha tresna",
      type: "text",
      placeholder: "Tandha Asih & Kado Dhigital (Amplop Digital)",
      maxLength: 70,
      section: "gift",
    },
    {
      name: "giftNote",
      label: "Catatan doa restu / amplop digital",
      type: "textarea",
      placeholder: "Donga puji pangestu panjenengan sami sampun dados peparing ingkang tanpa upami tumrap kalih mempelai.",
      maxLength: 350,
      section: "gift",
    },
    {
      name: "bankName1",
      label: "Nama Bank Rekening 1",
      type: "text",
      placeholder: "BCA",
      section: "gift",
    },
    {
      name: "accountNumber1",
      label: "Nomor Rekening 1",
      type: "text",
      placeholder: "8420198811",
      section: "gift",
    },
    {
      name: "accountHolder1",
      label: "Nama Pemilik Rekening 1",
      type: "text",
      placeholder: "Raden Mas Dananjaya",
      section: "gift",
    },
    {
      name: "bankName2",
      label: "Nama Bank Rekening 2",
      type: "text",
      placeholder: "Bank Mandiri",
      section: "gift",
    },
    {
      name: "accountNumber2",
      label: "Nomor Rekening 2",
      type: "text",
      placeholder: "1380029481720",
      section: "gift",
    },
    {
      name: "accountHolder2",
      label: "Nama Pemilik Rekening 2",
      type: "text",
      placeholder: "Raden Ajeng Sekar Kusumaningrum",
      section: "gift",
    },

    // --- SECTION: TEMA WARNA & GENDING AUDIO ---
    {
      name: "primaryColor",
      label: "Warna Utama / Aksen Emas",
      type: "text",
      placeholder: "#c59b27",
      section: "theme",
    },
    {
      name: "backgroundColor",
      label: "Warna Latar Belakang (Deep Navy)",
      type: "text",
      placeholder: "#0b1320",
      section: "theme",
    },
    {
      name: "cardColor",
      label: "Warna Kartu / Daluang",
      type: "text",
      placeholder: "#121d2f",
      section: "theme",
    },
    {
      name: "textColor",
      label: "Warna Teks Emas/Terang",
      type: "text",
      placeholder: "#fef3c7",
      section: "theme",
    },
    {
      name: "musicTitle",
      label: "Judul Gending Penganten",
      type: "text",
      placeholder: "Gamelan Kebo Giro & Seruling Wilasa Syahdu",
      section: "theme",
    },
    {
      name: "musicUrl",
      label: "Tautan File Audio Musik (MP3)",
      type: "text",
      placeholder: "https://cdn.pixabay.com/download/audio/2022/11/06/audio_c3c3167123.mp3?filename=a-thousand-years-cello-and-piano-orchestra-124991.mp3",
      section: "theme",
    },
  ],
  sample: {
    recipientName: "Bapak / Ibu / Sahabat Ingkang Kinurmatan",
    waxSealMonogram: "D & S",
    weddingTagline: "Pawiwahan Ageng & The Sacred Nusantara Matrimony",
    gununganSubtitle: "Serat Uleman Palakrama Adat Jawi Keraton",
    holyVerseQuote:
      "\"Dan di antara tanda-tanda kebesaran-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, agar kamu cenderung dan merasa tenteram kepadanya, dan Dia menjadikan di antaramu rasa kasih dan sayang.\" (QS. Ar-Rum: 21)",
    invitationMessage:
      "Kanthi nyenyuwun lumunturing sih wilasa Dalem Gusti Ingkang Maha Agung, kaparenga kula sakeluwarga ngaturi rawuh panjenengan ing pawiwahan dhauping putra-putri kula.\n\nKehadiran saha doa restu panjenengan sedaya dados tambahing berkah tuwin kamulyan tumrap kalih mempelai anggenipun ngambah gesang bebrayan enggal ingkang sakinah, mawaddah, warahmah.",
    eventDate: "Setu Pahing, 12 Desember 2026",
    targetIsoDate: "2026-12-12T08:00",
    senderFamily: "Keluarga Ageng Bpk. K.R.T. Dananjaya & Bpk. Dr. H. Suryonegoro",

    groomTitle: "Mempelai Kakung",
    groomName: "Raden Mas Dananjaya Bismantara, S.T., M.Sc.",
    groomParents: "Putra kaping kalih saking Bpk. K.R.T. Dananjaya & Ibu Hj. Ratna Ningsih",
    groomPhotoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80",

    brideTitle: "Mempelai Putri",
    brideName: "Raden Ajeng Sekar Kusumaningrum, B.A., M.Des.",
    brideParents: "Putri pambayun saking Bpk. Dr. H. Suryonegoro & Ibu Hj. Endang Sri Lestari",
    bridePhotoUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80",

    session1Time: "Kemis Kliwon, 10 Des 2026 • 09.00 - 12.00 WIB",
    session1Title: "Upacara Siraman & Pasang Bleketepe Tuwuhan",
    session1Desc: "Prosesi sesuci lair batin ngresiki raga, panyuwunan keselamatan dhumateng Gusti Kang Akarya Jagad.",

    session2Time: "Jemuah Legi, 11 Des 2026 • 19.00 - 21.30 WIB",
    session2Title: "Malam Midodareni & Nyantri Penganten",
    session2Desc: "Malam panyuwunan turunipun bidadari kahyangan, seserahan kancing gelung, lan wejangan catur wedha.",

    session3Time: "Setu Pahing, 12 Des 2026 • 08.00 - 10.00 WIB",
    session3Title: "Ijab Qabul Khidmat (Akad Nikah)",
    session3Desc: "Ikrar suci prasetyaning katresnan ing ngarsaning penghulu, wali, lan para saksi pinunjul.",

    session4Time: "Setu Pahing, 12 Des 2026 • 11.00 - 14.30 WIB",
    session4Title: "Upacara Panggih Penganten & Resepsi Ageng",
    session4Desc: "Balangan suruh, wijidadi, sinduran, kacar-kucur, dhahar klimah, dilajengaken ramah tamah dhahar sesarengan.",

    photo1Url: "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80",
    photo1Caption: "Rukuning katresnan ingkang kuncara manggala wilasa.",
    photo2Url: "https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=1200&q=80",
    photo2Caption: "Lumampah sesarengan hanggayuh kasampurnaning gesang.",
    photo3Url: "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1200&q=80",
    photo3Caption: "Nyawiji ing rasa, guyub rukun salaminya.",

    venueName: "Sasana Handrawina Ballroom & Pendopo Ageng Keraton",
    venueHall: "Grand Royal Atrium & Courtyard Taman Asri",
    venueAddress: "Kawasan Candi Keraton, Jl. Mayor Kusmanto No. 99, Surakarta, Jawa Tengah 57111",
    mapsUrl: "https://maps.google.com/?q=Surakarta",

    dressCodeTitle: "Busana Tradisional Ageng / Batik Formal Nusantara",
    dressCodeNote: "Katuran rawuh ngagem busana Beskap Jawi / Kebaya Nasional utawi Batik Tulis Lengan Panjang kanthi nuansa sogan, navy, lan emas.",

    giftInfoTitle: "Tandha Asih & Kado Dhigital (Amplop Digital)",
    giftNote: "Donga puji pangestu panjenengan sami sampun dados peparing ingkang tanpa upami tumrap kalih mempelai.",
    bankName1: "BCA",
    accountNumber1: "8420198811",
    accountHolder1: "Raden Mas Dananjaya",
    bankName2: "Bank Mandiri",
    accountNumber2: "1380029481720",
    accountHolder2: "Raden Ajeng Sekar Kusumaningrum",

    primaryColor: "#c59b27",
    backgroundColor: "#0b1320",
    cardColor: "#121d2f",
    textColor: "#fef3c7",
    musicTitle: "Gamelan Kebo Giro & Seruling Wilasa Syahdu",
    musicUrl: "https://cdn.pixabay.com/download/audio/2022/11/06/audio_c3c3167123.mp3?filename=a-thousand-years-cello-and-piano-orchestra-124991.mp3",
  },
};
