import type { TemplateMeta } from "../types";
import {
  WEDDING_COLOR_PRESETS,
  BACKGROUND_COLOR_PRESETS,
  CARD_COLOR_PRESETS,
  TEXT_COLOR_PRESETS,
} from "../color-presets";

export const mahligaiWeddingTemplate: TemplateMeta = {
  slug: "mahligai-wedding",
  name: "Mahligai Cinta: Pure Indonesian Wedding",
  category: "Undangan",
  tagline:
    "Undangan pernikahan digital murni khas Indonesia bernuansa cerah — cover buka undangan, ayat suci, silsilah mempelai, akad & resepsi, live countdown, perjalanan cinta, galeri prewedding, dan amplop digital.",
  description:
    "Solusi undangan pernikahan digital murni bertema Indonesia yang cerah, anggun, dan sakral. Dilengkapi cover eksklusif berhias nama tamu dinamis (?to=NamaTamu), animasi kelopak bunga melati yang melayang anggun, ayat suci Ar-Rum 21, profil kedua mempelai beserta silsilah orang tua, jadwal akad nikah & resepsi dengan integrasi Google Maps dan Google Calendar, live countdown timer, 4 babak kisah cinta, galeri foto prewedding cerah beresolusi tinggi, amplop digital dengan tombol 1-klik salin nomor rekening, serta buku tamu konfirmasi kehadiran (RSVP) & doa restu.",
  cardAccent: "bg-amber-50 text-amber-900 ring-1 ring-amber-300",
  highlights: [
    "Nuansa cerah nan suci: Warm Ivory, Champagne Gold, dan aksen floral melati nusantara",
    "Animasi kelopak bunga melati/mawar yang gugur melayang perlahan di latar belakang",
    "Cover pembuka interaktif personal (?to=NamaTamu) dengan pemutar audio instrumen romantis",
    "Kutipan ayat suci pernikahan Ar-Rum 21 dan salam pembuka takzim",
    "Profil mempelai pria & wanita lengkap dengan nama silsilah kedua orang tua dan akun Instagram",
    "Rangkaian acara sakral (Akad Nikah & Resepsi) dengan tombol 1-klik Google Maps & Calendar",
    "Widget Live Countdown Timer realtime menuju detik-detik akad pernikahan",
    "Kisah cinta 4 babak: Awal Bertemu, Merajut Komitmen, Khitbah/Lamaran, & Janji Suci",
    "Galeri foto prewedding cerah dengan modal lightbox pembesar & slot video teaser",
    "Amplop digital tanda kasih: Rekening BCA, Mandiri, QRIS, dan alamat kado fisik dengan toast salin instan",
    "Formulir RSVP konfirmasi kehadiran interaktif serta daftar ucapan doa restu keluarga dan sahabat",
    "Floating navigation bar untuk kemudahan berselancar di layar smartphone",
  ],
  fields: [
    // --- 1. COVER & HERO GATEWAY ---
    {
      name: "recipientName",
      label: "Nama tamu undangan default",
      type: "text",
      placeholder: "Bapak / Ibu / Saudara/i",
      helperText: "Akan digantikan otomatis jika dibuka dengan parameter tautan URL (?to=NamaTamu).",
      required: true,
      maxLength: 100,
      isRecipient: true,
      section: "hero",
    },
    {
      name: "weddingTitle",
      label: "Judul Cover Undangan",
      type: "text",
      placeholder: "The Wedding Celebration",
      required: true,
      maxLength: 100,
      section: "hero",
    },
    {
      name: "brideNickname",
      label: "Nama Panggilan Mempelai Wanita",
      type: "text",
      placeholder: "Shinta",
      required: true,
      maxLength: 40,
      section: "hero",
    },
    {
      name: "groomNickname",
      label: "Nama Panggilan Mempelai Pria",
      type: "text",
      placeholder: "Rama",
      required: true,
      maxLength: 40,
      section: "hero",
    },
    {
      name: "weddingDateText",
      label: "Teks Tanggal Hari H",
      type: "text",
      placeholder: "Minggu, 24 Oktober 2026",
      required: true,
      maxLength: 80,
      section: "hero",
    },
    {
      name: "coverPhoto",
      label: "Foto Sampul Utama Prewedding",
      type: "image",
      helperText: "Foto utama bertema cerah untuk cover & hero pembuka.",
      section: "hero",
    },
    {
      name: "openButtonText",
      label: "Teks Tombol Buka Undangan",
      type: "text",
      placeholder: "Buka Undangan",
      maxLength: 40,
      section: "hero",
    },

    // --- 2. AYAT SUCI & DOA PEMBUKA ---
    {
      name: "basmalahText",
      label: "Teks Kaligrafi / Basmalah",
      type: "text",
      placeholder: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
      maxLength: 80,
      section: "verse",
    },
    {
      name: "verseQuote",
      label: "Kutipan Ayat Pernikahan / Janji Suci",
      type: "textarea",
      placeholder: "Dan di antara tanda-tanda (kebesaran)-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, agar kamu cenderung dan merasa tenteram kepadanya, dan Dia menjadikan di antaramu rasa kasih dan sayang. Sungguh, pada yang demikian itu benar-benar terdapat tanda-tanda bagi kaum yang berpikir.",
      required: true,
      maxLength: 600,
      section: "verse",
    },
    {
      name: "verseSource",
      label: "Sumber Ayat / Kutipan",
      type: "text",
      placeholder: "QS. Ar-Rum: 21",
      maxLength: 60,
      section: "verse",
    },
    {
      name: "greetingText",
      label: "Salam & Kata Pengantar Undangan",
      type: "textarea",
      placeholder: "Assalamu'alaikum Warahmatullahi Wabarakatuh\nDengan memohon rahmat dan ridho Allah Subhanahu Wa Ta'ala, kami bermaksud mengundang Bapak/Ibu/Saudara/i untuk menghadiri dan memberikan doa restu pada hari pernikahan kami:",
      required: true,
      maxLength: 500,
      section: "verse",
    },

    // --- 3. PROFIL KEDUA MEMPELAI ---
    {
      name: "brideFullName",
      label: "Nama Lengkap Mempelai Wanita (beserta Gelar)",
      type: "text",
      placeholder: "Shinta Kirana Maharani, S.Ds.",
      required: true,
      maxLength: 80,
      section: "couple",
    },
    {
      name: "brideParents",
      label: "Silsilah Orang Tua Mempelai Wanita",
      type: "text",
      placeholder: "Putri pertama dari Bpk. Ir. Hendra Gunawan & Ibu Hj. Ratna Dewi",
      required: true,
      maxLength: 120,
      section: "couple",
    },
    {
      name: "brideInstagram",
      label: "Username Instagram Mempelai Wanita",
      type: "text",
      placeholder: "@shintakirana",
      maxLength: 50,
      section: "couple",
    },
    {
      name: "bridePhoto",
      label: "Foto Potret Mempelai Wanita",
      type: "image",
      helperText: "Foto potret berbusana cerah/anggun untuk mempelai wanita.",
      section: "couple",
    },
    {
      name: "groomFullName",
      label: "Nama Lengkap Mempelai Pria (beserta Gelar)",
      type: "text",
      placeholder: "Rama Adiputra Pratama, M.Kom.",
      required: true,
      maxLength: 80,
      section: "couple",
    },
    {
      name: "groomParents",
      label: "Silsilah Orang Tua Mempelai Pria",
      type: "text",
      placeholder: "Putra bungsu dari Bpk. Drs. H. Bambang Suryono & Ibu Hj. Sri Rahayu",
      required: true,
      maxLength: 120,
      section: "couple",
    },
    {
      name: "groomInstagram",
      label: "Username Instagram Mempelai Pria",
      type: "text",
      placeholder: "@ramapratama",
      maxLength: 50,
      section: "couple",
    },
    {
      name: "groomPhoto",
      label: "Foto Potret Mempelai Pria",
      type: "image",
      helperText: "Foto potret berbusana jas/beskap cerah untuk mempelai pria.",
      section: "couple",
    },

    // --- 4. RANGKAIAN ACARA SAKRAL ---
    {
      name: "akadTitle",
      label: "Judul Acara Sesi 1 (Akad Nikah / Pemberkatan)",
      type: "text",
      placeholder: "Akad Nikah",
      required: true,
      maxLength: 50,
      section: "events",
    },
    {
      name: "akadDayDate",
      label: "Hari & Tanggal Akad Nikah",
      type: "text",
      placeholder: "Minggu, 24 Oktober 2026",
      required: true,
      maxLength: 60,
      section: "events",
    },
    {
      name: "akadTime",
      label: "Waktu Pelaksanaan Akad Nikah",
      type: "text",
      placeholder: "Pukul 08.00 - 10.00 WIB",
      required: true,
      maxLength: 50,
      section: "events",
    },
    {
      name: "akadVenue",
      label: "Nama Tempat / Gedung / Masjid Akad",
      type: "text",
      placeholder: "Masjid Agung Al-Barkah",
      required: true,
      maxLength: 80,
      section: "events",
    },
    {
      name: "akadAddress",
      label: "Alamat Lengkap Lokasi Akad",
      type: "textarea",
      placeholder: "Jl. Veteran No. 12, Kebayoran Baru, Jakarta Selatan",
      required: true,
      maxLength: 250,
      section: "events",
    },
    {
      name: "akadMapsUrl",
      label: "Tautan Google Maps Lokasi Akad",
      type: "text",
      placeholder: "https://maps.google.com/?q=Jakarta",
      maxLength: 300,
      section: "events",
    },
    {
      name: "resepsiTitle",
      label: "Judul Acara Sesi 2 (Resepsi Pernikahan)",
      type: "text",
      placeholder: "Resepsi Pernikahan",
      required: true,
      maxLength: 50,
      section: "events",
    },
    {
      name: "resepsiDayDate",
      label: "Hari & Tanggal Resepsi Pernikahan",
      type: "text",
      placeholder: "Minggu, 24 Oktober 2026",
      required: true,
      maxLength: 60,
      section: "events",
    },
    {
      name: "resepsiTime",
      label: "Waktu Pelaksanaan Resepsi",
      type: "text",
      placeholder: "Pukul 11.00 - 14.00 WIB",
      required: true,
      maxLength: 50,
      section: "events",
    },
    {
      name: "resepsiVenue",
      label: "Nama Tempat / Ballroom Resepsi",
      type: "text",
      placeholder: "Grand Ballroom Balai Kartini",
      required: true,
      maxLength: 80,
      section: "events",
    },
    {
      name: "resepsiAddress",
      label: "Alamat Lengkap Lokasi Resepsi",
      type: "textarea",
      placeholder: "Jl. Gatot Subroto No. 37, Kuningan Barat, Mampang Prapatan, Jakarta Selatan",
      required: true,
      maxLength: 250,
      section: "events",
    },
    {
      name: "resepsiMapsUrl",
      label: "Tautan Google Maps Lokasi Resepsi",
      type: "text",
      placeholder: "https://maps.google.com/?q=Jakarta",
      maxLength: 300,
      section: "events",
    },
    {
      name: "calendarEventDate",
      label: "Tanggal Kalender (Format YYYY-MM-DD)",
      type: "text",
      placeholder: "2026-10-24",
      helperText: "Dipakai untuk sinkronisasi tombol Tambah ke Google Calendar.",
      maxLength: 20,
      section: "events",
    },

    // --- 5. HITUNG MUNDUR ACARA ---
    {
      name: "targetDate",
      label: "Waktu Target Hitung Mundur (ISO / YYYY-MM-DDTHH:mm:ss)",
      type: "text",
      placeholder: "2026-10-24T08:00:00",
      helperText: "Waktu dimulainya akad nikah untuk perhitungan countdown live.",
      required: true,
      maxLength: 30,
      section: "countdown",
    },
    {
      name: "countdownTitle",
      label: "Judul Bagian Hitung Mundur",
      type: "text",
      placeholder: "Menghitung Hari Bahagia",
      maxLength: 80,
      section: "countdown",
    },
    {
      name: "countdownSubtitle",
      label: "Kutipan / Deskripsi Hitung Mundur",
      type: "textarea",
      placeholder: "Tiada yang lebih indah selain menanti waktu dipersatukannya dua insan dalam ikatan suci mahligai pernikahan.",
      maxLength: 250,
      section: "countdown",
    },

    // --- 6. PERJALANAN CINTA (LOVE STORY) ---
    {
      name: "storyTitle",
      label: "Judul Bagian Kisah Kasih",
      type: "text",
      placeholder: "Kisah Kasih Kami",
      maxLength: 80,
      section: "story",
    },
    {
      name: "storySubtitle",
      label: "Subjudul Kisah Kasih",
      type: "text",
      placeholder: "Sebuah perjalanan indah yang dirajut oleh takdir, doa, dan kesetiaan.",
      maxLength: 150,
      section: "story",
    },
    {
      name: "story1Year",
      label: "Tahun Fase 1 (Awal Perjumpaan)",
      type: "text",
      placeholder: "2019",
      maxLength: 20,
      section: "story",
    },
    {
      name: "story1Title",
      label: "Judul Fase 1",
      type: "text",
      placeholder: "Pertemuan Pertama",
      maxLength: 60,
      section: "story",
    },
    {
      name: "story1Desc",
      label: "Deskripsi Fase 1",
      type: "textarea",
      placeholder: "Berawal dari perkenalan sederhana di bangku perkuliahan, percakapan hangat yang mengalir tanpa canggung menjadi awal mula getaran rasa yang kami simpan di dalam dada.",
      maxLength: 350,
      section: "story",
    },
    {
      name: "story2Year",
      label: "Tahun Fase 2 (Merajut Komitmen)",
      type: "text",
      placeholder: "2021",
      maxLength: 20,
      section: "story",
    },
    {
      name: "story2Title",
      label: "Judul Fase 2",
      type: "text",
      placeholder: "Merajut Janji Bersama",
      maxLength: 60,
      section: "story",
    },
    {
      name: "story2Desc",
      label: "Deskripsi Fase 2",
      type: "textarea",
      placeholder: "Kami memutuskan untuk saling mendampingi di setiap suka dan duka. Belajar saling memahami kekurangan dan bertumbuh bersama menjadi pribadi yang lebih dewasa.",
      maxLength: 350,
      section: "story",
    },
    {
      name: "story3Year",
      label: "Tahun Fase 3 (Lamaran / Khitbah)",
      type: "text",
      placeholder: "2024",
      maxLength: 20,
      section: "story",
    },
    {
      name: "story3Title",
      label: "Judul Fase 3",
      type: "text",
      placeholder: "Ikrar Khitbah & Restu Orang Tua",
      maxLength: 60,
      section: "story",
    },
    {
      name: "story3Desc",
      label: "Deskripsi Fase 3",
      type: "textarea",
      placeholder: "Dengan diiringi restu tulus kedua orang tua dan keluarga besar, langkah serius kami mantapkan dalam ikatan pertunangan suci yang penuh haru dan kebahagiaan.",
      maxLength: 350,
      section: "story",
    },
    {
      name: "story4Year",
      label: "Tahun Fase 4 (Menuju Mahligai Suci)",
      type: "text",
      placeholder: "2026",
      maxLength: 20,
      section: "story",
    },
    {
      name: "story4Title",
      label: "Judul Fase 4",
      type: "text",
      placeholder: "Mahligai Rumah Tangga",
      maxLength: 60,
      section: "story",
    },
    {
      name: "story4Desc",
      label: "Deskripsi Fase 4",
      type: "textarea",
      placeholder: "Insya Allah, ikrar suci akan kami ikrarkan di hadapan Sang Maha Pencipta untuk mengarungi bahtera kehidupan bersama hingga akhir hayat dalam sakinah, mawaddah, warahmah.",
      maxLength: 350,
      section: "story",
    },

    // --- 7. GALERI PREWEDDING & VIDEO ---
    {
      name: "galleryTitle",
      label: "Judul Bagian Galeri",
      type: "text",
      placeholder: "Potret Bahagia Kami",
      maxLength: 80,
      section: "gallery",
    },
    {
      name: "gallerySubtitle",
      label: "Subjudul Bagian Galeri",
      type: "text",
      placeholder: "Kumpulan momen hangat dan senyuman tulus menyambut hari suci.",
      maxLength: 150,
      section: "gallery",
    },
    {
      name: "photo1",
      label: "Foto Galeri 1 (Prewedding Utama)",
      type: "image",
      helperText: "Foto potret berdua dengan busana cerah/pastel.",
      section: "gallery",
    },
    {
      name: "photo1Caption",
      label: "Keterangan Foto 1",
      type: "text",
      placeholder: "Janji dalam Pandangan",
      maxLength: 60,
      section: "gallery",
    },
    {
      name: "photo2",
      label: "Foto Galeri 2 (Cincin & Detail)",
      type: "image",
      helperText: "Foto cincin pernikahan atau detail busana pengantin.",
      section: "gallery",
    },
    {
      name: "photo2Caption",
      label: "Keterangan Foto 2",
      type: "text",
      placeholder: "Simbol Ikatan Abadi",
      maxLength: 60,
      section: "gallery",
    },
    {
      name: "photo3",
      label: "Foto Galeri 3 (Tawa Bahagia)",
      type: "image",
      helperText: "Foto tawa ceria bersama pasangan.",
      section: "gallery",
    },
    {
      name: "photo3Caption",
      label: "Keterangan Foto 3",
      type: "text",
      placeholder: "Langkah Seirama",
      maxLength: 60,
      section: "gallery",
    },
    {
      name: "photo4",
      label: "Foto Galeri 4 (Lanskap Terang)",
      type: "image",
      helperText: "Foto pemandangan alam terbuka yang cerah.",
      section: "gallery",
    },
    {
      name: "photo4Caption",
      label: "Keterangan Foto 4",
      type: "text",
      placeholder: "Menatap Hari Esok Bersama",
      maxLength: 60,
      section: "gallery",
    },
    {
      name: "videoUrl",
      label: "Tautan Video Teaser YouTube (Opsional)",
      type: "text",
      placeholder: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      helperText: "Video YouTube teaser prewedding yang dapat diputar langsung di undangan.",
      maxLength: 300,
      section: "gallery",
    },

    // --- 8. TANDA KASIH & AMPLOP DIGITAL ---
    {
      name: "giftTitle",
      label: "Judul Bagian Amplop Digital",
      type: "text",
      placeholder: "Tanda Kasih & Amplop Digital",
      maxLength: 80,
      section: "gift",
    },
    {
      name: "giftSubtitle",
      label: "Deskripsi Pengantar Tanda Kasih",
      type: "textarea",
      placeholder: "Doa restu Anda adalah karunia yang paling berharga bagi kami. Namun jika Anda berkenan memberikan tanda kasih sebagai hadiah pernikahan, dapat disalurkan melalui rekening berikut:",
      maxLength: 350,
      section: "gift",
    },
    {
      name: "bank1Name",
      label: "Nama Bank 1",
      type: "text",
      placeholder: "Bank Central Asia (BCA)",
      maxLength: 50,
      section: "gift",
    },
    {
      name: "bank1Number",
      label: "Nomor Rekening Bank 1",
      type: "text",
      placeholder: "5420987654",
      maxLength: 40,
      section: "gift",
    },
    {
      name: "bank1AccountName",
      label: "Nama Pemilik Rekening Bank 1",
      type: "text",
      placeholder: "Shinta Kirana Maharani",
      maxLength: 80,
      section: "gift",
    },
    {
      name: "bank2Name",
      label: "Nama Bank 2",
      type: "text",
      placeholder: "Bank Mandiri / BSI",
      maxLength: 50,
      section: "gift",
    },
    {
      name: "bank2Number",
      label: "Nomor Rekening Bank 2",
      type: "text",
      placeholder: "1270009876543",
      maxLength: 40,
      section: "gift",
    },
    {
      name: "bank2AccountName",
      label: "Nama Pemilik Rekening Bank 2",
      type: "text",
      placeholder: "Rama Adiputra Pratama",
      maxLength: 80,
      section: "gift",
    },
    {
      name: "qrisPhoto",
      label: "Foto / Gambar Barcode QRIS (Opsional)",
      type: "image",
      helperText: "Gambar kode QRIS untuk mempermudah transfer lewat Gopay, ShopeePay, OVO, atau m-Banking.",
      section: "gift",
    },
    {
      name: "giftAddress",
      label: "Alamat Pengiriman Kado Fisik (Opsional)",
      type: "textarea",
      placeholder: "Perumahan Griya Indah Asri Blok C-12, Jl. Kenanga No. 5, Kebayoran Baru, Jakarta Selatan 12150 (Penerima: Rama & Shinta / 0812-3456-7890)",
      maxLength: 300,
      section: "gift",
    },

    // --- 9. BUKU TAMU & RSVP DOA RESTU ---
    {
      name: "rsvpTitle",
      label: "Judul Bagian RSVP & Ucapan Doa",
      type: "text",
      placeholder: "Konfirmasi Kehadiran & Doa Restu",
      maxLength: 80,
      section: "rsvp",
    },
    {
      name: "rsvpSubtitle",
      label: "Subjudul RSVP",
      type: "textarea",
      placeholder: "Merupakan kehormatan dan kebahagiaan bagi kami apabila Bapak/Ibu/Saudara/i berkenan hadir serta melantunkan doa restu untuk mahligai suci kami.",
      maxLength: 250,
      section: "rsvp",
    },

    // --- 10. UNGKAPAN TERIMA KASIH & PENUTUP ---
    {
      name: "closingTitle",
      label: "Judul Bagian Penutup",
      type: "text",
      placeholder: "Terima Kasih",
      maxLength: 60,
      section: "closing",
    },
    {
      name: "closingMessage",
      label: "Pesan Doa & Ungkapan Syukur Penutup",
      type: "textarea",
      placeholder: "Atas kehadiran, perhatian, serta doa restu yang tulus dari Bapak/Ibu/Saudara/i sekalian, kami sekeluarga besar menghaturkan sembah sujud dan terima kasih yang tiada terhingga.",
      required: true,
      maxLength: 400,
      section: "closing",
    },
    {
      name: "closingSalutation",
      label: "Salam Penutup",
      type: "text",
      placeholder: "Wassalamu'alaikum Warahmatullahi Wabarakatuh",
      maxLength: 80,
      section: "closing",
    },
    {
      name: "closingFamilyGroom",
      label: "Keluarga Besar Pihak Pria",
      type: "text",
      placeholder: "Keluarga Besar Bpk. Drs. H. Bambang Suryono & Ibu Hj. Sri Rahayu",
      maxLength: 120,
      section: "closing",
    },
    {
      name: "closingFamilyBride",
      label: "Keluarga Besar Pihak Wanita",
      type: "text",
      placeholder: "Keluarga Besar Bpk. Ir. Hendra Gunawan & Ibu Hj. Ratna Dewi",
      maxLength: 120,
      section: "closing",
    },
    {
      name: "closingSignature",
      label: "Tanda Tangan Nama Kedua Mempelai",
      type: "text",
      placeholder: "Rama & Shinta",
      required: true,
      maxLength: 60,
      section: "closing",
    },
    {
      name: "audioUrl",
      label: "Tautan Lagu Romantis Pengiring (MP3 Audio)",
      type: "audio",
      placeholder: "https://assets.mixkit.co/music/preview/mixkit-romantic-moment-1100.mp3",
      helperText: "Lagu romantis yang diputar lembut saat undangan dibuka.",
      section: "closing",
    },

    // --- PENGATURAN TAMPILAN & WARNA CERAH ---
    {
      name: "primaryColor",
      label: "Warna Aksen Utama (Gold / Rose / Sage)",
      type: "color",
      defaultValue: "#c59a3f",
      colorPresets: WEDDING_COLOR_PRESETS,
      section: "style",
    },
    {
      name: "backgroundColor",
      label: "Warna Latar Belakang (Cerah Hangat)",
      type: "color",
      defaultValue: "#fdfbf7",
      colorPresets: BACKGROUND_COLOR_PRESETS,
      section: "style",
    },
    {
      name: "cardColor",
      label: "Warna Kartu Kontainer",
      type: "color",
      defaultValue: "#ffffff",
      colorPresets: CARD_COLOR_PRESETS,
      section: "style",
    },
    {
      name: "textColor",
      label: "Warna Teks Utama",
      type: "color",
      defaultValue: "#332a1f",
      colorPresets: TEXT_COLOR_PRESETS,
      section: "style",
    },
  ],
  sample: {
    recipientName: "Tamu Undangan Terhormat",
    weddingTitle: "The Wedding Celebration of",
    brideNickname: "Shinta",
    groomNickname: "Rama",
    weddingDateText: "Minggu, 24 Oktober 2026",
    coverPhoto:
      "https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=1200&q=80",
    openButtonText: "Buka Undangan",

    basmalahText: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    verseQuote:
      "Dan di antara tanda-tanda (kebesaran)-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, agar kamu cenderung dan merasa tenteram kepadanya, dan Dia menjadikan di antaramu rasa kasih dan sayang. Sungguh, pada yang demikian itu benar-benar terdapat tanda-tanda bagi kaum yang berpikir.",
    verseSource: "QS. Ar-Rum: 21",
    greetingText:
      "Assalamu'alaikum Warahmatullahi Wabarakatuh\nDengan memohon rahmat dan ridho Allah Subhanahu Wa Ta'ala, kami bermaksud mengundang Bapak/Ibu/Saudara/i untuk menghadiri dan memberikan doa restu pada hari pernikahan kami:",

    brideFullName: "Shinta Kirana Maharani, S.Ds.",
    brideParents: "Putri pertama dari Bpk. Ir. Hendra Gunawan & Ibu Hj. Ratna Dewi",
    brideInstagram: "@shintakirana",
    bridePhoto:
      "https://images.unsplash.com/photo-1594552072238-b8a33785b261?auto=format&fit=crop&w=800&q=80",

    groomFullName: "Rama Adiputra Pratama, M.Kom.",
    groomParents: "Putra bungsu dari Bpk. Drs. H. Bambang Suryono & Ibu Hj. Sri Rahayu",
    groomInstagram: "@ramapratama",
    groomPhoto:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80",

    akadTitle: "Akad Nikah",
    akadDayDate: "Minggu, 24 Oktober 2026",
    akadTime: "Pukul 08.00 - 10.00 WIB",
    akadVenue: "Masjid Agung Al-Barkah",
    akadAddress: "Jl. Veteran No. 12, Kebayoran Baru, Jakarta Selatan",
    akadMapsUrl: "https://maps.google.com/?q=Jakarta",

    resepsiTitle: "Resepsi Pernikahan",
    resepsiDayDate: "Minggu, 24 Oktober 2026",
    resepsiTime: "Pukul 11.00 - 14.00 WIB",
    resepsiVenue: "Grand Ballroom Balai Kartini",
    resepsiAddress: "Jl. Gatot Subroto No. 37, Kuningan Barat, Mampang Prapatan, Jakarta Selatan",
    resepsiMapsUrl: "https://maps.google.com/?q=Jakarta",
    calendarEventDate: "2026-10-24",

    targetDate: "2026-10-24T08:00:00",
    countdownTitle: "Menghitung Hari Bahagia",
    countdownSubtitle:
      "Tiada yang lebih indah selain menanti waktu dipersatukannya dua insan dalam ikatan suci mahligai pernikahan.",

    storyTitle: "Kisah Kasih Kami",
    storySubtitle: "Sebuah perjalanan indah yang dirajut oleh takdir, doa, dan kesetiaan.",
    story1Year: "2019",
    story1Title: "Pertemuan Pertama",
    story1Desc:
      "Berawal dari perkenalan sederhana di bangku perkuliahan, percakapan hangat yang mengalir tanpa canggung menjadi awal mula getaran rasa yang kami simpan di dalam dada.",
    story2Year: "2021",
    story2Title: "Merajut Janji Bersama",
    story2Desc:
      "Kami memutuskan untuk saling mendampingi di setiap suka dan duka. Belajar saling memahami kekurangan dan bertumbuh bersama menjadi pribadi yang lebih dewasa.",
    story3Year: "2024",
    story3Title: "Ikrar Khitbah & Restu Orang Tua",
    story3Desc:
      "Dengan diiringi restu tulus kedua orang tua dan keluarga besar, langkah serius kami mantapkan dalam ikatan pertunangan suci yang penuh haru dan kebahagiaan.",
    story4Year: "2026",
    story4Title: "Mahligai Rumah Tangga",
    story4Desc:
      "Insya Allah, ikrar suci akan kami ikrarkan di hadapan Sang Maha Pencipta untuk mengarungi bahtera kehidupan bersama hingga akhir hayat dalam sakinah, mawaddah, warahmah.",

    galleryTitle: "Potret Bahagia Kami",
    gallerySubtitle: "Kumpulan momen hangat dan senyuman tulus menyambut hari suci.",
    photo1:
      "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80",
    photo1Caption: "Janji dalam Pandangan",
    photo2:
      "https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?auto=format&fit=crop&w=800&q=80",
    photo2Caption: "Simbol Ikatan Abadi",
    photo3:
      "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=800&q=80",
    photo3Caption: "Langkah Seirama",
    photo4:
      "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?auto=format&fit=crop&w=800&q=80",
    photo4Caption: "Menatap Hari Esok Bersama",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",

    giftTitle: "Tanda Kasih & Amplop Digital",
    giftSubtitle:
      "Doa restu Anda adalah karunia yang paling berharga bagi kami. Namun jika Anda berkenan memberikan tanda kasih sebagai hadiah pernikahan, dapat disalurkan melalui rekening berikut:",
    bank1Name: "Bank Central Asia (BCA)",
    bank1Number: "5420987654",
    bank1AccountName: "Shinta Kirana Maharani",
    bank2Name: "Bank Mandiri",
    bank2Number: "1270009876543",
    bank2AccountName: "Rama Adiputra Pratama",
    qrisPhoto:
      "https://images.unsplash.com/photo-1556742049-0a67c5574f73?auto=format&fit=crop&w=600&q=80",
    giftAddress:
      "Perumahan Griya Indah Asri Blok C-12, Jl. Kenanga No. 5, Kebayoran Baru, Jakarta Selatan 12150 (Penerima: Rama & Shinta / 0812-3456-7890)",

    rsvpTitle: "Konfirmasi Kehadiran & Doa Restu",
    rsvpSubtitle:
      "Merupakan kehormatan dan kebahagiaan bagi kami apabila Bapak/Ibu/Saudara/i berkenan hadir serta melantunkan doa restu untuk mahligai suci kami.",

    closingTitle: "Terima Kasih",
    closingMessage:
      "Atas kehadiran, perhatian, serta doa restu yang tulus dari Bapak/Ibu/Saudara/i sekalian, kami sekeluarga besar menghaturkan sembah sujud dan terima kasih yang tiada terhingga.",
    closingSalutation: "Wassalamu'alaikum Warahmatullahi Wabarakatuh\nKami yang berbahagia,",
    closingFamilyGroom:
      "Keluarga Besar Bpk. Drs. H. Bambang Suryono & Ibu Hj. Sri Rahayu",
    closingFamilyBride:
      "Keluarga Besar Bpk. Ir. Hendra Gunawan & Ibu Hj. Ratna Dewi",
    closingSignature: "Rama & Shinta",
    audioUrl: "https://assets.mixkit.co/music/preview/mixkit-romantic-moment-1100.mp3",

    primaryColor: "#c59a3f", // Warm Champagne Gold
    backgroundColor: "#fdfbf7", // Warm Ivory Cerah
    cardColor: "#ffffff", // Pure White Card
    textColor: "#332a1f", // Deep Warm Earth
  },
};
