import type { TemplateMeta } from "../types";
import {
  BIRTHDAY_COLOR_PRESETS,
  BACKGROUND_COLOR_PRESETS,
  CARD_COLOR_PRESETS,
  TEXT_COLOR_PRESETS,
} from "../color-presets";

export const birthdayTemplate: TemplateMeta = {
  slug: "birthday",
  name: "Birthday Tribute Website",
  category: "Perayaan",
  tagline: "Website perayaan ulang tahun interaktif dengan tiup lilin, memori foto, doa terindah, dan musik pesta.",
  description:
    "Website perayaan ulang tahun personal yang imersif dan meriah. Dilengkapi potret utama, kue interaktif dengan lilin yang bisa ditiup (menghasilkan ledakan konfeti & pesan rahasia), galeri polaroid kenangan, linimasa babak usia, kartu doa pilihan, surat ucapan menyentuh, serta pemutar musik pesta.",
  cardAccent: "bg-amber-500/15 text-amber-600",
  highlights: [
    "Ritual interaktif tiup lilin kue ulang tahun & konfeti",
    "Galeri foto kenangan polaroid dengan lightbox popup",
    "Metrik usia hidup & 3 babak momen membanggakan",
    "4 kartu doa & harapan terindah untuk penerima",
    "Kustomisasi warna multi-elemen bebas & pemutar audio pesta",
  ],
  fields: [
    // 1. Warna Multi-Elemen
    {
      name: "primaryColor",
      label: "Warna Aksen Utama",
      type: "color",
      defaultValue: "#e8453c",
      helperText: "Warna tombol pesta, api lilin, badge perayaan, angka usia, dan aksen kado.",
      colorPresets: BIRTHDAY_COLOR_PRESETS,
    },
    {
      name: "backgroundColor",
      label: "Warna Latar Belakang Website",
      type: "color",
      defaultValue: "#fffdf9",
      helperText: "Warna kanvas seluruh halaman perayaan.",
      colorPresets: BACKGROUND_COLOR_PRESETS,
    },
    {
      name: "cardColor",
      label: "Warna Kartu & Kotak Konten",
      type: "color",
      defaultValue: "#ffffff",
      helperText: "Warna dasar kartu kue, galeri polaroid, dan amplop surat.",
      colorPresets: CARD_COLOR_PRESETS,
    },
    {
      name: "textColor",
      label: "Warna Teks Judul",
      type: "color",
      defaultValue: "#1f1b16",
      helperText: "Warna nama yang berulang tahun dan judul-judul perayaan.",
      colorPresets: TEXT_COLOR_PRESETS,
    },
    {
      name: "bodyTextColor",
      label: "Warna Teks Isi & Doa",
      type: "color",
      defaultValue: "#4a3e31",
      helperText: "Warna narasi paragraf, kutipan doa, dan isi surat.",
      colorPresets: TEXT_COLOR_PRESETS,
    },

    // 2. Yang Berulang Tahun & Cover (Hero)
    {
      name: "recipientName",
      label: "Nama yang Berulang Tahun",
      type: "text",
      placeholder: "Dinda Anandita",
      required: true,
      maxLength: 60,
      isRecipient: true,
    },
    {
      name: "senderName",
      label: "Nama Pengirim / Pemberi Ucapan",
      type: "text",
      placeholder: "Geng Kosan & Sahabat",
      required: true,
      maxLength: 60,
    },
    {
      name: "age",
      label: "Usia yang Dirayakan",
      type: "number",
      placeholder: "24",
      required: true,
      min: 1,
      max: 120,
      helperText: "Ditampilkan megah pada badge & kartu perayaan.",
    },
    {
      name: "greeting",
      label: "Sapaan Pembuka",
      type: "text",
      placeholder: "Selamat Ulang Tahun Ke-24! 🎉",
      required: true,
      maxLength: 80,
      defaultValue: "Selamat Ulang Tahun! 🎉",
    },
    {
      name: "heroBadge",
      label: "Badge Perayaan",
      type: "text",
      placeholder: "✨ Official Birthday Tribute for Our Favorite Human",
      maxLength: 80,
      defaultValue: "✨ Official Birthday Tribute for You",
    },
    {
      name: "title",
      label: "Judul Utama Perayaan",
      type: "text",
      placeholder: "Merayakan Hari Kelahiran Dinda",
      required: true,
      maxLength: 100,
      defaultValue: "Merayakan Hari Spesialmu",
    },
    {
      name: "tagline",
      label: "Tagline / Pesan Hangat Pembuka",
      type: "textarea",
      placeholder: "Terima kasih telah hadir di dunia, menebarkan tawa yang tulus, dan menjadi cahaya bagi orang-orang di sekelilingmu.",
      maxLength: 300,
      rows: 3,
    },
    {
      name: "heroImage",
      label: "Foto Potret Utama",
      type: "text",
      placeholder: "https://...",
      helperText: "Foto terbaik orang yang berulang tahun.",
    },
    {
      name: "birthDate",
      label: "Tanggal Lahir / Hari Ulang Tahun",
      type: "date",
      helperText: "Digunakan untuk menghitung pencapaian hari-hari hidup yang penuh berkah.",
    },

    // 3. Kue & Ritual Tiup Lilin
    {
      name: "cakeTitle",
      label: "Judul Kue Perayaan",
      type: "text",
      placeholder: "Kue Impian & Doa Terindah",
      maxLength: 80,
      defaultValue: "Kue Ulang Tahun & Permohonan Tulus",
    },
    {
      name: "cakeWishPrompt",
      label: "Ajakan Tiup Lilin",
      type: "text",
      placeholder: "Tutup matamu, buat satu permohonan tulus, lalu tiup lilinnya!",
      maxLength: 120,
      defaultValue: "Tutup matamu, buat satu permohonan di dalam hati, lalu tiup lilinnya!",
    },
    {
      name: "secretWishMessage",
      label: "Pesan Kejutan Rahasia (Muncul Setelah Lilin Ditiup)",
      type: "textarea",
      placeholder: "Semoga semua harapan, impian besar, dan doa terbaikmu di usia ini dikabulkan semesta. Tetaplah bahagia dan bersinar! 🎂✨",
      maxLength: 300,
      rows: 3,
      defaultValue: "Semoga di usia baru ini setiap impian besarmu didekatkan, langkahmu dimudahkan, dan kebahagiaan selalu memelukmu tanpa henti! 🎂✨",
    },

    // 4. Linimasa Babak Usia
    {
      name: "milestoneTitle",
      label: "Judul Linimasa Usia",
      type: "text",
      placeholder: "Babak-Babak Berharga Dalam Hidupmu",
      maxLength: 80,
      defaultValue: "Jejak Langkah & Pencapaian Membanggakan",
    },
    { name: "milestone1Year", label: "Tahun / Periode 1", type: "text", maxLength: 30 },
    { name: "milestone1Title", label: "Judul Babak 1", type: "text", maxLength: 80 },
    { name: "milestone1Desc", label: "Deskripsi Babak 1", type: "textarea", maxLength: 300, rows: 2 },
    { name: "milestone2Year", label: "Tahun / Periode 2", type: "text", maxLength: 30 },
    { name: "milestone2Title", label: "Judul Babak 2", type: "text", maxLength: 80 },
    { name: "milestone2Desc", label: "Deskripsi Babak 2", type: "textarea", maxLength: 300, rows: 2 },
    { name: "milestone3Year", label: "Tahun / Periode 3", type: "text", maxLength: 30 },
    { name: "milestone3Title", label: "Judul Babak 3", type: "text", maxLength: 80 },
    { name: "milestone3Desc", label: "Deskripsi Babak 3", type: "textarea", maxLength: 300, rows: 2 },

    // 5. Galeri Foto Kenangan Polaroid
    {
      name: "galleryTitle",
      label: "Judul Galeri Kenangan",
      type: "text",
      placeholder: "Potret Kenangan & Momen Manis Kita",
      maxLength: 80,
      defaultValue: "Galeri Senyuman & Momen Manis",
    },
    {
      name: "gallerySubtitle",
      label: "Subjudul Galeri",
      type: "text",
      placeholder: "Kumpulan tawa, petualangan, dan detik-detik berharga bersamamu.",
      maxLength: 160,
    },
    { name: "galleryImg1", label: "Foto 1", type: "text" },
    { name: "galleryCaption1", label: "Caption 1", type: "text", maxLength: 100 },
    { name: "galleryDate1", label: "Tahun/Lokasi 1", type: "text", maxLength: 50 },
    { name: "galleryImg2", label: "Foto 2", type: "text" },
    { name: "galleryCaption2", label: "Caption 2", type: "text", maxLength: 100 },
    { name: "galleryDate2", label: "Tahun/Lokasi 2", type: "text", maxLength: 50 },
    { name: "galleryImg3", label: "Foto 3", type: "text" },
    { name: "galleryCaption3", label: "Caption 3", type: "text", maxLength: 100 },
    { name: "galleryDate3", label: "Tahun/Lokasi 3", type: "text", maxLength: 50 },
    { name: "galleryImg4", label: "Foto 4", type: "text" },
    { name: "galleryCaption4", label: "Caption 4", type: "text", maxLength: 100 },
    { name: "galleryDate4", label: "Tahun/Lokasi 4", type: "text", maxLength: 50 },
    { name: "galleryImg5", label: "Foto 5", type: "text" },
    { name: "galleryCaption5", label: "Caption 5", type: "text", maxLength: 100 },
    { name: "galleryDate5", label: "Tahun/Lokasi 5", type: "text", maxLength: 50 },
    { name: "galleryImg6", label: "Foto 6", type: "text" },
    { name: "galleryCaption6", label: "Caption 6", type: "text", maxLength: 100 },
    { name: "galleryDate6", label: "Tahun/Lokasi 6", type: "text", maxLength: 50 },

    // 6. Doa & Harapan Terbaik
    {
      name: "wishesTitle",
      label: "Judul Bagian Doa & Harapan",
      type: "text",
      placeholder: "Doa & Harapan Tulus di Usia Baru",
      maxLength: 80,
      defaultValue: "Doa & Harapan Terbaik Untukmu",
    },
    { name: "wish1", label: "Doa 1 (Kesehatan & Jiwa)", type: "text", maxLength: 160 },
    { name: "wish2", label: "Doa 2 (Karier & Langkah Masa Depan)", type: "text", maxLength: 160 },
    { name: "wish3", label: "Doa 3 (Kebahagiaan & Kedamaian)", type: "text", maxLength: 160 },
    { name: "wish4", label: "Doa 4 (Harapan Impian Terbesar)", type: "text", maxLength: 160 },

    // 7. Surat Utama
    {
      name: "quote",
      label: "Kutipan Harapan Pembuka",
      type: "text",
      placeholder: "Semoga tahun ini menjadi tahun yang paling membahagiakan untukmu.",
      maxLength: 160,
    },
    {
      name: "message",
      label: "Isi Surat Ucapan Lengkap",
      type: "textarea",
      placeholder: "Tuliskan seluruh doa, curahan terima kasih, dan harapan tulusmu di sini...",
      required: true,
      maxLength: 4000,
      rows: 10,
    },
    {
      name: "signature",
      label: "Tanda Tangan Pengirim",
      type: "text",
      placeholder: "Dari kami yang selalu menyayangimu, Geng Kosan",
      maxLength: 80,
    },
    { name: "letterDate", label: "Tanggal Surat", type: "date" },

    // 8. Musik Latar
    {
      name: "musicTitle",
      label: "Judul Musik Latar",
      type: "text",
      placeholder: "Happy Birthday Celebration Melody",
      maxLength: 80,
    },
    {
      name: "bgMusicUrl",
      label: "Tautan Langsung Audio (.mp3)",
      type: "text",
      maxLength: 1000,
    },
  ],
  sample: {
    primaryColor: "#e8453c",
    backgroundColor: "#fffdf9",
    cardColor: "#ffffff",
    textColor: "#1f1b16",
    bodyTextColor: "#4a3e31",
    recipientName: "Dinda Anandita",
    senderName: "Geng Kosan & Sahabat",
    age: 24,
    greeting: "Selamat Ulang Tahun Ke-24! 🎉",
    heroBadge: "✨ Official Birthday Tribute for Our Favorite Human",
    title: "Merayakan Hari Bahagia Dinda",
    tagline:
      "Terima kasih telah lahir ke dunia, membawa jutaan tawa lepas, dan selalu menjadi alasan kenapa hari-hari biasa terasa begitu berwarna.",
    heroImage:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1000&q=80",
    birthDate: "2002-09-21",

    cakeTitle: "Kue Impian & Ritual Tiup Lilin",
    cakeWishPrompt: "Tutup matamu sejenak, buat satu permohonan tulus di hati, lalu tiup lilinnya!",
    secretWishMessage:
      "Semoga di usia 24 tahun ini, setiap impian besar yang kamu simpan dalam doa segera terwujud. Tetaplah menjadi Dinda yang hangat, kuat, dan selalu bangga atas dirimu sendiri! 🎂✨",

    milestoneTitle: "Jejak Langkah & Kisah Berhargamu",
    milestone1Year: "2020",
    milestone1Title: "Awal Petualangan Baru",
    milestone1Desc: "Hari pertama merantau, beradaptasi dengan lingkungan baru dan membuktikan keberanianmu melangkah mandiri.",
    milestone2Year: "2023",
    milestone2Title: "Pencapaian Besar & Karya Terbaik",
    milestone2Desc: "Menyelesaikan tanggung jawab besar dengan senyum bangga dan tekad pantang menyerah.",
    milestone3Year: "2026",
    milestone3Title: "Menyambut Usia Penuh Harapan",
    milestone3Desc: "Melangkah mantap menuju babak kedewasaan yang penuh berkah, karya cemerlang, dan kebahagiaan.",

    galleryTitle: "Galeri Senyuman & Tawa Bersama",
    gallerySubtitle: "Potret-potret kebersamaan yang membuktikan bahwa memiliki kamu adalah anugerah terindah.",
    galleryImg1:
      "https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=800&q=80",
    galleryCaption1: "Pesta kejutan kecil penuh tawa",
    galleryDate1: "Kosan Ceria, 2024",
    galleryImg2:
      "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=800&q=80",
    galleryCaption2: "Momen seru liburan akhir tahun",
    galleryDate2: "Pantai Indah, 2024",
    galleryImg3:
      "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80",
    galleryCaption3: "Kue pertama buatan sendiri",
    galleryDate3: "Dapur Kosan, 2025",
    galleryImg4:
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=800&q=80",
    galleryCaption4: "Konser musik & bernyanyi kencang berdua",
    galleryDate4: "Jakarta, 2025",
    galleryImg5:
      "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=800&q=80",
    galleryCaption5: "Senja santai & obrolan masa depan",
    galleryDate5: "Bandung, 2025",
    galleryImg6:
      "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?auto=format&fit=crop&w=800&q=80",
    galleryCaption6: "Malam syukuran penuh doa",
    galleryDate6: "Rumah Makan, 2026",

    wishesTitle: "Empat Doa Tulus Untukmu di Usia Baru",
    wish1: "Semoga selalu dilimpahi kesehatan raga, ketenangan jiwa, dan tidur malam yang selalu nyenyak.",
    wish2: "Semoga langkah karier dan studimu dibukakan pintu kemudahan seluas-luasnya dengan hasil terbaik.",
    wish3: "Semoga hatimu selalu dipenuhi rasa syukur, dikelilingi orang-orang baik, dan dijauhkan dari beban pikiran.",
    wish4: "Semoga impian terbesar yang sedang kamu perjuangkan tahun ini menjadi kenyataan yang membanggakan.",

    quote: "Semoga tahun ini menjadi tahun yang paling ramah, penuh berkah, dan sebaik tawamu.",
    message:
      "Dua puluh empat tahun yang lalu, semesta menghadirkan orang sehebat kamu ke dunia.\n\nKamu adalah orang yang paling cepat bilang “ayo berangkat” setiap kali ada yang butuh teman bicara, orang yang tulus mendengarkan tanpa menghakimi, dan sosok yang selalu menebarkan energi positif ke mana pun kamu pergi.\n\nDi ulang tahunmu yang ke-24 ini, kami hanya ingin kamu tahu betapa bersyukurnya kami bisa berjalan di sampingmu. Semoga kamu tidak pernah lupa betapa berharganya dirimu, betapa hebatnya setiap langkah yang sudah kamu tempuh, dan betapa banyak orang yang mendoakan kebaikanmu setiap hari.\n\nSelamat bertambah usia, Dinda! Rayakan hari ini dengan senyuman paling lebar.",
    signature: "Dengan tulus & sayang, Teman-teman Kosan",
    letterDate: "2026-09-21",
    musicTitle: "",
    bgMusicUrl: "",
  },
};
