import type { TemplateMeta } from "../types";

export const exLibrisTemplate: TemplateMeta = {
  slug: "ex-libris",
  name: "Ex Libris",
  category: "Surat Romantis",
  description:
    "Surat cinta sastra klasik bergaya buku antik edisi pertama langka (Antiquarian First Edition). Menampilkan etiket cap buku Ex Libris kolektor pribadi, kata pengantar penulis berhuruf inisial berornamen emas (illuminated drop cap), 4 bab narasi perjalanan cinta (Caput I-IV), 4 catatan pinggir bertinta sepia (handwritten marginalia), spesifikasi kurasi penjilidan kulit Florentine, serta tombol interaktif penyemat pita pembatas buku sutra merah tua dengan alunan melodi selo perpustakaan kuno.",
  tagline: "Ex Libris: Menjilid Kisah Cinta Abadi Kita Menjadi Buku Antik Langka",
  cardAccent: "border-amber-400/40 bg-gradient-to-br from-[#1a0f12] via-[#241418] to-[#12080a] text-amber-200",
  highlights: [
    "Konsep Buku Antik Edisi Pertama: Mengabadikan Cinta Sebagai Mahakarya Sastra Klasik",
    "Etiket Cap Ex Libris Kolektor Pribadi (Ex Libris Bookplate Seal)",
    "Surat Kata Pengantar Penulis (Author's Epistolary Foreword) di Kertas Katun Berserat",
    "4 Bab Narasi Cinta (Caput I-IV) Lengkap dengan Kutipan Pembuka (Epigraph)",
    "4 Catatan Pinggir Tulisan Tangan (Handwritten Marginalia) Bertinta Sepia",
    "Interaksi Pita Pembatas Buku Sutra (Silk Ribbon Bookmark) & Melodi Selo Klasik",
  ],
  fields: [
    // Section 1: Etiket Ex Libris & Hak Cipta
    {
      name: "recipientName",
      label: "Nama Sang Muse / Pemilik Buku (Ex Libris)",
      type: "text",
      placeholder: "Seraphina Eleanor",
      required: true,
      isRecipient: true,
      section: "Etiket Ex Libris & Hak Cipta",
    },
    {
      name: "senderName",
      label: "Nama Penulis / Peracik Kata (The Wordsmith)",
      type: "text",
      placeholder: "Theodore Vance",
      required: true,
      section: "Etiket Ex Libris & Hak Cipta",
    },
    {
      name: "bookTitle",
      label: "Judul Buku Mahakarya",
      type: "text",
      placeholder: "The Chronology of an Unending Devotion",
      defaultValue: "The Chronology of an Unending Devotion",
      section: "Etiket Ex Libris & Hak Cipta",
    },
    {
      name: "bookSubtitle",
      label: "Subjudul Buku",
      type: "text",
      placeholder: "An Antiquarian Record of Two Wandering Souls Finding Home",
      defaultValue: "An Antiquarian Record of Two Wandering Souls Finding Home",
      section: "Etiket Ex Libris & Hak Cipta",
    },
    {
      name: "editionLimitation",
      label: "Keterangan Edisi Terbatas",
      type: "text",
      placeholder: "First & Sole Edition • Copy 01/01 Printed for Eternity",
      defaultValue: "First & Sole Edition • Copy 01/01 Printed for Eternity",
      section: "Etiket Ex Libris & Hak Cipta",
    },
    {
      name: "printingPress",
      label: "Percetakan Klasik (Colophon Press)",
      type: "text",
      placeholder: "Officina Lettera • Florence & London",
      defaultValue: "Officina Lettera • Florence & London",
      section: "Etiket Ex Libris & Hak Cipta",
    },
    {
      name: "publicationDate",
      label: "Tanggal Terbit / Momen Penulisan",
      type: "text",
      placeholder: "Malam Saat Kisah Ini Pertama Kali Dituliskan",
      defaultValue: "Malam Saat Kisah Ini Pertama Kali Dituliskan",
      section: "Etiket Ex Libris & Hak Cipta",
    },
    {
      name: "frontispieceEpigraph",
      label: "Kutipan Epigraph di Halaman Depan",
      type: "textarea",
      placeholder: "Kutipan dedikasi di halaman depan buku...",
      defaultValue:
        "Untukmu, yang kepadanya seluruh aksara dan halaman hidupku kupersembahkan. Di antara miliaran kalimat yang pernah ditulis manusia, namamu adalah satu-satunya yang ingin kubaca berulang kali hingga ujung waktu.",
      section: "Etiket Ex Libris & Hak Cipta",
    },

    // Section 2: Kata Pengantar Penulis
    {
      name: "forewordTitle",
      label: "Judul Kata Pengantar",
      type: "text",
      placeholder: "Prolog: Puisi Hidup yang Tak Pernah Usai Kubaca",
      defaultValue: "Prolog: Puisi Hidup yang Tak Pernah Usai Kubaca",
      section: "Kata Pengantar Penulis",
    },
    {
      name: "forewordDate",
      label: "Waktu & Tempat Penulisan Kata Pengantar",
      type: "text",
      placeholder: "Musim Gugur, Di Bawah Cahaya Lampu Meja Perpustakaan",
      defaultValue: "Musim Gugur, Di Bawah Cahaya Lampu Meja Perpustakaan",
      section: "Kata Pengantar Penulis",
    },
    {
      name: "mainMessage",
      label: "Isi Surat Kata Pengantar Romantis",
      type: "textarea",
      placeholder: "Tuliskan isi surat kata pengantar cinta yang puitis...",
      defaultValue:
        "Seraphina yang terkasih,\n\nMereka yang mencintai buku tua tahu bahwa nilai sejati sebuah karya bukanlah terletak pada mulusnya sampul kulit, melainkan pada jejak jemari yang membalik halamannya dengan penuh kekaguman. Demikianlah aku memandang kisah kita.\n\nSebelum kamu hadir, hidupku hanyalah sekumpulan draft kasar tanpa arah—kalimat-kalimat yang terputus di tengah jalan dan paragraf yang gamang mencari maknanya. Namun saat pandangan kita pertama kali beradu, seolah ada seorang maestro yang meneteskan tinta emas ke atas lembaran kosong, mengubah setiap kekosongan menjadi kidung asmara yang megah.\n\nBuku ini bukanlah fiksi, melainkan catatan hidup tentang bagaimana seorang manusia biasa menemukan surga kecilnya di dalam bola matamu. Setiap kali kamu tertawa, setiap kali jemarimu menggenggam tanganku dalam hening, ada baris bait baru yang terpatri abadi di dalam jiwaku. Semoga buku ini menjadi bukti bahwa di dunia yang serba fana dan tergesa, ada satu cinta yang dijilid dengan benang kesetiaan yang tak akan pernah lapuk oleh masa.",
      section: "Kata Pengantar Penulis",
    },
    {
      name: "forewordSignoff",
      label: "Kalimat Penutup Kata Pengantar",
      type: "text",
      placeholder: "Dengan seluruh tinta jiwa yang tak akan pernah kering,",
      defaultValue: "Dengan seluruh tinta jiwa yang tak akan pernah kering,",
      section: "Kata Pengantar Penulis",
    },

    // Section 3: 4 Bab Utama Kisah Kita
    {
      name: "chapter1Title",
      label: "Bab I: Judul Bab",
      type: "text",
      placeholder: "The Uncharted Prelude (Halaman Pembuka Takdir)",
      defaultValue: "The Uncharted Prelude (Halaman Pembuka Takdir)",
      section: "4 Bab Cerita Cinta",
    },
    {
      name: "chapter1Epigraph",
      label: "Bab I: Kutipan Pembuka (Epigraph)",
      type: "text",
      placeholder: "Takdir tidak pernah terburu-buru, ia hanya membalik halaman tepat pada waktunya.",
      defaultValue: "Takdir tidak pernah terburu-buru, ia hanya membalik halaman tepat pada waktunya.",
      section: "4 Bab Cerita Cinta",
    },
    {
      name: "chapter1Story",
      label: "Bab I: Narasi Kisah",
      type: "textarea",
      placeholder: "Ceritakan pertemuan pertama...",
      defaultValue:
        "Pertemuan kita bukanlah kebetulan biasa, melainkan simfoni yang telah disusun rapi oleh semesta. Di tengah keramaian kota, kehadiranmu menyala dengan keanggunan tenang yang langsung mencuri seluruh fokus duniaku.",
      section: "4 Bab Cerita Cinta",
    },
    {
      name: "chapter1Meaning",
      label: "Bab I: Makna Filosofis",
      type: "text",
      placeholder: "Makna bab ini...",
      defaultValue: "Awal mula dari setiap hal indah yang hari ini kita sebut sebagai rumah.",
      section: "4 Bab Cerita Cinta",
    },

    {
      name: "chapter2Title",
      label: "Bab II: Judul Bab",
      type: "text",
      placeholder: "The Sanctuary of Whispered Truths (Ruang Suci Kejujuran)",
      defaultValue: "The Sanctuary of Whispered Truths (Ruang Suci Kejujuran)",
      section: "4 Bab Cerita Cinta",
    },
    {
      name: "chapter2Epigraph",
      label: "Bab II: Kutipan Pembuka (Epigraph)",
      type: "text",
      placeholder: "Cinta sejati dimulai saat dua manusia tak lagi perlu memakai topeng di hadapan satu sama lain.",
      defaultValue: "Cinta sejati dimulai saat dua manusia tak lagi perlu memakai topeng di hadapan satu sama lain.",
      section: "4 Bab Cerita Cinta",
    },
    {
      name: "chapter2Story",
      label: "Bab II: Narasi Kisah",
      type: "textarea",
      placeholder: "Ceritakan saat saling membuka hati...",
      defaultValue:
        "Malam-malam panjang saat kita bisa menceritakan luka masa lalu, ketakutan terdalam, dan impian paling rahasia tanpa takut dihakimi. Di matamu, aku menemukan ruang aman di mana aku bisa menjadi diriku yang seutuhnya.",
      section: "4 Bab Cerita Cinta",
    },
    {
      name: "chapter2Meaning",
      label: "Bab II: Makna Filosofis",
      type: "text",
      placeholder: "Makna bab ini...",
      defaultValue: "Kedalaman rasa percaya yang menjadi fondasi tak tergoyahkan bagi jiwa kita.",
      section: "4 Bab Cerita Cinta",
    },

    {
      name: "chapter3Title",
      label: "Bab III: Judul Bab",
      type: "text",
      placeholder: "Weathering the Autumn Tempest (Mengatasi Badai Hidup)",
      defaultValue: "Weathering the Autumn Tempest (Mengatasi Badai Hidup)",
      section: "4 Bab Cerita Cinta",
    },
    {
      name: "chapter3Epigraph",
      label: "Bab III: Kutipan Pembuka (Epigraph)",
      type: "text",
      placeholder: "Angin kencang mungkin merontokkan dedaunan, namun hanya akan memperkokoh akar pohon tua.",
      defaultValue: "Angin kencang mungkin merontokkan dedaunan, namun hanya akan memperkokoh akar pohon tua.",
      section: "4 Bab Cerita Cinta",
    },
    {
      name: "chapter3Story",
      label: "Bab III: Narasi Kisah",
      type: "textarea",
      placeholder: "Ceritakan masa-masa sulit yang dilewati bersama...",
      defaultValue:
        "Ketika kehidupan menghadirkan keraguan, kelelahan, dan jarak, kita tidak saling melepaskan pegangan. Kita belajar bahwa cinta bukanlah ketiadaan badai, melainkan keberanian untuk berlayar menembusnya berdampingan.",
      section: "4 Bab Cerita Cinta",
    },
    {
      name: "chapter3Meaning",
      label: "Bab III: Makna Filosofis",
      type: "text",
      placeholder: "Makna bab ini...",
      defaultValue: "Kekuatan komitmen yang membuktikan bahwa ikatan kita kebal terhadap ujian waktu.",
      section: "4 Bab Cerita Cinta",
    },

    {
      name: "chapter4Title",
      label: "Bab IV: Judul Bab",
      type: "text",
      placeholder: "The Infinite Epilogue (Epilog Abadi yang Menanti)",
      defaultValue: "The Infinite Epilogue (Epilog Abadi yang Menanti)",
      section: "4 Bab Cerita Cinta",
    },
    {
      name: "chapter4Epigraph",
      label: "Bab IV: Kutipan Pembuka (Epigraph)",
      type: "text",
      placeholder: "Buku terbaik bukanlah buku yang tamat, melainkan yang terus dituliskan hari demi hari.",
      defaultValue: "Buku terbaik bukanlah buku yang tamat, melainkan yang terus dituliskan hari demi hari.",
      section: "4 Bab Cerita Cinta",
    },
    {
      name: "chapter4Story",
      label: "Bab IV: Narasi Kisah",
      type: "textarea",
      placeholder: "Ceritakan janji masa depan...",
      defaultValue:
        "Semua halaman kosong di depan kita menunggu untuk diisi: rumah yang hangat, tawa anak cucu, perjalanan melintasi benua, dan saat rambut kita mulai memutih bersama. Janjiku adalah tetap menatapmu dengan rasa cinta yang sama seperti halaman pertama.",
      section: "4 Bab Cerita Cinta",
    },
    {
      name: "chapter4Meaning",
      label: "Bab IV: Makna Filosofis",
      type: "text",
      placeholder: "Makna bab ini...",
      defaultValue: "Sebuah janji abadi bahwa epilog kita tidak akan pernah memiliki kata 'tamat'.",
      section: "4 Bab Cerita Cinta",
    },

    // Section 4: 4 Catatan Pinggir (Handwritten Marginalia)
    {
      name: "marginalia1Page",
      label: "Catatan 1: Halaman Buku",
      type: "text",
      placeholder: "Halaman 17 • Sudut Kanan Atas",
      defaultValue: "Halaman 17 • Sudut Kanan Atas",
      section: "4 Catatan Pinggir (Marginalia)",
    },
    {
      name: "marginalia1Note",
      label: "Catatan 1: Isi Catatan Tinta Sepia",
      type: "text",
      placeholder: "Di sudut kedai itu, saat kamu tertawa lepas, aku tahu duniaku telah menemukan porosnya.",
      defaultValue: "Di sudut kedai itu, saat kamu tertawa lepas, aku tahu duniaku telah menemukan porosnya.",
      section: "4 Catatan Pinggir (Marginalia)",
    },
    {
      name: "marginalia1Context",
      label: "Catatan 1: Konteks Momen",
      type: "text",
      placeholder: "Kencan pertama di tengah hujan gerimis",
      defaultValue: "Kencan pertama di tengah hujan gerimis",
      section: "4 Catatan Pinggir (Marginalia)",
    },

    {
      name: "marginalia2Page",
      label: "Catatan 2: Halaman Buku",
      type: "text",
      placeholder: "Halaman 54 • Garis Bawah Paragraf",
      defaultValue: "Halaman 54 • Garis Bawah Paragraf",
      section: "4 Catatan Pinggir (Marginalia)",
    },
    {
      name: "marginalia2Note",
      label: "Catatan 2: Isi Catatan Tinta Sepia",
      type: "text",
      placeholder: "Kamu tertidur di bahuku saat kereta melaju malam itu. Aku menahan napas agar kamu tak terbangun.",
      defaultValue: "Kamu tertidur di bahuku saat kereta melaju malam itu. Aku menahan napas agar kamu tak terbangun.",
      section: "4 Catatan Pinggir (Marginalia)",
    },
    {
      name: "marginalia2Context",
      label: "Catatan 2: Konteks Momen",
      type: "text",
      placeholder: "Perjalanan pulang setelah seharian menjelajah",
      defaultValue: "Perjalanan pulang setelah seharian menjelajah",
      section: "4 Catatan Pinggir (Marginalia)",
    },

    {
      name: "marginalia3Page",
      label: "Catatan 3: Halaman Buku",
      type: "text",
      placeholder: "Halaman 108 • Diapit Tanda Bintang",
      defaultValue: "Halaman 108 • Diapit Tanda Bintang",
      section: "4 Catatan Pinggir (Marginalia)",
    },
    {
      name: "marginalia3Note",
      label: "Catatan 3: Isi Catatan Tinta Sepia",
      type: "text",
      placeholder: "Terima kasih telah menggenggam tanganku saat dunia terasa begitu berat dan bising.",
      defaultValue: "Terima kasih telah menggenggam tanganku saat dunia terasa begitu berat dan bising.",
      section: "4 Catatan Pinggir (Marginalia)",
    },
    {
      name: "marginalia3Context",
      label: "Catatan 3: Konteks Momen",
      type: "text",
      placeholder: "Hari terberat di tempat kerja yang terobati oleh pelukanmu",
      defaultValue: "Hari terberat di tempat kerja yang terobati oleh pelukanmu",
      section: "4 Catatan Pinggir (Marginalia)",
    },

    {
      name: "marginalia4Page",
      label: "Catatan 4: Halaman Buku",
      type: "text",
      placeholder: "Halaman 240 • Sudut Terlipat (Dog-Eared)",
      defaultValue: "Halaman 240 • Sudut Terlipat (Dog-Eared)",
      section: "4 Catatan Pinggir (Marginalia)",
    },
    {
      name: "marginalia4Note",
      label: "Catatan 4: Isi Catatan Tinta Sepia",
      type: "text",
      placeholder: "Bahkan jika buku ini memiliki sejuta halaman, namamu akan selalu menjadi kata terindah di setiap barisnya.",
      defaultValue: "Bahkan jika buku ini memiliki sejuta halaman, namamu akan selalu menjadi kata terindah di setiap barisnya.",
      section: "4 Catatan Pinggir (Marginalia)",
    },
    {
      name: "marginalia4Context",
      label: "Catatan 4: Konteks Momen",
      type: "text",
      placeholder: "Janji bisu yang dituliskan di larut malam",
      defaultValue: "Janji bisu yang dituliskan di larut malam",
      section: "4 Catatan Pinggir (Marginalia)",
    },

    // Section 5: Spesifikasi Penjilidan Buku
    {
      name: "bindingStyle",
      label: "Sampul & Jilidan Kulit (Binding)",
      type: "text",
      placeholder: "Full Florentine Crimson Morocco Leather with 24k Gold Tooling",
      defaultValue: "Full Florentine Crimson Morocco Leather with 24k Gold Tooling",
      section: "Spesifikasi Buku Langka",
    },
    {
      name: "paperType",
      label: "Jenis Kertas Antik (Paper Stock)",
      type: "text",
      placeholder: "Handmade 100% Cotton Rag Deckle-Edge Paper (Acid-Free)",
      defaultValue: "Handmade 100% Cotton Rag Deckle-Edge Paper (Acid-Free)",
      section: "Spesifikasi Buku Langka",
    },
    {
      name: "typographyDetails",
      label: "Tipografi & Iluminasi",
      type: "text",
      placeholder: "Monotype Baskerville & Gilded Hand-Illuminated Drop Caps",
      defaultValue: "Monotype Baskerville & Gilded Hand-Illuminated Drop Caps",
      section: "Spesifikasi Buku Langka",
    },
    {
      name: "preservationStatus",
      label: "Status Pelestarian Arsip",
      type: "text",
      placeholder: "Indestructible • Dilindungi oleh kesetiaan dan cinta abadi",
      defaultValue: "Indestructible • Dilindungi oleh kesetiaan dan cinta abadi",
      section: "Spesifikasi Buku Langka",
    },

    // Section 6: Warna, Pita Sutra & Musik
    {
      name: "bookmarkButtonText",
      label: "Teks Tombol Pembatas Sutra",
      type: "text",
      placeholder: "Sematkan Pita Pembatas Sutra",
      defaultValue: "Sematkan Pita Pembatas Sutra",
      section: "Pita Sutra & Musik",
    },
    {
      name: "bookmarkSuccessMessage",
      label: "Pesan Interaksi Pita Disematkan",
      type: "text",
      placeholder: "Pita sutra burgundy terselip anggun di antara lembaran kisah kita.",
      defaultValue: "Pita sutra burgundy terselip anggun di antara lembaran kisah kita.",
      section: "Pita Sutra & Musik",
    },
    {
      name: "primaryColor",
      label: "Warna Emas Penjilid (Bookbinder's Gold)",
      type: "color",
      defaultValue: "#d4af37",
      section: "Pita Sutra & Musik",
    },
    {
      name: "secondaryColor",
      label: "Warna Kulit Maroko Merah (Crimson Leather)",
      type: "color",
      defaultValue: "#8b1e2d",
      section: "Pita Sutra & Musik",
    },
    {
      name: "accentColor",
      label: "Warna Pita Sutra (Burgundy Ribbon)",
      type: "color",
      defaultValue: "#be123c",
      section: "Pita Sutra & Musik",
    },
    {
      name: "musicTrack",
      label: "URL Musik Selo Perpustakaan Kuno (Opsional)",
      type: "text",
      placeholder: "https://example.com/audio/antiquarian-library-cello.mp3",
      defaultValue: "https://cdn.pixabay.com/download/audio/2022/10/14/audio_993d05e3f1.mp3?filename=romantic-cello-and-piano-122941.mp3",
      section: "Pita Sutra & Musik",
    },
  ],
  sample: {
    recipientName: "Seraphina Eleanor",
    senderName: "Theodore Vance",
    bookTitle: "The Chronology of an Unending Devotion",
    bookSubtitle: "An Antiquarian Record of Two Wandering Souls Finding Home",
    editionLimitation: "First & Sole Edition • Copy 01/01 Printed for Eternity",
    printingPress: "Officina Lettera • Florence & London",
    publicationDate: "Malam Saat Kisah Ini Pertama Kali Dituliskan",
    frontispieceEpigraph:
      "Untukmu, yang kepadanya seluruh aksara dan halaman hidupku kupersembahkan. Di antara miliaran kalimat yang pernah ditulis manusia, namamu adalah satu-satunya yang ingin kubaca berulang kali hingga ujung waktu.",
    forewordTitle: "Prolog: Puisi Hidup yang Tak Pernah Usai Kubaca",
    forewordDate: "Musim Gugur, Di Bawah Cahaya Lampu Meja Perpustakaan",
    mainMessage:
      "Seraphina yang terkasih,\n\nMereka yang mencintai buku tua tahu bahwa nilai sejati sebuah karya bukanlah terletak pada mulusnya sampul kulit, melainkan pada jejak jemari yang membalik halamannya dengan penuh kekaguman. Demikianlah aku memandang kisah kita.\n\nSebelum kamu hadir, hidupku hanyalah sekumpulan draft kasar tanpa arah—kalimat-kalimat yang terputus di tengah jalan dan paragraf yang gamang mencari maknanya. Namun saat pandangan kita pertama kali beradu, seolah ada seorang maestro yang meneteskan tinta emas ke atas lembaran kosong, mengubah setiap kekosongan menjadi kidung asmara yang megah.\n\nBuku ini bukanlah fiksi, melainkan catatan hidup tentang bagaimana seorang manusia biasa menemukan surga kecilnya di dalam bola matamu. Setiap kali kamu tertawa, setiap kali jemarimu menggenggam tanganku dalam hening, ada baris bait baru yang terpatri abadi di dalam jiwaku. Semoga buku ini menjadi bukti bahwa di dunia yang serba fana dan tergesa, ada satu cinta yang dijilid dengan benang kesetiaan yang tak akan pernah lapuk oleh masa.",
    forewordSignoff: "Dengan seluruh tinta jiwa yang tak akan pernah kering,",
    chapter1Title: "The Uncharted Prelude (Halaman Pembuka Takdir)",
    chapter1Epigraph: "Takdir tidak pernah terburu-buru, ia hanya membalik halaman tepat pada waktunya.",
    chapter1Story:
      "Pertemuan kita bukanlah kebetulan biasa, melainkan simfoni yang telah disusun rapi oleh semesta. Di tengah keramaian kota, kehadiranmu menyala dengan keanggunan tenang yang langsung mencuri seluruh fokus duniaku.",
    chapter1Meaning: "Awal mula dari setiap hal indah yang hari ini kita sebut sebagai rumah.",
    chapter2Title: "The Sanctuary of Whispered Truths (Ruang Suci Kejujuran)",
    chapter2Epigraph: "Cinta sejati dimulai saat dua manusia tak lagi perlu memakai topeng di hadapan satu sama lain.",
    chapter2Story:
      "Malam-malam panjang saat kita bisa menceritakan luka masa lalu, ketakutan terdalam, dan impian paling rahasia tanpa takut dihakimi. Di matamu, aku menemukan ruang aman di mana aku bisa menjadi diriku yang seutuhnya.",
    chapter2Meaning: "Kedalaman rasa percaya yang menjadi fondasi tak tergoyahkan bagi jiwa kita.",
    chapter3Title: "Weathering the Autumn Tempest (Mengatasi Badai Hidup)",
    chapter3Epigraph: "Angin kencang mungkin merontokkan dedaunan, namun hanya akan memperkokoh akar pohon tua.",
    chapter3Story:
      "Ketika kehidupan menghadirkan keraguan, kelelahan, dan jarak, kita tidak saling melepaskan pegangan. Kita belajar bahwa cinta bukanlah ketiadaan badai, melainkan keberanian untuk berlayar menembusnya berdampingan.",
    chapter3Meaning: "Kekuatan komitmen yang membuktikan bahwa ikatan kita kebal terhadap ujian waktu.",
    chapter4Title: "The Infinite Epilogue (Epilog Abadi yang Menanti)",
    chapter4Epigraph: "Buku terbaik bukanlah buku yang tamat, melainkan yang terus dituliskan hari demi hari.",
    chapter4Story:
      "Semua halaman kosong di depan kita menunggu untuk diisi: rumah yang hangat, tawa anak cucu, perjalanan melintasi benua, dan saat rambut kita mulai memutih bersama. Janjiku adalah tetap menatapmu dengan rasa cinta yang sama seperti halaman pertama.",
    chapter4Meaning: "Sebuah janji abadi bahwa epilog kita tidak akan pernah memiliki kata 'tamat'.",
    marginalia1Page: "Halaman 17 • Sudut Kanan Atas",
    marginalia1Note: "Di sudut kedai itu, saat kamu tertawa lepas, aku tahu duniaku telah menemukan porosnya.",
    marginalia1Context: "Kencan pertama di tengah hujan gerimis",
    marginalia2Page: "Halaman 54 • Garis Bawah Paragraf",
    marginalia2Note: "Kamu tertidur di bahuku saat kereta melaju malam itu. Aku menahan napas agar kamu tak terbangun.",
    marginalia2Context: "Perjalanan pulang setelah seharian menjelajah",
    marginalia3Page: "Halaman 108 • Diapit Tanda Bintang",
    marginalia3Note: "Terima kasih telah menggenggam tanganku saat dunia terasa begitu berat dan bising.",
    marginalia3Context: "Hari terberat di tempat kerja yang terobati oleh pelukanmu",
    marginalia4Page: "Halaman 240 • Sudut Terlipat (Dog-Eared)",
    marginalia4Note: "Bahkan jika buku ini memiliki sejuta halaman, namamu akan selalu menjadi kata terindah di setiap barisnya.",
    marginalia4Context: "Janji bisu yang dituliskan di larut malam",
    bindingStyle: "Full Florentine Crimson Morocco Leather with 24k Gold Tooling",
    paperType: "Handmade 100% Cotton Rag Deckle-Edge Paper (Acid-Free)",
    typographyDetails: "Monotype Baskerville & Gilded Hand-Illuminated Drop Caps",
    preservationStatus: "Indestructible • Dilindungi oleh kesetiaan dan cinta abadi",
    bookmarkButtonText: "Sematkan Pita Pembatas Sutra",
    bookmarkSuccessMessage: "Pita sutra burgundy terselip anggun di antara lembaran kisah kita.",
    primaryColor: "#d4af37",
    secondaryColor: "#8b1e2d",
    accentColor: "#be123c",
    musicTrack: "https://cdn.pixabay.com/download/audio/2022/10/14/audio_993d05e3f1.mp3?filename=romantic-cello-and-piano-122941.mp3",
  },
};
