import type { TemplateMeta } from "../types";

export const cartographyLoveTemplate: TemplateMeta = {
  slug: "cartography-love",
  name: "Cartographie de l'Amour",
  category: "Surat Romantis",
  description:
    "Surat cinta mewah bertema seni kartografi maritim Renaisans dan peta samudra cinta (The Royal Cartographer's Silk Sea Chart & Carte de Tendre). Menampilkan sertifikat kartografi kerajaan dalam bingkai baroque cartouche, koordinat pelayaran sakral lintang dan bujur, warkah kapten di bawah cahaya lentera kabin kapal, eksplorasi 4 kepulauan cinta interaktif (Archipelago of Tender Seas), 4 instrumen navigasi kuningan maritim sakral (Astrolab, Sekstan, Jam Pasir Emas, Kompas Mawar), meteran kedalaman lubuk hati (Soundings in Fathoms) dan Sumpah Nakhoda Abadi, serta botol laut antik interaktif (Message in a Bottle) yang dapat dibuka untuk mengungkap gulungan pesan rahasia diiringi simfoni bahari yang memikat.",
  tagline: "Cartographie de l'Amour: Mengarungi Samudra Rasa Menuju Dermaga Abadi di Hatimu",
  cardAccent: "border-teal-500/40 bg-gradient-to-br from-[#06121e] via-[#0b1e32] to-[#081726] text-amber-200",
  highlights: [
    "Konsep Kartografi Maritim Renaisans: Peta Sutra Samudra Cinta (Carte de Tendre)",
    "Bingkai Royal Cartouche dengan Koordinat Sakral Lintang & Bujur (Latitude/Longitude)",
    "Warkah Catatan Pelayaran Nakhoda di Bawah Cahaya Lentera Kabin (Captain's Logbook)",
    "4 Kepulauan Cinta Interaktif (Île de la Rencontre, Golfe des Murmures, Détroit des Tempêtes, Cap de l'Éternité)",
    "4 Instrumen Navigasi Kuningan Sakral (Astrolab, Sekstan, Jam Pasir Emas, Mawar Kompas)",
    "Interaksi Membuka Sumbat Botol Laut Kaca (Message in a Bottle) & Melodi Bahari",
  ],
  fields: [
    // Section 1: Sertifikat Kartografi & Royal Chart Cartouche
    {
      name: "recipientName",
      label: "Nama Sang Mercusuar Sanubari (The Keeper of My Harbor)",
      type: "text",
      placeholder: "Seraphina Clarisse",
      required: true,
      isRecipient: true,
      section: "Sertifikat Kartografi Samudra",
    },
    {
      name: "senderName",
      label: "Nama Sang Penjelajah Samudra (The Devoted Mariner)",
      type: "text",
      placeholder: "Captain Julian Vance",
      required: true,
      section: "Sertifikat Kartografi Samudra",
    },
    {
      name: "mapSheetNo",
      label: "Nomor Registrasi Peta Kerajaan",
      type: "text",
      placeholder: "CHART-N°17-AMORIS",
      defaultValue: "CHART-N°17-AMORIS",
      section: "Sertifikat Kartografi Samudra",
    },
    {
      name: "royalCartoucheTitle",
      label: "Judul Bingkai Cartouche Kerajaan",
      type: "text",
      placeholder: "NOVA ET ACCURATA TOTIUS AMORIS TABULA",
      defaultValue: "NOVA ET ACCURATA TOTIUS AMORIS TABULA",
      section: "Sertifikat Kartografi Samudra",
    },
    {
      name: "chartSubtitle",
      label: "Subjudul Peta Samudra",
      type: "text",
      placeholder: "Peta Sutra Pelayaran Jiwa Mengarungi Samudra Kasih Menuju Dermaga Keabadian",
      defaultValue: "Peta Sutra Pelayaran Jiwa Mengarungi Samudra Kasih Menuju Dermaga Keabadian",
      section: "Sertifikat Kartografi Samudra",
    },
    {
      name: "initialMeetingCoordinates",
      label: "Koordinat Titik Awal Pertemuan",
      type: "text",
      placeholder: "48°51'24\"N • 02°21'07\"E (Titik Awal Jangkar Hati Ditebarkan)",
      defaultValue: "48°51'24\"N • 02°21'07\"E (Titik Awal Jangkar Hati Ditebarkan)",
      section: "Sertifikat Kartografi Samudra",
    },
    {
      name: "destinationCoordinates",
      label: "Koordinat Labuhan Tujuan Abadi",
      type: "text",
      placeholder: "00°00'00\"N • ∞°∞'∞\"E (Dermaga Kasih Tanpa Batas Akhir)",
      defaultValue: "00°00'00\"N • ∞°∞'∞\"E (Dermaga Kasih Tanpa Batas Akhir)",
      section: "Sertifikat Kartografi Samudra",
    },
    {
      name: "cartographerSeal",
      label: "Segel Lembaga Kartografi Kerajaan",
      type: "text",
      placeholder: "Regia Societas Cartographica Amoris • Sigillum Authenticarium",
      defaultValue: "Regia Societas Cartographica Amoris • Sigillum Authenticarium",
      section: "Sertifikat Kartografi Samudra",
    },
    {
      name: "seaCurrentNote",
      label: "Kondisi Perairan & Catatan Rumb Navigasi",
      type: "text",
      placeholder: "Perairan Tenang Bebas Karang Prasangka • Diterangi Bintang Kejora",
      defaultValue: "Perairan Tenang Bebas Karang Prasangka • Diterangi Bintang Kejora",
      section: "Sertifikat Kartografi Samudra",
    },

    // Section 2: Warkah Pelayaran Nakhoda (The Captain's Midnight Logbook)
    {
      name: "logbookDate",
      label: "Tanggal & Titik Jurnal Pelayaran",
      type: "text",
      placeholder: "Tengah Malam di Titik Balik Samudra • Malam Berbintang Tenang",
      defaultValue: "Tengah Malam di Titik Balik Samudra • Malam Berbintang Tenang",
      section: "Warkah Pelayaran Nakhoda",
    },
    {
      name: "logbookTitle",
      label: "Judul Catatan Jurnal Pelayaran",
      type: "text",
      placeholder: "Catatan Warkah Nakhoda di Bawah Cahaya Lentera Kabin",
      defaultValue: "Catatan Warkah Nakhoda di Bawah Cahaya Lentera Kabin",
      section: "Warkah Pelayaran Nakhoda",
    },
    {
      name: "mainMessage",
      label: "Isi Warkah Pelayaran Kasih (Warkah Utama)",
      type: "textarea",
      placeholder: "Tuliskan surat cinta pelayaran mendalam untuk pasanganmu...",
      required: true,
      section: "Warkah Pelayaran Nakhoda",
    },
    {
      name: "marinerAxiom",
      label: "Aksioma Filosofis Pelaut Cinta",
      type: "text",
      placeholder: "Kutipan filosofis pelayaran...",
      defaultValue:
        "Kapal mungkin mengarungi seribu samudra bergelora, namun ia hanya membutuhkan satu mercusuar untuk tahu ke mana harus pulang.",
      section: "Warkah Pelayaran Nakhoda",
    },
    {
      name: "captainSignatureTitle",
      label: "Sebutan Penutup Tanda Tangan Nakhoda",
      type: "text",
      placeholder: "Nakhoda yang Selalu Menghadapkan Layarnya ke Arah Hatimu,",
      defaultValue: "Nakhoda yang Selalu Menghadapkan Layarnya ke Arah Hatimu,",
      section: "Warkah Pelayaran Nakhoda",
    },

    // Section 3: 4 Kepulauan Cinta Interaktif (Archipelago of Tender Seas)
    {
      name: "island1Name",
      label: "Kepulauan 1: Nama Pulau/Teluk",
      type: "text",
      placeholder: "Île de la Première Rencontre (Pulau Pertemuan Pertama)",
      defaultValue: "Île de la Première Rencontre (Pulau Pertemuan Pertama)",
      section: "4 Kepulauan Cinta",
    },
    {
      name: "island1Coordinates",
      label: "Kepulauan 1: Koordinat & Topografi",
      type: "text",
      placeholder: "Lat 14°08'N, Long 60°58'W • Laguna Pasir Emas Berair Kristal",
      defaultValue: "Lat 14°08'N, Long 60°58'W • Laguna Pasir Emas Berair Kristal",
      section: "4 Kepulauan Cinta",
    },
    {
      name: "island1Sounding",
      label: "Kepulauan 1: Kedalaman Depa (Sounding Depth)",
      type: "text",
      placeholder: "Kedalaman 24 Depa • Air Bening Menembus Dasar Karang Hati",
      defaultValue: "Kedalaman 24 Depa • Air Bening Menembus Dasar Karang Hati",
      section: "4 Kepulauan Cinta",
    },
    {
      name: "island1Story",
      label: "Kepulauan 1: Catatan Narasi Cinta",
      type: "textarea",
      placeholder: "Narasi pulau pertemuan pertama...",
      defaultValue:
        "Teluk teduh berpasir putih di mana sauh kapalku pertama kali dijatuhkan. Hari saat tatap mata kita saling bersua, seketika gelombang keraguan di jiwaku mereda, digantikan oleh kedamaian yang belum pernah kutemukan di pelabuhan manapun.",
      section: "4 Kepulauan Cinta",
    },
    {
      name: "island1Beacon",
      label: "Kepulauan 1: Landmark Jiwa",
      type: "text",
      placeholder: "Sauh Emas Pertama yang Mengunci Rasa",
      defaultValue: "Sauh Emas Pertama yang Mengunci Rasa",
      section: "4 Kepulauan Cinta",
    },

    {
      name: "island2Name",
      label: "Kepulauan 2: Nama Pulau/Teluk",
      type: "text",
      placeholder: "Golfe des Murmures (Teluk Bisikan Kasih)",
      defaultValue: "Golfe des Murmures (Teluk Bisikan Kasih)",
      section: "4 Kepulauan Cinta",
    },
    {
      name: "island2Coordinates",
      label: "Kepulauan 2: Koordinat & Topografi",
      type: "text",
      placeholder: "Lat 21°19'N, Long 157°52'W • Perairan Teduh Bernaung Bukit Asri",
      defaultValue: "Lat 21°19'N, Long 157°52'W • Perairan Teduh Bernaung Bukit Asri",
      section: "4 Kepulauan Cinta",
    },
    {
      name: "island2Sounding",
      label: "Kepulauan 2: Kedalaman Depa (Sounding Depth)",
      type: "text",
      placeholder: "Kedalaman 60 Depa • Bebas Dari Riak dan Embusan Gelisah",
      defaultValue: "Kedalaman 60 Depa • Bebas Dari Riak dan Embusan Gelisah",
      section: "4 Kepulauan Cinta",
    },
    {
      name: "island2Story",
      label: "Kepulauan 2: Catatan Narasi Cinta",
      type: "textarea",
      placeholder: "Narasi teluk bisikan kasih...",
      defaultValue:
        "Perairan sunyi di balik teluk pelindung tempat rahasia, impian, dan tawa kita berpadu dalam kehangatan malam. Di sini kita belajar saling membuka kerentanan tanpa rasa takut, membiarkan deburan ombak menjadi melodi pengantar tidur bagi jiwa kita.",
      section: "4 Kepulauan Cinta",
    },
    {
      name: "island2Beacon",
      label: "Kepulauan 2: Landmark Jiwa",
      type: "text",
      placeholder: "Rembulan Kembar Penuntun Kegelapan Malam",
      defaultValue: "Rembulan Kembar Penuntun Kegelapan Malam",
      section: "4 Kepulauan Cinta",
    },

    {
      name: "island3Name",
      label: "Kepulauan 3: Nama Pulau/Teluk",
      type: "text",
      placeholder: "Détroit des Tempêtes Vaincues (Selat Badai yang Ditaklukkan)",
      defaultValue: "Détroit des Tempêtes Vaincues (Selat Badai yang Ditaklukkan)",
      section: "4 Kepulauan Cinta",
    },
    {
      name: "island3Coordinates",
      label: "Kepulauan 3: Koordinat & Topografi",
      type: "text",
      placeholder: "Lat 35°58'S, Long 138°08'E • Tebing Karang Granit yang Kokoh",
      defaultValue: "Lat 35°58'S, Long 138°08'E • Tebing Karang Granit yang Kokoh",
      section: "4 Kepulauan Cinta",
    },
    {
      name: "island3Sounding",
      label: "Kepulauan 3: Kedalaman Depa (Sounding Depth)",
      type: "text",
      placeholder: "Kedalaman 120 Depa • Fondasi Karang Abadi Tak Tergoyahkan",
      defaultValue: "Kedalaman 120 Depa • Fondasi Karang Abadi Tak Tergoyahkan",
      section: "4 Kepulauan Cinta",
    },
    {
      name: "island3Story",
      label: "Kepulauan 3: Catatan Narasi Cinta",
      type: "textarea",
      placeholder: "Narasi selat badai yang ditaklukkan...",
      defaultValue:
        "Jalur pelayaran sempit berkarang terjal di mana kita pernah diuji oleh pasang surut dan badai hidup yang sengit. Namun dengan saling menggenggam tangan erat di atas kemudi, kita berhasil menaklukkan setiap hempasan ombak dan keluar menjadi nahkoda cinta yang jauh lebih tangguh.",
      section: "4 Kepulauan Cinta",
    },
    {
      name: "island3Beacon",
      label: "Kepulauan 3: Landmark Jiwa",
      type: "text",
      placeholder: "Lentera Mercusuar Granit Abadi Tak Pernah Padam",
      defaultValue: "Lentera Mercusuar Granit Abadi Tak Pernah Padam",
      section: "4 Kepulauan Cinta",
    },

    {
      name: "island4Name",
      label: "Kepulauan 4: Nama Pulau/Teluk",
      type: "text",
      placeholder: "Cap de l'Éternité (Tanjung Keabadian)",
      defaultValue: "Cap de l'Éternité (Tanjung Keabadian)",
      section: "4 Kepulauan Cinta",
    },
    {
      name: "island4Coordinates",
      label: "Kepulauan 4: Koordinat & Topografi",
      type: "text",
      placeholder: "Lat 00°00'N, Long 00°00'E • Samudra Terbuka Tanpa Batas Akhir",
      defaultValue: "Lat 00°00'N, Long 00°00'E • Samudra Terbuka Tanpa Batas Akhir",
      section: "4 Kepulauan Cinta",
    },
    {
      name: "island4Sounding",
      label: "Kepulauan 4: Kedalaman Depa (Sounding Depth)",
      type: "text",
      placeholder: "Kedalaman Samudra Hati (Palung Tanpa Batas Ukuran)",
      defaultValue: "Kedalaman Samudra Hati (Palung Tanpa Batas Ukuran)",
      section: "4 Kepulauan Cinta",
    },
    {
      name: "island4Story",
      label: "Kepulauan 4: Catatan Narasi Cinta",
      type: "textarea",
      placeholder: "Narasi tanjung keabadian...",
      defaultValue:
        "Ujung tanjung megah tempat laut dan langit menyatu menjadi satu garis cakrawala keemasan. Tempat di mana matahari tak pernah terbenam, dan pelayaran kita bukan lagi tentang mencari tanah baru, melainkan menikmati setiap embusan angin berdua selamanya.",
      section: "4 Kepulauan Cinta",
    },
    {
      name: "island4Beacon",
      label: "Kepulauan 4: Landmark Jiwa",
      type: "text",
      placeholder: "Cakrawala Fajar Keemasan Tanpa Batas Waktu",
      defaultValue: "Cakrawala Fajar Keemasan Tanpa Batas Waktu",
      section: "4 Kepulauan Cinta",
    },

    // Section 4: 4 Instrumen Navigasi Sakral Pelaut
    {
      name: "instrument1Name",
      label: "Instrumen 1: Nama Instrumen",
      type: "text",
      placeholder: "The Brass Astrolabe (Astrolab Bintang)",
      defaultValue: "The Brass Astrolabe (Astrolab Bintang)",
      section: "4 Instrumen Navigasi",
    },
    {
      name: "instrument1Role",
      label: "Instrumen 1: Fungsi Penuntun",
      type: "text",
      placeholder: "Penjajar Posisi Bintang Penuntun Jiwa",
      defaultValue: "Penjajar Posisi Bintang Penuntun Jiwa",
      section: "4 Instrumen Navigasi",
    },
    {
      name: "instrument1Desc",
      label: "Instrumen 1: Filosofi Navigasi",
      type: "textarea",
      placeholder: "Uraikan filosofi instrumen...",
      defaultValue:
        "Ditempa dari kuningan murni untuk memetakan rasi bintang di langit. Setiap kali aku mengarahkannya ke langit malam, hanya ada satu konstelasi yang menjadi poros pandanganku: kilau matamu yang selalu menenangkan setiap gundah.",
      section: "4 Instrumen Navigasi",
    },

    {
      name: "instrument2Name",
      label: "Instrumen 2: Nama Instrumen",
      type: "text",
      placeholder: "The Mariner's Sextant (Sekstan Maritim)",
      defaultValue: "The Mariner's Sextant (Sekstan Maritim)",
      section: "4 Instrumen Navigasi",
    },
    {
      name: "instrument2Role",
      label: "Instrumen 2: Fungsi Penuntun",
      type: "text",
      placeholder: "Pengukur Sudut Kemilau Senyuman",
      defaultValue: "Pengukur Sudut Kemilau Senyuman",
      section: "4 Instrumen Navigasi",
    },
    {
      name: "instrument2Desc",
      label: "Instrumen 2: Filosofi Navigasi",
      type: "textarea",
      placeholder: "Uraikan filosofi instrumen...",
      defaultValue:
        "Instrumen cermin ganda untuk mengukur sudut elevasi matahari dari garis cakrawala. Menjadi pengingat abadi bahwa kehangatan senyummu selalu berada pada sudut yang tepat untuk menghangatkan geladak hidupku di cuaca terdingin sekalipun.",
      section: "4 Instrumen Navigasi",
    },

    {
      name: "instrument3Name",
      label: "Instrumen 3: Nama Instrumen",
      type: "text",
      placeholder: "The Hourglass of Golden Sand (Jam Pasir Emas)",
      defaultValue: "The Hourglass of Golden Sand (Jam Pasir Emas)",
      section: "4 Instrumen Navigasi",
    },
    {
      name: "instrument3Role",
      label: "Instrumen 3: Fungsi Penuntun",
      type: "text",
      placeholder: "Penakar Butiran Waktu Sakral Berdua",
      defaultValue: "Penakar Butiran Waktu Sakral Berdua",
      section: "4 Instrumen Navigasi",
    },
    {
      name: "instrument3Desc",
      label: "Instrumen 3: Filosofi Navigasi",
      type: "textarea",
      placeholder: "Uraikan filosofi instrumen...",
      defaultValue:
        "Dua labu kaca kristal tertutup dengan pasir pantai keemasan yang menetes tanpa henti. Membuktikan bahwa setiap butir detik yang kulalui bersamamu adalah berkah tak ternilai yang tak akan pernah kubiarkan hanyut sia-sia.",
      section: "4 Instrumen Navigasi",
    },

    {
      name: "instrument4Name",
      label: "Instrumen 4: Nama Instrumen",
      type: "text",
      placeholder: "The Magnetic Compass Rose (Mawar Kompas Magnetik)",
      defaultValue: "The Magnetic Compass Rose (Mawar Kompas Magnetik)",
      section: "4 Instrumen Navigasi",
    },
    {
      name: "instrument4Role",
      label: "Instrumen 4: Fungsi Penuntun",
      type: "text",
      placeholder: "Penunjuk Kutub Utara Hati Sejati",
      defaultValue: "Penunjuk Kutub Utara Hati Sejati",
      section: "4 Instrumen Navigasi",
    },
    {
      name: "instrument4Desc",
      label: "Instrumen 4: Filosofi Navigasi",
      type: "textarea",
      placeholder: "Uraikan filosofi instrumen...",
      defaultValue:
        "Jarum besi magnetik yang mengambang bebas di atas mangkuk minyak atsiri. Dikelilingi kabut sepekat apapun atau badai sekuat apapun, jarum ini tak pernah bimbang: kutub utaranya selalu menunjuk lurus ke arah tempatmu berada.",
      section: "4 Instrumen Navigasi",
    },

    // Section 5: Kedalaman Lubuk Hati & Sumpah Pelaut
    {
      name: "bathymetricDepth",
      label: "Kedalaman Hidrografi Lubuk Hati (Fathoms)",
      type: "text",
      placeholder: "10,000 Fathoms • Kedalaman Jiwa Tanpa Titik Dasar",
      defaultValue: "10,000 Fathoms • Kedalaman Jiwa Tanpa Titik Dasar",
      section: "Kedalaman Lubuk Hati & Sumpah",
    },
    {
      name: "tradeWindName",
      label: "Embusan Angin Pasat Utama",
      type: "text",
      placeholder: "Breeze of Constant Tenderness • Selalu Mendorong Kita Maju",
      defaultValue: "Breeze of Constant Tenderness • Selalu Mendorong Kita Maju",
      section: "Kedalaman Lubuk Hati & Sumpah",
    },
    {
      name: "oceanicCurrent",
      label: "Arus Samudra Penjaga Arah",
      type: "text",
      placeholder: "Gulf Stream of Eternal Loyalty • Arus Hangat Kesetiaan Penuh",
      defaultValue: "Gulf Stream of Eternal Loyalty • Arus Hangat Kesetiaan Penuh",
      section: "Kedalaman Lubuk Hati & Sumpah",
    },
    {
      name: "anchorStatus",
      label: "Status Jangkar dan Dermaga",
      type: "text",
      placeholder: "Terkunci Rapat di Palung Hatimu • Tak Akan Goyah oleh Topan Apapun",
      defaultValue: "Terkunci Rapat di Palung Hatimu • Tak Akan Goyah oleh Topan Apapun",
      section: "Kedalaman Lubuk Hati & Sumpah",
    },
    {
      name: "admiraltyOathTitle",
      label: "Judul Piagam Sumpah Nakhoda",
      type: "text",
      placeholder: "The Mariner's Eternal Admiralty Oath (Sumpah Nakhoda di Hadapan Samudra)",
      defaultValue: "The Mariner's Eternal Admiralty Oath (Sumpah Nakhoda di Hadapan Samudra)",
      section: "Kedalaman Lubuk Hati & Sumpah",
    },
    {
      name: "admiraltyOathText",
      label: "Naskah Piagam Sumpah Nakhoda",
      type: "textarea",
      placeholder: "Isi piagam sumpah nakhoda...",
      defaultValue:
        "Di hadapan luasnya samudra raya dan di bawah kesaksian bintang-bintang navigasi langit, aku bersumpah untuk senantiasa menjadi nahkoda yang setia memegang kemudi perahu kita, tidak akan pernah meninggalkan geladak di saat badai paling kelam menerpa, dan akan terus menjaga nyala api mercusuar kasih kita hingga akhir hayat.",
      section: "Kedalaman Lubuk Hati & Sumpah",
    },
    {
      name: "admiraltySignerTitle",
      label: "Gelar Nakhoda yang Menandatangani",
      type: "text",
      placeholder: "Nakhoda Pelayaran Jiwa & Pelindung Haluan Hidupmu,",
      defaultValue: "Nakhoda Pelayaran Jiwa & Pelindung Haluan Hidupmu,",
      section: "Kedalaman Lubuk Hati & Sumpah",
    },

    // Section 6: Pesan Botol Hanyut & Musik Bahari
    {
      name: "bottleLabel",
      label: "Label Botol Laut Antik",
      type: "text",
      placeholder: "Botol Laut Kaca Zamrud Bersegel Gabus Lilin",
      defaultValue: "Botol Laut Kaca Zamrud Bersegel Gabus Lilin",
      section: "Pesan Botol Hanyut & Musik",
    },
    {
      name: "bottleButtonText",
      label: "Teks Tombol Buka Sumbat Gabus",
      type: "text",
      placeholder: "Buka Sumbat Gabus Botol Laut",
      defaultValue: "Buka Sumbat Gabus Botol Laut",
      section: "Pesan Botol Hanyut & Musik",
    },
    {
      name: "bottleSecretMessage",
      label: "Gulungan Pesan Rahasia di Dalam Botol (Secret Confession)",
      type: "textarea",
      placeholder: "Tuliskan pesan rahasia yang paling intim dan menyentuh hati...",
      defaultValue:
        "Jika surat ini pernah hanyut di ribuan perairan asing, ketahuilah bahwa ombak akan selalu tahu arah untuk mengantarkannya tepat ke tanganmu. Dari jutaan pelabuhan di dunia, hanya pelukanmu satu-satunya dermaga tempat hatiku merasa genap dan pulang.",
      section: "Pesan Botol Hanyut & Musik",
    },
    {
      name: "bottleClosingQuote",
      label: "Kutipan Penutup Botol Laut",
      type: "text",
      placeholder: "Dihanyutkan di lautan waktu, ditakdirkan untuk berlabuh di genggamanmu selamanya.",
      defaultValue: "Dihanyutkan di lautan waktu, ditakdirkan untuk berlabuh di genggamanmu selamanya.",
      section: "Pesan Botol Hanyut & Musik",
    },

    // Theme & Music
    {
      name: "primaryColor",
      label: "Warna Utama (Aksen Emas / Kuningan Maritim)",
      type: "color",
      defaultValue: "#d4af37",
      section: "Pengaturan Tampilan & Musik",
    },
    {
      name: "secondaryColor",
      label: "Warna Sekunder (Verdigris Teal / Sea Foam)",
      type: "color",
      defaultValue: "#2dd4bf",
      section: "Pengaturan Tampilan & Musik",
    },
    {
      name: "accentColor",
      label: "Warna Aksen (Deep Nautical Indigo)",
      type: "color",
      defaultValue: "#0b1e32",
      section: "Pengaturan Tampilan & Musik",
    },
    {
      name: "musicTrack",
      label: "URL Musik Latar (Melodi Akustik Samudra)",
      type: "text",
      placeholder: "https://cdn.pixabay.com/download/audio/...",
      defaultValue: "https://cdn.pixabay.com/download/audio/2022/03/15/audio_c89b7b9cf4.mp3?filename=celestial-music-box-waltz-10928.mp3",
      section: "Pengaturan Tampilan & Musik",
    },
  ],
  sample: {
    recipientName: "Seraphina Clarisse",
    senderName: "Captain Julian Vance",
    mapSheetNo: "CHART-N°17-AMORIS",
    royalCartoucheTitle: "NOVA ET ACCURATA TOTIUS AMORIS TABULA",
    chartSubtitle: "Peta Sutra Pelayaran Jiwa Mengarungi Samudra Kasih Menuju Dermaga Keabadian",
    initialMeetingCoordinates: "48°51'24\"N • 02°21'07\"E (Titik Awal Jangkar Hati Ditebarkan)",
    destinationCoordinates: "00°00'00\"N • ∞°∞'∞\"E (Dermaga Kasih Tanpa Batas Akhir)",
    cartographerSeal: "Regia Societas Cartographica Amoris • Sigillum Authenticarium",
    seaCurrentNote: "Perairan Tenang Bebas Karang Prasangka • Diterangi Bintang Kejora",
    logbookDate: "Tengah Malam di Titik Balik Samudra • Malam Berbintang Tenang",
    logbookTitle: "Catatan Warkah Nakhoda di Bawah Cahaya Lentera Kabin",
    mainMessage:
      "Seraphina yang selalu menjadi bintang penuntun hidupku,\n\nSeorang pelaut sejati menghabiskan separuh usianya mempelajari pasang surut air laut, meraba peta-peta tua di bawah temaram lentera, dan bergulat melawan badai demi mencari pulau yang dijanjikan dalam dongeng masa lalu. Namun malam ini, saat kapalku meluncur tenang membelah ombak di bawah kubah langit berbintang, aku menyadari sebuah kebenaran mutlak: sebelum mengenalmu, aku hanyalah pengelana yang tersesat di tengah samudra yang dingin tanpa tahu arah tujuan pulang.\n\nKehadiranmu dalam hidupku adalah mercusuar paling kukuh yang pernah ada. Di saat kabut prasangka menebal dan angin keraguan berembus kencang, suaramu adalah kompas yang menenangkan haluanku. Senyumanmu adalah fajar keemasan yang menepis kegelapan malam terpanjang di geladak kapal hatiku. Bersamamu, aku tidak lagi takut pada gemuruh ombak ataupun palung laut yang tak terukur, karena kutahu di sampingmulah sauh jiwaku telah terkunci dengan sempurna.\n\nPeta samudra ini kupersembahkan sebagai piagam abadi cinta kita. Setiap garis rumb navigasi, setiap sudut derajat lintang dan bujur yang tertera di atas perkamen ini, adalah saksi bahwa ke manapun angin takdir meniupkan layarku, seluruh haluan perahu hidupku akan senantiasa berlayar menuju pelukanmu.",
    marinerAxiom:
      "Kapal mungkin mengarungi seribu samudra bergelora, namun ia hanya membutuhkan satu mercusuar untuk tahu ke mana harus pulang.",
    captainSignatureTitle: "Nakhoda yang Selalu Menghadapkan Layarnya ke Arah Hatimu,",
    island1Name: "Île de la Première Rencontre (Pulau Pertemuan Pertama)",
    island1Coordinates: "Lat 14°08'N, Long 60°58'W • Laguna Pasir Emas Berair Kristal",
    island1Sounding: "Kedalaman 24 Depa • Air Bening Menembus Dasar Karang Hati",
    island1Story:
      "Teluk teduh berpasir putih di mana sauh kapalku pertama kali dijatuhkan. Hari saat tatap mata kita saling bersua, seketika gelombang keraguan di jiwaku mereda, digantikan oleh kedamaian yang belum pernah kutemukan di pelabuhan manapun.",
    island1Beacon: "Sauh Emas Pertama yang Mengunci Rasa",
    island2Name: "Golfe des Murmures (Teluk Bisikan Kasih)",
    island2Coordinates: "Lat 21°19'N, Long 157°52'W • Perairan Teduh Bernaung Bukit Asri",
    island2Sounding: "Kedalaman 60 Depa • Bebas Dari Riak dan Embusan Gelisah",
    island2Story:
      "Perairan sunyi di balik teluk pelindung tempat rahasia, impian, dan tawa kita berpadu dalam kehangatan malam. Di sini kita belajar saling membuka kerentanan tanpa rasa takut, membiarkan deburan ombak menjadi melodi pengantar tidur bagi jiwa kita.",
    island2Beacon: "Rembulan Kembar Penuntun Kegelapan Malam",
    island3Name: "Détroit des Tempêtes Vaincues (Selat Badai yang Ditaklukkan)",
    island3Coordinates: "Lat 35°58'S, Long 138°08'E • Tebing Karang Granit yang Kokoh",
    island3Sounding: "Kedalaman 120 Depa • Fondasi Karang Abadi Tak Tergoyahkan",
    island3Story:
      "Jalur pelayaran sempit berkarang terjal di mana kita pernah diuji oleh pasang surut dan badai hidup yang sengit. Namun dengan saling menggenggam tangan erat di atas kemudi, kita berhasil menaklukkan setiap hempasan ombak dan keluar menjadi nahkoda cinta yang jauh lebih tangguh.",
    island3Beacon: "Lentera Mercusuar Granit Abadi Tak Pernah Padam",
    island4Name: "Cap de l'Éternité (Tanjung Keabadian)",
    island4Coordinates: "Lat 00°00'N, Long 00°00'E • Samudra Terbuka Tanpa Batas Akhir",
    island4Sounding: "Kedalaman Samudra Hati (Palung Tanpa Batas Ukuran)",
    island4Story:
      "Ujung tanjung megah tempat laut dan langit menyatu menjadi satu garis cakrawala keemasan. Tempat di mana matahari tak pernah terbenam, dan pelayaran kita bukan lagi tentang mencari tanah baru, melainkan menikmati setiap embusan angin berdua selamanya.",
    island4Beacon: "Cakrawala Fajar Keemasan Tanpa Batas Waktu",
    instrument1Name: "The Brass Astrolabe (Astrolab Bintang)",
    instrument1Role: "Penjajar Posisi Bintang Penuntun Jiwa",
    instrument1Desc:
      "Ditempa dari kuningan murni untuk memetakan rasi bintang di langit. Setiap kali aku mengarahkannya ke langit malam, hanya ada satu konstelasi yang menjadi poros pandanganku: kilau matamu yang selalu menenangkan setiap gundah.",
    instrument2Name: "The Mariner's Sextant (Sekstan Maritim)",
    instrument2Role: "Pengukur Sudut Kemilau Senyuman",
    instrument2Desc:
      "Instrumen cermin ganda untuk mengukur sudut elevasi matahari dari garis cakrawala. Menjadi pengingat abadi bahwa kehangatan senyummu selalu berada pada sudut yang tepat untuk menghangatkan geladak hidupku di cuaca terdingin sekalipun.",
    instrument3Name: "The Hourglass of Golden Sand (Jam Pasir Emas)",
    instrument3Role: "Penakar Butiran Waktu Sakral Berdua",
    instrument3Desc:
      "Dua labu kaca kristal tertutup dengan pasir pantai keemasan yang menetes tanpa henti. Membuktikan bahwa setiap butir detik yang kulalui bersamamu adalah berkah tak ternilai yang tak akan pernah kubiarkan hanyut sia-sia.",
    instrument4Name: "The Magnetic Compass Rose (Mawar Kompas Magnetik)",
    instrument4Role: "Penunjuk Kutub Utara Hati Sejati",
    instrument4Desc:
      "Jarum besi magnetik yang mengambang bebas di atas mangkuk minyak atsiri. Dikelilingi kabut sepekat apapun atau badai sekuat apapun, jarum ini tak pernah bimbang: kutub utaranya selalu menunjuk lurus ke arah tempatmu berada.",
    bathymetricDepth: "10,000 Fathoms • Kedalaman Jiwa Tanpa Titik Dasar",
    tradeWindName: "Breeze of Constant Tenderness • Selalu Mendorong Kita Maju",
    oceanicCurrent: "Gulf Stream of Eternal Loyalty • Arus Hangat Kesetiaan Penuh",
    anchorStatus: "Terkunci Rapat di Palung Hatimu • Tak Akan Goyah oleh Topan Apapun",
    admiraltyOathTitle: "The Mariner's Eternal Admiralty Oath (Sumpah Nakhoda di Hadapan Samudra)",
    admiraltyOathText:
      "Di hadapan luasnya samudra raya dan di bawah kesaksian bintang-bintang navigasi langit, aku bersumpah untuk senantiasa menjadi nahkoda yang setia memegang kemudi perahu kita, tidak akan pernah meninggalkan geladak di saat badai paling kelam menerpa, dan akan terus menjaga nyala api mercusuar kasih kita hingga akhir hayat.",
    admiraltySignerTitle: "Nakhoda Pelayaran Jiwa & Pelindung Haluan Hidupmu,",
    bottleLabel: "Botol Laut Kaca Zamrud Bersegel Gabus Lilin",
    bottleButtonText: "Buka Sumbat Gabus Botol Laut",
    bottleSecretMessage:
      "Jika surat ini pernah hanyut di ribuan perairan asing, ketahuilah bahwa ombak akan selalu tahu arah untuk mengantarkannya tepat ke tanganmu. Dari jutaan pelabuhan di dunia, hanya pelukanmu satu-satunya dermaga tempat hatiku merasa genap dan pulang.",
    bottleClosingQuote: "Dihanyutkan di lautan waktu, ditakdirkan untuk berlabuh di genggamanmu selamanya.",
    primaryColor: "#d4af37",
    secondaryColor: "#2dd4bf",
    accentColor: "#0b1e32",
    musicTrack: "https://cdn.pixabay.com/download/audio/2022/03/15/audio_c89b7b9cf4.mp3?filename=celestial-music-box-waltz-10928.mp3",
  },
};
