import type { TemplateMeta } from "../types";

export const chateauWeddingTemplate: TemplateMeta = {
  slug: "chateau-wedding",
  name: "Château de Versailles: Mariage Royal",
  category: "Undangan",
  description:
    "Undangan pernikahan megah bertema pesta dansa istana kerajaan Prancis Baroque dan kemegahan Versailles (The Grand French Baroque Palace & Chandelier Gala Wedding). Menampilkan bingkai ukiran emas Rococo boiserie, lambang segel wangsa kehormatan (Heraldic Sovereign Crest) dengan monogram inisial mempelai bertahbis mahkota, maklumat resmi titah pernikahan, kisah cinta bangsawan di taman istana, 4 paviliun acara istana interaktif (Chapelle Royale, Galerie des Glaces, Grand Couvert, & Parterre d'Eau), panduan protokol kedatangan dan gerbang kehormatan, etiket busana haute couture dengan 4 swatch warna kerajaan, form konfirmasi RSVP kerajaan interaktif, vault rekening tanda kasih digital dengan tombol salin satu-klik, serta simfoni waltz orkestra istana yang megah.",
  tagline: "Château de Versailles: Titah Suci Penyatuan Dua Wangsa dalam Kemegahan Abadi",
  cardAccent: "border-amber-400/40 bg-gradient-to-br from-[#1a050c] via-[#2e0915] to-[#120308] text-amber-200",
  highlights: [
    "Konsep Istana Kerajaan Prancis Baroque & Gala Ballroom Versailles (Hall of Mirrors)",
    "Lambang Segel Wangsa Kehormatan (Heraldic Sovereign Crest) & Maklumat Titah Kerajaan",
    "Kisah Cinta Dua Hati di Balik Gerbang Istana & Janji Suci Bersepuh Emas",
    "4 Paviliun Acara Istana Interaktif (Pemberkatan Katedral, Pawai Cermin, Jamuan Kenegaraan, Dansa Waltz)",
    "Panduan Busana Bangsawan Haute Couture dengan 4 Swatch Warna Kehormatan Istana",
    "Vault Tanda Kasih Digital dengan Tombol Satu-Klik Salin No. Rekening & Alunan Simfoni Waltz",
  ],
  fields: [
    // Section 1: Titah Proklamasi Kerajaan & Monogram Wangsa
    {
      name: "coupleMonogram",
      label: "Monogram Inisial Mempelai",
      type: "text",
      placeholder: "H & C",
      defaultValue: "H & C",
      section: "Proklamasi & Monogram Kerajaan",
    },
    {
      name: "weddingTitle",
      label: "Judul Perayaan Pernikahan Kerajaan",
      type: "text",
      placeholder: "Le Grand Mariage Royal de Henri & Camille",
      defaultValue: "Le Grand Mariage Royal de Henri & Camille",
      section: "Proklamasi & Monogram Kerajaan",
    },
    {
      name: "royalProclamationHeader",
      label: "Tajuk Maklumat Titah Kerajaan",
      type: "text",
      placeholder: "DE PAR LE ROI • PROCLAMATION ROYALE",
      defaultValue: "DE PAR LE ROI • PROCLAMATION ROYALE",
      section: "Proklamasi & Monogram Kerajaan",
    },
    {
      name: "invitationSubtitle",
      label: "Subjudul Undangan Kehormatan",
      type: "text",
      placeholder: "Dengan Memohon Berkah & Rahmat Illahi, Kami Menitahkan Kehadiran Anda",
      defaultValue: "Dengan Memohon Berkah & Rahmat Illahi, Kami Menitahkan Kehadiran Anda",
      section: "Proklamasi & Monogram Kerajaan",
    },
    {
      name: "recipientName",
      label: "Nama Tamu Undangan Terhormat",
      type: "text",
      placeholder: "Yang Mulia Tamu Undangan Kehormatan",
      required: true,
      isRecipient: true,
      section: "Proklamasi & Monogram Kerajaan",
    },
    {
      name: "weddingDate",
      label: "Hari & Tanggal Pernikahan",
      type: "text",
      placeholder: "Minggu, 15 November 2026",
      defaultValue: "Minggu, 15 November 2026",
      section: "Proklamasi & Monogram Kerajaan",
    },
    {
      name: "weddingTime",
      label: "Rentang Waktu Acara",
      type: "text",
      placeholder: "Pukul 10.00 - 23.30 CET",
      defaultValue: "Pukul 10.00 - 23.30 CET",
      section: "Proklamasi & Monogram Kerajaan",
    },
    {
      name: "groomName",
      label: "Nama Mempelai Pria",
      type: "text",
      placeholder: "Lord Henri Alexandre de Valois",
      required: true,
      defaultValue: "Lord Henri Alexandre de Valois",
      section: "Proklamasi & Monogram Kerajaan",
    },
    {
      name: "groomParents",
      label: "Silsilah Orang Tua Mempelai Pria",
      type: "text",
      placeholder: "Putra Sulung dari Duc Lorenzo de Valois & Duchesse Vivienne de Montmirail",
      defaultValue: "Putra Sulung dari Duc Lorenzo de Valois & Duchesse Vivienne de Montmirail",
      section: "Proklamasi & Monogram Kerajaan",
    },
    {
      name: "brideName",
      label: "Nama Mempelai Wanita",
      type: "text",
      placeholder: "Lady Camille Geneviève de Bourbon",
      required: true,
      defaultValue: "Lady Camille Geneviève de Bourbon",
      section: "Proklamasi & Monogram Kerajaan",
    },
    {
      name: "brideParents",
      label: "Silsilah Orang Tua Mempelai Wanita",
      type: "text",
      placeholder: "Putri Kedua dari Marquis François de Bourbon & Marquise Hélène de La Tour",
      defaultValue: "Putri Kedua dari Marquis François de Bourbon & Marquise Hélène de La Tour",
      section: "Proklamasi & Monogram Kerajaan",
    },
    {
      name: "sacredVerse",
      label: "Ayat Suci / Deklarasi Ikrar Perjanjian",
      type: "textarea",
      placeholder: "Kutipan ayat suci atau sumpah...",
      defaultValue:
        "“Dan di antara tanda-tanda kebesaran-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, agar kamu cenderung dan merasa tenteram kepadanya, dan Dia menjadikan di antaramu rasa kasih dan sayang.”",
      section: "Proklamasi & Monogram Kerajaan",
    },

    // Section 2: Kisah Asmara di Bawah Lentera Istana (The Royal Court Chronicle)
    {
      name: "storyTitle",
      label: "Judul Kisah Asmara Bangsawan",
      type: "text",
      placeholder: "Asmara Dua Hati di Balik Gerbang Versailles",
      defaultValue: "Asmara Dua Hati di Balik Gerbang Versailles",
      section: "Kisah Asmara Kerajaan",
    },
    {
      name: "storySubtitle",
      label: "Subjudul Kisah Asmara",
      type: "text",
      placeholder: "Menyatukan Dua Wangsa di Bawah Kilau Lentera Emas dan Alunan Harpa Prancis",
      defaultValue: "Menyatukan Dua Wangsa di Bawah Kilau Lentera Emas dan Alunan Harpa Prancis",
      section: "Kisah Asmara Kerajaan",
    },
    {
      name: "mainMessage",
      label: "Narasi Kisah Cinta (Warkah Utama)",
      type: "textarea",
      placeholder: "Tuliskan narasi perjalanan cinta kedua mempelai...",
      required: true,
      defaultValue:
        "Pertemuan kami terukir di sebuah malam perayaan di taman air mancur Versailles, saat alunan musik petik harpa mengalir di antara gemerisik dedaunan musim gugur. Di tengah riuhnya para bangsawan dan kilau lentera emas, sebuah pandangan mata mengunci takdir kami dalam satu ikatan batin yang tak terpisahkan.\n\nMelewati perjalanan waktu dengan saling menguatkan harkat dan martabat cinta, kami menyadari bahwa mahkota kemuliaan sejati bukanlah tahta kekuasaan, melainkan ketulusan hati yang saling melindungi dalam suka dan duka. Kini, dengan penuh rasa hormat dan syukur kepada Tuhan Yang Maha Esa, kami menitahkan kehadiran Yang Terhormat untuk menyaksikan pengukuhan janji suci kami di aula kemuliaan istana.",
      section: "Kisah Asmara Kerajaan",
    },
    {
      name: "royalAxiom",
      label: "Aksioma Filosofis Asmara Istana",
      type: "text",
      placeholder: "Kutipan filosofis kerajaan...",
      defaultValue: "Cinta sejati adalah mahkota tertinggi yang tidak akan pernah pudar oleh pergantian takhta zaman.",
      section: "Kisah Asmara Kerajaan",
    },
    {
      name: "senderName",
      label: "Nama Tanda Tangan Pasangan Pengantin",
      type: "text",
      placeholder: "Henri & Camille",
      defaultValue: "Henri & Camille",
      section: "Kisah Asmara Kerajaan",
    },

    // Section 3: 4 Paviliun Acara Istana Interaktif (Les 4 Grands Salons)
    {
      name: "salon1Time",
      label: "Paviliun 1: Waktu Acara",
      type: "text",
      placeholder: "10:00 - 12:00 CET",
      defaultValue: "10:00 - 12:00 CET",
      section: "4 Paviliun Acara Istana",
    },
    {
      name: "salon1Title",
      label: "Paviliun 1: Nama Prosesi",
      type: "text",
      placeholder: "Salon de Vénus: Pemberkatan & Ikrar Janji Suci",
      defaultValue: "Salon de Vénus: Pemberkatan & Ikrar Janji Suci",
      section: "4 Paviliun Acara Istana",
    },
    {
      name: "salon1Location",
      label: "Paviliun 1: Lokasi Area",
      type: "text",
      placeholder: "Chapelle Royale, Château de Versailles",
      defaultValue: "Chapelle Royale, Château de Versailles",
      section: "4 Paviliun Acara Istana",
    },
    {
      name: "salon1Desc",
      label: "Paviliun 1: Keterangan Prosesi",
      type: "textarea",
      placeholder: "Deskripsi prosesi...",
      defaultValue:
        "Upacara sakral pengucapan janji suci di hadapan altar emas berlapis beludru kirmizi dengan iringan paduan suara katedral dan pertukaran cincin pusaka wangsa.",
      section: "4 Paviliun Acara Istana",
    },

    {
      name: "salon2Time",
      label: "Paviliun 2: Waktu Acara",
      type: "text",
      placeholder: "16:30 - 18:30 CET",
      defaultValue: "16:30 - 18:30 CET",
      section: "4 Paviliun Acara Istana",
    },
    {
      name: "salon2Title",
      label: "Paviliun 2: Nama Prosesi",
      type: "text",
      placeholder: "Galerie des Glaces: Pawai Sampanye di Lorong Cermin",
      defaultValue: "Galerie des Glaces: Pawai Sampanye di Lorong Cermin",
      section: "4 Paviliun Acara Istana",
    },
    {
      name: "salon2Location",
      label: "Paviliun 2: Lokasi Area",
      type: "text",
      placeholder: "La Grande Galerie des Glaces",
      defaultValue: "La Grande Galerie des Glaces",
      section: "4 Paviliun Acara Istana",
    },
    {
      name: "salon2Desc",
      label: "Paviliun 2: Keterangan Prosesi",
      type: "textarea",
      placeholder: "Deskripsi prosesi...",
      defaultValue:
        "Sambutan kehormatan para bangsawan di lorong cermin kristal legendaris dengan sajian sampanye vintage dan alunan harpa klasik Prancis.",
      section: "4 Paviliun Acara Istana",
    },

    {
      name: "salon3Time",
      label: "Paviliun 3: Waktu Acara",
      type: "text",
      placeholder: "19:00 - 21:00 CET",
      defaultValue: "19:00 - 21:00 CET",
      section: "4 Paviliun Acara Istana",
    },
    {
      name: "salon3Title",
      label: "Paviliun 3: Nama Prosesi",
      type: "text",
      placeholder: "Grand Couvert Royal: Jamuan Makan Malam Kenegaraan",
      defaultValue: "Grand Couvert Royal: Jamuan Makan Malam Kenegaraan",
      section: "4 Paviliun Acara Istana",
    },
    {
      name: "salon3Location",
      label: "Paviliun 3: Lokasi Area",
      type: "text",
      placeholder: "Salon d'Hercule & Grand Vestibule",
      defaultValue: "Salon d'Hercule & Grand Vestibule",
      section: "4 Paviliun Acara Istana",
    },
    {
      name: "salon3Desc",
      label: "Paviliun 3: Keterangan Prosesi",
      type: "textarea",
      placeholder: "Deskripsi prosesi...",
      defaultValue:
        "Jamuan makan malam fine dining haute cuisine klasik Prancis di bawah gemerlap cahaya 50 chandelier kristal dan set meja porselen istana.",
      section: "4 Paviliun Acara Istana",
    },

    {
      name: "salon4Time",
      label: "Paviliun 4: Waktu Acara",
      type: "text",
      placeholder: "21:00 - Selesai",
      defaultValue: "21:00 - Selesai",
      section: "4 Paviliun Acara Istana",
    },
    {
      name: "salon4Title",
      label: "Paviliun 4: Nama Prosesi",
      type: "text",
      placeholder: "Parterre d'Eau: Dansa Waltz & Kembang Api Megah",
      defaultValue: "Parterre d'Eau: Dansa Waltz & Kembang Api Megah",
      section: "4 Paviliun Acara Istana",
    },
    {
      name: "salon4Location",
      label: "Paviliun 4: Lokasi Area",
      type: "text",
      placeholder: "Terrasse du Grand Parterre & Les Fontaines",
      defaultValue: "Terrasse du Grand Parterre & Les Fontaines",
      section: "4 Paviliun Acara Istana",
    },
    {
      name: "salon4Desc",
      label: "Paviliun 4: Keterangan Prosesi",
      type: "textarea",
      placeholder: "Deskripsi prosesi...",
      defaultValue:
        "Dansa waltz pertama kedua mempelai diiringi orkestra simfoni kerajaan, pemotongan kue pengantin mahkota, dan pertunjukan kembang api spektakuler di atas kolam air mancur istana.",
      section: "4 Paviliun Acara Istana",
    },

    // Section 4: Protokol Kedatangan & Panduan Lokasi Istana
    {
      name: "chateauName",
      label: "Nama Istana / Estate Kerajaan",
      type: "text",
      placeholder: "Château de Versailles • Domaine Royal",
      defaultValue: "Château de Versailles • Domaine Royal",
      section: "Protokol & Lokasi Istana",
    },
    {
      name: "chateauSubname",
      label: "Wilayah & Kota Istana",
      type: "text",
      placeholder: "Place d'Armes, 78000 Versailles, France",
      defaultValue: "Place d'Armes, 78000 Versailles, France",
      section: "Protokol & Lokasi Istana",
    },
    {
      name: "chateauAddress",
      label: "Alamat Lengkap Gerbang Istana",
      type: "textarea",
      placeholder: "Alamat lengkap...",
      defaultValue: "Place d'Armes, 78000 Versailles, Île-de-France, France",
      section: "Protokol & Lokasi Istana",
    },
    {
      name: "carriageProtocol",
      label: "Protokol Kereta Kencana & Akses Kendaraan",
      type: "textarea",
      placeholder: "Protokol kedatangan tamu...",
      defaultValue:
        "Tamu kehormatan disambut melalui Grille d'Honneur (Gerbang Kehormatan Utama). Disediakan layanan pengawalan protokoler, valet parking privat, dan kereta kencana hias.",
      section: "Protokol & Lokasi Istana",
    },
    {
      name: "mapsUrl",
      label: "URL Google Maps Lokasi",
      type: "text",
      placeholder: "https://maps.google.com/?q=Château+de+Versailles",
      defaultValue: "https://maps.google.com/?q=Château+de+Versailles",
      section: "Protokol & Lokasi Istana",
    },

    // Section 5: Etiket Bangsawan & Dress Code Haute Couture
    {
      name: "dressCodeTheme",
      label: "Tema Busana Bangsawan",
      type: "text",
      placeholder: "Black Tie Baroque Elegance • Haute Couture Royale",
      defaultValue: "Black Tie Baroque Elegance • Haute Couture Royale",
      section: "Etiket & Dress Code Bangsawan",
    },
    {
      name: "dressCodeDesc",
      label: "Deskripsi Panduan Busana",
      type: "textarea",
      placeholder: "Penjelasan dress code...",
      defaultValue:
        "Para pria disarankan mengenakan setelan tuxedo hitam klasik atau velvet smoking jacket. Para wanita disarankan mengenakan gaun malam megah (ball gown) bernuansa royal palace dengan aksen permata atau brokat klasik.",
      section: "Etiket & Dress Code Bangsawan",
    },
    {
      name: "colorSwatch1",
      label: "Swatch Warna 1: Imperial Burgundy Velvet",
      type: "text",
      placeholder: "Imperial Burgundy Velvet (#500724)",
      defaultValue: "Imperial Burgundy Velvet (#500724)",
      section: "Etiket & Dress Code Bangsawan",
    },
    {
      name: "colorSwatch2",
      label: "Swatch Warna 2: Versailles Gold Leaf",
      type: "text",
      placeholder: "Versailles Gold Leaf (#d4af37)",
      defaultValue: "Versailles Gold Leaf (#d4af37)",
      section: "Etiket & Dress Code Bangsawan",
    },
    {
      name: "colorSwatch3",
      label: "Swatch Warna 3: Midnight King's Navy",
      type: "text",
      placeholder: "Midnight King's Navy (#0f172a)",
      defaultValue: "Midnight King's Navy (#0f172a)",
      section: "Etiket & Dress Code Bangsawan",
    },
    {
      name: "colorSwatch4",
      label: "Swatch Warna 4: Fleur-de-Lis Silk Ivory",
      type: "text",
      placeholder: "Fleur-de-Lis Silk Ivory (#f8fafc)",
      defaultValue: "Fleur-de-Lis Silk Ivory (#f8fafc)",
      section: "Etiket & Dress Code Bangsawan",
    },
    {
      name: "courtEtiquetteNotes",
      label: "Catatan Protokol Kehormatan Istana",
      type: "textarea",
      placeholder: "Catatan tata krama istana...",
      defaultValue:
        "Demi menjaga keluhuran suasana istana bersejarah, para tamu dimohon untuk tiba di Grille d'Honneur 30 menit sebelum prosesi dimulai serta mematuhi tata tertib protokoler perjamuan kenegaraan.",
      section: "Etiket & Dress Code Bangsawan",
    },

    // Section 6: Konfirmasi Kehadiran Bangsawan (RSVP), Tanda Kasih Digital & Simfoni
    {
      name: "bank1Name",
      label: "Bank 1: Nama Bank",
      type: "text",
      placeholder: "BCA (Bank Central Asia)",
      defaultValue: "BCA (Bank Central Asia)",
      section: "RSVP & Tanda Kasih Kerajaan",
    },
    {
      name: "bank1AccountNo",
      label: "Bank 1: Nomor Rekening",
      type: "text",
      placeholder: "8820912411",
      defaultValue: "8820912411",
      section: "RSVP & Tanda Kasih Kerajaan",
    },
    {
      name: "bank1Holder",
      label: "Bank 1: Atas Nama Rekening",
      type: "text",
      placeholder: "Lord Henri Alexandre de Valois",
      defaultValue: "Lord Henri Alexandre de Valois",
      section: "RSVP & Tanda Kasih Kerajaan",
    },
    {
      name: "bank2Name",
      label: "Bank 2: Nama Bank",
      type: "text",
      placeholder: "Bank Mandiri",
      defaultValue: "Bank Mandiri",
      section: "RSVP & Tanda Kasih Kerajaan",
    },
    {
      name: "bank2AccountNo",
      label: "Bank 2: Nomor Rekening",
      type: "text",
      placeholder: "1370098231044",
      defaultValue: "1370098231044",
      section: "RSVP & Tanda Kasih Kerajaan",
    },
    {
      name: "bank2Holder",
      label: "Bank 2: Atas Nama Rekening",
      type: "text",
      placeholder: "Lady Camille Geneviève de Bourbon",
      defaultValue: "Lady Camille Geneviève de Bourbon",
      section: "RSVP & Tanda Kasih Kerajaan",
    },
    {
      name: "giftMessage",
      label: "Pesan Pengantar Tanda Kasih (Royal Vault of Blessings)",
      type: "textarea",
      placeholder: "Pesan tanda kasih...",
      defaultValue:
        "Kehadiran dan doa restu Yang Terhormat adalah anugerah terbesar dalam penyatuan suci wangsa kami. Namun jika berkenan memberikan tanda kasih berupa kado pernikahan, kami menyediakan pundi digital di atas dengan rasa terima kasih yang mendalam.",
      section: "RSVP & Tanda Kasih Kerajaan",
    },
    {
      name: "rsvpDeadline",
      label: "Batas Waktu Konfirmasi RSVP Kerajaan",
      type: "text",
      placeholder: "Mohon konfirmasi kehadiran sebelum 20 Oktober 2026",
      defaultValue: "Mohon konfirmasi kehadiran sebelum 20 Oktober 2026",
      section: "RSVP & Tanda Kasih Kerajaan",
    },

    // Palette & Music
    {
      name: "primaryColor",
      label: "Warna Utama (Versailles Gold Leaf)",
      type: "color",
      defaultValue: "#d4af37",
      section: "Pengaturan Tampilan & Musik",
    },
    {
      name: "secondaryColor",
      label: "Warna Sekunder (Imperial Burgundy Velvet)",
      type: "color",
      defaultValue: "#991b1b",
      section: "Pengaturan Tampilan & Musik",
    },
    {
      name: "accentColor",
      label: "Warna Aksen (Velvet Deep Wine)",
      type: "color",
      defaultValue: "#24060f",
      section: "Pengaturan Tampilan & Musik",
    },
    {
      name: "musicTrack",
      label: "URL Musik Latar (Simfoni Waltz Istana Versailles)",
      type: "text",
      placeholder: "https://cdn.pixabay.com/download/audio/...",
      defaultValue: "https://cdn.pixabay.com/download/audio/2022/03/15/audio_c89b7b9cf4.mp3?filename=celestial-music-box-waltz-10928.mp3",
      section: "Pengaturan Tampilan & Musik",
    },
  ],
  sample: {
    coupleMonogram: "H & C",
    weddingTitle: "Le Grand Mariage Royal de Henri & Camille",
    royalProclamationHeader: "DE PAR LE ROI • PROCLAMATION ROYALE",
    invitationSubtitle: "Dengan Memohon Berkah & Rahmat Illahi, Kami Menitahkan Kehadiran Anda",
    recipientName: "Yang Mulia Tamu Undangan Kehormatan",
    weddingDate: "Minggu, 15 November 2026",
    weddingTime: "Pukul 10.00 - 23.30 CET",
    groomName: "Lord Henri Alexandre de Valois",
    groomParents: "Putra Sulung dari Duc Lorenzo de Valois & Duchesse Vivienne de Montmirail",
    brideName: "Lady Camille Geneviève de Bourbon",
    brideParents: "Putri Kedua dari Marquis François de Bourbon & Marquise Hélène de La Tour",
    sacredVerse:
      "“Dan di antara tanda-tanda kebesaran-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, agar kamu cenderung dan merasa tenteram kepadanya, dan Dia menjadikan di antaramu rasa kasih dan sayang.”",
    storyTitle: "Asmara Dua Hati di Balik Gerbang Versailles",
    storySubtitle: "Menyatukan Dua Wangsa di Bawah Kilau Lentera Emas dan Alunan Harpa Prancis",
    mainMessage:
      "Pertemuan kami terukir di sebuah malam perayaan di taman air mancur Versailles, saat alunan musik petik harpa mengalir di antara gemerisik dedaunan musim gugur. Di tengah riuhnya para bangsawan dan kilau lentera emas, sebuah pandangan mata mengunci takdir kami dalam satu ikatan batin yang tak terpisahkan.\n\nMelewati perjalanan waktu dengan saling menguatkan harkat dan martabat cinta, kami menyadari bahwa mahkota kemuliaan sejati bukanlah tahta kekuasaan, melainkan ketulusan hati yang saling melindungi dalam suka dan duka. Kini, dengan penuh rasa hormat dan syukur kepada Tuhan Yang Maha Esa, kami menitahkan kehadiran Yang Terhormat untuk menyaksikan pengukuhan janji suci kami di aula kemuliaan istana.",
    royalAxiom: "Cinta sejati adalah mahkota tertinggi yang tidak akan pernah pudar oleh pergantian takhta zaman.",
    senderName: "Henri & Camille",
    salon1Time: "10:00 - 12:00 CET",
    salon1Title: "Salon de Vénus: Pemberkatan & Ikrar Janji Suci",
    salon1Location: "Chapelle Royale, Château de Versailles",
    salon1Desc:
      "Upacara sakral pengucapan janji suci di hadapan altar emas berlapis beludru kirmizi dengan iringan paduan suara katedral dan pertukaran cincin pusaka wangsa.",
    salon2Time: "16:30 - 18:30 CET",
    salon2Title: "Galerie des Glaces: Pawai Sampanye di Lorong Cermin",
    salon2Location: "La Grande Galerie des Glaces",
    salon2Desc:
      "Sambutan kehormatan para bangsawan di lorong cermin kristal legendaris dengan sajian sampanye vintage dan alunan harpa klasik Prancis.",
    salon3Time: "19:00 - 21:00 CET",
    salon3Title: "Grand Couvert Royal: Jamuan Makan Malam Kenegaraan",
    salon3Location: "Salon d'Hercule & Grand Vestibule",
    salon3Desc:
      "Jamuan makan malam fine dining haute cuisine klasik Prancis di bawah gemerlap cahaya 50 chandelier kristal dan set meja porselen istana.",
    salon4Time: "21:00 - Selesai",
    salon4Title: "Parterre d'Eau: Dansa Waltz & Kembang Api Megah",
    salon4Location: "Terrasse du Grand Parterre & Les Fontaines",
    salon4Desc:
      "Dansa waltz pertama kedua mempelai diiringi orkestra simfoni kerajaan, pemotongan kue pengantin mahkota, dan pertunjukan kembang api spektakuler di atas kolam air mancur istana.",
    chateauName: "Château de Versailles • Domaine Royal",
    chateauSubname: "Place d'Armes, 78000 Versailles, France",
    chateauAddress: "Place d'Armes, 78000 Versailles, Île-de-France, France",
    carriageProtocol:
      "Tamu kehormatan disambut melalui Grille d'Honneur (Gerbang Kehormatan Utama). Disediakan layanan pengawalan protokoler, valet parking privat, dan kereta kencana hias.",
    mapsUrl: "https://maps.google.com/?q=Château+de+Versailles",
    dressCodeTheme: "Black Tie Baroque Elegance • Haute Couture Royale",
    dressCodeDesc:
      "Para pria disarankan mengenakan setelan tuxedo hitam klasik atau velvet smoking jacket. Para wanita disarankan mengenakan gaun malam megah (ball gown) bernuansa royal palace dengan aksen permata atau brokat klasik.",
    colorSwatch1: "Imperial Burgundy Velvet (#500724)",
    colorSwatch2: "Versailles Gold Leaf (#d4af37)",
    colorSwatch3: "Midnight King's Navy (#0f172a)",
    colorSwatch4: "Fleur-de-Lis Silk Ivory (#f8fafc)",
    courtEtiquetteNotes:
      "Demi menjaga keluhuran suasana istana bersejarah, para tamu dimohon untuk tiba di Grille d'Honneur 30 menit sebelum prosesi dimulai serta mematuhi tata tertib protokoler perjamuan kenegaraan.",
    bank1Name: "BCA (Bank Central Asia)",
    bank1AccountNo: "8820912411",
    bank1Holder: "Lord Henri Alexandre de Valois",
    bank2Name: "Bank Mandiri",
    bank2AccountNo: "1370098231044",
    bank2Holder: "Lady Camille Geneviève de Bourbon",
    giftMessage:
      "Kehadiran dan doa restu Yang Terhormat adalah anugerah terbesar dalam penyatuan suci wangsa kami. Namun jika berkenan memberikan tanda kasih berupa kado pernikahan, kami menyediakan pundi digital di atas dengan rasa terima kasih yang mendalam.",
    rsvpDeadline: "Mohon konfirmasi kehadiran sebelum 20 Oktober 2026",
    primaryColor: "#d4af37",
    secondaryColor: "#991b1b",
    accentColor: "#24060f",
    musicTrack: "https://cdn.pixabay.com/download/audio/2022/03/15/audio_c89b7b9cf4.mp3?filename=celestial-music-box-waltz-10928.mp3",
  },
};
