import type { TemplateMeta } from "../types";
import {
  FRIENDSHIP_COLOR_PRESETS,
  BACKGROUND_COLOR_PRESETS,
  CARD_COLOR_PRESETS,
  TEXT_COLOR_PRESETS,
} from "../color-presets";

export const friendshipTemplate: TemplateMeta = {
  slug: "friendship",
  name: "Friendship Tribute Website",
  category: "Pertemanan",
  tagline: "Website persembahan sahabat sejati dengan fist bump interaktif, kilas kenangan, galeri polaroid, dan surat dari hati.",
  description:
    "Website persembahan persahabatan interaktif dan hangat yang cocok untuk hadiah sahabat terbaik. Menampilkan potret kebersamaan, interaksi Fist Bump / Tos Sahabat dengan bunyi akord akustik & janji persahabatan rahasia, statistik & linimasa petualangan, galeri foto polaroid dengan lightbox, 4 kartu sifat terbaik sahabat, surat kebersamaan yang tulus, serta pemutar lagu kenangan.",
  cardAccent: "bg-emerald-500/15 text-emerald-700",
  highlights: [
    "Interaksi Fist Bump / Tos Sahabat dengan akord akustik & janji rahasia",
    "Pajangan potret persahabatan dengan lencana & tahun pertemanan",
    "Statistik kebersamaan & 3 tonggak petualangan seru bersama",
    "Galeri 6 foto polaroid kenangan sahabat dengan lightbox interaktif",
    "4 kartu apresiasi sifat terbaik sahabat & surat tulus menyentuh hati",
  ],
  fields: [
    // 1. Warna Multi-Elemen
    {
      name: "primaryColor",
      label: "Warna Aksen Sahabat (Primary Color)",
      type: "color",
      defaultValue: "#2f6f5e",
      helperText: "Warna lencana persahabatan, tombol fist bump, dan ornamen kartu.",
      colorPresets: FRIENDSHIP_COLOR_PRESETS,
    },
    {
      name: "backgroundColor",
      label: "Warna Latar Belakang Website (Background)",
      type: "color",
      defaultValue: "#f7f9f6",
      helperText: "Warna dasar latar belakang website persahabatan.",
      colorPresets: BACKGROUND_COLOR_PRESETS,
    },
    {
      name: "cardColor",
      label: "Warna Kartu & Konten (Card Container)",
      type: "color",
      defaultValue: "#ffffff",
      helperText: "Warna kartu surat, kartu kenangan, dan panel statistik.",
      colorPresets: CARD_COLOR_PRESETS,
    },
    {
      name: "textColor",
      label: "Warna Teks Judul & Nama",
      type: "color",
      defaultValue: "#1a2e26",
      helperText: "Warna nama sahabat dan judul-judul bagian.",
      colorPresets: TEXT_COLOR_PRESETS,
    },
    {
      name: "bodyTextColor",
      label: "Warna Teks Isi & Cerita",
      type: "color",
      defaultValue: "#334155",
      helperText: "Warna narasi kenangan, surat, dan pesan pelengkap.",
      colorPresets: TEXT_COLOR_PRESETS,
    },

    // 2. Info Hero & Profil Sahabat
    {
      name: "recipientName",
      label: "Nama Sahabat",
      type: "text",
      placeholder: "Bagas Adiputra",
      required: true,
      maxLength: 60,
      isRecipient: true,
      helperText: "Nama sahabat yang dituju.",
    },
    {
      name: "nickname",
      label: "Panggilan Akrab / Nickname",
      type: "text",
      placeholder: "Bro Bagas / Sobat Kental",
      maxLength: 40,
      helperText: "Panggilan akrab atau julukan santai.",
    },
    {
      name: "friendsSince",
      label: "Berteman Sejak",
      type: "text",
      placeholder: "2016 • Bangku SMA",
      maxLength: 60,
      helperText: "Tahun atau momen awal kalian mulai bersahabat.",
    },
    {
      name: "heroBadge",
      label: "Lencana Persahabatan (Badge)",
      type: "text",
      placeholder: "Partner in Crime Since Day One",
      maxLength: 60,
      helperText: "Badge kecil di atas nama sahabat pada bagian pembuka.",
    },
    {
      name: "title",
      label: "Judul Utama Persembahan",
      type: "text",
      placeholder: "Untuk Sahabat Terbaik Seumur Hidup",
      maxLength: 80,
      helperText: "Headline besar di halaman utama pembuka.",
    },
    {
      name: "tagline",
      label: "Kalimat Pembuka / Tagline",
      type: "text",
      placeholder: "Dari sekadar teman sebangku, sampai jadi orang yang paling tahu isi kepalaku.",
      maxLength: 160,
      helperText: "Sub-judul atau pesan ringkas di bawah judul pembuka.",
    },
    {
      name: "heroImage",
      label: "Foto Utama Sahabat / Bersama",
      type: "image",
      helperText: "Foto potret berdua atau foto sahabat terbaik dalam resolusi tinggi.",
    },

    // 3. Interaksi Fist Bump & Janji Rahasia
    {
      name: "fistBumpTitle",
      label: "Judul Fist Bump Interaktif",
      type: "text",
      placeholder: "Tos Sahabat / Fist Bump",
      maxLength: 60,
      helperText: "Judul tombol interaksi tos sahabat.",
    },
    {
      name: "fistBumpPrompt",
      label: "Petunjuk Interaksi",
      type: "text",
      placeholder: "Tekan kepalan tangan untuk tos & dengarkan bunyi pertemanan!",
      maxLength: 120,
      helperText: "Instruksi interaksi bagi sahabat saat membuka website.",
    },
    {
      name: "secretPledgeMessage",
      label: "Janji Sahabat Rahasia (Muncul Setelah Tos)",
      type: "textarea",
      placeholder: "Pledge: Apapun yang terjadi di masa depan, kalau salah satu butuh bantuan jam 2 pagi, pintu rumah selalu terbuka lebar!",
      maxLength: 500,
      rows: 3,
      helperText: "Pesan rahasia atau ikrar persahabatan yang muncul dengan efek confetti/sound.",
    },

    // 4. Statistik & Linimasa Petualangan
    {
      name: "totalYears",
      label: "Lama Bersahabat",
      type: "text",
      placeholder: "8+ Tahun",
      maxLength: 30,
      helperText: "Durasi pertemanan yang sudah terlewati.",
    },
    {
      name: "deepTalks",
      label: "Estimasi Deep Talk / Ngopi",
      type: "text",
      placeholder: "1,200+ Jam",
      maxLength: 30,
      helperText: "Jumlah jam ngopi atau curhat bersama.",
    },
    {
      name: "zeroSecrets",
      label: "Tingkat Rahasia Bocor",
      type: "text",
      placeholder: "0 Rahasia",
      maxLength: 30,
      helperText: "Humor persahabatan (misal: 0 Rahasia Bocor atau 100% Solid).",
    },
    {
      name: "milestoneTitle",
      label: "Judul Bagian Linimasa",
      type: "text",
      placeholder: "Kilas Balik Petualangan Kita",
      maxLength: 80,
    },
    {
      name: "milestone1Year",
      label: "Tahun Tonggak 1",
      type: "text",
      placeholder: "2016",
      maxLength: 20,
    },
    {
      name: "milestone1Title",
      label: "Judul Tonggak 1",
      type: "text",
      placeholder: "Pertemuan Pertama",
      maxLength: 60,
    },
    {
      name: "milestone1Desc",
      label: "Deskripsi Tonggak 1",
      type: "text",
      placeholder: "Ketemu waktu orientasi sekolah, sama-sama telat dan dihukum bareng.",
      maxLength: 160,
    },
    {
      name: "milestone2Year",
      label: "Tahun Tonggak 2",
      type: "text",
      placeholder: "2019",
      maxLength: 20,
    },
    {
      name: "milestone2Title",
      label: "Judul Tonggak 2",
      type: "text",
      placeholder: "Road Trip Dadakan",
      maxLength: 60,
    },
    {
      name: "milestone2Desc",
      label: "Deskripsi Tonggak 2",
      type: "text",
      placeholder: "Motor mogok waktu touring hujan deras, tapi malah jadi cerita paling lucu.",
      maxLength: 160,
    },
    {
      name: "milestone3Year",
      label: "Tahun Tonggak 3",
      type: "text",
      placeholder: "2024 - Sekarang",
      maxLength: 20,
    },
    {
      name: "milestone3Title",
      label: "Judul Tonggak 3",
      type: "text",
      placeholder: "Saling Menopang Karier",
      maxLength: 60,
    },
    {
      name: "milestone3Desc",
      label: "Deskripsi Tonggak 3",
      type: "text",
      placeholder: "Meskipun sibuk dengan jalur masing-masing, selalu ada waktu untuk berkabar.",
      maxLength: 160,
    },

    // 5. Galeri Polaroid Kenangan
    {
      name: "galleryTitle",
      label: "Judul Galeri Kenangan",
      type: "text",
      placeholder: "Galeri Foto & Momen Seru",
      maxLength: 80,
    },
    {
      name: "gallerySubtitle",
      label: "Sub-judul Galeri Kenangan",
      type: "text",
      placeholder: "Setiap jepretan menyimpan tawa yang nggak pernah luntur.",
      maxLength: 120,
    },
    {
      name: "galleryImg1",
      label: "Foto Kenangan 1",
      type: "image",
    },
    {
      name: "galleryCaption1",
      label: "Keterangan Foto 1",
      type: "text",
      placeholder: "Kopdar malam mingguan di warung kopi",
      maxLength: 60,
    },
    {
      name: "galleryDate1",
      label: "Waktu Foto 1",
      type: "text",
      placeholder: "Oktober 2018",
      maxLength: 30,
    },
    {
      name: "galleryImg2",
      label: "Foto Kenangan 2",
      type: "image",
    },
    {
      name: "galleryCaption2",
      label: "Keterangan Foto 2",
      type: "text",
      placeholder: "Muncak gunung pertama bareng",
      maxLength: 60,
    },
    {
      name: "galleryDate2",
      label: "Waktu Foto 2",
      type: "text",
      placeholder: "Juli 2020",
      maxLength: 30,
    },
    {
      name: "galleryImg3",
      label: "Foto Kenangan 3",
      type: "image",
    },
    {
      name: "galleryCaption3",
      label: "Keterangan Foto 3",
      type: "text",
      placeholder: "Wisuda & rayain bareng kawan-kawan",
      maxLength: 60,
    },
    {
      name: "galleryDate3",
      label: "Waktu Foto 3",
      type: "text",
      placeholder: "September 2022",
      maxLength: 30,
    },
    {
      name: "galleryImg4",
      label: "Foto Kenangan 4",
      type: "image",
    },
    {
      name: "galleryCaption4",
      label: "Keterangan Foto 4",
      type: "text",
      placeholder: "Kerja kelompok yang berujung nongkrong",
      maxLength: 60,
    },
    {
      name: "galleryDate4",
      label: "Waktu Foto 4",
      type: "text",
      placeholder: "Mei 2023",
      maxLength: 30,
    },
    {
      name: "galleryImg5",
      label: "Foto Kenangan 5",
      type: "image",
    },
    {
      name: "galleryCaption5",
      label: "Keterangan Foto 5",
      type: "text",
      placeholder: "Liburan pantai dadakan waktu weekend",
      maxLength: 60,
    },
    {
      name: "galleryDate5",
      label: "Waktu Foto 5",
      type: "text",
      placeholder: "Januari 2024",
      maxLength: 30,
    },
    {
      name: "galleryImg6",
      label: "Foto Kenangan 6",
      type: "image",
    },
    {
      name: "galleryCaption6",
      label: "Keterangan Foto 6",
      type: "text",
      placeholder: "Foto terbaru pas reuni bareng",
      maxLength: 60,
    },
    {
      name: "galleryDate6",
      label: "Waktu Foto 6",
      type: "text",
      placeholder: "Agustus 2024",
      maxLength: 30,
    },

    // 6. Kartu Sifat Terbaik Sahabat
    {
      name: "wishesTitle",
      label: "Judul Bagian Sifat Sahabat",
      type: "text",
      placeholder: "Hal yang Paling Aku Kagumi Darimu",
      maxLength: 80,
    },
    {
      name: "quality1Title",
      label: "Sifat Terbaik 1",
      type: "text",
      placeholder: "Pendengar Tanpa Menghakimi",
      maxLength: 50,
    },
    {
      name: "quality1Desc",
      label: "Ulasan Sifat 1",
      type: "text",
      placeholder: "Selalu siap mendengarkan uneg-uneg terbodoh sekalipun tanpa langsung nge-judge.",
      maxLength: 140,
    },
    {
      name: "quality2Title",
      label: "Sifat Terbaik 2",
      type: "text",
      placeholder: "Paling Loyal & Dapat Diandalkan",
      maxLength: 50,
    },
    {
      name: "quality2Desc",
      label: "Ulasan Sifat 2",
      type: "text",
      placeholder: "Kalau butuh bantuan jam berapapun, kamu orang pertama yang selalu angkat telepon.",
      maxLength: 140,
    },
    {
      name: "quality3Title",
      label: "Sifat Terbaik 3",
      type: "text",
      placeholder: "Humor yang Nggak Ada Habisnya",
      maxLength: 50,
    },
    {
      name: "quality3Desc",
      label: "Ulasan Sifat 3",
      type: "text",
      placeholder: "Bahkan di hari paling berat sekalipun, celetukanmu selalu bikin suasana cair seketika.",
      maxLength: 140,
    },
    {
      name: "quality4Title",
      label: "Sifat Terbaik 4",
      type: "text",
      placeholder: "Pendukung Mimpi Garis Keras",
      maxLength: 50,
    },
    {
      name: "quality4Desc",
      label: "Ulasan Sifat 4",
      type: "text",
      placeholder: "Ketika orang lain meremehkan rencana gilaku, kamu yang pertama bilang 'Gass!'",
      maxLength: 140,
    },

    // 7. Surat Persahabatan & Penutup
    {
      name: "quote",
      label: "Kutipan Persahabatan",
      type: "text",
      placeholder: "Sahabat sejati bukan mereka yang tak pernah terpisah, tapi mereka yang saat berjumpa kembali terasa tak ada yang berubah.",
      maxLength: 200,
    },
    {
      name: "message",
      label: "Isi Surat Persahabatan",
      type: "textarea",
      placeholder: "Tuliskan pesan tulus dan apresiasi untuk sahabatmu...",
      required: true,
      maxLength: 3000,
      rows: 9,
    },
    {
      name: "senderName",
      label: "Nama Pengirim",
      type: "text",
      placeholder: "Yudha Pratama",
      required: true,
      maxLength: 60,
    },
    {
      name: "signature",
      label: "Gelar / Kata Penutup Tanda Tangan",
      type: "text",
      placeholder: "Sahabatmu Selamanya,",
      maxLength: 40,
    },
    {
      name: "letterDate",
      label: "Tanggal Surat",
      type: "date",
    },

    // 8. Musik Latar
    {
      name: "musicTitle",
      label: "Judul Lagu Persahabatan",
      type: "text",
      placeholder: "Count On Me - Bruno Mars (Acoustic)",
      maxLength: 60,
    },
    {
      name: "bgMusicUrl",
      label: "URL Audio Lagu Latar (MP3 / Direct Stream)",
      type: "text",
      placeholder: "https://example.com/audio/friendship-theme.mp3",
      maxLength: 255,
      helperText: "Tautan file audio MP3 langsung. Jika dikosongkan, musik akustik synth lembut akan dimainkan.",
    },
  ],
  sample: {
    primaryColor: "#2f6f5e",
    backgroundColor: "#f7f9f6",
    cardColor: "#ffffff",
    textColor: "#1a2e26",
    bodyTextColor: "#334155",
    recipientName: "Bagas Adiputra",
    nickname: "Bro Bagas",
    friendsSince: "2016 • Bangku SMA",
    heroBadge: "Partner in Crime Since Day One",
    title: "Untuk Sahabat Terbaik Seumur Hidup",
    tagline: "Dari sekadar teman sebangku, sampai jadi orang yang paling tahu isi kepala dan rahasia terbesarku.",
    heroImage:
      "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1000&q=80",
    fistBumpTitle: "Tos Sahabat / Fist Bump",
    fistBumpPrompt: "Ketuk kepalan tangan di bawah untuk tos & dengarkan bunyi pertemanan kita!",
    secretPledgeMessage:
      "🤝 IKRAR PERSAHABATAN: Apapun yang terjadi di masa depan, entah jarak memisahkan atau kesibukan menenggelamkan, kalau salah satu butuh bantuan jam 2 pagi, pintu rumah selalu terbuka lebar tanpa banyak tanya!",
    totalYears: "8+ Tahun",
    deepTalks: "1,200+ Jam",
    zeroSecrets: "0 Rahasia Bocor",
    milestoneTitle: "Kilas Balik Perjalanan Persahabatan Kita",
    milestone1Year: "2016",
    milestone1Title: "Pertemuan Pertama",
    milestone1Desc: "Waktu orientasi sekolah, kita sama-sama telat dan dihukum push up bareng di lapangan.",
    milestone2Year: "2019",
    milestone2Title: "Touring Motor Dadakan",
    milestone2Desc: "Motor mogok pas hujan badai di pegunungan, tapi kita malah ketawa sambil dorong bareng.",
    milestone3Year: "2024 - Sekarang",
    milestone3Title: "Menapaki Karier Masing-Masing",
    milestone3Desc: "Meskipun beda kantor dan sering lembur, obrolan kita selalu nyambung layaknya kemarin sore.",
    galleryTitle: "Koleksi Momen Terbaik Kita",
    gallerySubtitle: "Setiap tawa dan kekonyolan yang terekam dalam perjalanan panjang ini.",
    galleryImg1:
      "https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=800&q=80",
    galleryCaption1: "Ngopi santai sampai larut malam",
    galleryDate1: "Oktober 2018",
    galleryImg2:
      "https://images.unsplash.com/photo-1539635278303-d4002c07eae3?auto=format&fit=crop&w=800&q=80",
    galleryCaption2: "Road trip seru ke pantai selatan",
    galleryDate2: "Juli 2020",
    galleryImg3:
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=800&q=80",
    galleryCaption3: "Selebrasi bareng wisuda sarjana",
    galleryDate3: "September 2022",
    galleryImg4:
      "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80",
    galleryCaption4: "Kerja kelompok yang berujung gaming",
    galleryDate4: "Mei 2023",
    galleryImg5:
      "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=800&q=80",
    galleryCaption5: "Pesta kembang api akhir tahun",
    galleryDate5: "Desember 2023",
    galleryImg6:
      "https://images.unsplash.com/photo-1543269865-cbf427effbad?auto=format&fit=crop&w=800&q=80",
    galleryCaption6: "Reuni dadakan formasi lengkap",
    galleryDate6: "Agustus 2024",
    wishesTitle: "Empat Hal yang Paling Aku Hargai Darimu",
    quality1Title: "Pendengar Tanpa Menghakimi",
    quality1Desc: "Selalu siap jadi tempat berkeluh kesah tanpa pernah memotong atau langsung memojokkan.",
    quality2Title: "Paling Loyal & Dapat Diandalkan",
    quality2Desc: "Tak peduli jam berapa ditelepon, kalau darurat kamu selalu jadi orang pertama yang merespons.",
    quality3Title: "Sense of Humor yang Luar Biasa",
    quality3Desc: "Bahkan di masa-masa terpuruk, candaan recehmu selalu berhasil memecah ketegangan.",
    quality4Title: "Suporter Paling Garis Keras",
    quality4Desc: "Ketika semua orang meragukan ide gilaku, kamu satu-satunya yang percaya dan ikut berjuang.",
    quote:
      "Sahabat sejati bukan mereka yang tak pernah terpisah, melainkan mereka yang saat berjumpa kembali terasa tak ada satu detik pun yang berubah.",
    message:
      "Bro Bagas,\n\nKita jarang sekali ngomong yang sentimental atau terlalu serius, jadi anggap saja surat ini adalah salah satu momen langka yang perlu diabadikan.\n\nTerima kasih banyak sudah jadi sahabat terbaik selama lebih dari delapan tahun ini. Dari zaman kita masih bingung mau kuliah di mana, pontang-panting nyari kerja, sampai sekarang kita sama-sama menapaki jalan karier masing-masing.\n\nTerima kasih sudah selalu ada saat aku butuh orang untuk ngobrol tanpa topeng. Sukses selalu buat semua impian dan target barumu. Tetap jadi Bagas yang jujur, kocak, dan rendah hati. Pintu rumahku selalu terbuka buat lu kapan saja!",
    senderName: "Yudha Pratama",
    signature: "Sahabatmu Selamanya,",
    letterDate: "2026-09-20",
    musicTitle: "Acoustic Friendship Melody",
    bgMusicUrl: "",
  },
};
