import type { TemplateMeta } from "../types";

export const artExhibitionTemplate: TemplateMeta = {
  slug: "art-exhibition",
  name: "The Grand Vernissage & Art Exhibition",
  category: "Undangan",
  tagline:
    "Undangan pameran seni & vernissage eksklusif — tiket VIP pass, countdown malam pembukaan, kurasi 3 karya seni, dress code avant-garde, dan audio ambient galeri.",
  description:
    "Undangan digital premium bergaya editorial kuratorial galeri seni kontemporer. Menampilkan tiket VIP Vernissage Pass interaktif, sapaan kolektor via URL (?to=Nama), hitung mundur malam vernissage, preview 3 karya seni berbingkai katalogus dengan medium & dimensi, rundown 4 sesi acara kuratorial, panduan dress code monokrom, navigasi Google Maps, dukungan patron seni, dan pemutar audio ambient galeri.",
  cardAccent: "bg-zinc-900 text-zinc-100 ring-1 ring-zinc-700",
  highlights: [
    "Tiket masuk VIP Vernissage Pass dengan nomor serial & stempel kurator interaktif",
    "Sapaan nama kolektor seni dinamis via tautan (?to=NamaTamu)",
    "Widget Live Countdown Timer menghitung mundur menuju malam pembukaan",
    "Preview 3 karya seni kurasi berbingkai editorial lengkap dengan medium & dimensi",
    "Timeline rundown 4 sesi acara (VIP Reception, Tour Kurator, Soundscape, Networking)",
    "Panduan dress code Avant-Garde / All Black lengkap dengan 4 swatch warna",
    "Dukungan patron seni & nomor rekening dengan tombol salin instan",
    "Integrasi peta lokasi venue langsung ke Google Maps",
    "Pemutar audio ambient galeri kontemporer mengambang",
  ],
  fields: [
    // --- SECTION: TIKET & COVER VIP ---
    {
      name: "recipientName",
      label: "Nama kolektor / tamu undangan (penerima)",
      type: "text",
      placeholder: "Bapak / Ibu Kolektor & Penikmat Seni",
      required: true,
      maxLength: 60,
      isRecipient: true,
      section: "ticket",
    },
    {
      name: "ticketNumber",
      label: "Nomor seri tiket VIP",
      type: "text",
      placeholder: "VIP-VERNISSAGE-0842",
      maxLength: 30,
      helperText: "Nomor seri unik tiket pass di bagian atas.",
      section: "ticket",
    },
    {
      name: "curatorSeal",
      label: "Teks stempel segel kurator",
      type: "text",
      placeholder: "CURATORIAL APPROVED // ADMIT ONE",
      maxLength: 40,
      section: "ticket",
    },
    {
      name: "exhibitionSub",
      label: "Subjudul pameran / Jenis acara",
      type: "text",
      placeholder: "Solo Art Exhibition Vernissage & Private Viewing",
      maxLength: 80,
      section: "ticket",
    },

    // --- SECTION: KURATORIAL & SENIMAN ---
    {
      name: "exhibitionTitle",
      label: "Judul utama pameran",
      type: "text",
      placeholder: "TRANSCENDENCE: Shadows of the Finite",
      required: true,
      maxLength: 100,
      section: "curatorial",
    },
    {
      name: "artistName",
      label: "Nama seniman / studio pembuat karya",
      type: "text",
      placeholder: "Julian Thorne & Studio Lumina",
      required: true,
      maxLength: 80,
      section: "curatorial",
    },
    {
      name: "curatorName",
      label: "Nama kurator pameran",
      type: "text",
      placeholder: "Dr. Arisya Danu, M.Sn.",
      maxLength: 80,
      section: "curatorial",
    },
    {
      name: "curatorialStatement",
      label: "Pengantar kuratorial / Pesan undangan",
      type: "textarea",
      placeholder:
        "Sebuah eksplorasi visual tentang batas antara memori, materialitas, dan ruang hening. Kami mengundang Anda untuk menjadi saksi perdana pembukaan ruang dialog estetika ini...",
      required: true,
      maxLength: 1200,
      section: "curatorial",
    },
    {
      name: "senderName",
      label: "Tuan rumah / Pengundang (pengirim)",
      type: "text",
      placeholder: "Dewan Kurator Lumina Space",
      required: true,
      maxLength: 60,
      section: "curatorial",
    },

    // --- SECTION: JADWAL & LOKASI ---
    {
      name: "eventDate",
      label: "Hari & tanggal pembukaan",
      type: "text",
      placeholder: "Sabtu, 24 Oktober 2026",
      required: true,
      maxLength: 50,
      section: "event",
    },
    {
      name: "eventTime",
      label: "Waktu vernissage",
      type: "text",
      placeholder: "18.30 – 22.00 WIB",
      required: true,
      maxLength: 50,
      section: "event",
    },
    {
      name: "targetDateIso",
      label: "Waktu ISO untuk Countdown Timer",
      type: "text",
      placeholder: "2026-10-24T18:30:00",
      maxLength: 30,
      helperText: "Format: YYYY-MM-DDTHH:mm:ss (contoh: 2026-10-24T18:30:00).",
      section: "event",
    },
    {
      name: "venueName",
      label: "Nama galeri / gedung pameran",
      type: "text",
      placeholder: "Lumina Contemporary Art Space",
      required: true,
      maxLength: 80,
      section: "event",
    },
    {
      name: "venueHall",
      label: "Ruang galeri / Pavilion",
      type: "text",
      placeholder: "Main Atrium & North Pavilion",
      maxLength: 60,
      section: "event",
    },
    {
      name: "venueAddress",
      label: "Alamat lengkap galeri",
      type: "text",
      placeholder: "Jl. Seni Budaya No. 88, Menteng, Jakarta Pusat",
      required: true,
      maxLength: 200,
      section: "event",
    },
    {
      name: "mapsUrl",
      label: "Tautan Google Maps",
      type: "text",
      placeholder: "https://maps.google.com/?q=Jakarta+Art+Gallery",
      maxLength: 300,
      section: "event",
    },

    // --- SECTION: RUNDOWN ACARA ---
    {
      name: "session1Time",
      label: "Waktu Sesi 1",
      type: "text",
      placeholder: "18.30 – 19.15 WIB",
      maxLength: 30,
      section: "rundown",
    },
    {
      name: "session1Title",
      label: "Judul Sesi 1",
      type: "text",
      placeholder: "VIP Arrival & Welcoming Reception",
      maxLength: 60,
      section: "rundown",
    },
    {
      name: "session1Desc",
      label: "Keterangan Sesi 1",
      type: "text",
      placeholder: "Registrasi tamu kehormatan, penyerahan katalog edisi khusus, dan signature cocktail di foyer.",
      maxLength: 150,
      section: "rundown",
    },
    {
      name: "session2Time",
      label: "Waktu Sesi 2",
      type: "text",
      placeholder: "19.15 – 20.00 WIB",
      maxLength: 30,
      section: "rundown",
    },
    {
      name: "session2Title",
      label: "Judul Sesi 2",
      type: "text",
      placeholder: "Curatorial Tour & Artist Vernissage Speech",
      maxLength: 60,
      section: "rundown",
    },
    {
      name: "session2Desc",
      label: "Keterangan Sesi 2",
      type: "text",
      placeholder: "Sambutan pembuka oleh Dewan Kurator dilanjutkan tur kuratorial eksklusif bersama seniman.",
      maxLength: 150,
      section: "rundown",
    },
    {
      name: "session3Time",
      label: "Waktu Sesi 3",
      type: "text",
      placeholder: "20.00 – 21.00 WIB",
      maxLength: 30,
      section: "rundown",
    },
    {
      name: "session3Title",
      label: "Judul Sesi 3",
      type: "text",
      placeholder: "Private Viewing & Ambient Soundscape",
      maxLength: 60,
      section: "rundown",
    },
    {
      name: "session3Desc",
      label: "Keterangan Sesi 3",
      type: "text",
      placeholder: "Eksplorasi intim ruang instalasi dengan komposisi live ambient acoustic yang imersif.",
      maxLength: 150,
      section: "rundown",
    },
    {
      name: "session4Time",
      label: "Waktu Sesi 4",
      type: "text",
      placeholder: "21.00 – 22.00 WIB",
      maxLength: 30,
      section: "rundown",
    },
    {
      name: "session4Title",
      label: "Judul Sesi 4",
      type: "text",
      placeholder: "Patron Acquisition & Wine Networking",
      maxLength: 60,
      section: "rundown",
    },
    {
      name: "session4Desc",
      label: "Keterangan Sesi 4",
      type: "text",
      placeholder: "Sesi akuisisi privat bagi kolektor seni, dialog kuratorial santai, dan wine tasting.",
      maxLength: 150,
      section: "rundown",
    },

    // --- SECTION: PREVIEW KARYA SENI (3 ARTWORKS) ---
    {
      name: "artwork1Title",
      label: "Judul Karya Seni 1",
      type: "text",
      placeholder: "Solitude in Crimson (2026)",
      maxLength: 80,
      section: "artworks",
    },
    {
      name: "artwork1Medium",
      label: "Medium & Ukuran Karya 1",
      type: "text",
      placeholder: "Oil, textured linen & acrylic on Belgian canvas (160 × 200 cm)",
      maxLength: 100,
      section: "artworks",
    },
    {
      name: "artwork1Desc",
      label: "Catatan Kurasi Karya 1",
      type: "text",
      placeholder: "Refleksi mendalam mengenai kesunyian di tengah percepatan visual era digital kontemporer.",
      maxLength: 200,
      section: "artworks",
    },
    {
      name: "artwork1Url",
      label: "URL Gambar Karya 1",
      type: "image",
      placeholder: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1200&q=80",
      section: "artworks",
    },
    {
      name: "artwork2Title",
      label: "Judul Karya Seni 2",
      type: "text",
      placeholder: "Echoes of the Monolith (2025)",
      maxLength: 80,
      section: "artworks",
    },
    {
      name: "artwork2Medium",
      label: "Medium & Ukuran Karya 2",
      type: "text",
      placeholder: "Cast bronze, charred oak & raw volcanic basalt (85 × 60 × 140 cm)",
      maxLength: 100,
      section: "artworks",
    },
    {
      name: "artwork2Desc",
      label: "Catatan Kurasi Karya 2",
      type: "text",
      placeholder: "Struktur monolitik yang membekukan resonansi geologis bumi dan peradaban kuno.",
      maxLength: 200,
      section: "artworks",
    },
    {
      name: "artwork2Url",
      label: "URL Gambar Karya 2",
      type: "image",
      placeholder: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=1200&q=80",
      section: "artworks",
    },
    {
      name: "artwork3Title",
      label: "Judul Karya Seni 3",
      type: "text",
      placeholder: "Luminescence No. IV (2026)",
      maxLength: 80,
      section: "artworks",
    },
    {
      name: "artwork3Medium",
      label: "Medium & Ukuran Karya 3",
      type: "text",
      placeholder: "Patinated brass sheets, mineral pigments & gold leaf (120 × 120 cm)",
      maxLength: 100,
      section: "artworks",
    },
    {
      name: "artwork3Desc",
      label: "Catatan Kurasi Karya 3",
      type: "text",
      placeholder: "Permainan gradasi spektrum cahaya yang berubah seiring sudut pandang pengamat.",
      maxLength: 200,
      section: "artworks",
    },
    {
      name: "artwork3Url",
      label: "URL Gambar Karya 3",
      type: "image",
      placeholder: "https://images.unsplash.com/photo-1547891654-e66ed7ebb968?auto=format&fit=crop&w=1200&q=80",
      section: "artworks",
    },

    // --- SECTION: DRESS CODE & PATRON SENI ---
    {
      name: "dressCodeTitle",
      label: "Tema Busana (Dress Code)",
      type: "text",
      placeholder: "Avant-Garde Minimalist / All-Black Chic",
      maxLength: 60,
      section: "guide",
    },
    {
      name: "dressCodeNotes",
      label: "Catatan Pedoman Busana",
      type: "text",
      placeholder: "Tamu disarankan mengenakan busana bernuansa monokrom gelap, arang, atau aksen merah galeri.",
      maxLength: 200,
      section: "guide",
    },
    {
      name: "paletteColor1",
      label: "Kode Hex Swatch 1",
      type: "color",
      placeholder: "#111111",
      section: "guide",
    },
    {
      name: "paletteName1",
      label: "Nama Warna Swatch 1",
      type: "text",
      placeholder: "Obsidian Noir",
      maxLength: 30,
      section: "guide",
    },
    {
      name: "paletteColor2",
      label: "Kode Hex Swatch 2",
      type: "color",
      placeholder: "#27272a",
      section: "guide",
    },
    {
      name: "paletteName2",
      label: "Nama Warna Swatch 2",
      type: "text",
      placeholder: "Graphite Charcoal",
      maxLength: 30,
      section: "guide",
    },
    {
      name: "paletteColor3",
      label: "Kode Hex Swatch 3",
      type: "color",
      placeholder: "#f4f4f5",
      section: "guide",
    },
    {
      name: "paletteName3",
      label: "Nama Warna Swatch 3",
      type: "text",
      placeholder: "Gallery Alabaster",
      maxLength: 30,
      section: "guide",
    },
    {
      name: "paletteColor4",
      label: "Kode Hex Swatch 4",
      type: "color",
      placeholder: "#dc2626",
      section: "guide",
    },
    {
      name: "paletteName4",
      label: "Nama Warna Swatch 4",
      type: "text",
      placeholder: "Curator Vermillion",
      maxLength: 30,
      section: "guide",
    },

    // Patron & Donasi Galeri
    {
      name: "patronBankName",
      label: "Nama Bank / Institusi Patron",
      type: "text",
      placeholder: "BCA / Lumina Arts Foundation",
      maxLength: 50,
      section: "guide",
    },
    {
      name: "patronAccountNo",
      label: "Nomor Rekening Patron Seni",
      type: "text",
      placeholder: "8820491029",
      maxLength: 40,
      section: "guide",
    },
    {
      name: "patronAccountName",
      label: "Nama Pemilik Rekening",
      type: "text",
      placeholder: "Yayasan Seni Rupa Lumina",
      maxLength: 60,
      section: "guide",
    },
    {
      name: "patronNote",
      label: "Keterangan Patronage",
      type: "text",
      placeholder: "Dukungan patron seni untuk penerbitan katalogus resmi & program residensi seniman muda.",
      maxLength: 200,
      section: "guide",
    },

    // --- SECTION: TEMA WARNA & AUDIO ---
    {
      name: "backgroundColor",
      label: "Warna Latar Belakang",
      type: "color",
      placeholder: "#09090b",
      section: "theme",
    },
    {
      name: "cardColor",
      label: "Warna Kartu / Kanvas",
      type: "color",
      placeholder: "#18181b",
      section: "theme",
    },
    {
      name: "textColor",
      label: "Warna Teks Utama",
      type: "color",
      placeholder: "#fafafa",
      section: "theme",
    },
    {
      name: "musicUrl",
      label: "URL Audio Ambient Galeri (.mp3)",
      type: "text",
      placeholder: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=ambient-piano-amp-strings-10711.mp3",
      maxLength: 500,
      section: "theme",
    },
    {
      name: "musicTitle",
      label: "Judul Musik Ambient",
      type: "text",
      placeholder: "Ambient Nocturne in D Minor",
      maxLength: 60,
      section: "theme",
    },
  ],
  sample: {
    recipientName: "Bapak & Ibu Kolektor Terhormat",
    ticketNumber: "VIP-VERNISSAGE-0842",
    curatorSeal: "CURATORIAL APPROVED // ADMIT ONE",
    exhibitionSub: "Solo Art Exhibition Vernissage & Private Viewing",
    exhibitionTitle: "TRANSCENDENCE: Shadows of the Finite",
    artistName: "Julian Thorne & Studio Lumina",
    curatorName: "Dr. Arisya Danu, M.Sn.",
    curatorialStatement:
      "Sebuah eksplorasi visual tentang batas antara memori, materialitas, dan ruang hening. 'TRANSCENDENCE: Shadows of the Finite' merajut narasi keberadaan manusia di persimpangan zaman material dan dimensi transendental.\n\nMerupakan suatu kehormatan dan kebahagiaan bagi kami untuk menyambut kehadiran Anda dalam malam pembukaan perdana (Vernissage & Private Viewing) ini, merayakan keindahan perenungan estetik bersama para kurator, kolektor, dan penikmat seni rupa.",
    senderName: "Dewan Kurator Lumina Space",
    eventDate: "Sabtu, 24 Oktober 2026",
    eventTime: "18.30 – 22.00 WIB",
    targetDateIso: "2026-10-24T18:30:00",
    venueName: "Lumina Contemporary Art Space",
    venueHall: "Main Atrium & North Pavilion",
    venueAddress: "Jl. Seni Budaya No. 88, Menteng, Jakarta Pusat",
    mapsUrl: "https://maps.google.com/?q=Jakarta+Art+Gallery",

    session1Time: "18.30 – 19.15 WIB",
    session1Title: "VIP Arrival & Welcoming Reception",
    session1Desc: "Registrasi tamu kehormatan, penyerahan katalog edisi khusus, dan signature cocktail di foyer.",
    session2Time: "19.15 – 20.00 WIB",
    session2Title: "Curatorial Tour & Artist Vernissage Speech",
    session2Desc: "Sambutan pembuka oleh Dewan Kurator dilanjutkan tur kuratorial eksklusif bersama seniman.",
    session3Time: "20.00 – 21.00 WIB",
    session3Title: "Private Viewing & Ambient Soundscape",
    session3Desc: "Eksplorasi intim ruang instalasi dengan komposisi live ambient acoustic yang imersif.",
    session4Time: "21.00 – 22.00 WIB",
    session4Title: "Patron Acquisition & Wine Networking",
    session4Desc: "Sesi akuisisi privat bagi kolektor seni, dialog kuratorial santai, dan wine tasting.",

    artwork1Title: "Solitude in Crimson (2026)",
    artwork1Medium: "Oil, textured linen & acrylic on Belgian canvas (160 × 200 cm)",
    artwork1Desc: "Refleksi mendalam mengenai kesunyian di tengah percepatan visual era digital kontemporer.",
    artwork1Url: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1200&q=80",

    artwork2Title: "Echoes of the Monolith (2025)",
    artwork2Medium: "Cast bronze, charred oak & raw volcanic basalt (85 × 60 × 140 cm)",
    artwork2Desc: "Struktur monolitik yang membekukan resonansi geologis bumi dan peradaban kuno.",
    artwork2Url: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=1200&q=80",

    artwork3Title: "Luminescence No. IV (2026)",
    artwork3Medium: "Patinated brass sheets, mineral pigments & gold leaf (120 × 120 cm)",
    artwork3Desc: "Permainan gradasi spektrum cahaya yang berubah seiring sudut pandang pengamat.",
    artwork3Url: "https://images.unsplash.com/photo-1547891654-e66ed7ebb968?auto=format&fit=crop&w=1200&q=80",

    dressCodeTitle: "Avant-Garde Minimalist / All-Black Chic",
    dressCodeNotes: "Tamu disarankan mengenakan busana bernuansa monokrom gelap, arang, atau aksen merah galeri.",
    paletteColor1: "#111111",
    paletteName1: "Obsidian Noir",
    paletteColor2: "#27272a",
    paletteName2: "Graphite Charcoal",
    paletteColor3: "#f4f4f5",
    paletteName3: "Gallery Alabaster",
    paletteColor4: "#dc2626",
    paletteName4: "Curator Vermillion",

    patronBankName: "BCA / Lumina Arts Foundation",
    patronAccountNo: "8820491029",
    patronAccountName: "Yayasan Seni Rupa Lumina",
    patronNote: "Dukungan patron seni untuk penerbitan katalogus resmi & program residensi seniman muda.",

    backgroundColor: "#09090b",
    cardColor: "#18181b",
    textColor: "#fafafa",
    musicUrl: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=ambient-piano-amp-strings-10711.mp3",
    musicTitle: "Ambient Nocturne in D Minor",
  },
};
