import type { TemplateMeta } from "../types";

export const birthdayGazetteTemplate: TemplateMeta = {
  slug: "birthday-gazette",
  name: "The Birthday Gazette",
  category: "Perayaan",
  tagline:
    "Surat kabar edisi khusus ulang tahun bertema vintage broadsheet — headline breaking news, tajuk editorial personal, metrik usia, galeri pers, horoskop, dan kupon kado.",
  description:
    "Surat ulang tahun bergaya koran cetak vintage (The Birthday Gazette) yang penuh karakter dan nostalgia. Menampilkan tajuk breaking news perayaan usia baru, surat redaksi utama yang menyentuh, metrik perjalanan hidup di bumi, galeri foto liputan pers eksklusif, ramalan horoskop keberuntungan & 4 doa masa depan, kolom iklan baris berisi 4 kupon hadiah interaktif, serta pemutar piringan hitam audio pesta.",
  cardAccent: "bg-stone-800 text-stone-100 ring-1 ring-stone-600",
  highlights: [
    "Format surat kabar broadsheet vintage dengan masthead & headline breaking news",
    "Surat tajuk rencana redaksi yang mendalam dengan drop caps & stempel verifikasi",
    "Infografis metrik waktu jejak kehidupan (hari hidup, tawa, momen berharga)",
    "Galeri 3 foto pers jurnalistik dengan caption berita eksklusif",
    "Kolom ramalan horoskop positif dan 4 kartu doa babak usia baru",
    "Kolom iklan baris dengan 4 kupon kado interaktif yang dapat diklaim penerima",
    "Pemutar piringan hitam audio jazz/akustik perayaan mengambang",
  ],
  fields: [
    // --- SECTION: HEADLINE & EDISI KORAN ---
    {
      name: "recipientName",
      label: "Nama tokoh utama / yang berulang tahun",
      type: "text",
      placeholder: "Clarissa Aurelia",
      required: true,
      maxLength: 60,
      isRecipient: true,
      section: "masthead",
    },
    {
      name: "ageNumber",
      label: "Angka usia baru",
      type: "text",
      placeholder: "24",
      required: true,
      maxLength: 10,
      section: "masthead",
    },
    {
      name: "issueVolume",
      label: "Nomor volume / edisi koran",
      type: "text",
      placeholder: "VOL. XXIV // NO. 10",
      maxLength: 40,
      section: "masthead",
    },
    {
      name: "publishDate",
      label: "Tanggal cetak edisi (Hari ulang tahun)",
      type: "text",
      placeholder: "Minggu, 25 Oktober 2026",
      required: true,
      maxLength: 60,
      section: "masthead",
    },
    {
      name: "weatherForecast",
      label: "Prakiraan cuaca hari ini",
      type: "text",
      placeholder: "100% Cerah, Bertabur Senyuman & Harapan Baru",
      maxLength: 80,
      section: "masthead",
    },
    {
      name: "gazetteHeadline",
      label: "Headline utama koran",
      type: "text",
      placeholder: "BREAKING NEWS: Bintang Paling Bersinar Resmi Menginjak Babak Usia ke-24!",
      required: true,
      maxLength: 120,
      section: "masthead",
    },
    {
      name: "newspaperSubhead",
      label: "Subjudul berita utama",
      type: "text",
      placeholder: "Dunia merayakan hari kelahiran sosok luar biasa yang senantiasa membawa kehangatan dan inspirasi.",
      maxLength: 150,
      section: "masthead",
    },

    // --- SECTION: TAJUK RENCANA REDAKSI (SURAT UTAMA) ---
    {
      name: "editorialTitle",
      label: "Judul surat / artikel editorial",
      type: "text",
      placeholder: "Catatan Redaksi: Sebuah Perjalanan Penuh Makna, Tawa, dan Cinta",
      required: true,
      maxLength: 100,
      section: "editorial",
    },
    {
      name: "editorialLetter",
      label: "Isi surat utama (Panjang & mendalam)",
      type: "textarea",
      placeholder:
        "Hari ini, edisi khusus The Birthday Gazette kami terbitkan sebagai persembahan kecil untuk merayakan hadirmu di dunia...\n\nTerima kasih telah menjadi teman berbagi tawa yang paling tulus, pendengar setia di kala badai, dan sosok yang selalu menyalakan cahaya di sekitar.",
      required: true,
      maxLength: 1500,
      section: "editorial",
    },
    {
      name: "senderName",
      label: "Nama pengirim / Pemimpin redaksi",
      type: "text",
      placeholder: "Dimas Arya",
      required: true,
      maxLength: 60,
      section: "editorial",
    },
    {
      name: "senderTitle",
      label: "Jabatan pengirim di redaksi",
      type: "text",
      placeholder: "Sahabat Sejati // Pemimpin Redaksi Seumur Hidup",
      maxLength: 80,
      section: "editorial",
    },

    // --- SECTION: METRIK JEJAK KEHIDUPAN ---
    {
      name: "metric1Value",
      label: "Nilai metrik 1",
      type: "text",
      placeholder: "8.766",
      section: "metrics",
    },
    {
      name: "metric1Label",
      label: "Label metrik 1",
      type: "text",
      placeholder: "Hari Menerangi Dunia",
      section: "metrics",
    },
    {
      name: "metric2Value",
      label: "Nilai metrik 2",
      type: "text",
      placeholder: "1.400+",
      section: "metrics",
    },
    {
      name: "metric2Label",
      label: "Label metrik 2",
      type: "text",
      placeholder: "Secangkir Kopi & Tawa Bersama",
      section: "metrics",
    },
    {
      name: "metric3Value",
      label: "Nilai metrik 3",
      type: "text",
      placeholder: "100%",
      section: "metrics",
    },
    {
      name: "metric3Label",
      label: "Label metrik 3",
      type: "text",
      placeholder: "Kebaikan Hati Tanpa Pamrih",
      section: "metrics",
    },
    {
      name: "metric4Value",
      label: "Nilai metrik 4",
      type: "text",
      placeholder: "Tak Terhingga",
      section: "metrics",
    },
    {
      name: "metric4Label",
      label: "Label metrik 4",
      type: "text",
      placeholder: "Momen Indah Menanti di Masa Depan",
      section: "metrics",
    },

    // --- SECTION: GALERI LIPUTAN PERS ---
    {
      name: "photo1Url",
      label: "URL Foto Pers 1 (Foto Utama)",
      type: "text",
      placeholder: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=80",
      section: "photos",
    },
    {
      name: "photo1Caption",
      label: "Caption Berita Foto 1",
      type: "text",
      placeholder: "Potret sang tokoh utama saat menatap masa depan dengan senyuman paling memikat.",
      section: "photos",
    },
    {
      name: "photo1Tag",
      label: "Tag Foto 1",
      type: "text",
      placeholder: "LIPUTAN UTAMA",
      section: "photos",
    },
    {
      name: "photo2Url",
      label: "URL Foto Pers 2",
      type: "text",
      placeholder: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=80",
      section: "photos",
    },
    {
      name: "photo2Caption",
      label: "Caption Berita Foto 2",
      type: "text",
      placeholder: "Momen keceriaan spontan yang terekam kamera saat menjelajahi sudut kota favorit.",
      section: "photos",
    },
    {
      name: "photo2Tag",
      label: "Tag Foto 2",
      type: "text",
      placeholder: "MOMEN SPONTAN",
      section: "photos",
    },
    {
      name: "photo3Url",
      label: "URL Foto Pers 3",
      type: "text",
      placeholder: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80",
      section: "photos",
    },
    {
      name: "photo3Caption",
      label: "Caption Berita Foto 3",
      type: "text",
      placeholder: "Tawa lepas yang membuktikan bahwa kebahagiaan selalu ada dalam setiap detik perjalanan.",
      section: "photos",
    },
    {
      name: "photo3Tag",
      label: "Tag Foto 3",
      type: "text",
      placeholder: "SOROT LENSA",
      section: "photos",
    },

    // --- SECTION: HOROSKOP & KARTU DOA ---
    {
      name: "horoscopeTitle",
      label: "Judul ramalan bintang",
      type: "text",
      placeholder: "Horoskop & Ramalan Babak Usia Baru",
      section: "horoscope",
    },
    {
      name: "horoscopeText",
      label: "Teks ramalan positif",
      type: "textarea",
      placeholder:
        "Bintang-bintang meramalkan tahun yang penuh kelimpahan karya, petualangan baru yang mendebarkan, dan kedamaian hati yang melimpah. Segala rintangan di masa lalu kini berubah menjadi batu loncatan kesuksesanmu.",
      section: "horoscope",
    },
    {
      name: "wish1Title",
      label: "Judul Doa 1 (Karier & Cita-Cita)",
      type: "text",
      placeholder: "Karier & Karya Cemerlang",
      section: "horoscope",
    },
    {
      name: "wish1Desc",
      label: "Pesan Doa 1",
      type: "text",
      placeholder: "Semoga setiap karya dan langkah besarmu menemukan jalan terbaik dan diakui luas.",
      section: "horoscope",
    },
    {
      name: "wish2Title",
      label: "Judul Doa 2 (Kesehatan & Ketenangan)",
      type: "text",
      placeholder: "Raga Bugar & Hati Tentram",
      section: "horoscope",
    },
    {
      name: "wish2Desc",
      label: "Pesan Doa 2",
      type: "text",
      placeholder: "Diberkahi kesehatan raga yang prima serta kedamaian batin dalam setiap hembusan nafas.",
      section: "horoscope",
    },
    {
      name: "wish3Title",
      label: "Judul Doa 3 (Cinta & Kebersamaan)",
      type: "text",
      placeholder: "Dikelilingi Kasih Sejati",
      section: "horoscope",
    },
    {
      name: "wish3Desc",
      label: "Pesan Doa 3",
      type: "text",
      placeholder: "Selalu dikelilingi sahabat dan keluarga yang tulus mendukungmu dalam segala keadaan.",
      section: "horoscope",
    },
    {
      name: "wish4Title",
      label: "Judul Doa 4 (Petualangan Baru)",
      type: "text",
      placeholder: "Eksplorasi Tanpa Batas",
      section: "horoscope",
    },
    {
      name: "wish4Desc",
      label: "Pesan Doa 4",
      type: "text",
      placeholder: "Semoga babak baru ini membawamu menjelajahi tempat-tempat baru yang kau impikan.",
      section: "horoscope",
    },

    // --- SECTION: IKLAN BARIS & KUPON KADO ---
    {
      name: "voucher1Title",
      label: "Judul Kupon 1",
      type: "text",
      placeholder: "Kupon Traktir Makan Malam Favorit",
      section: "classifieds",
    },
    {
      name: "voucher1Desc",
      label: "Keterangan Kupon 1",
      type: "text",
      placeholder: "Berlaku kapan saja di restoran favorit pilihanmu. Sepenuhnya dibiayai oleh pengirim!",
      section: "classifieds",
    },
    {
      name: "voucher2Title",
      label: "Judul Kupon 2",
      type: "text",
      placeholder: "Kupon Bebas Curhat & Dengar 24/7",
      section: "classifieds",
    },
    {
      name: "voucher2Desc",
      label: "Keterangan Kupon 2",
      type: "text",
      placeholder: "Bebas menelepon atau bertemu kapan pun kau butuh teman berbagi cerita tanpa dihakimi.",
      section: "classifieds",
    },
    {
      name: "voucher3Title",
      label: "Judul Kupon 3",
      type: "text",
      placeholder: "Kupon Jalan-Jalan Santai Sore",
      section: "classifieds",
    },
    {
      name: "voucher3Desc",
      label: "Keterangan Kupon 3",
      type: "text",
      placeholder: "Jalan santai menikmati sunset, hunting foto, dan minum es kopi tanpa terburu waktu.",
      section: "classifieds",
    },
    {
      name: "voucher4Title",
      label: "Judul Kupon 4",
      type: "text",
      placeholder: "Kupon Hadiah Kejutan Rahasia",
      section: "classifieds",
    },
    {
      name: "voucher4Desc",
      label: "Keterangan Kupon 4",
      type: "text",
      placeholder: "Bisa ditukar dengan satu barang impian yang sedang masuk dalam wishlist-mu saat ini.",
      section: "classifieds",
    },

    // --- SECTION: TEMA WARNA & AUDIO ---
    {
      name: "primaryColor",
      label: "Warna Aksen Headline / Redline",
      type: "text",
      placeholder: "#dc2626",
      section: "theme",
    },
    {
      name: "backgroundColor",
      label: "Warna Latar Kertas Koran",
      type: "text",
      placeholder: "#f4efe6",
      section: "theme",
    },
    {
      name: "cardColor",
      label: "Warna Kolom Cetak Koran",
      type: "text",
      placeholder: "#fdfbf7",
      section: "theme",
    },
    {
      name: "textColor",
      label: "Warna Tinta Cetak Utama",
      type: "text",
      placeholder: "#1c1917",
      section: "theme",
    },
    {
      name: "musicTitle",
      label: "Judul Musik Koran",
      type: "text",
      placeholder: "Vintage Jazz Cafe & Birthday Melody",
      section: "theme",
    },
    {
      name: "musicUrl",
      label: "Tautan File Audio Musik (MP3)",
      type: "text",
      placeholder: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=ambient-piano-amp-strings-10711.mp3",
      section: "theme",
    },
  ],
  sample: {
    recipientName: "Clarissa Aurelia",
    ageNumber: "24",
    issueVolume: "VOL. XXIV // NO. 10",
    publishDate: "Minggu, 25 Oktober 2026",
    weatherForecast: "100% Cerah, Bertabur Senyuman & Harapan Baru",
    gazetteHeadline: "BREAKING NEWS: Bintang Paling Bersinar Resmi Menginjak Babak Usia ke-24!",
    newspaperSubhead: "Dunia merayakan hari kelahiran sosok luar biasa yang senantiasa membawa kehangatan, tawa, dan inspirasi bagi sekelilingnya.",

    editorialTitle: "Catatan Redaksi: Sebuah Perjalanan Penuh Makna, Tawa, dan Cinta",
    editorialLetter:
      "Hari ini, edisi khusus The Birthday Gazette kami terbitkan secara istimewa sebagai persembahan kecil untuk merayakan hadirmu di dunia.\n\nTidak terasa waktu terus bergulir, membawamu menapaki babak baru yang kian dewasa dan bijaksana. Terima kasih telah menjadi teman berbagi tawa yang paling tulus, pendengar setia di kala badai melanda, dan sosok yang selalu menyalakan cahaya di mana pun kau berada.\n\nSemoga di usia yang baru ini, setiap langkah kakimu senantiasa dinaungi keberkahan, impian-impian besarmu menemukan jalan terindahnya untuk terwujud, dan senyuman manismu tak pernah pudar oleh waktu. Selamat ulang tahun, sang tokoh utama!",
    senderName: "Dimas Arya",
    senderTitle: "Sahabat Sejati // Pemimpin Redaksi Seumur Hidup",

    metric1Value: "8.766",
    metric1Label: "Hari Menerangi Dunia",
    metric2Value: "1.400+",
    metric2Label: "Secangkir Kopi & Tawa Bersama",
    metric3Value: "100%",
    metric3Label: "Kebaikan Hati Tanpa Pamrih",
    metric4Value: "Tak Terhingga",
    metric4Label: "Momen Indah Menanti di Masa Depan",

    photo1Url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=80",
    photo1Caption: "Potret sang tokoh utama saat menatap masa depan dengan senyuman paling memikat.",
    photo1Tag: "LIPUTAN UTAMA",

    photo2Url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=80",
    photo2Caption: "Momen keceriaan spontan yang terekam kamera saat menjelajahi sudut kota favorit.",
    photo2Tag: "MOMEN SPONTAN",

    photo3Url: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80",
    photo3Caption: "Tawa lepas yang membuktikan bahwa kebahagiaan selalu ada dalam setiap detik perjalanan.",
    photo3Tag: "SOROT LENSA",

    horoscopeTitle: "Horoskop & Ramalan Babak Usia Baru",
    horoscopeText:
      "Bintang-bintang meramalkan tahun yang penuh kelimpahan karya, petualangan baru yang mendebarkan, dan kedamaian hati yang melimpah. Segala rintangan di masa lalu kini berubah menjadi batu loncatan kesuksesanmu.",

    wish1Title: "Karier & Karya Cemerlang",
    wish1Desc: "Semoga setiap karya dan langkah besarmu menemukan jalan terbaik dan diakui luas.",
    wish2Title: "Raga Bugar & Hati Tentram",
    wish2Desc: "Diberkahi kesehatan raga yang prima serta kedamaian batin dalam setiap hembusan nafas.",
    wish3Title: "Dikelilingi Kasih Sejati",
    wish3Desc: "Selalu dikelilingi sahabat dan keluarga yang tulus mendukungmu dalam segala keadaan.",
    wish4Title: "Eksplorasi Tanpa Batas",
    wish4Desc: "Semoga babak baru ini membawamu menjelajahi tempat-tempat baru yang kau impikan.",

    voucher1Title: "Kupon Traktir Makan Malam Favorit",
    voucher1Desc: "Berlaku kapan saja di restoran favorit pilihanmu. Sepenuhnya dibiayai oleh pengirim!",
    voucher2Title: "Kupon Bebas Curhat & Dengar 24/7",
    voucher2Desc: "Bebas menelepon atau bertemu kapan pun kau butuh teman berbagi cerita tanpa dihakimi.",
    voucher3Title: "Kupon Jalan-Jalan Santai Sore",
    voucher3Desc: "Jalan santai menikmati sunset, hunting foto, dan minum es kopi tanpa terburu waktu.",
    voucher4Title: "Kupon Hadiah Kejutan Rahasia",
    voucher4Desc: "Bisa ditukar dengan satu barang impian yang sedang masuk dalam wishlist-mu saat ini.",

    primaryColor: "#dc2626",
    backgroundColor: "#f4efe6",
    cardColor: "#fdfbf7",
    textColor: "#1c1917",
    musicTitle: "Vintage Jazz Cafe & Birthday Melody",
    musicUrl: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=ambient-piano-amp-strings-10711.mp3",
  },
};
