import type { TemplateMeta } from "../types";
import {
  STARLIGHT_COLOR_PRESETS,
  BACKGROUND_COLOR_PRESETS,
  CARD_COLOR_PRESETS,
  TEXT_COLOR_PRESETS,
} from "../color-presets";

export const starlightLoveTemplate: TemplateMeta = {
  slug: "starlight-love",
  name: "Celestial Starlight Romance",
  category: "Romansa",
  tagline:
    "Surat cinta semesta bertema starlight cerah mewah — sertifikat dedikasi bintang resmi, live counter waktu cinta, peta 5 rasi bintang kenangan, galeri polaroid, dan 5 janji semesta abadi.",
  description:
    "Pengalaman romansa celestial mewah bernuansa terang dan hangat (Bright Ethereal Starlight Luxury). Dilengkapi sertifikat bintang resmi berkoordinat astronomis, live ticker waktu yang dihabiskan di bawah langit yang sama, peta rasi 5 bintang kenangan interaktif, lentera cinta yang bisa diterbangkan dengan efek audio gemerincing bintang, galeri 4 foto polaroid kosmik, 5 janji semesta abadi, bisikan rahasia tersembunyi, dan surat cinta mendalam.",
  cardAccent: "bg-amber-50 text-amber-800 ring-1 ring-amber-300",
  highlights: [
    "Nuansa langit cerah kosmik emas & sampanye (Bright Celestial Dawn)",
    "Sertifikat dedikasi bintang resmi berstempel wax seal kosmik",
    "Live counter waktu cinta di bawah naungan semesta yang sama",
    "Peta rasi 5 bintang kenangan interaktif (Interactive Star Chart)",
    "Lentera cinta bercahaya & efek audio chimes bintang interaktif",
    "Galeri 4 foto polaroid kenangan berselotip rasi bintang emas",
    "5 pilar janji semesta abadi & bisikan rahasia tersembunyi",
    "Surat cinta puitis di atas lembaran kertas starlight mewah",
  ],
  fields: [
    // --- SECTION: IDENTITAS & KONSTELASI ---
    {
      name: "recipientName",
      label: "Nama kekasih (penerima)",
      type: "text",
      placeholder: "Clarissa Aurelia",
      required: true,
      maxLength: 60,
      isRecipient: true,
      section: "constellation",
    },
    {
      name: "senderName",
      label: "Nama kamu (pengirim)",
      type: "text",
      placeholder: "Reyhan Danendra",
      required: true,
      maxLength: 60,
      section: "constellation",
    },
    {
      name: "constellationTitle",
      label: "Nama rasi bintang kenangan",
      type: "text",
      placeholder: "Constellation of Our First Spark ✨",
      maxLength: 80,
      helperText: "Nama puitis untuk gugusan bintang momen cinta kalian.",
      section: "constellation",
    },
    {
      name: "specialDate",
      label: "Tanggal momen pertama / pertemuan",
      type: "text",
      placeholder: "14 Februari 2023",
      maxLength: 40,
      section: "constellation",
    },
    {
      name: "anniversaryDate",
      label: "Tanggal jadian / awal kisah (YYYY-MM-DD)",
      type: "text",
      placeholder: "2023-02-14",
      maxLength: 30,
      helperText: "Format: YYYY-MM-DD. Digunakan untuk live counter waktu di bawah langit yang sama.",
      section: "constellation",
    },
    {
      name: "starName",
      label: "Nama bintang simbolik yang dipersembahkan",
      type: "text",
      placeholder: "Stella Clarissa Majoris ✨",
      maxLength: 80,
      helperText: "Nama bintang khusus yang dipersembahkan untuk kekasih di langit semesta.",
      section: "constellation",
    },
    {
      name: "starCoordinate",
      label: "Koordinat astronomis simbolik",
      type: "text",
      placeholder: "RA 05h 35m • Dec -05° 23′ (Celestial Orion)",
      maxLength: 60,
      helperText: "Koordinat bintang atau lokasi kenangan tempat cinta bersemi.",
      section: "constellation",
    },
    {
      name: "starMagnitude",
      label: "Tingkat kecerahan bintang (Magnitudo)",
      type: "text",
      placeholder: "Magnitude 1.0 (Bintang Terang Utama)",
      maxLength: 50,
      section: "constellation",
    },
    {
      name: "starRegistryId",
      label: "Nomor registrasi bintang resmi",
      type: "text",
      placeholder: "STAR-LOVE-2023-CLARISSA",
      maxLength: 40,
      section: "constellation",
    },
    {
      name: "starDedicationQuote",
      label: "Kutipan dedikasi pada sertifikat bintang",
      type: "text",
      placeholder: "Didaftarkan abadi di hamparan galaksi, bersinar selamanya hanya untukmu.",
      maxLength: 150,
      section: "constellation",
    },

    // --- SECTION: PETA RASI BINTANG KENANGAN (5 BINTANG) ---
    {
      name: "constellationStory",
      label: "Kisah di balik rasi bintang kenangan",
      type: "textarea",
      placeholder:
        "Rasi bintang ini tercipta dari jalinan kenangan manis kita: tatap mata pertama, tawa saat kehujanan bersama, dan janji suci untuk saling menjaga selamanya.",
      maxLength: 350,
      rows: 2,
      section: "stars",
    },
    {
      name: "star1",
      label: "Bintang 1 (Janji Kedamaian)",
      type: "text",
      placeholder: "Bintang Kedamaian: Selalu menjadi pelabuhan paling tenang dan aman saat harimu terasa lelah.",
      maxLength: 180,
      section: "stars",
    },
    {
      name: "star2",
      label: "Bintang 2 (Janji Ketulusan)",
      type: "text",
      placeholder: "Bintang Ketulusan: Menjagamu dengan kejujuran, kehangatan, dan kesetiaan yang tak luntur oleh waktu.",
      maxLength: 180,
      section: "stars",
    },
    {
      name: "star3",
      label: "Bintang 3 (Janji Kehangatan)",
      type: "text",
      placeholder: "Bintang Kehangatan: Menjadi selimut di kala dingin dan pelukan paling tulus di setiap senja.",
      maxLength: 180,
      section: "stars",
    },
    {
      name: "star4",
      label: "Bintang 4 (Janji Tawa & Senyuman)",
      type: "text",
      placeholder: "Bintang Tawa: Mengukir senyuman di wajahmu bahkan di saat hari-hari terasa berat.",
      maxLength: 180,
      section: "stars",
    },
    {
      name: "star5",
      label: "Bintang 5 (Janji Keabadian)",
      type: "text",
      placeholder: "Bintang Keabadian: Terus menggenggam jemarimu dan menatap langit masa depan bersama-sama hingga menua.",
      maxLength: 180,
      section: "stars",
    },

    // --- SECTION: GALERI FOTO POLAROID KOSMIK (4 FOTO) ---
    {
      name: "starlightPhotoUrl",
      label: "Foto polaroid 1 (Foto Utama di Bawah Langit)",
      type: "text",
      placeholder:
        "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=1000&q=80",
      maxLength: 1000,
      section: "memories",
    },
    {
      name: "starlightPhotoCaption",
      label: "Keterangan foto polaroid 1",
      type: "text",
      placeholder: "Pertama kali menatap gemintang bersama di atas bukit.",
      maxLength: 120,
      section: "memories",
    },
    {
      name: "secondPhotoUrl",
      label: "Foto polaroid 2 (Genggaman Hangat)",
      type: "text",
      placeholder:
        "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=1000&q=80",
      maxLength: 1000,
      section: "memories",
    },
    {
      name: "secondPhotoCaption",
      label: "Keterangan foto polaroid 2",
      type: "text",
      placeholder: "Genggaman jemari yang selalu menghangatkan dinginnya malam.",
      maxLength: 120,
      section: "memories",
    },
    {
      name: "photo3Url",
      label: "Foto polaroid 3 (Tawa Senja)",
      type: "text",
      placeholder:
        "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=1000&q=80",
      maxLength: 1000,
      section: "memories",
    },
    {
      name: "photo3Caption",
      label: "Keterangan foto polaroid 3",
      type: "text",
      placeholder: "Tawa renyahmu di bawah cahaya senja keemasan.",
      maxLength: 120,
      section: "memories",
    },
    {
      name: "photo4Url",
      label: "Foto polaroid 4 (Momen Berhenti)",
      type: "text",
      placeholder:
        "https://images.unsplash.com/photo-1513279922550-250c2129b13a?auto=format&fit=crop&w=1000&q=80",
      maxLength: 1000,
      section: "memories",
    },
    {
      name: "photo4Caption",
      label: "Keterangan foto polaroid 4",
      type: "text",
      placeholder: "Saat dunia di luar sana terasa sunyi dan hanya ada kita berdua.",
      maxLength: 120,
      section: "memories",
    },

    // --- SECTION: BISIKAN RAHASIA & LENTERA ---
    {
      name: "secretStarlightWhisper",
      label: "Bisikan bintang rahasia (Hidden Message)",
      type: "textarea",
      placeholder:
        "Bisikan Rahasia: Dari triliunan kemungkinan di semesta ini, tidak ada satu detik pun yang kusesali saat memilihmu. Kamu adalah keajaiban terindah dalam hidupku. Aku mencintaimu, hari ini dan selamanya.",
      maxLength: 400,
      rows: 3,
      helperText: "Pesan tersembunyi yang terkunci dan dapat dibuka dengan tombol interaktif.",
      section: "lantern",
    },
    {
      name: "lanternTitle",
      label: "Judul kartu lentera cahaya",
      type: "text",
      placeholder: "Lentera Harapan yang Tak Pernah Padam 🏮",
      maxLength: 80,
      section: "lantern",
    },
    {
      name: "lanternMessage",
      label: "Isi doa pada lentera",
      type: "textarea",
      placeholder:
        "Lentera ini membawa doa dan rasa syukurku atas hadirnya dirimu. Semoga hangatnya cahaya cinta kita selalu menerangi setiap lorong waktu yang kita lalui bersama.",
      maxLength: 600,
      rows: 3,
      section: "lantern",
    },

    // --- SECTION: SURAT CINTA SEMESTA ---
    {
      name: "title",
      label: "Judul surat cinta",
      type: "text",
      placeholder: "Di Antara Miliaran Bintang di Langit Semesta",
      required: true,
      maxLength: 100,
      section: "letter",
    },
    {
      name: "openingQuote",
      label: "Kutipan puitis pembuka",
      type: "textarea",
      placeholder:
        "Jika setiap bintang di langit malam adalah alasan mengapa aku mencintaimu, maka seluruh galaksi ini pun tak akan cukup untuk menghitungnya.",
      maxLength: 300,
      rows: 2,
      section: "letter",
    },
    {
      name: "message",
      label: "Isi surat cinta mendalam",
      type: "textarea",
      placeholder:
        "Tuliskan seluruh isi hatimu di sini...\n\nPisahkan setiap paragraf dengan baris kosong.",
      required: true,
      maxLength: 4000,
      rows: 10,
      section: "letter",
    },
    {
      name: "closingWord",
      label: "Kalimat penutup",
      type: "text",
      placeholder: "Mencintaimu hingga ke ujung galaksi terluar,",
      maxLength: 80,
      section: "letter",
    },
    {
      name: "signature",
      label: "Tanda tangan",
      type: "text",
      placeholder: "Reyhan Danendra",
      maxLength: 60,
      section: "letter",
    },

    // --- SECTION: TEMA CERAH & MUSIK ---
    {
      name: "primaryColor",
      label: "Warna aksen emas bintang & lentera",
      type: "color",
      defaultValue: "#d97706",
      helperText: "Warna kilau emas bintang, tombol lentera, dan stempel semesta.",
      colorPresets: STARLIGHT_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "backgroundColor",
      label: "Warna latar belakang (Warna Cerah)",
      type: "color",
      defaultValue: "#fdfbf7",
      helperText: "Warna kanvas cerah lembut bertabur partikel starlight.",
      colorPresets: BACKGROUND_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "cardColor",
      label: "Warna kartu & kertas surat",
      type: "color",
      defaultValue: "#ffffff",
      helperText: "Warna dasar kartu sertifikat dan amplop surat.",
      colorPresets: CARD_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "textColor",
      label: "Warna teks judul & nama",
      type: "color",
      defaultValue: "#1c1917",
      helperText: "Warna teks judul utama (espresso/midnight tegas).",
      colorPresets: TEXT_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "bodyTextColor",
      label: "Warna isi paragraf surat",
      type: "color",
      defaultValue: "#44403c",
      helperText: "Warna tulisan paragraf surat yang nyaman dibaca.",
      colorPresets: TEXT_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "musicTitle",
      label: "Judul audio malam (opsional)",
      type: "text",
      placeholder: "Starlight Lofi Piano & Music Box",
      maxLength: 80,
      section: "theme",
    },
    {
      name: "bgMusicUrl",
      label: "Tautan audio malam (.mp3 opsional)",
      type: "text",
      placeholder: "",
      maxLength: 1000,
      helperText: "Pilih file audio dari perangkat Anda atau biarkan kosong jika tanpa musik.",
      section: "theme",
    },
  ],
  sample: {
    recipientName: "Clarissa Aurelia",
    senderName: "Reyhan Danendra",
    constellationTitle: "Constellation of Our First Spark ✨",
    specialDate: "14 Februari 2023",
    anniversaryDate: "2023-02-14",
    starName: "Stella Clarissa Majoris ✨",
    starCoordinate: "RA 05h 35m • Dec -05° 23′ (Celestial Orion)",
    starMagnitude: "Magnitude 1.0 (Bintang Terang Utama)",
    starRegistryId: "STAR-LOVE-2023-CLARISSA",
    starDedicationQuote:
      "Didaftarkan abadi di hamparan galaksi, bersinar selamanya hanya untukmu.",
    constellationStory:
      "Rasi bintang ini tercipta dari jalinan kenangan manis kita: tatap mata pertama di bawah temaram senja, tawa saat kehujanan bersama di pelataran kafe, dan janji suci untuk saling menggenggam tangan selamanya.",
    star1: "Bintang Kedamaian: Selalu menjadi pelabuhan paling tenang dan aman saat harimu terasa lelah.",
    star2: "Bintang Ketulusan: Menjagamu dengan kejujuran, kehangatan, dan kesetiaan yang tak luntur oleh waktu.",
    star3: "Bintang Kehangatan: Menjadi selimut di kala dingin dan pelukan paling tulus di setiap senja.",
    star4: "Bintang Tawa: Mengukir senyuman di wajahmu bahkan di saat hari-hari terasa berat.",
    star5: "Bintang Keabadian: Terus menggenggam jemarimu dan menatap langit masa depan bersama-sama hingga menua.",
    starlightPhotoUrl:
      "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=1000&q=80",
    starlightPhotoCaption: "Pertama kali menatap gemintang bersama di atas bukit.",
    secondPhotoUrl:
      "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=1000&q=80",
    secondPhotoCaption: "Genggaman jemari yang selalu menghangatkan dinginnya malam.",
    photo3Url:
      "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=1000&q=80",
    photo3Caption: "Tawa renyahmu di bawah cahaya senja keemasan.",
    photo4Url:
      "https://images.unsplash.com/photo-1513279922550-250c2129b13a?auto=format&fit=crop&w=1000&q=80",
    photo4Caption: "Saat dunia di luar sana terasa sunyi dan hanya ada kita berdua.",
    secretStarlightWhisper:
      "Bisikan Rahasia: Dari triliunan kemungkinan di semesta ini, tidak ada satu detik pun yang kusesali saat memilihmu. Kamu adalah keajaiban terindah dalam hidupku. Aku mencintaimu, hari ini dan selamanya.",
    lanternTitle: "Lentera Harapan yang Tak Pernah Padam 🏮",
    lanternMessage:
      "Lentera ini membawa doa dan rasa syukurku atas hadirnya dirimu. Semoga hangatnya cahaya cinta kita selalu menerangi setiap lorong waktu yang kita lalui bersama.",
    title: "Di Antara Miliaran Bintang di Langit Semesta",
    openingQuote:
      "Jika setiap bintang di langit adalah alasan mengapa aku mencintaimu, maka seluruh galaksi ini pun tak akan cukup untuk menghitungnya.",
    message:
      "Clarissa,\n\nSetiap kali aku menatap bentangan langit, aku selalu terpana menyadari betapa luas dan megahnya alam semesta ini. Namun di tengah keheningan kosmik yang tak berujung, hatiku menemukan tempat berlabuh yang paling hangat: dirimu.\n\nKehadiranmu dalam hidupku bukan sekadar kebetulan, melainkan takdir terindah yang digariskan semesta. Senyumanmu adalah fajar yang selalu menepis gelap, dan tawamu adalah melodi paling merdu yang menenangkan setiap kekhawatiranku.\n\nDi hari yang indah ini, aku ingin menegaskan kembali rasa cintaku padamu. Tak peduli sejauh apa roda waktu berputar atau seberapa jauh jalan yang harus kita tempuh, rasa kagum dan sayangku padamu akan tetap bersinar abadi, seperti bintang utara yang tak pernah bergeser dari porosnya.\n\nTerima kasih telah menjadi bagian paling bersinar dalam galaksi hidupku.",
    closingWord: "Mencintaimu hingga ke ujung galaksi terluar,",
    signature: "Reyhan Danendra",
    primaryColor: "#d97706",
    backgroundColor: "#fdfbf7",
    cardColor: "#ffffff",
    textColor: "#1c1917",
    bodyTextColor: "#44403c",
    musicTitle: "",
    bgMusicUrl: "",
  },
};
