import type { TemplateMeta } from "../types";
import {
  STARLIGHT_COLOR_PRESETS,
  TEXT_COLOR_PRESETS,
} from "../color-presets";

export const starlightLoveTemplate: TemplateMeta = {
  slug: "starlight-love",
  name: "Celestial Starlight Romance",
  category: "Romansa",
  tagline:
    "Surat cinta langit malam berbintang — rasi bintang kenangan, lentera cahaya cinta, dan tiga janji semesta.",
  description:
    "Pengalaman romansa malam mewah bertabur bintang (dark celestial luxury). Dilengkapi dengan peta rasi bintang kenangan spesial, koordinat simbolik, lentera cinta bercahaya interaktif, kartu surat kaca temaram (dark glassmorphism), tiga bintang harapan, dan pemutar audio malam romantis.",
  cardAccent: "bg-slate-900 text-amber-300 ring-1 ring-amber-400/30",
  highlights: [
    "Nuansa langit malam kosmik bertabur bintang berkilau",
    "Peta rasi bintang kenangan berdua (Our Constellation Date)",
    "Tombol pembuka interaktif: Terbangkan Lentera Cinta",
    "Lembar surat cinta kaca temaram (Dark Glassmorphism)",
    "Tiga bintang harapan dan janji cinta semesta",
    "Kartu lentera cahaya bersinar (Glowing Love Lantern)",
    "Pemutar melodi instrumen malam yang menenangkan jiwa",
  ],
  fields: [
    // --- SECTION: IDENTITAS & KONSTELASI ---
    {
      name: "recipientName",
      label: "Nama kekasih (penerima)",
      type: "text",
      placeholder: "Clarissa Aurelia",
      required: true,
      maxLength: 60,
      isRecipient: true,
      section: "constellation",
    },
    {
      name: "senderName",
      label: "Nama kamu (pengirim)",
      type: "text",
      placeholder: "Reyhan Danendra",
      required: true,
      maxLength: 60,
      section: "constellation",
    },
    {
      name: "constellationTitle",
      label: "Nama rasi bintang kenangan",
      type: "text",
      placeholder: "Constellation of Our First Spark ✨",
      maxLength: 80,
      helperText: "Nama puitis untuk gugusan bintang momen cinta kalian.",
      section: "constellation",
    },
    {
      name: "specialDate",
      label: "Tanggal pertemuan / kenangan",
      type: "text",
      placeholder: "14 Februari 2023",
      maxLength: 40,
      section: "constellation",
    },
    {
      name: "starCoordinate",
      label: "Koordinat kenangan simbolik",
      type: "text",
      placeholder: "RA 05h 35m • Dec -05° 23′ (Orion)",
      maxLength: 60,
      helperText: "Koordinat astronomis atau lokasi kota tempat pertama kali bertemu.",
      section: "constellation",
    },
    {
      name: "starName",
      label: "Nama bintang simbolik berdua",
      type: "text",
      placeholder: "Stella Clarissa Majoris ✨",
      maxLength: 80,
      helperText: "Nama bintang khusus yang dipersembahkan untuk kekasih di langit malam.",
      section: "constellation",
    },
    {
      name: "anniversaryDate",
      label: "Momen perayaan / Tanggal jadian",
      type: "text",
      placeholder: "14 Februari 2023 • Malam Langit Sejajar",
      maxLength: 60,
      section: "constellation",
    },

    // --- SECTION: PORTAL FOTO KOSMIK & KENANGAN ---
    {
      name: "starlightPhotoUrl",
      label: "Foto kenangan utama (Portal Bintang)",
      type: "text",
      placeholder:
        "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=1000&q=80",
      maxLength: 1000,
      helperText: "Foto romantis berdua di bawah taburan bintang malam atau cahaya lentera.",
      section: "memories",
    },
    {
      name: "starlightPhotoCaption",
      label: "Keterangan foto portal bintang",
      type: "text",
      placeholder: "Malam pertama kita menatap gemintang bersama di atas bukit.",
      maxLength: 120,
      section: "memories",
    },
    {
      name: "secondPhotoUrl",
      label: "Foto kenangan kedua (Nebula Kasih)",
      type: "text",
      placeholder:
        "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=1000&q=80",
      maxLength: 1000,
      helperText: "Foto pelengkap momen hangat bersama.",
      section: "memories",
    },
    {
      name: "secondPhotoCaption",
      label: "Keterangan foto kenangan kedua",
      type: "text",
      placeholder: "Genggaman jemari yang selalu menghangatkan dinginnya malam.",
      maxLength: 120,
      section: "memories",
    },

    // --- SECTION: SURAT CINTA SEMESTA ---
    {
      name: "title",
      label: "Judul surat cinta",
      type: "text",
      placeholder: "Di Antara Miliaran Bintang di Langit Semesta",
      required: true,
      maxLength: 100,
      section: "letter",
    },
    {
      name: "openingQuote",
      label: "Kutipan puitis pembuka",
      type: "textarea",
      placeholder:
        "Jika setiap bintang di langit adalah alasan mengapa aku mencintaimu, maka seluruh galaksi ini pun tak akan cukup untuk menghitungnya.",
      maxLength: 300,
      rows: 2,
      section: "letter",
    },
    {
      name: "message",
      label: "Isi surat cinta",
      type: "textarea",
      placeholder:
        "Tuliskan seluruh isi hatimu di sini...\n\nPisahkan setiap paragraf dengan baris kosong untuk kerapian tampilan kaca temaram.",
      required: true,
      maxLength: 4000,
      rows: 10,
      section: "letter",
    },
    {
      name: "closingWord",
      label: "Kalimat penutup",
      type: "text",
      placeholder: "Mencintaimu hingga ke ujung galaksi terluar,",
      maxLength: 80,
      section: "letter",
    },
    {
      name: "signature",
      label: "Tanda tangan",
      type: "text",
      placeholder: "Reyhan Danendra",
      maxLength: 60,
      section: "letter",
    },

    // --- SECTION: TIGA BINTANG HARAPAN & JANJI ---
    {
      name: "wishesTitle",
      label: "Judul seksi bintang harapan",
      type: "text",
      placeholder: "Tiga Bintang Harapan di Bawah Langit Malam",
      maxLength: 80,
      section: "stars",
    },
    {
      name: "star1",
      label: "Bintang 1 (Harapan Pertama)",
      type: "text",
      placeholder: "Bintang Kedamaian: Selalu menjadi pelabuhan paling tenang saat duniamu riuh.",
      maxLength: 160,
      section: "stars",
    },
    {
      name: "star2",
      label: "Bintang 2 (Harapan Kedua)",
      type: "text",
      placeholder: "Bintang Ketulusan: Terus menjagamu dengan kejujuran dan rasa hormat yang tak luntur.",
      maxLength: 160,
      section: "stars",
    },
    {
      name: "star3",
      label: "Bintang 3 (Harapan Ketiga)",
      type: "text",
      placeholder: "Bintang Keabadian: Berjalan berdampingan hingga rambut kita memutih bersama.",
      maxLength: 160,
      section: "stars",
    },

    // --- SECTION: LENTERA CAHAYA (GLOWING LANTERN) ---
    {
      name: "lanternTitle",
      label: "Judul kartu lentera cahaya",
      type: "text",
      placeholder: "Lentera Harapan yang Tak Pernah Padam 🏮",
      maxLength: 80,
      section: "lantern",
    },
    {
      name: "lanternMessage",
      label: "Isi pesan lentera",
      type: "textarea",
      placeholder:
        "Cahaya lentera ini melambangkan doaku yang selalu menyala untuk kebahagiaanmu...",
      maxLength: 600,
      rows: 3,
      section: "lantern",
    },

    // --- SECTION: TEMA & MUSIK ---
    {
      name: "primaryColor",
      label: "Warna aksen bintang & lentera",
      type: "color",
      defaultValue: "#f5c542",
      helperText: "Warna kilau bintang, tombol lentera, dan ornamen rasi bintang.",
      colorPresets: STARLIGHT_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "backgroundColor",
      label: "Warna latar langit malam",
      type: "color",
      defaultValue: "#0b0f19",
      helperText: "Warna dasar kanvas langit kosmik malam.",
      colorPresets: [
        { label: "Deep Midnight Navy", value: "#0b0f19", description: "Biru dongker pekat malam kosmik" },
        { label: "Obsidian Black", value: "#09090b", description: "Hitam obsidian pekat luar angkasa" },
        { label: "Dark Indigo", value: "#0f172a", description: "Indigo malam berbintang" },
        { label: "Velvet Nebula", value: "#1e112a", description: "Ungu tua nebula misterius" },
        { label: "Abyssal Slate", value: "#0f141c", description: "Abu-abu laut malam gelap" },
      ],
      section: "theme",
    },
    {
      name: "cardColor",
      label: "Warna wadah kaca temaram",
      type: "color",
      defaultValue: "#131b2e",
      helperText: "Warna kartu surat kaca (dark glassmorphism).",
      colorPresets: [
        { label: "Midnight Glass", value: "#131b2e", description: "Kaca navy malam elegan" },
        { label: "Obsidian Card", value: "#18181b", description: "Kaca gelap arang pekat" },
        { label: "Nebula Glass", value: "#231535", description: "Kaca ungu velvet temaram" },
      ],
      section: "theme",
    },
    {
      name: "textColor",
      label: "Warna judul & nama",
      type: "color",
      defaultValue: "#fef3c7",
      helperText: "Warna teks judul emas muda.",
      colorPresets: TEXT_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "bodyTextColor",
      label: "Warna isi paragraf",
      type: "color",
      defaultValue: "#cbd5e1",
      helperText: "Warna teks paragraf surat (silver/slate lembut).",
      colorPresets: TEXT_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "musicTitle",
      label: "Judul audio malam (opsional)",
      type: "text",
      placeholder: "Starlight Lofi Piano & Music Box",
      maxLength: 80,
      section: "theme",
    },
    {
      name: "bgMusicUrl",
      label: "Tautan audio malam (.mp3)",
      type: "text",
      placeholder: "https://cdn.pixabay.com/download/audio/2022/10/14/audio_9939f792cb.mp3",
      maxLength: 1000,
      helperText: "Tautan langsung ke file audio mp3 malam yang menenangkan.",
      section: "theme",
    },
  ],
  sample: {
    recipientName: "Clarissa Aurelia",
    senderName: "Reyhan Danendra",
    constellationTitle: "Constellation of Our First Spark ✨",
    specialDate: "14 Februari 2023",
    starCoordinate: "RA 05h 35m • Dec -05° 23′ (Celestial Orion)",
    starName: "Stella Clarissa Majoris ✨",
    anniversaryDate: "14 Februari 2023 • Malam Langit Sejajar",
    starlightPhotoUrl:
      "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=1000&q=80",
    starlightPhotoCaption: "Malam pertama kita menatap gemintang bersama di atas bukit.",
    secondPhotoUrl:
      "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=1000&q=80",
    secondPhotoCaption: "Genggaman jemari yang selalu menghangatkan dinginnya malam.",
    title: "Di Antara Miliaran Bintang di Langit Semesta",
    openingQuote:
      "Jika setiap bintang di langit malam adalah alasan mengapa aku mencintaimu, maka seluruh galaksi ini pun tak akan cukup untuk menghitungnya.",
    message:
      "Clarissa,\n\nSetiap kali aku menatap langit malam, aku selalu terpana menyadari betapa luas dan megahnya alam semesta ini. Namun di tengah keheningan kosmik yang tak berujung, hatiku menemukan tempat berlabuh yang paling hangat: dirimu.\n\nKehadiranmu dalam hidupku bukan sekadar kebetulan, melainkan takdir terindah yang digariskan bintang. Senyumanmu adalah fajar yang selalu menepis gelap, dan tawamu adalah melodi paling merdu yang menenangkan setiap kekhawatiranku.\n\nDi malam yang hening ini, aku ingin menegaskan kembali rasa cintaku padamu. Tak peduli sejauh apa roda waktu berputar atau seberapa dingin malam merayap, rasa kagum dan sayangku padamu akan tetap bersinar abadi, seperti bintang utara yang tak pernah bergeser dari porosnya.",
    closingWord: "Mencintaimu hingga ke ujung galaksi terluar,",
    signature: "Reyhan Danendra",
    wishesTitle: "Tiga Bintang Harapan di Bawah Langit Malam",
    star1: "Bintang Kedamaian: Selalu menjadi pelabuhan paling tenang dan aman saat harimu terasa lelah.",
    star2: "Bintang Ketulusan: Menjagamu dengan kejujuran, kehangatan, dan kesetiaan yang tak luntur oleh waktu.",
    star3: "Bintang Keabadian: Terus menggenggam jemarimu dan menatap langit masa depan bersama-sama.",
    lanternTitle: "Lentera Harapan yang Tak Pernah Padam 🏮",
    lanternMessage:
      "Lentera ini membawa doa dan rasa syukurku atas hadirnya dirimu. Semoga hangatnya cahaya cinta kita selalu menerangi setiap lorong waktu yang kita lalui bersama.",
    primaryColor: "#f5c542",
    backgroundColor: "#0b0f19",
    cardColor: "#131b2e",
    textColor: "#fef3c7",
    bodyTextColor: "#cbd5e1",
    musicTitle: "Starlight Lofi Piano & Music Box",
    bgMusicUrl: "https://cdn.pixabay.com/download/audio/2022/10/14/audio_9939f792cb.mp3",
  },
};
