import type { TemplateMeta } from "../types";
import {
  BACKGROUND_COLOR_PRESETS,
  CARD_COLOR_PRESETS,
  TEXT_COLOR_PRESETS,
} from "../color-presets";

export const royalGardenWeddingTemplate: TemplateMeta = {
  slug: "royal-garden-wedding",
  name: "Royal Botanical Wedding & Walimah",
  category: "Undangan",
  tagline:
    "Undangan pernikahan botani mewah — segel lilin monogram, live countdown, rundown acara, amplop digital, dan galeri prewedding.",
  description:
    "Sebuah undangan pernikahan digital agung bertema botanical garden kerajaan. Menampilkan amplop mewah bersegel lilin monogram personal, nama tamu kustom via URL (?to=Nama), widget hitung mundur (countdown timer) interaktif, rundown sesi acara, panduan dress code & palet warna, navigasi Google Maps, amplop digital dengan fitur salin nomor rekening, serta pemutar musik orkestra romantis.",
  cardAccent: "bg-emerald-50 text-emerald-900 ring-1 ring-emerald-300",
  highlights: [
    "Amplop bertekstur linen mewah dengan segel lilin monogram inisial mempelai",
    "Sapaan nama tamu undangan dinamis via tautan (?to=NamaTamu)",
    "Widget Live Countdown Timer menghitung mundur menuju hari pernikahan",
    "Timeline rundown acara terstruktur (Akad Nikah, Resepsi, Ramah Tamah)",
    "Galeri foto prewedding berbingkai emas floral 3-frame",
    "Panduan dress code lengkap dengan rekomendasi palet warna busana",
    "Amplop digital & kartu tanda kasih dengan tombol salin no. rekening instan",
    "Integrasi peta lokasi venue langsung ke Google Maps",
    "Pemutar melodi instrumen romantis berputar melayang",
  ],
  fields: [
    // --- SECTION: AMPLOP & COVER ---
    {
      name: "recipientName",
      label: "Nama tamu undangan (penerima)",
      type: "text",
      placeholder: "Bapak / Ibu / Sahabat Terkasih",
      required: true,
      maxLength: 60,
      isRecipient: true,
      section: "envelope",
    },
    {
      name: "waxSealMonogram",
      label: "Inisial monogram segel lilin",
      type: "text",
      placeholder: "R & A",
      maxLength: 10,
      helperText: "Inisial kedua mempelai pada stempel segel lilin (misal: R & A).",
      section: "envelope",
    },
    {
      name: "weddingTagline",
      label: "Subjudul undangan / Tagline",
      type: "text",
      placeholder: "The Holy Matrimony & Wedding Reception",
      maxLength: 80,
      section: "envelope",
    },

    // --- SECTION: MEMPELAI & PESAN ---
    {
      name: "groomName",
      label: "Nama lengkap mempelai pria",
      type: "text",
      placeholder: "Raden Arya Daniswara, S.T.",
      required: true,
      maxLength: 80,
      section: "couple",
    },
    {
      name: "groomParents",
      label: "Orang tua mempelai pria",
      type: "text",
      placeholder: "Putra dari Bpk. Ir. Daniswara & Ibu Hj. Ratna Sari",
      maxLength: 120,
      section: "couple",
    },
    {
      name: "brideName",
      label: "Nama lengkap mempelai wanita",
      type: "text",
      placeholder: "Anindita Kirana Putri, B.Des.",
      required: true,
      maxLength: 80,
      section: "couple",
    },
    {
      name: "brideParents",
      label: "Orang tua mempelai wanita",
      type: "text",
      placeholder: "Putri dari Bpk. Dr. H. Suryo Kusumo & Ibu Siti Rahmawati",
      maxLength: 120,
      section: "couple",
    },
    {
      name: "holyVerseQuote",
      label: "Kutipan suci / Ayat cinta",
      type: "textarea",
      placeholder:
        "\"Dan di antara tanda-tanda kebesaran-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, agar kamu cenderung dan merasa tenteram kepadanya, dan Dia menjadikan di antaramu rasa kasih dan sayang.\" (QS. Ar-Rum: 21)",
      maxLength: 400,
      rows: 3,
      section: "couple",
    },
    {
      name: "invitationMessage",
      label: "Pesan pembuka undangan",
      type: "textarea",
      placeholder:
        "Dengan memohon rahmat dan ridho Allah Subhanahu Wa Ta'ala, kami bermaksud mengundang Bapak/Ibu/Saudara/i untuk hadir dan memberikan doa restu pada hari bahagia pernikahan putra-putri kami.",
      maxLength: 800,
      rows: 4,
      section: "couple",
    },

    // --- SECTION: WAKTU & LOKASI (COUNTDOWN & MAPS) ---
    {
      name: "eventDate",
      label: "Hari & tanggal acara",
      type: "text",
      placeholder: "Sabtu, 28 Desember 2024",
      required: true,
      maxLength: 60,
      section: "event",
    },
    {
      name: "targetIsoDate",
      label: "Tanggal target hitung mundur (ISO YYYY-MM-DDTHH:mm)",
      type: "text",
      placeholder: "2024-12-28T09:00",
      helperText: "Format tanggal untuk menjalankan countdown timer (misal: 2024-12-28T09:00).",
      section: "event",
    },
    {
      name: "venueName",
      label: "Nama gedung / venue pernikahan",
      type: "text",
      placeholder: "The Royal Glasshouse & Botanical Garden",
      required: true,
      maxLength: 100,
      section: "event",
    },
    {
      name: "venueAddress",
      label: "Alamat lengkap venue",
      type: "textarea",
      placeholder: "Jl. Dago Giri No. 88, Lembang, Bandung, Jawa Barat 40391",
      maxLength: 250,
      rows: 2,
      section: "event",
    },
    {
      name: "mapsUrl",
      label: "Tautan Google Maps",
      type: "text",
      placeholder: "https://maps.google.com/?q=Bandung",
      maxLength: 1000,
      helperText: "Tautan langsung ke pin lokasi Google Maps untuk mempermudah navigasi tamu.",
      section: "event",
    },

    // --- SECTION: RUNDOWN ACARA ---
    {
      name: "session1Title",
      label: "Sesi 1: Judul sesi",
      type: "text",
      placeholder: "Akad Nikah / Pemberkatan",
      maxLength: 60,
      section: "rundown",
    },
    {
      name: "session1Time",
      label: "Sesi 1: Waktu",
      type: "text",
      placeholder: "08.00 - 10.00 WIB",
      maxLength: 40,
      section: "rundown",
    },
    {
      name: "session1Desc",
      label: "Sesi 1: Keterangan",
      type: "text",
      placeholder: "Prosesi ijab qabul khidmat bersama keluarga inti & kerabat dekat.",
      maxLength: 150,
      section: "rundown",
    },
    {
      name: "session2Title",
      label: "Sesi 2: Judul sesi",
      type: "text",
      placeholder: "Resepsi Pernikahan (Grand Reception)",
      maxLength: 60,
      section: "rundown",
    },
    {
      name: "session2Time",
      label: "Sesi 2: Waktu",
      type: "text",
      placeholder: "11.00 - 14.00 WIB",
      maxLength: 40,
      section: "rundown",
    },
    {
      name: "session2Desc",
      label: "Sesi 2: Keterangan",
      type: "text",
      placeholder: "Santap siang bersama, ramah tamah, dan sesi foto bersama kedua mempelai.",
      maxLength: 150,
      section: "rundown",
    },
    {
      name: "session3Title",
      label: "Sesi 3: Judul sesi",
      type: "text",
      placeholder: "Sunset Celebration & After Party",
      maxLength: 60,
      section: "rundown",
    },
    {
      name: "session3Time",
      label: "Sesi 3: Waktu",
      type: "text",
      placeholder: "16.00 - 18.00 WIB",
      maxLength: 40,
      section: "rundown",
    },
    {
      name: "session3Desc",
      label: "Sesi 3: Keterangan",
      type: "text",
      placeholder: "Pertunjukan live acoustic & pelepasan lentera harapan di taman botani.",
      maxLength: 150,
      section: "rundown",
    },

    // --- SECTION: FOTO PREWEDDING ---
    {
      name: "photo1Url",
      label: "Foto Prewedding 1 (Utama)",
      type: "text",
      placeholder:
        "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1000&q=80",
      maxLength: 1000,
      section: "photos",
    },
    {
      name: "photo1Caption",
      label: "Keterangan Foto 1",
      type: "text",
      placeholder: "Dua hati yang bersatu dalam ikatan suci cinta abadi.",
      maxLength: 120,
      section: "photos",
    },
    {
      name: "photo2Url",
      label: "Foto Prewedding 2",
      type: "text",
      placeholder:
        "https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=1000&q=80",
      maxLength: 1000,
      section: "photos",
    },
    {
      name: "photo2Caption",
      label: "Keterangan Foto 2",
      type: "text",
      placeholder: "Melangkah bersama menatap masa depan yang cerah.",
      maxLength: 120,
      section: "photos",
    },
    {
      name: "photo3Url",
      label: "Foto Prewedding 3",
      type: "text",
      placeholder:
        "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1000&q=80",
      maxLength: 1000,
      section: "photos",
    },
    {
      name: "photo3Caption",
      label: "Keterangan Foto 3",
      type: "text",
      placeholder: "Senyum kebahagiaan yang akan kami jaga selamanya.",
      maxLength: 120,
      section: "photos",
    },

    // --- SECTION: DRESS CODE TAMU ---
    {
      name: "dressCodeTitle",
      label: "Tema Dress Code Tamu",
      type: "text",
      placeholder: "Botanical Formal / Royal Emerald & Gold",
      maxLength: 80,
      section: "dresscode",
    },
    {
      name: "dressCodeNote",
      label: "Catatan panduan busana",
      type: "text",
      placeholder: "Disarankan mengenakan busana formal bernuansa hijau zamrud, sage, champagne, atau putih.",
      maxLength: 180,
      section: "dresscode",
    },

    // --- SECTION: AMPLOP DIGITAL / TANDA KASIH ---
    {
      name: "giftInfoTitle",
      label: "Judul seksi tanda kasih",
      type: "text",
      placeholder: "Tanda Kasih & Doa Restu (Amplop Digital)",
      maxLength: 80,
      section: "gift",
    },
    {
      name: "bankName1",
      label: "Bank / e-Wallet 1",
      type: "text",
      placeholder: "BCA",
      maxLength: 40,
      section: "gift",
    },
    {
      name: "accountNumber1",
      label: "Nomor Rekening 1",
      type: "text",
      placeholder: "8420192831",
      maxLength: 40,
      section: "gift",
    },
    {
      name: "accountHolder1",
      label: "Atas Nama Rekening 1",
      type: "text",
      placeholder: "Raden Arya Daniswara",
      maxLength: 60,
      section: "gift",
    },
    {
      name: "bankName2",
      label: "Bank / e-Wallet 2",
      type: "text",
      placeholder: "Bank Mandiri",
      maxLength: 40,
      section: "gift",
    },
    {
      name: "accountNumber2",
      label: "Nomor Rekening 2",
      type: "text",
      placeholder: "1320098472910",
      maxLength: 40,
      section: "gift",
    },
    {
      name: "accountHolder2",
      label: "Atas Nama Rekening 2",
      type: "text",
      placeholder: "Anindita Kirana Putri",
      maxLength: 60,
      section: "gift",
    },

    // --- SECTION: TEMA & MUSIK ---
    {
      name: "primaryColor",
      label: "Warna aksen utama (Zamrud / Gold)",
      type: "color",
      defaultValue: "#064e3b",
      helperText: "Warna hijau zamrud kerajaan dan aksen tombol.",
      colorPresets: [
        { label: "Royal Emerald", value: "#064e3b", description: "Hijau zamrud botani agung" },
        { label: "Imperial Gold", value: "#92400e", description: "Emas tembaga kemewahan" },
        { label: "Midnight Sage", value: "#14532d", description: "Hijau lumut hutan elegan" },
        { label: "Burgundy Velvet", value: "#701a75", description: "Ungu tua velvet bangsawan" },
        { label: "Sapphire Royal", value: "#1e3a8a", description: "Biru safir megah" },
      ],
      section: "theme",
    },
    {
      name: "backgroundColor",
      label: "Warna latar belakang kanvas",
      type: "color",
      defaultValue: "#f4f7f4",
      helperText: "Warna latar kertas linen lembut.",
      colorPresets: BACKGROUND_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "cardColor",
      label: "Warna lembaran kartu undangan",
      type: "color",
      defaultValue: "#ffffff",
      helperText: "Warna wadah kartu undangan utama.",
      colorPresets: CARD_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "textColor",
      label: "Warna judul & nama mempelai",
      type: "color",
      defaultValue: "#064e3b",
      helperText: "Warna teks judul kaligrafi.",
      colorPresets: TEXT_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "bodyTextColor",
      label: "Warna teks isi paragraf",
      type: "color",
      defaultValue: "#374151",
      helperText: "Warna teks deskripsi dan informasi acara.",
      colorPresets: TEXT_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "musicTitle",
      label: "Judul musik pengiring",
      type: "text",
      placeholder: "A Thousand Years (Cello & Piano Orchestra)",
      maxLength: 80,
      section: "theme",
    },
    {
      name: "bgMusicUrl",
      label: "Tautan audio (.mp3)",
      type: "text",
      placeholder: "https://cdn.pixabay.com/download/audio/2022/11/06/audio_c3c3167123.mp3",
      maxLength: 1000,
      helperText: "Tautan langsung ke file audio mp3 yang berputar saat undangan dibuka.",
      section: "theme",
    },
  ],
  sample: {
    recipientName: "Bapak / Ibu / Sahabat Terkasih",
    waxSealMonogram: "R & A",
    weddingTagline: "The Holy Matrimony & Wedding Reception",
    groomName: "Raden Arya Daniswara, S.T.",
    groomParents: "Putra dari Bpk. Ir. Daniswara & Ibu Hj. Ratna Sari",
    brideName: "Anindita Kirana Putri, B.Des.",
    brideParents: "Putri dari Bpk. Dr. H. Suryo Kusumo & Ibu Siti Rahmawati",
    holyVerseQuote:
      "\"Dan di antara tanda-tanda kebesaran-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, agar kamu cenderung dan merasa tenteram kepadanya, dan Dia menjadikan di antaramu rasa kasih dan sayang.\" (QS. Ar-Rum: 21)",
    invitationMessage:
      "Dengan memohon rahmat dan ridho Allah Subhanahu Wa Ta'ala, kami bermaksud mengundang Bapak/Ibu/Saudara/i untuk hadir dan memberikan doa restu pada hari bahagia pernikahan putra-putri kami.",
    eventDate: "Sabtu, 28 Desember 2024",
    targetIsoDate: "2024-12-28T09:00",
    venueName: "The Royal Glasshouse & Botanical Garden",
    venueAddress: "Jl. Dago Giri No. 88, Lembang, Bandung, Jawa Barat 40391",
    mapsUrl: "https://maps.google.com/?q=Bandung",
    session1Title: "Akad Nikah / Pemberkatan",
    session1Time: "08.00 - 10.00 WIB",
    session1Desc: "Prosesi ijab qabul khidmat bersama keluarga inti & kerabat dekat.",
    session2Title: "Resepsi Pernikahan (Grand Reception)",
    session2Time: "11.00 - 14.00 WIB",
    session2Desc: "Santap siang bersama, ramah tamah, dan sesi foto bersama kedua mempelai.",
    session3Title: "Sunset Celebration & After Party",
    session3Time: "16.00 - 18.00 WIB",
    session3Desc: "Pertunjukan live acoustic & pelepasan lentera harapan di taman botani.",
    photo1Url:
      "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1000&q=80",
    photo1Caption: "Dua hati yang bersatu dalam ikatan suci cinta abadi.",
    photo2Url:
      "https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=1000&q=80",
    photo2Caption: "Melangkah bersama menatap masa depan yang cerah.",
    photo3Url:
      "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1000&q=80",
    photo3Caption: "Senyum kebahagiaan yang akan kami jaga selamanya.",
    dressCodeTitle: "Botanical Formal / Royal Emerald & Gold",
    dressCodeNote: "Disarankan mengenakan busana formal bernuansa hijau zamrud, sage, champagne, atau putih gading.",
    giftInfoTitle: "Tanda Kasih & Doa Restu (Amplop Digital)",
    bankName1: "BCA",
    accountNumber1: "8420192831",
    accountHolder1: "Raden Arya Daniswara",
    bankName2: "Bank Mandiri",
    accountNumber2: "1320098472910",
    accountHolder2: "Anindita Kirana Putri",
    primaryColor: "#064e3b",
    backgroundColor: "#f4f7f4",
    cardColor: "#ffffff",
    textColor: "#064e3b",
    bodyTextColor: "#374151",
    musicTitle: "A Thousand Years (Cello & Piano Orchestra)",
    bgMusicUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
  },
};
