import type { TemplateMeta } from "../types";

export const birthdayPassportTemplate: TemplateMeta = {
  slug: "birthday-passport",
  name: "The Birthday Passport",
  category: "Perayaan",
  tagline:
    "Paspor penjelajah dunia edisi ulang tahun — biodata resmi berhologram, 4 stempel visa perjalanan hidup, surat diplomatik, kartu pos antik, dan tiket boarding pass first-class.",
  description:
    "Template perayaan ulang tahun bertema 'The Wanderlust Birthday Passport & Expedition Journal' yang mewah, berjiwa petualang, dan sangat elegan. Menampilkan sampul paspor kulit beraksen emas yang dapat dibuka, halaman identitas biometrik berstempel hologram dan kode MRZ, 4 stempel visa imigrasi tahapan hidup, surat penjelajah di atas kertas guilloché antik, 3 kartu pos berperangko air mail, tiket boarding pass penerbangan babak usia baru dengan 4 doa destinasi, serta pemutar musik santai in-flight lounge.",
  cardAccent: "bg-blue-950 text-amber-300 ring-1 ring-amber-400/50",
  highlights: [
    "Sampul paspor kulit vintage bertekstur realistis dengan lambang monogram emas",
    "Halaman identitas paspor resmi dengan foto biometrik, stempel hologram, & kode MRZ",
    "4 stempel visa imigrasi warna-warni yang merepresentasikan fase perjalanan hidup",
    "Surat diplomatik penjelajah penuh makna di atas kertas perkamen berpola guilloché",
    "Galeri 3 kartu pos memorabilia berstempel pos vintage & cap 'AIR MAIL'",
    "Boarding pass maskapai penerbangan VIP 'AERO-BIRTHDAY' berisi 4 pilar doa babak baru",
    "Pemutar audio travel jazz / bossa nova mengambang dengan kontrol in-flight",
  ],
  fields: [
    // --- SECTION: BIODATA PASPOR RESMI ---
    {
      name: "recipientName",
      label: "Nama lengkap pemilik paspor (Yang berulang tahun)",
      type: "text",
      placeholder: "Clarissa Valery Putri",
      required: true,
      maxLength: 60,
      isRecipient: true,
      section: "passport_bio",
    },
    {
      name: "passportNumber",
      label: "Nomor registrasi paspor",
      type: "text",
      placeholder: "EXP-2026-BDAY25",
      maxLength: 30,
      section: "passport_bio",
    },
    {
      name: "nationality",
      label: "Kewarganegaraan / Identitas jiwa",
      type: "text",
      placeholder: "Citizen of the Universe // Heart of Gold",
      maxLength: 50,
      section: "passport_bio",
    },
    {
      name: "birthDate",
      label: "Tanggal lahir & usia baru",
      type: "text",
      placeholder: "24 Oktober 2001 (Babak Usia ke-25)",
      required: true,
      maxLength: 60,
      section: "passport_bio",
    },
    {
      name: "birthPlace",
      label: "Tempat kelahiran / Asal perjalanan",
      type: "text",
      placeholder: "Jakarta, Indonesia // Terra Firm",
      maxLength: 60,
      section: "passport_bio",
    },
    {
      name: "issuingAuthority",
      label: "Otoritas penerbit paspor",
      type: "text",
      placeholder: "Ministry of Joy, Growth & Good Memories",
      maxLength: 70,
      section: "passport_bio",
    },
    {
      name: "bearerPhotoUrl",
      label: "Foto resmi paspor (URL)",
      type: "text",
      placeholder: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=80",
      section: "passport_bio",
    },
    {
      name: "passportTagline",
      label: "Motto penjelajah / Semboyan paspor",
      type: "textarea",
      placeholder:
        "Diberikan hak penuh untuk mengarungi samudera waktu, memetik kebahagiaan di setiap pelabuhan, dan terus melangkah tanpa rasa takut.",
      maxLength: 250,
      section: "passport_bio",
    },

    // --- SECTION: 4 STEMPEL VISA PERJALANAN HIDUP ---
    {
      name: "visa1Country",
      label: "Visa 1: Kode Imigrasi / Destinasi",
      type: "text",
      placeholder: "EXP-01 // WONDERLAND",
      maxLength: 30,
      section: "visas",
    },
    {
      name: "visa1Title",
      label: "Visa 1: Nama Visa & Makna",
      type: "text",
      placeholder: "Visa of Innocence & Wonder",
      maxLength: 50,
      section: "visas",
    },
    {
      name: "visa1Date",
      label: "Visa 1: Periode Stempel",
      type: "text",
      placeholder: "ENTRY: MASA KECIL",
      maxLength: 30,
      section: "visas",
    },
    {
      name: "visa1Desc",
      label: "Visa 1: Catatan Perjalanan",
      type: "textarea",
      placeholder: "Masa di mana imajinasi melangit tinggi dan setiap sudut dunia tampak penuh keajaiban.",
      maxLength: 180,
      section: "visas",
    },

    {
      name: "visa2Country",
      label: "Visa 2: Kode Imigrasi / Destinasi",
      type: "text",
      placeholder: "EXP-02 // ADVENTURE",
      maxLength: 30,
      section: "visas",
    },
    {
      name: "visa2Title",
      label: "Visa 2: Nama Visa & Makna",
      type: "text",
      placeholder: "Visa of Courage & Exploration",
      maxLength: 50,
      section: "visas",
    },
    {
      name: "visa2Date",
      label: "Visa 2: Periode Stempel",
      type: "text",
      placeholder: "ENTRY: MASA REMAJA",
      maxLength: 30,
      section: "visas",
    },
    {
      name: "visa2Desc",
      label: "Visa 2: Catatan Perjalanan",
      type: "textarea",
      placeholder: "Keberanian keluar dari zona nyaman, menjajal hal-hal baru, dan merajut persahabatan sejati.",
      maxLength: 180,
      section: "visas",
    },

    {
      name: "visa3Country",
      label: "Visa 3: Kode Imigrasi / Destinasi",
      type: "text",
      placeholder: "EXP-03 // RESILIENCE",
      maxLength: 30,
      section: "visas",
    },
    {
      name: "visa3Title",
      label: "Visa 3: Nama Visa & Makna",
      type: "text",
      placeholder: "Visa of Resilience & Growth",
      maxLength: 50,
      section: "visas",
    },
    {
      name: "visa3Date",
      label: "Visa 3: Periode Stempel",
      type: "text",
      placeholder: "ENTRY: DEWASA AWAL",
      maxLength: 30,
      section: "visas",
    },
    {
      name: "visa3Desc",
      label: "Visa 3: Catatan Perjalanan",
      type: "textarea",
      placeholder: "Mengarungi badai kehidupan dengan keteguhan hati, membuktikan bahwa dirimu lebih kuat dari yang kau duga.",
      maxLength: 180,
      section: "visas",
    },

    {
      name: "visa4Country",
      label: "Visa 4: Kode Imigrasi / Destinasi",
      type: "text",
      placeholder: "EXP-04 // FUTURE VOYAGE",
      maxLength: 30,
      section: "visas",
    },
    {
      name: "visa4Title",
      label: "Visa 4: Nama Visa & Makna",
      type: "text",
      placeholder: "Visa of Wisdom & New Horizon",
      maxLength: 50,
      section: "visas",
    },
    {
      name: "visa4Date",
      label: "Visa 4: Periode Stempel",
      type: "text",
      placeholder: "ENTRY: BABAK BARU",
      maxLength: 30,
      section: "visas",
    },
    {
      name: "visa4Desc",
      label: "Visa 4: Catatan Perjalanan",
      type: "textarea",
      placeholder: "Memasuki babak baru dengan kebijaksanaan, ketenangan batin, dan optimisme tak terbatas.",
      maxLength: 180,
      section: "visas",
    },

    // --- SECTION: SURAT DIPLOMATIK PENJELAJAH ---
    {
      name: "letterTitle",
      label: "Judul surat diplomatik",
      type: "text",
      placeholder: "Warkat Diplomatik: Catatan Terindah Bagi Rekan Seperjalanan",
      required: true,
      maxLength: 100,
      section: "dispatch",
    },
    {
      name: "letterContent",
      label: "Isi surat utama (Panjang, mendalam & reflektif)",
      type: "textarea",
      placeholder:
        "Kepada sang penjelajah yang paling saya kagumi...\n\nHidup adalah ekspedisi terpanjang yang kita arungi, dan memiliki dirimu sebagai rekan perjalanan adalah salah satu anugerah paling berharga.",
      required: true,
      section: "dispatch",
    },
    {
      name: "senderName",
      label: "Nama pengirim / Rekan penjelajah",
      type: "text",
      placeholder: "Arya Bimasakti",
      required: true,
      maxLength: 60,
      section: "dispatch",
    },
    {
      name: "senderTitle",
      label: "Peran / Keterangan pengirim",
      type: "text",
      placeholder: "Chief of Expedition // Sahabat Seperjalanan Seumur Hidup",
      maxLength: 70,
      section: "dispatch",
    },

    // --- SECTION: 3 KARTU POS MEMORABILIA ---
    {
      name: "postcard1Photo",
      label: "Foto Kartu Pos 1 (URL)",
      type: "text",
      placeholder: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=80",
      section: "postcards",
    },
    {
      name: "postcard1Location",
      label: "Lokasi / Destinasi Kartu Pos 1",
      type: "text",
      placeholder: "Kala Menatap Senja di Sudut Kota",
      maxLength: 60,
      section: "postcards",
    },
    {
      name: "postcard1Date",
      label: "Tanggal / Cap Pos 1",
      type: "text",
      placeholder: "Postmark // 14 Juli 2024",
      maxLength: 40,
      section: "postcards",
    },
    {
      name: "postcard1Note",
      label: "Catatan Tulisan Tangan Kartu Pos 1",
      type: "textarea",
      placeholder: "Secangkir kopi hangat, angin sejuk, dan percakapan panjang yang tak pernah kehabisan topik menyenangkan.",
      maxLength: 180,
      section: "postcards",
    },

    {
      name: "postcard2Photo",
      label: "Foto Kartu Pos 2 (URL)",
      type: "text",
      placeholder: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80",
      section: "postcards",
    },
    {
      name: "postcard2Location",
      label: "Lokasi / Destinasi Kartu Pos 2",
      type: "text",
      placeholder: "Puncak Bukit Penuh Gelak Tawa",
      maxLength: 60,
      section: "postcards",
    },
    {
      name: "postcard2Date",
      label: "Tanggal / Cap Pos 2",
      type: "text",
      placeholder: "Postmark // 28 Desember 2024",
      maxLength: 40,
      section: "postcards",
    },
    {
      name: "postcard2Note",
      label: "Catatan Tulisan Tangan Kartu Pos 2",
      type: "textarea",
      placeholder: "Tawa renyahmu di tengah lelahnya mendaki adalah bukti nyata bahwa kebahagiaan itu menular.",
      maxLength: 180,
      section: "postcards",
    },

    {
      name: "postcard3Photo",
      label: "Foto Kartu Pos 3 (URL)",
      type: "text",
      placeholder: "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1200&q=80",
      section: "postcards",
    },
    {
      name: "postcard3Location",
      label: "Lokasi / Destinasi Kartu Pos 3",
      type: "text",
      placeholder: "Malam Perayaan Penuh Kenangan",
      maxLength: 60,
      section: "postcards",
    },
    {
      name: "postcard3Date",
      label: "Tanggal / Cap Pos 3",
      type: "text",
      placeholder: "Postmark // 05 Mei 2025",
      maxLength: 40,
      section: "postcards",
    },
    {
      name: "postcard3Note",
      label: "Catatan Tulisan Tangan Kartu Pos 3",
      type: "textarea",
      placeholder: "Momen ketika kita sadar bahwa apa pun yang terjadi, kita selalu punya rumah untuk pulang.",
      maxLength: 180,
      section: "postcards",
    },

    // --- SECTION: BOARDING PASS BABAK BARU & 4 DOA DESTINASI ---
    {
      name: "flightNumber",
      label: "Nomor Penerbangan",
      type: "text",
      placeholder: "AERO-BDAY25",
      maxLength: 20,
      section: "boarding_pass",
    },
    {
      name: "seatNumber",
      label: "Nomor Kursi VIP",
      type: "text",
      placeholder: "01A FIRST CLASS",
      maxLength: 20,
      section: "boarding_pass",
    },
    {
      name: "departureChapter",
      label: "Asal Penerbangan (Babak Lalu)",
      type: "text",
      placeholder: "CHAPTER 24 (PASSED WITH GLORY)",
      maxLength: 50,
      section: "boarding_pass",
    },
    {
      name: "arrivalChapter",
      label: "Destinasi Kedatangan (Babak Baru)",
      type: "text",
      placeholder: "CHAPTER 25 (LIMITLESS JOY)",
      maxLength: 50,
      section: "boarding_pass",
    },

    {
      name: "wish1Title",
      label: "Doa Destinasi 1: Judul Harapan",
      type: "text",
      placeholder: "Clear Skies: Ketenangan Jiwa",
      maxLength: 50,
      section: "boarding_pass",
    },
    {
      name: "wish1Desc",
      label: "Doa Destinasi 1: Uraian Pesan",
      type: "textarea",
      placeholder: "Semoga langit batinmu selalu jernih dan bebas dari awan badai kegelisahan.",
      maxLength: 160,
      section: "boarding_pass",
    },

    {
      name: "wish2Title",
      label: "Doa Destinasi 2: Judul Harapan",
      type: "text",
      placeholder: "Smooth Turbulence: Ketangguhan Batin",
      maxLength: 50,
      section: "boarding_pass",
    },
    {
      name: "wish2Desc",
      label: "Doa Destinasi 2: Uraian Pesan",
      type: "textarea",
      placeholder: "Setiap riak tantangan di masa depan dapat kau lalui dengan senyuman dan hati yang tegar.",
      maxLength: 160,
      section: "boarding_pass",
    },

    {
      name: "wish3Title",
      label: "Doa Destinasi 3: Judul Harapan",
      type: "text",
      placeholder: "First-Class Fortune: Kelimpahan Berkah",
      maxLength: 50,
      section: "boarding_pass",
    },
    {
      name: "wish3Desc",
      label: "Doa Destinasi 3: Uraian Pesan",
      type: "textarea",
      placeholder: "Pintu-pintu rezeki, karier, dan karya cemerlang terbuka lebar dalam babak usiamu saat ini.",
      maxLength: 160,
      section: "boarding_pass",
    },

    {
      name: "wish4Title",
      label: "Doa Destinasi 4: Judul Harapan",
      type: "text",
      placeholder: "Golden Haven: Kasih yang Tulus",
      maxLength: 50,
      section: "boarding_pass",
    },
    {
      name: "wish4Desc",
      label: "Doa Destinasi 4: Uraian Pesan",
      type: "textarea",
      placeholder: "Selalu dipertemukan dengan orang-orang berhati tulus yang menyayangi dan menjagamu.",
      maxLength: 160,
      section: "boarding_pass",
    },

    // --- SECTION: WARNA & AUDIO LOUNGE ---
    {
      name: "primaryColor",
      label: "Warna Sampul Paspor Kulit",
      type: "color",
      placeholder: "#0f1e36",
      section: "styling",
    },
    {
      name: "accentColor",
      label: "Warna Emboss Emas Paspor",
      type: "color",
      placeholder: "#d4af37",
      section: "styling",
    },
    {
      name: "backgroundColor",
      label: "Warna Latar Meja / Ekspedisi",
      type: "color",
      placeholder: "#f1ede4",
      section: "styling",
    },
    {
      name: "paperColor",
      label: "Warna Kertas Paspor",
      type: "color",
      placeholder: "#faf8f2",
      section: "styling",
    },
    {
      name: "textColor",
      label: "Warna Teks Tinta",
      type: "color",
      placeholder: "#1b2533",
      section: "styling",
    },
    {
      name: "musicTitle",
      label: "Judul Musik Travel Lounge",
      type: "text",
      placeholder: "In-Flight Bossa & Acoustic Voyage",
      maxLength: 60,
      section: "audio",
    },
    {
      name: "musicUrl",
      label: "URL File Musik Audio (MP3)",
      type: "text",
      placeholder: "https://cdn.pixabay.com/download/audio/2022/05/16/audio_db6591201e.mp3?filename=acoustic-guitars-ambient-111163.mp3",
      section: "audio",
    },
  ],
  sample: {
    recipientName: "Clarissa Valery Putri",
    passportNumber: "EXP-2026-BDAY25",
    nationality: "Citizen of the Universe // Heart of Gold",
    birthDate: "24 Oktober 2001 (Babak Usia ke-25)",
    birthPlace: "Jakarta, Indonesia // Terra Firm",
    issuingAuthority: "Ministry of Joy, Growth & Good Memories",
    bearerPhotoUrl:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=80",
    passportTagline:
      "Diberikan hak penuh untuk mengarungi samudera waktu, memetik kebahagiaan di setiap pelabuhan, dan terus melangkah tanpa rasa takut.",

    visa1Country: "EXP-01 // WONDERLAND",
    visa1Title: "Visa of Innocence & Wonder",
    visa1Date: "ENTRY: MASA KECIL",
    visa1Desc:
      "Masa di mana imajinasi melangit tinggi, tawa mekar tanpa beban, dan setiap sudut dunia tampak penuh keajaiban.",

    visa2Country: "EXP-02 // ADVENTURE",
    visa2Title: "Visa of Courage & Exploration",
    visa2Date: "ENTRY: MASA REMAJA",
    visa2Desc:
      "Keberanian keluar dari zona nyaman, menjajal hal-hal baru, belajar dari kegagalan, dan merajut persahabatan sejati.",

    visa3Country: "EXP-03 // RESILIENCE",
    visa3Title: "Visa of Resilience & Growth",
    visa3Date: "ENTRY: DEWASA AWAL",
    visa3Desc:
      "Mengarungi badai kehidupan dengan keteguhan hati, membuktikan bahwa dirimu jauh lebih tangguh dari yang pernah kau bayangkan.",

    visa4Country: "EXP-04 // FUTURE VOYAGE",
    visa4Title: "Visa of Wisdom & New Horizon",
    visa4Date: "ENTRY: BABAK BARU",
    visa4Desc:
      "Memasuki babak baru dengan kebijaksanaan yang matang, ketenangan batin, dan optimisme tak terbatas menyongsong masa depan.",

    letterTitle: "Warkat Diplomatik: Catatan Terindah Bagi Rekan Seperjalanan",
    letterContent:
      "Kepada sang penjelajah luar biasa yang hari ini merayakan ulang tahunnya,\n\nHidup ini sejatinya adalah ekspedisi panjang yang penuh tikungan tak terduga, panorama menakjubkan, dan kadang kala cuaca berkabut yang menguji kesabaran. Namun memiliki seseorang sepertimu—yang senantiasa memancarkan kehangatan, kebaikan tulus, dan senyuman yang menyinari jalan—membuat setiap mil perjalanan terasa begitu berharga.\n\nMelihatmu tumbuh menapaki babak usia ke-25 adalah kehormatan tersendiri. Terima kasih telah menjadi teman berbagi tawa yang paling tulus, tempat berteduh di kala badai melanda, dan sosok yang tak pernah lelah menyebarkan energi positif kepada siapa pun di sekitarmu.\n\nDi babak baru ini, kiranya semesta membuka gerbang-gerbang petualangan terindah, menjauhkanmu dari segala marabahaya, dan menuntun langkah kakimu menuju destinasi impian yang paling kau dambakan. Selamat ulang tahun, sang pengelana sejati!",
    senderName: "Arya Bimasakti",
    senderTitle: "Chief of Expedition // Sahabat Seperjalanan Seumur Hidup",

    postcard1Photo:
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=80",
    postcard1Location: "Kala Menatap Senja di Sudut Kota",
    postcard1Date: "Postmark // 14 Juli 2024",
    postcard1Note:
      "Secangkir kopi hangat, hembusan angin sejuk sore hari, dan percakapan panjang yang tak pernah kehabisan topik menyenangkan.",

    postcard2Photo:
      "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80",
    postcard2Location: "Puncak Bukit Penuh Gelak Tawa",
    postcard2Date: "Postmark // 28 Desember 2024",
    postcard2Note:
      "Tawa renyahmu di tengah lelahnya mendaki adalah bukti nyata bahwa kebahagiaan paling murni ada dalam kesederhanaan bersama.",

    postcard3Photo:
      "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1200&q=80",
    postcard3Location: "Malam Perayaan Penuh Kenangan",
    postcard3Date: "Postmark // 05 Mei 2025",
    postcard3Note:
      "Momen ketika kita tersadar bahwa apa pun yang terjadi di dunia luar, kita selalu memiliki tempat yang hangat untuk pulang.",

    flightNumber: "AERO-BDAY25",
    seatNumber: "01A FIRST CLASS",
    departureChapter: "CHAPTER 24 (PASSED WITH GLORY)",
    arrivalChapter: "CHAPTER 25 (LIMITLESS JOY)",

    wish1Title: "Clear Skies: Ketenangan Jiwa",
    wish1Desc: "Semoga langit batinmu selalu dinaungi ketenangan dan bebas dari kabut kecemasan.",

    wish2Title: "Smooth Flight: Ketangguhan Batin",
    wish2Desc: "Setiap riak tantangan di masa depan dapat kau lalui dengan senyuman dan kepala tegak.",

    wish3Title: "First-Class Fortune: Kelimpahan Berkah",
    wish3Desc: "Pintu-pintu rezeki, karier, dan karya cemerlang terbuka lebar dalam babak usiamu saat ini.",

    wish4Title: "Golden Haven: Kasih yang Tulus",
    wish4Desc: "Selalu dipertemukan dengan orang-orang berhati tulus yang menyayangi dan menjagamu apa adanya.",

    primaryColor: "#0f1e36",
    accentColor: "#d4af37",
    backgroundColor: "#f1ede4",
    paperColor: "#faf8f2",
    textColor: "#1b2533",
    musicTitle: "In-Flight Bossa & Acoustic Voyage",
    musicUrl:
      "https://cdn.pixabay.com/download/audio/2022/05/16/audio_db6591201e.mp3?filename=acoustic-guitars-ambient-111163.mp3",
  },
};
