import type { TemplateMeta } from "../types";
import {
  MIXTAPE_COLOR_PRESETS,
  BACKGROUND_COLOR_PRESETS,
  CARD_COLOR_PRESETS,
  TEXT_COLOR_PRESETS,
} from "../color-presets";

export const loveMixtapeTemplate: TemplateMeta = {
  slug: "love-mixtape",
  name: "Retro Love Mixtape & Cassette",
  category: "Romansa",
  tagline:
    "Kaset pita cinta analog 90-an — roda kaset berputar, tracklist lagu kenangan, dan surat cinta di dalam sleeve kaset.",
  description:
    "Pengalaman berkirim pesan cinta bergaya kaset pita mixtape retro tahun 90-an. Menampilkan kaset fisik interaktif dengan roda pita berputar saat lagu dimainkan, label tulisan tangan spidol personal, tracklist lagu penuh kenangan berdua, dan lembaran surat cinta yang terlipat rapi di dalam sleeve kaset.",
  cardAccent: "bg-amber-50 text-amber-900 ring-1 ring-amber-300",
  highlights: [
    "Fisik kaset pita analog dengan roda pita berputar (Spinning Tape Reels)",
    "Stiker label kaset tulisan spidol personal",
    "Tracklist lagu kenangan berdua beserta cerita di balik lagunya",
    "Lipatan sleeve kaset (J-Card Sleeve) berisi surat cinta panjang",
    "Memo tulisan tangan manis di sisi belakang kaset",
    "Pemutar audio bergaya pemutar kaset analog vintage",
  ],
  fields: [
    // --- SECTION: IDENTITAS & LABEL KASET ---
    {
      name: "recipientName",
      label: "Nama kekasih (penerima)",
      type: "text",
      placeholder: "Nadia Safitri",
      required: true,
      maxLength: 60,
      isRecipient: true,
      section: "cassette",
    },
    {
      name: "senderName",
      label: "Nama kamu (pengirim)",
      type: "text",
      placeholder: "Dimas Anggara",
      required: true,
      maxLength: 60,
      section: "cassette",
    },
    {
      name: "tapeTitle",
      label: "Judul mixtape di label kaset",
      type: "text",
      placeholder: "Songs That Feel Like You • Vol. 1",
      maxLength: 80,
      helperText: "Judul yang tertulis pada stiker label kaset pita.",
      section: "cassette",
    },
    {
      name: "releaseYear",
      label: "Tahun / Edisi kaset",
      type: "text",
      placeholder: "Est. 2022 • Special Edition",
      maxLength: 40,
      section: "cassette",
    },
    {
      name: "sideLabel",
      label: "Label sisi kaset",
      type: "text",
      placeholder: "SIDE A • FOR YOUR EARS ONLY",
      maxLength: 40,
      section: "cassette",
    },
    {
      name: "totalDuration",
      label: "Total durasi mixtape",
      type: "text",
      placeholder: "Side A: 24 Menit • 3 Lagu Penuh Cinta",
      maxLength: 50,
      helperText: "Keterangan durasi pemutaran pita kaset.",
      section: "cassette",
    },
    {
      name: "albumCoverPhotoUrl",
      label: "Foto sampul album kaset (Mixtape Artwork)",
      type: "text",
      placeholder:
        "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=800&q=80",
      maxLength: 1000,
      helperText: "Foto romantis berdua sebagai artwork sampul album kaset mixtape.",
      section: "cassette",
    },

    // --- SECTION: FOTO KENANGAN & LIRIK FAVORIT ---
    {
      name: "sleeveMemoryPhotoUrl",
      label: "Foto polaroid di lipatan sleeve kaset",
      type: "text",
      placeholder:
        "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=1000&q=80",
      maxLength: 1000,
      helperText: "Foto cetak kenangan yang terselip di dalam lipatan kertas sleeve kaset.",
      section: "memories",
    },
    {
      name: "sleevePhotoCaption",
      label: "Keterangan foto sleeve kaset",
      type: "text",
      placeholder: "Tawa kita di sore itu, terselip selamanya di antara pita kenangan.",
      maxLength: 120,
      section: "memories",
    },
    {
      name: "favoriteLyric",
      label: "Kutipan lirik lagu cinta favorit",
      type: "text",
      placeholder: "Kau adalah melodi yang tak pernah bosan kuputar berulang kali di kepalaku.",
      maxLength: 200,
      section: "memories",
    },

    // --- SECTION: SURAT SLEEVE KASET (J-CARD) ---
    {
      name: "title",
      label: "Judul surat di dalam sleeve",
      type: "text",
      placeholder: "Catatan Dari Balik Pita Magnetik",
      required: true,
      maxLength: 100,
      section: "letter",
    },
    {
      name: "introMessage",
      label: "Pengantar surat",
      type: "text",
      placeholder: "Untuk seseorang yang melodi tawanya selalu memenuhi kepalaku,",
      maxLength: 120,
      section: "letter",
    },
    {
      name: "message",
      label: "Isi surat cinta",
      type: "textarea",
      placeholder:
        "Tuliskan surat cintamu di sini...\n\nPisahkan setiap paragraf dengan baris kosong agar format lipatan sleeve rapi.",
      required: true,
      maxLength: 4000,
      rows: 10,
      section: "letter",
    },
    {
      name: "closingStatement",
      label: "Kalimat penutup",
      type: "text",
      placeholder: "Selalu memutar kenangan tentangmu,",
      maxLength: 80,
      section: "letter",
    },
    {
      name: "signature",
      label: "Tanda tangan",
      type: "text",
      placeholder: "Dimas Anggara",
      maxLength: 60,
      section: "letter",
    },

    // --- SECTION: TRACKLIST LAGU KENANGAN ---
    {
      name: "tracklistTitle",
      label: "Judul seksi tracklist",
      type: "text",
      placeholder: "Daftar Lagu di Balik Kisah Kita",
      maxLength: 80,
      section: "tracks",
    },
    {
      name: "track1Title",
      label: "Lagu 1: Judul lagu & artis",
      type: "text",
      placeholder: "Track 01: Reality Club — Anything You Want",
      maxLength: 100,
      section: "tracks",
    },
    {
      name: "track1Meaning",
      label: "Lagu 1: Cerita & makna kenangan",
      type: "text",
      placeholder: "Lagu yang kita dengarkan berdua saat pertama kali terjebak hujan bersama di mobil.",
      maxLength: 180,
      section: "tracks",
    },
    {
      name: "track2Title",
      label: "Lagu 2: Judul lagu & artis",
      type: "text",
      placeholder: "Track 02: Sheila On 7 — Anugerah Terindah yang Pernah Kumiliki",
      maxLength: 100,
      section: "tracks",
    },
    {
      name: "track2Meaning",
      label: "Lagu 2: Cerita & makna kenangan",
      type: "text",
      placeholder: "Lirik yang selalu mengingatkanku betapa bersyukurnya aku bisa memilikimu.",
      maxLength: 180,
      section: "tracks",
    },
    {
      name: "track3Title",
      label: "Lagu 3: Judul lagu & artis",
      type: "text",
      placeholder: "Track 03: Danilla — Senja di Ambang Pilu",
      maxLength: 100,
      section: "tracks",
    },
    {
      name: "track3Meaning",
      label: "Lagu 3: Cerita & makna kenangan",
      type: "text",
      placeholder: "Melodi tenang yang selalu kita dengarkan saat duduk berdua menikmati senja sore.",
      maxLength: 180,
      section: "tracks",
    },

    // --- SECTION: CATATAN TAMBAHAN (INLAY NOTE) ---
    {
      name: "handwrittenNote",
      label: "Memo catatan tulisan tangan (belakang kaset)",
      type: "textarea",
      placeholder:
        "P.S. Jika kaset ini kusut, putar rodanya dengan bolpoin. Tapi cintaku padamu takkan pernah kusut selamanya :)",
      maxLength: 300,
      rows: 2,
      section: "note",
    },

    // --- SECTION: TEMA & MUSIK ---
    {
      name: "primaryColor",
      label: "Warna bodi kaset pita",
      type: "color",
      defaultValue: "#e15b64",
      helperText: "Warna plastik bodi kaset dan tombol retro.",
      colorPresets: MIXTAPE_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "backgroundColor",
      label: "Warna latar belakang halaman",
      type: "color",
      defaultValue: "#fbf8f3",
      helperText: "Warna kanvas di luar kaset.",
      colorPresets: BACKGROUND_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "cardColor",
      label: "Warna kertas sleeve (J-Card)",
      type: "color",
      defaultValue: "#ffffff",
      helperText: "Warna lembaran surat sleeve kaset.",
      colorPresets: CARD_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "textColor",
      label: "Warna teks judul",
      type: "color",
      defaultValue: "#27272a",
      helperText: "Warna teks judul surat dan label kaset.",
      colorPresets: TEXT_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "bodyTextColor",
      label: "Warna teks isi surat",
      type: "color",
      defaultValue: "#4b5563",
      helperText: "Warna tulisan paragraf surat.",
      colorPresets: TEXT_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "musicTitle",
      label: "Judul audio kaset (opsional)",
      type: "text",
      placeholder: "Anything You Want (Acoustic Tape)",
      maxLength: 80,
      section: "theme",
    },
    {
      name: "bgMusicUrl",
      label: "Tautan audio kaset (.mp3)",
      type: "text",
      placeholder: "https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a73467.mp3",
      maxLength: 1000,
      helperText: "Tautan langsung ke file audio mp3 yang diputar oleh kaset.",
      section: "theme",
    },
  ],
  sample: {
    recipientName: "Nadia Safitri",
    senderName: "Dimas Anggara",
    tapeTitle: "Songs That Feel Like You • Vol. 1",
    releaseYear: "Est. 2022 • Special Edition",
    sideLabel: "SIDE A • FOR YOUR EARS ONLY",
    totalDuration: "Side A: 24 Menit • 3 Lagu Penuh Cinta",
    albumCoverPhotoUrl:
      "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=800&q=80",
    sleeveMemoryPhotoUrl:
      "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=1000&q=80",
    sleevePhotoCaption: "Tawa kita di sore itu, terselip selamanya di antara pita kenangan.",
    favoriteLyric:
      "Kau adalah melodi yang tak pernah bosan kuputar berulang kali di kepalaku.",
    title: "Catatan Dari Balik Pita Magnetik",
    introMessage: "Untuk seseorang yang melodi tawanya selalu memenuhi kepalaku,",
    message:
      "Nadia,\n\nKatanya, orang-orang di masa lalu merekam mixtape untuk orang yang paling mereka cintai—karena memilih lagu dan menyusunnya satu per satu butuh waktu, perhatian, dan ketulusan hati. Kaset digital ini adalah caraku merangkum apa yang kurasakan padamu.\n\nSetiap melodi yang ada di sini punya jejak tawamu, caramu memiringkan kepala saat berpikir, dan bagaimana caramu menggenggam tanganku erat saat kita menyeberang jalan. Bersamamu, hidup yang terkadang bising ini terasa seperti lagu favorit yang tak pernah ingin kuhentikan.\n\nTerima kasih telah mewarnai hari-hariku dengan harmoni yang begitu indah. Kaset ini milikmu, selamanya.",
    closingStatement: "Selalu memutar kenangan tentangmu,",
    signature: "Dimas Anggara",
    tracklistTitle: "Daftar Lagu di Balik Kisah Kita",
    track1Title: "Track 01: Reality Club — Anything You Want",
    track1Meaning: "Lagu yang kita dengarkan berdua saat pertama kali terjebak hujan bersama di mobil.",
    track2Title: "Track 02: Sheila On 7 — Anugerah Terindah yang Pernah Kumiliki",
    track2Meaning: "Lirik yang selalu mengingatkanku betapa bersyukurnya aku bisa memilikimu dalam hidupku.",
    track3Title: "Track 03: Danilla — Senja di Ambang Pilu",
    track3Meaning: "Melodi tenang yang selalu kita dengarkan saat duduk berdua menikmati senja sore di kedai kopi.",
    handwrittenNote:
      "P.S. Jika kaset ini kusut, putar rodanya dengan bolpoin. Tapi cintaku padamu takkan pernah kusut selamanya :)",
    primaryColor: "#e15b64",
    backgroundColor: "#fbf8f3",
    cardColor: "#ffffff",
    textColor: "#27272a",
    bodyTextColor: "#4b5563",
    musicTitle: "Anything You Want (Acoustic Tape)",
    bgMusicUrl: "https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a73467.mp3",
  },
};
