import type { TemplateMeta } from "../types";
import {
  MIXTAPE_COLOR_PRESETS,
  BACKGROUND_COLOR_PRESETS,
  CARD_COLOR_PRESETS,
  TEXT_COLOR_PRESETS,
} from "../color-presets";

export const loveMixtapeTemplate: TemplateMeta = {
  slug: "love-mixtape",
  name: "Retro Love Mixtape & Cassette",
  category: "Romansa",
  tagline:
    "Kaset pita analog 90-an — fitur bolak-balik Side A/B, visualizer equalizer, 6 tracklist kenangan, galeri polaroid, dan pesan rahasia tersembunyi.",
  description:
    "Pengalaman berkirim surat cinta paling otentik bergaya kaset pita mixtape retro tahun 90-an. Dilengkapi dengan bodi kaset interaktif yang bisa dibolak-balik (Side A & Side B), roda pita berputar dengan visualizer equalizer, live tape counter durasi cinta, tracklist lengkap 6 lagu kenangan, 3 lembar foto polaroid berselotip vintage, booklet lirik lagu favorit, hingga pesan tersembunyi (hidden track) yang penuh kejutan romantis.",
  cardAccent: "bg-amber-50 text-amber-900 ring-1 ring-amber-300",
  highlights: [
    "Fisik kaset pita analog bolak-balik Side A & Side B interaktif",
    "Roda kaset berputar (Spinning Reels) & spektrum audio equalizer animasi",
    "Kalkulator durasi pita cinta real-time (Magnetic Tape Love Counter)",
    "Tracklist lengkap 6 lagu kenangan berdua (Side A Classics & Side B Acoustic)",
    "Galeri 3 foto polaroid dengan aksen selotip vintage dan catatan kenangan",
    "Booklet lirik lagu favorit & pesan rahasia tersembunyi (Hidden Bonus Track)",
    "Lipatan sleeve kaset J-Card panjang dengan memo tulisan tangan",
  ],
  fields: [
    // --- SECTION: IDENTITAS & LABEL KASET ---
    {
      name: "recipientName",
      label: "Nama kekasih (penerima)",
      type: "text",
      placeholder: "Nadia Safitri",
      required: true,
      maxLength: 60,
      isRecipient: true,
      section: "cassette",
    },
    {
      name: "senderName",
      label: "Nama kamu (pengirim)",
      type: "text",
      placeholder: "Dimas Anggara",
      required: true,
      maxLength: 60,
      section: "cassette",
    },
    {
      name: "tapeTitle",
      label: "Judul mixtape di label kaset",
      type: "text",
      placeholder: "Songs That Feel Like You • Vol. 1",
      maxLength: 80,
      helperText: "Judul yang tertulis pada stiker label kaset pita.",
      section: "cassette",
    },
    {
      name: "anniversaryDate",
      label: "Tanggal jadian / momen spesial (opsional)",
      type: "text",
      placeholder: "2022-10-14",
      maxLength: 30,
      helperText: "Format: YYYY-MM-DD. Menghitung durasi cinta yang terekam pada pita kaset secara live.",
      section: "cassette",
    },
    {
      name: "releaseYear",
      label: "Tahun / Edisi kaset",
      type: "text",
      placeholder: "Est. 2022 • Special Edition",
      maxLength: 40,
      section: "cassette",
    },
    {
      name: "sideLabel",
      label: "Label Sisi A kaset",
      type: "text",
      placeholder: "SIDE A • FOR YOUR EARS ONLY",
      maxLength: 40,
      section: "cassette",
    },
    {
      name: "totalDuration",
      label: "Total durasi mixtape",
      type: "text",
      placeholder: "Side A & B: 48 Menit • 6 Lagu Penuh Cinta",
      maxLength: 50,
      helperText: "Keterangan durasi pemutaran pita kaset.",
      section: "cassette",
    },
    {
      name: "albumCoverPhotoUrl",
      label: "Foto sampul album kaset (Mixtape Artwork)",
      type: "text",
      placeholder:
        "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=800&q=80",
      maxLength: 1000,
      helperText: "Foto romantis berdua sebagai artwork sampul album kaset mixtape.",
      section: "cassette",
    },

    // --- SECTION: SURAT SLEEVE KASET (J-CARD) ---
    {
      name: "title",
      label: "Judul surat di dalam sleeve",
      type: "text",
      placeholder: "Catatan Dari Balik Pita Magnetik",
      required: true,
      maxLength: 100,
      section: "letter",
    },
    {
      name: "introMessage",
      label: "Pengantar surat",
      type: "text",
      placeholder: "Untuk seseorang yang melodi tawanya selalu memenuhi kepalaku,",
      maxLength: 120,
      section: "letter",
    },
    {
      name: "message",
      label: "Isi surat cinta",
      type: "textarea",
      placeholder:
        "Tuliskan surat cintamu di sini...\n\nPisahkan setiap paragraf dengan baris kosong agar format lipatan sleeve rapi.",
      required: true,
      maxLength: 4000,
      rows: 10,
      section: "letter",
    },
    {
      name: "closingStatement",
      label: "Kalimat penutup",
      type: "text",
      placeholder: "Selalu memutar kenangan tentangmu,",
      maxLength: 80,
      section: "letter",
    },
    {
      name: "signature",
      label: "Tanda tangan",
      type: "text",
      placeholder: "Dimas Anggara",
      maxLength: 60,
      section: "letter",
    },

    // --- SECTION: TRACKLIST LAGU KENANGAN (SIDE A & SIDE B) ---
    {
      name: "tracklistTitle",
      label: "Judul seksi tracklist",
      type: "text",
      placeholder: "Daftar Lagu di Balik Kisah Kita",
      maxLength: 80,
      section: "tracks",
    },
    {
      name: "track1Title",
      label: "Lagu 1 (Side A): Judul lagu & artis",
      type: "text",
      placeholder: "Track 01: Reality Club — Anything You Want",
      maxLength: 100,
      section: "tracks",
    },
    {
      name: "track1Meaning",
      label: "Lagu 1: Cerita & makna kenangan",
      type: "text",
      placeholder: "Lagu yang kita dengarkan berdua saat pertama kali terjebak hujan bersama di mobil.",
      maxLength: 180,
      section: "tracks",
    },
    {
      name: "track2Title",
      label: "Lagu 2 (Side A): Judul lagu & artis",
      type: "text",
      placeholder: "Track 02: Sheila On 7 — Anugerah Terindah yang Pernah Kumiliki",
      maxLength: 100,
      section: "tracks",
    },
    {
      name: "track2Meaning",
      label: "Lagu 2: Cerita & makna kenangan",
      type: "text",
      placeholder: "Lirik yang selalu mengingatkanku betapa bersyukurnya aku bisa memilikimu.",
      maxLength: 180,
      section: "tracks",
    },
    {
      name: "track3Title",
      label: "Lagu 3 (Side A): Judul lagu & artis",
      type: "text",
      placeholder: "Track 03: Danilla — Senja di Ambang Pilu",
      maxLength: 100,
      section: "tracks",
    },
    {
      name: "track3Meaning",
      label: "Lagu 3: Cerita & makna kenangan",
      type: "text",
      placeholder: "Melodi tenang yang selalu kita dengarkan saat duduk berdua menikmati senja sore.",
      maxLength: 180,
      section: "tracks",
    },
    {
      name: "sideBTitle",
      label: "Label Sisi B kaset",
      type: "text",
      placeholder: "SIDE B • ACOUSTIC & HIDDEN GEMS",
      maxLength: 60,
      section: "tracks",
    },
    {
      name: "track4Title",
      label: "Lagu 4 (Side B): Judul lagu & artis",
      type: "text",
      placeholder: "Track 04: Kings of Convenience — Cayman Islands",
      maxLength: 100,
      section: "tracks",
    },
    {
      name: "track4Meaning",
      label: "Lagu 4: Cerita & makna kenangan",
      type: "text",
      placeholder: "Lagu pengantar tidur ketika kita saling bercerita lewat telepon hingga larut.",
      maxLength: 180,
      section: "tracks",
    },
    {
      name: "track5Title",
      label: "Lagu 5 (Side B): Judul lagu & artis",
      type: "text",
      placeholder: "Track 05: Maliq & D'Essentials — Kita Bikin Romantis",
      maxLength: 100,
      section: "tracks",
    },
    {
      name: "track5Meaning",
      label: "Lagu 5: Cerita & makna kenangan",
      type: "text",
      placeholder: "Tentang hal-hal kecil sederhana: sarapan berdua dan caramu tersenyum.",
      maxLength: 180,
      section: "tracks",
    },
    {
      name: "track6Title",
      label: "Lagu 6 (Side B): Judul lagu & artis",
      type: "text",
      placeholder: "Track 06: Pamungkas — To The Bone",
      maxLength: 100,
      section: "tracks",
    },
    {
      name: "track6Meaning",
      label: "Lagu 6: Cerita & makna kenangan",
      type: "text",
      placeholder: "Karena sejak hari itu, tak ada lagi yang bisa menggantikan posisimu di hatiku.",
      maxLength: 180,
      section: "tracks",
    },

    // --- SECTION: FOTO POLAROID & LIRIK FAVORIT ---
    {
      name: "sleeveMemoryPhotoUrl",
      label: "Foto polaroid 1 di sleeve kaset",
      type: "text",
      placeholder:
        "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=1000&q=80",
      maxLength: 1000,
      helperText: "Foto cetak kenangan pertama yang terselip di dalam lipatan kertas sleeve kaset.",
      section: "memories",
    },
    {
      name: "sleevePhotoCaption",
      label: "Keterangan foto polaroid 1",
      type: "text",
      placeholder: "Tawa kita di sore itu, terselip selamanya di antara pita kenangan.",
      maxLength: 120,
      section: "memories",
    },
    {
      name: "photo2Url",
      label: "Foto polaroid 2 di sleeve kaset",
      type: "text",
      placeholder:
        "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=1000&q=80",
      maxLength: 1000,
      helperText: "Foto kenangan kedua yang mempercantik galeri sleeve kaset.",
      section: "memories",
    },
    {
      name: "photo2Caption",
      label: "Keterangan foto polaroid 2",
      type: "text",
      placeholder: "Kala itu kita tertawa lepas tanpa peduli waktu terus berputar.",
      maxLength: 120,
      section: "memories",
    },
    {
      name: "photo3Url",
      label: "Foto polaroid 3 di sleeve kaset",
      type: "text",
      placeholder:
        "https://images.unsplash.com/photo-1513279922550-250c2129b13a?auto=format&fit=crop&w=1000&q=80",
      maxLength: 1000,
      helperText: "Foto kenangan ketiga yang melengkapi lembaran cinta kalian.",
      section: "memories",
    },
    {
      name: "photo3Caption",
      label: "Keterangan foto polaroid 3",
      type: "text",
      placeholder: "Senja di pelataran stasiun saat kau tersenyum menatap mataku.",
      maxLength: 120,
      section: "memories",
    },
    {
      name: "lyricSongTitle",
      label: "Judul lagu untuk lirik favorit",
      type: "text",
      placeholder: "Reality Club — Anything You Want",
      maxLength: 80,
      section: "memories",
    },
    {
      name: "favoriteLyric",
      label: "Kutipan lirik lagu cinta favorit",
      type: "text",
      placeholder: "Kau adalah melodi yang tak pernah bosan kuputar berulang kali di kepalaku.",
      maxLength: 250,
      section: "memories",
    },

    // --- SECTION: PESAN RAHASIA & CATATAN TAMBAHAN ---
    {
      name: "secretDedication",
      label: "Pesan rahasia tersembunyi (Hidden Bonus Track)",
      type: "textarea",
      placeholder:
        "Bonus Track: Kalau kamu membaca sampai bagian tersembunyi ini, terima kasih sudah menjadi tempat ternyaman untuk pulang. Peluk aku saat kita bertemu nanti, ya!",
      maxLength: 400,
      rows: 3,
      helperText: "Pesan tersembunyi yang dapat dibuka di sisi kaset Side B.",
      section: "note",
    },
    {
      name: "handwrittenNote",
      label: "Memo catatan tulisan tangan (belakang kaset)",
      type: "textarea",
      placeholder:
        "P.S. Jika kaset ini kusut, putar rodanya dengan bolpoin. Tapi cintaku padamu takkan pernah kusut selamanya :)",
      maxLength: 300,
      rows: 2,
      section: "note",
    },

    // --- SECTION: TEMA & MUSIK ---
    {
      name: "primaryColor",
      label: "Warna bodi kaset pita",
      type: "color",
      defaultValue: "#e15b64",
      helperText: "Warna plastik bodi kaset dan tombol retro.",
      colorPresets: MIXTAPE_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "backgroundColor",
      label: "Warna latar belakang halaman",
      type: "color",
      defaultValue: "#fbf8f3",
      helperText: "Warna kanvas di luar kaset.",
      colorPresets: BACKGROUND_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "cardColor",
      label: "Warna kertas sleeve (J-Card)",
      type: "color",
      defaultValue: "#ffffff",
      helperText: "Warna lembaran surat sleeve kaset.",
      colorPresets: CARD_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "textColor",
      label: "Warna teks judul",
      type: "color",
      defaultValue: "#27272a",
      helperText: "Warna teks judul surat dan label kaset.",
      colorPresets: TEXT_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "bodyTextColor",
      label: "Warna teks isi surat",
      type: "color",
      defaultValue: "#4b5563",
      helperText: "Warna tulisan paragraf surat.",
      colorPresets: TEXT_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "musicTitle",
      label: "Judul audio kaset (opsional)",
      type: "text",
      placeholder: "Anything You Want (Acoustic Tape)",
      maxLength: 80,
      section: "theme",
    },
    {
      name: "bgMusicUrl",
      label: "Tautan audio kaset (.mp3)",
      type: "text",
      placeholder: "",
      maxLength: 1000,
      helperText: "Pilih file audio dari perangkat Anda atau biarkan kosong jika tanpa musik.",
      section: "theme",
    },
  ],
  sample: {
    recipientName: "Nadia Safitri",
    senderName: "Dimas Anggara",
    tapeTitle: "Songs That Feel Like You • Vol. 1",
    anniversaryDate: "2022-10-14",
    releaseYear: "Est. 2022 • Special Edition",
    sideLabel: "SIDE A • FOR YOUR EARS ONLY",
    sideBTitle: "SIDE B • ACOUSTIC & HIDDEN GEMS",
    totalDuration: "Side A & B: 48 Menit • 6 Lagu Penuh Cinta",
    albumCoverPhotoUrl:
      "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=800&q=80",
    sleeveMemoryPhotoUrl:
      "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=1000&q=80",
    sleevePhotoCaption: "Tawa kita di sore itu, terselip selamanya di antara pita kenangan.",
    photo2Url:
      "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=1000&q=80",
    photo2Caption: "Kala itu kita tertawa lepas tanpa peduli waktu terus berputar.",
    photo3Url:
      "https://images.unsplash.com/photo-1513279922550-250c2129b13a?auto=format&fit=crop&w=1000&q=80",
    photo3Caption: "Senja di pelataran stasiun saat kau tersenyum menatap mataku.",
    lyricSongTitle: "Reality Club — Anything You Want",
    favoriteLyric:
      "Kau adalah melodi yang tak pernah bosan kuputar berulang kali di kepalaku, selamanya.",
    title: "Catatan Dari Balik Pita Magnetik",
    introMessage: "Untuk seseorang yang melodi tawanya selalu memenuhi kepalaku,",
    message:
      "Nadia,\n\nKatanya, orang-orang di masa lalu merekam mixtape untuk orang yang paling mereka cintai—karena memilih lagu dan menyusunnya satu per satu butuh waktu, perhatian, dan ketulusan hati. Kaset digital ini adalah caraku merangkum apa yang kurasakan padamu.\n\nSetiap melodi yang ada di sini punya jejak tawamu, caramu memiringkan kepala saat berpikir, dan bagaimana caramu menggenggam tanganku erat saat kita menyeberang jalan. Bersamamu, hidup yang terkadang bising ini terasa seperti lagu favorit yang tak pernah ingin kuhentikan.\n\nTerima kasih telah mewarnai hari-hariku dengan harmoni yang begitu indah. Kaset ini milikmu, selamanya.",
    closingStatement: "Selalu memutar kenangan tentangmu,",
    signature: "Dimas Anggara",
    tracklistTitle: "Daftar Lagu di Balik Kisah Kita",
    track1Title: "Track 01: Reality Club — Anything You Want",
    track1Meaning: "Lagu yang kita dengarkan berdua saat pertama kali terjebak hujan bersama di mobil.",
    track2Title: "Track 02: Sheila On 7 — Anugerah Terindah yang Pernah Kumiliki",
    track2Meaning: "Lirik yang selalu mengingatkanku betapa bersyukurnya aku bisa memilikimu dalam hidupku.",
    track3Title: "Track 03: Danilla — Senja di Ambang Pilu",
    track3Meaning: "Melodi tenang yang selalu kita dengarkan saat duduk berdua menikmati senja sore di kedai kopi.",
    track4Title: "Track 04: Kings of Convenience — Cayman Islands",
    track4Meaning: "Lagu pengantar tidur ketika kita saling bercerita lewat telepon hingga larut malam.",
    track5Title: "Track 05: Maliq & D'Essentials — Kita Bikin Romantis",
    track5Meaning: "Tentang hal-hal kecil sederhana: sarapan berdua dan caramu tertawa tersipu.",
    track6Title: "Track 06: Pamungkas — To The Bone",
    track6Meaning: "Karena sejak hari pertama bertemu, tak ada lagi yang bisa menggantikan posisimu di hatiku.",
    secretDedication:
      "Bonus Track: Kalau kamu membaca sampai bagian tersembunyi ini, terima kasih sudah menjadi tempat ternyaman untuk pulang. Peluk aku saat kita bertemu nanti, ya!",
    handwrittenNote:
      "P.S. Jika kaset ini kusut, putar rodanya dengan bolpoin. Tapi cintaku padamu takkan pernah kusut selamanya :)",
    primaryColor: "#e15b64",
    backgroundColor: "#fbf8f3",
    cardColor: "#ffffff",
    textColor: "#27272a",
    bodyTextColor: "#4b5563",
    musicTitle: "",
    bgMusicUrl: "",
  },
};
