import type { TemplateMeta } from "../types";
import {
  BIRTHDAY_COLOR_PRESETS,
  BACKGROUND_COLOR_PRESETS,
  CARD_COLOR_PRESETS,
  TEXT_COLOR_PRESETS,
} from "../color-presets";

export const birthdayCelebrationTemplate: TemplateMeta = {
  slug: "birthday-celebration",
  name: "Grand Birthday Party & Wish Cake",
  category: "Perayaan",
  tagline:
    "Perayaan ulang tahun murni klasik — kue bolu interaktif tiup lilin dengan efek asap & konfeti, kado kejutan yang bisa dibuka, galeri polaroid, kartu doa, dan surat perayaan menyentuh.",
  description:
    "Template perayaan ulang tahun digital paling otentik, mewah, dan meriah. Menampilkan kue bolu bertingkat dengan lilin yang menyala dan bisa ditiup (menghasilkan suara selebrasi, hujan konfeti, dan pesan rahasia), kotak kado interaktif berpita emas, linimasa milestone usia emas, galeri foto polaroid kenangan, 4 kartu doa & harapan tulus, bucket list impian usia baru, serta surat ucapan mendalam.",
  cardAccent: "bg-rose-50 text-rose-700 ring-1 ring-rose-300",
  highlights: [
    "Kue bolu ulang tahun interaktif dengan lilin menyala & ritual tiup lilin",
    "Efek selebrasi: hujan konfeti, balon pesta melayang, dan audio chimes",
    "Kotak kado kejutan interaktif yang bisa dibuka untuk melihat hadiah/voucher",
    "Statistik usia hidup & linimasa 3 babak pencapaian membanggakan",
    "Galeri 6 foto polaroid kenangan berselotip pesta & lightbox",
    "4 kartu doa terindah & resolusi bucket list di usia baru",
    "Surat ucapan cinta & apresiasi mendalam berstempel perayaan",
  ],
  fields: [
    // --- SECTION: IDENTITAS & PENERIMA ---
    {
      name: "recipientName",
      label: "Nama yang berulang tahun",
      type: "text",
      placeholder: "Clarissa Aurelia",
      required: true,
      maxLength: 60,
      isRecipient: true,
      section: "hero",
    },
    {
      name: "senderName",
      label: "Nama kamu / pengirim ucapan",
      type: "text",
      placeholder: "Arga & Seluruh Keluarga",
      required: true,
      maxLength: 60,
      section: "hero",
    },
    {
      name: "age",
      label: "Usia baru yang dirayakan (Angka)",
      type: "number",
      placeholder: "23",
      required: true,
      section: "hero",
    },
    {
      name: "birthDate",
      label: "Tanggal lahir (YYYY-MM-DD)",
      type: "text",
      placeholder: "2003-10-15",
      maxLength: 30,
      helperText: "Digunakan untuk menghitung jumlah hari penuh tawa dan kebahagiaan.",
      section: "hero",
    },
    {
      name: "heroGreeting",
      label: "Sapaan pembuka perayaan",
      type: "text",
      placeholder: "Happy 23rd Birthday, Sunshine! 🎉",
      maxLength: 80,
      section: "hero",
    },
    {
      name: "heroHeadline",
      label: "Headline perayaan",
      type: "text",
      placeholder: "Merayakan Hadirnya Senyuman Paling Hangat di Dunia",
      maxLength: 100,
      section: "hero",
    },
    {
      name: "heroCoverPhoto",
      label: "Foto potret utama yang berulang tahun",
      type: "text",
      placeholder:
        "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1000&q=80",
      maxLength: 1000,
      helperText: "Foto portrait terbaik yang dipajang di poster perayaan utama.",
      section: "hero",
    },

    // --- SECTION: KUE & RITUAL TIUP LILIN ---
    {
      name: "cakeFlavor",
      label: "Varian rasa kue ulang tahun",
      type: "text",
      placeholder: "Strawberry Sweet Velvet & Chantilly Cream",
      maxLength: 60,
      section: "cake",
    },
    {
      name: "cakeWishPrompt",
      label: "Panduan make a wish sebelum tiup lilin",
      type: "text",
      placeholder: "Tutup matamu sejenak, bisikkan satu permohonan tulus di hati, lalu tiup lilinnya!",
      maxLength: 120,
      section: "cake",
    },
    {
      name: "secretWishMessage",
      label: "Pesan rahasia setelah lilin ditiup",
      type: "textarea",
      placeholder:
        "Semoga di usia yang baru ini, setiap langkahmu selalu dipeluk rasa aman, setiap impian besarmu didekatkan, dan tawamu tak pernah pudar. Selamat bertambah usia, manusia paling berharga! 🎂✨",
      maxLength: 400,
      rows: 3,
      helperText: "Pesan kejutan yang langsung muncul seketika lilin ditiup.",
      section: "cake",
    },

    // --- SECTION: KOTAK KADO KEJUTAN ---
    {
      name: "giftBoxTitle",
      label: "Judul hadiah / voucher kejutan",
      type: "text",
      placeholder: "Tiket Liburan Berdua & Dinner Spesial Favoritmu 🎁",
      maxLength: 80,
      section: "gift",
    },
    {
      name: "giftBoxMessage",
      label: "Pesan isi kotak kado",
      type: "textarea",
      placeholder:
        "Kado ini mungkin sederhana, tapi disiapkan dengan seluruh cinta. Weekend ini, kita luangkan waktu seharian penuh untuk melakukan hal-hal yang paling kamu sukai tanpa gangguan apapun!",
      maxLength: 350,
      rows: 3,
      section: "gift",
    },
    {
      name: "giftBoxCode",
      label: "Kode kado / voucher traktiran (opsional)",
      type: "text",
      placeholder: "CLARISSA-SWEET23-TREAT",
      maxLength: 40,
      section: "gift",
    },

    // --- SECTION: MILESTONE & BABAK KEHIDUPAN ---
    {
      name: "milestoneTitle",
      label: "Judul seksi linimasa kehidupan",
      type: "text",
      placeholder: "Tiga Babak Indah Menuju Usia Kedewasaan",
      maxLength: 80,
      section: "milestone",
    },
    {
      name: "milestone1Year",
      label: "Tahun milestone 1",
      type: "text",
      placeholder: "2021",
      maxLength: 20,
      section: "milestone",
    },
    {
      name: "milestone1Title",
      label: "Judul milestone 1",
      type: "text",
      placeholder: "Langkah Berani Memulai Mimpi Baru",
      maxLength: 80,
      section: "milestone",
    },
    {
      name: "milestone1Desc",
      label: "Cerita milestone 1",
      type: "text",
      placeholder: "Saat kamu berani keluar dari zona nyaman dan membuktikan ketangguhan dirimu.",
      maxLength: 180,
      section: "milestone",
    },
    {
      name: "milestone2Year",
      label: "Tahun milestone 2",
      type: "text",
      placeholder: "2024",
      maxLength: 20,
      section: "milestone",
    },
    {
      name: "milestone2Title",
      label: "Judul milestone 2",
      type: "text",
      placeholder: "Pencapaian Besar & Karya Membanggakan",
      maxLength: 80,
      section: "milestone",
    },
    {
      name: "milestone2Desc",
      label: "Cerita milestone 2",
      type: "text",
      placeholder: "Menuntaskan tanggung jawab besar dengan senyuman puas dan apresiasi dari banyak orang.",
      maxLength: 180,
      section: "milestone",
    },
    {
      name: "milestone3Year",
      label: "Tahun milestone 3",
      type: "text",
      placeholder: "2026",
      maxLength: 20,
      section: "milestone",
    },
    {
      name: "milestone3Title",
      label: "Judul milestone 3",
      type: "text",
      placeholder: "Menyambut Era Emas yang Gemilang",
      maxLength: 80,
      section: "milestone",
    },
    {
      name: "milestone3Desc",
      label: "Cerita milestone 3",
      type: "text",
      placeholder: "Memasuki babak baru dengan hati yang lebih tenang, bijaksana, dan penuh keyakinan.",
      maxLength: 180,
      section: "milestone",
    },

    // --- SECTION: GALERI FOTO POLAROID (6 FOTO) ---
    {
      name: "galleryPhoto1",
      label: "Foto polaroid 1",
      type: "text",
      placeholder:
        "https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=800&q=80",
      maxLength: 1000,
      section: "gallery",
    },
    {
      name: "galleryCaption1",
      label: "Keterangan foto 1",
      type: "text",
      placeholder: "Tawa renyah saat perayaan kejutan kecil",
      maxLength: 80,
      section: "gallery",
    },
    {
      name: "galleryPhoto2",
      label: "Foto polaroid 2",
      type: "text",
      placeholder:
        "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=800&q=80",
      maxLength: 1000,
      section: "gallery",
    },
    {
      name: "galleryCaption2",
      label: "Keterangan foto 2",
      type: "text",
      placeholder: "Momen liburan seru di tepi pantai",
      maxLength: 80,
      section: "gallery",
    },
    {
      name: "galleryPhoto3",
      label: "Foto polaroid 3",
      type: "text",
      placeholder:
        "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80",
      maxLength: 1000,
      section: "gallery",
    },
    {
      name: "galleryCaption3",
      label: "Keterangan foto 3",
      type: "text",
      placeholder: "Menikmati secangkir kopi hangat berdua",
      maxLength: 80,
      section: "gallery",
    },
    {
      name: "galleryPhoto4",
      label: "Foto polaroid 4",
      type: "text",
      placeholder:
        "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=800&q=80",
      maxLength: 1000,
      section: "gallery",
    },
    {
      name: "galleryCaption4",
      label: "Keterangan foto 4",
      type: "text",
      placeholder: "Menyanyi lagu favorit sekuat tenaga",
      maxLength: 80,
      section: "gallery",
    },
    {
      name: "galleryPhoto5",
      label: "Foto polaroid 5",
      type: "text",
      placeholder:
        "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=800&q=80",
      maxLength: 1000,
      section: "gallery",
    },
    {
      name: "galleryCaption5",
      label: "Keterangan foto 5",
      type: "text",
      placeholder: "Senja tenang dengan obrolan masa depan",
      maxLength: 80,
      section: "gallery",
    },
    {
      name: "galleryPhoto6",
      label: "Foto polaroid 6",
      type: "text",
      placeholder:
        "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?auto=format&fit=crop&w=800&q=80",
      maxLength: 1000,
      section: "gallery",
    },
    {
      name: "galleryCaption6",
      label: "Keterangan foto 6",
      type: "text",
      placeholder: "Malam syukuran penuh pelukan hangat",
      maxLength: 80,
      section: "gallery",
    },

    // --- SECTION: KARTU DOA & HARAPAN ---
    {
      name: "wish1Title",
      label: "Doa 1: Judul",
      type: "text",
      placeholder: "Kesehatan Raga & Ketenangan Batin",
      maxLength: 50,
      section: "wishes",
    },
    {
      name: "wish1Desc",
      label: "Doa 1: Isi harapan",
      type: "text",
      placeholder: "Semoga selalu diberikan fisik yang bugar, pikiran yang damai, dan tidur malam yang nyenyak.",
      maxLength: 150,
      section: "wishes",
    },
    {
      name: "wish2Title",
      label: "Doa 2: Judul",
      type: "text",
      placeholder: "Karier Cemerlang & Rezeki Berkah",
      maxLength: 50,
      section: "wishes",
    },
    {
      name: "wish2Desc",
      label: "Doa 2: Isi harapan",
      type: "text",
      placeholder: "Semoga setiap pintu rezeki dan kesempatan emas dibukakan dengan jalan yang mudah dan penuh berkah.",
      maxLength: 150,
      section: "wishes",
    },
    {
      name: "wish3Title",
      label: "Doa 3: Judul",
      type: "text",
      placeholder: "Dikelilingi Orang-Orang Tulus",
      maxLength: 50,
      section: "wishes",
    },
    {
      name: "wish3Desc",
      label: "Doa 3: Isi harapan",
      type: "text",
      placeholder: "Semoga langkahmu selalu dijaga dan dikelilingi oleh sahabat serta keluarga yang menyayangimu apa adanya.",
      maxLength: 150,
      section: "wishes",
    },
    {
      name: "wish4Title",
      label: "Doa 4: Judul",
      type: "text",
      placeholder: "Impian Terbesar Menjadi Nyata",
      maxLength: 50,
      section: "wishes",
    },
    {
      name: "wish4Desc",
      label: "Doa 4: Isi harapan",
      type: "text",
      placeholder: "Semoga cita-cita yang kamu semogakan dalam sujud dan doa diam-diam segera diijabah oleh semesta.",
      maxLength: 150,
      section: "wishes",
    },

    // --- SECTION: BUCKET LIST USIA BARU ---
    {
      name: "bucketList1",
      label: "Bucket list impian 1",
      type: "text",
      placeholder: "Menjelajahi tempat baru yang selama ini tersimpan di wishlist",
      maxLength: 100,
      section: "bucket",
    },
    {
      name: "bucketList2",
      label: "Bucket list impian 2",
      type: "text",
      placeholder: "Menyisihkan waktu santai khusus untuk self-care tanpa beban kerja",
      maxLength: 100,
      section: "bucket",
    },
    {
      name: "bucketList3",
      label: "Bucket list impian 3",
      type: "text",
      placeholder: "Membuat karya baru dan merayakan setiap kemenangan kecil",
      maxLength: 100,
      section: "bucket",
    },

    // --- SECTION: SURAT UCAPAN RESMI ---
    {
      name: "letterTitle",
      label: "Judul surat ucapan",
      type: "text",
      placeholder: "Sebuah Surat Cinta di Hari Kelahiranmu",
      required: true,
      maxLength: 80,
      section: "letter",
    },
    {
      name: "introMessage",
      label: "Pengantar surat",
      type: "text",
      placeholder: "Untuk seseorang yang kehadirannya selalu menjadi hadiah terbaik bagi sekitarnya,",
      maxLength: 120,
      section: "letter",
    },
    {
      name: "message",
      label: "Isi surat ulang tahun utama",
      type: "textarea",
      placeholder:
        "Tuliskan surat ulang tahun yang menyentuh di sini...\n\nPisahkan setiap paragraf dengan baris kosong.",
      required: true,
      maxLength: 4000,
      rows: 10,
      section: "letter",
    },
    {
      name: "closingStatement",
      label: "Kalimat penutup",
      type: "text",
      placeholder: "Dengan pelukan paling hangat & doa tanpa jeda,",
      maxLength: 80,
      section: "letter",
    },
    {
      name: "signature",
      label: "Tanda tangan",
      type: "text",
      placeholder: "Arga Pranata",
      maxLength: 60,
      section: "letter",
    },

    // --- SECTION: WARNA & AUDIO PESTA ---
    {
      name: "primaryColor",
      label: "Warna aksen pesta (Bolu, Tombol, Lilin)",
      type: "color",
      defaultValue: "#e11d48",
      colorPresets: BIRTHDAY_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "backgroundColor",
      label: "Warna latar belakang perayaan",
      type: "color",
      defaultValue: "#fffaf7",
      colorPresets: BACKGROUND_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "cardColor",
      label: "Warna kartu & kertas surat",
      type: "color",
      defaultValue: "#ffffff",
      colorPresets: CARD_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "textColor",
      label: "Warna teks judul",
      type: "color",
      defaultValue: "#1c1917",
      colorPresets: TEXT_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "bodyTextColor",
      label: "Warna teks isi surat & doa",
      type: "color",
      defaultValue: "#44403c",
      colorPresets: TEXT_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "musicTitle",
      label: "Judul musik perayaan (opsional)",
      type: "text",
      placeholder: "Happy Birthday Joyful Chimes",
      maxLength: 80,
      section: "theme",
    },
    {
      name: "bgMusicUrl",
      label: "Tautan audio pesta (.mp3 opsional)",
      type: "text",
      placeholder: "",
      maxLength: 1000,
      helperText: "Pilih file audio dari perangkat Anda atau biarkan kosong jika tanpa musik.",
      section: "theme",
    },
  ],
  sample: {
    recipientName: "Clarissa Aurelia",
    senderName: "Arga & Seluruh Keluarga",
    age: 23,
    birthDate: "2003-10-15",
    heroGreeting: "Happy 23rd Birthday, Sunshine! 🎉",
    heroHeadline: "Merayakan Hadirnya Senyuman Paling Hangat di Dunia",
    heroCoverPhoto:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1000&q=80",
    cakeFlavor: "Strawberry Sweet Velvet & Chantilly Cream",
    cakeWishPrompt:
      "Tutup matamu sejenak, bisikkan satu permohonan tulus di hati, lalu klik tombol untuk tiup lilinnya!",
    secretWishMessage:
      "Semoga di usia 23 tahun ini, setiap langkahmu selalu dipeluk rasa aman, setiap impian besarmu didekatkan, dan tawamu tak pernah pudar. Selamat bertambah usia, manusia paling berharga! 🎂✨",
    giftBoxTitle: "Tiket Liburan Berdua & Dinner Spesial Favoritmu 🎁",
    giftBoxMessage:
      "Kado ini disiapkan dengan seluruh cinta! Weekend ini, kita luangkan waktu seharian penuh untuk kulineran, belanja hal favoritmu, dan menikmati senja tanpa gangguan apapun.",
    giftBoxCode: "CLARISSA-SWEET23-TREAT",
    milestoneTitle: "Tiga Babak Indah Menuju Usia Kedewasaan",
    milestone1Year: "2021",
    milestone1Title: "Langkah Berani Memulai Mimpi Baru",
    milestone1Desc: "Saat kamu berani melangkah keluar dari zona nyaman dan membuktikan kemandirianmu.",
    milestone2Year: "2024",
    milestone2Title: "Pencapaian Besar & Karya Membanggakan",
    milestone2Desc: "Menuntaskan tanggung jawab besar dengan senyuman puas dan apresiasi dari banyak orang.",
    milestone3Year: "2026",
    milestone3Title: "Menyambut Era Emas yang Gemilang",
    milestone3Desc: "Memasuki usia 23 dengan hati yang lebih tenang, bijaksana, dan penuh keyakinan diri.",
    galleryPhoto1:
      "https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=800&q=80",
    galleryCaption1: "Tawa renyah saat perayaan kejutan kecil",
    galleryPhoto2:
      "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=800&q=80",
    galleryCaption2: "Momen liburan seru di tepi pantai",
    galleryPhoto3:
      "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80",
    galleryCaption3: "Menikmati secangkir kopi hangat berdua",
    galleryPhoto4:
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=800&q=80",
    galleryCaption4: "Menyanyi lagu favorit sekuat tenaga",
    galleryPhoto5:
      "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=800&q=80",
    galleryCaption5: "Senja tenang dengan obrolan masa depan",
    galleryPhoto6:
      "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?auto=format&fit=crop&w=800&q=80",
    galleryCaption6: "Malam syukuran penuh pelukan hangat",
    wish1Title: "Kesehatan Raga & Jiwa",
    wish1Desc: "Semoga selalu dilimpahi tubuh yang bugar, pikiran yang damai, dan tidur malam yang selalu nyenyak.",
    wish2Title: "Karier & Pintu Rezeki",
    wish2Desc: "Semoga setiap ikhtiar dan cita-citamu dibukakan pintu kemudahan seluas-luasnya dengan hasil terbaik.",
    wish3Title: "Cinta & Ketulusan",
    wish3Desc: "Semoga hatimu selalu hangat, dijauhkan dari rasa kesepian, dan dikelilingi orang yang tulus menyayangimu.",
    wish4Title: "Kemenangan Terbesar",
    wish4Desc: "Semoga impian terbesar yang kamu doakan diam-diam segera diwujudkan semesta di waktu yang tepat.",
    bucketList1: "Menjelajahi kota baru yang selalu ada di daftar impianmu",
    bucketList2: "Menyisihkan waktu luang khusus untuk self-care tanpa rasa bersalah",
    bucketList3: "Mencapai satu target besar yang sedang kamu tekuni saat ini",
    letterTitle: "Sebuah Surat Cinta di Hari Kelahiranmu",
    introMessage: "Untuk seseorang yang kehadirannya selalu menjadi anugerah terindah bagi kami,",
    message:
      "Clarissa,\n\nDua puluh tiga tahun yang lalu, semesta menghadirkan orang sehebat kamu ke dunia—membawa tawa renyah, kebaikan yang tak pernah pamrih, dan kehangatan yang selalu menenangkan siapa pun di dekatmu.\n\nMelihat bagaimana kamu tumbuh, berjuang melewati hari-hari lelah dengan senyuman, dan tetap bertahan menjadi sosok yang lembut adalah kebanggaan terbesar yang kami rasakan. Kamu mungkin sering merasa biasa saja, tapi bagi kami, kamu adalah anugerah luar biasa yang tak tergantikan.\n\nDi hari ulang tahunmu ini, berhentilah sejenak dari segala kesibukan. Nikmati kue manismu, rayakan setiap detik perjalananmu, dan ketahuilah bahwa ada begitu banyak doa yang memelukmu dari dekat maupun jauh.\n\nSelamat ulang tahun ke-23, Clarissa! Semoga langkahmu ke depan semakin terang dan bahagia.",
    closingStatement: "Dengan pelukan paling hangat & doa tanpa henti,",
    signature: "Arga Pranata",
    primaryColor: "#e11d48",
    backgroundColor: "#fffaf7",
    cardColor: "#ffffff",
    textColor: "#1c1917",
    bodyTextColor: "#44403c",
    musicTitle: "",
    bgMusicUrl: "",
  },
};
