import type { TemplateMeta } from "../types";

export const symphonyLoveTemplate: TemplateMeta = {
  slug: "symphony-love",
  name: "La Symphonie Éternelle",
  category: "Surat Romantis",
  description:
    "Surat cinta mewah bertema naskah partitur musik klasik maestro dan warkah solilokui grand piano abad ke-19 (The Master Composer's Opus Amoris & Romantic Symphony). Menampilkan lembar judul partitur resmi Opus Amoris dengan garis pentagram emas dan tanda tempo metronom, bingkai lukisan potret sang muse terkasih, warkah solilokui komposer di keheningan larut malam, 4 babak gerakan simfoni cinta interaktif (Allegro Vivace, Andante Cantabile, Scherzo con Brio, Finale Maestoso), 4 instrumen harmoni jiwa klasik (Grand Piano, Stradivarius Cello, Concert Harp, Silver Flute), metrik resonansi akustik 432 Hz dan Sumpah Maestro, tombol interaktif dentang akord cinta terakhir (Final Cadence) yang membuka pesan rahasia, serta alunan simfoni piano klasik yang memikat.",
  tagline: "La Symphonie Éternelle: Menyatukan Detak Dua Jiwa Menjadi Partitur Abadi",
  cardAccent: "border-amber-500/40 bg-gradient-to-br from-[#120c0a] via-[#1d120d] to-[#0c0806] text-amber-200",
  highlights: [
    "Konsep Naskah Partitur Musik Klasik Romantisisme Abad ke-19 (Chopin & Debussy Opus)",
    "Halaman Judul Partitur Resmi Opus dengan Garis Pentagram & Potret Bingkai Emas Sang Muse",
    "Warkah Solilokui Komposer di Samping Grand Piano & Aksioma Melodi Cinta",
    "4 Gerakan Simfoni Cinta Interaktif (Allegro Pertemuan, Andante Bisikan, Scherzo Canda, Finale Akord Abadi)",
    "4 Instrumen Harmoni Jiwa (Grand Piano, Cello Stradivarius, Harpa Konser, & Seruling Perak)",
    "Interaksi Dentang Akord Penutup (Final Cadence) & Alunan Simfoni Piano Klasik",
  ],
  fields: [
    // Section 1: Halaman Judul Partitur Opus & Dedikasi Komposer
    {
      name: "opusNo",
      label: "Nomor Opus & Tangga Nada Musik",
      type: "text",
      placeholder: "OPUS N°24 IN C-SHARP MINOR",
      defaultValue: "OPUS N°24 IN C-SHARP MINOR",
      section: "Halaman Judul Partitur",
    },
    {
      name: "scoreTitle",
      label: "Judul Mahakarya Partitur Simfoni",
      type: "text",
      placeholder: "L'AMOUR ÉTERNEL: CONCERTO DI DUE ANIME",
      defaultValue: "L'AMOUR ÉTERNEL: CONCERTO DI DUE ANIME",
      section: "Halaman Judul Partitur",
    },
    {
      name: "tempoMarking",
      label: "Tanda Tempo & Petunjuk Ekspresi",
      type: "text",
      placeholder: "Adagio con Amore e Molto Espressivo (♩ = 60)",
      defaultValue: "Adagio con Amore e Molto Espressivo (♩ = 60)",
      section: "Halaman Judul Partitur",
    },
    {
      name: "keySignature",
      label: "Tanda Mula & Tangga Nada (Key Signature)",
      type: "text",
      placeholder: "4 Sharps (F# - C# - G# - D#) • Simfoni Empat Musim Jiwa",
      defaultValue: "4 Sharps (F# - C# - G# - D#) • Simfoni Empat Musim Jiwa",
      section: "Halaman Judul Partitur",
    },
    {
      name: "recipientName",
      label: "Nama Sang Muse Abadi (Penerima)",
      type: "text",
      placeholder: "Éléonore Vivienne de Chantal",
      required: true,
      isRecipient: true,
      section: "Halaman Judul Partitur",
    },
    {
      name: "senderName",
      label: "Nama Sang Maestro Komposer (Pengirim)",
      type: "text",
      placeholder: "Maestro Julian de Saint-Germain",
      required: true,
      section: "Halaman Judul Partitur",
    },
    {
      name: "dedicationText",
      label: "Teks Dedikasi Partitur",
      type: "text",
      placeholder: "Dédié avec toute la dévotion de mon âme à ma muse éternelle",
      defaultValue: "Dédié avec toute la dévotion de mon âme à ma muse éternelle",
      section: "Halaman Judul Partitur",
    },
    {
      name: "musePhotoUrl",
      label: "URL Foto Potret Sang Muse / Pasangan Tercinta",
      type: "image",
      placeholder: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=80",
      defaultValue: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=80",
      section: "Halaman Judul Partitur",
    },
    {
      name: "pianoScorePhotoUrl",
      label: "URL Foto Grand Piano & Ruang Resonansi",
      type: "image",
      placeholder: "https://images.unsplash.com/photo-1520523839898-50712825e617?auto=format&fit=crop&w=1200&q=80",
      defaultValue: "https://images.unsplash.com/photo-1520523839898-50712825e617?auto=format&fit=crop&w=1200&q=80",
      section: "Halaman Judul Partitur",
    },

    // Section 2: Warkah Solilokui Komposer di Samping Grand Piano
    {
      name: "soliloquyTitle",
      label: "Judul Catatan Solilokui Komposer",
      type: "text",
      placeholder: "Solilokui Malam di Balik Tuts Grand Piano",
      defaultValue: "Solilokui Malam di Balik Tuts Grand Piano",
      section: "Warkah Solilokui Komposer",
    },
    {
      name: "soliloquyTime",
      label: "Waktu Penulisan Warkah Musik",
      type: "text",
      placeholder: "Tengah Malam • Pukul 02:15 di Bawah Temaram Lilin Salon Musik",
      defaultValue: "Tengah Malam • Pukul 02:15 di Bawah Temaram Lilin Salon Musik",
      section: "Warkah Solilokui Komposer",
    },
    {
      name: "mainMessage",
      label: "Isi Surat Cinta Komposer (Warkah Utama)",
      type: "textarea",
      placeholder: "Tuliskan narasi puitis cinta dari lubuk hati...",
      required: true,
      defaultValue:
        "Éléonore yang teramat kucintai,\n\nSeorang komposer menghabiskan seluruh umurnya merangkai sunyi menjadi nada, mencari frekuensi yang mampu menembus batas waktu di antara tuts tuts gading hitam dan putih. Namun malam ini, di tengah heningnya salon musik ini saat lilin perlahan meleleh ke cawannya, aku menyadari sebuah kepastian yang mutlak: sebelum mengenalmu, seluruh musik yang kutulis hanyalah bunyi hampa yang meratapi kesepian jiwanya sendiri.\n\nKehadiranmu mengubah setiap denyut nadiku menjadi melodi yang bernyawa. Suaramu saat berbisik lembut adalah nada Adagio yang paling menenangkan badai di kepalaku; tawa renyahmu adalah irama Scherzo yang memancarkan seribu percik cahaya ke dalam kegelapan; dan tatap matamu adalah akord Maestoso yang mengunci seluruh kesetiaanku dalam satu harmoni suci.\n\nPartitur Opus ini kutulis bukan dengan tinta biasa, melainkan dengan getaran rasa syukur yang tak bertepi. Selama nafasku masih berhembus, setiap nada dalam hidupku akan selalu digubah untuk memuliakan cintamu, menjaga senyumanmu, dan memastikan bahwa kita berdua tidak akan pernah berjalan sumbang di panggung semesta ini.",
      section: "Warkah Solilokui Komposer",
    },
    {
      name: "musicalAxiom",
      label: "Aksioma Filosofis Musik & Cinta",
      type: "text",
      placeholder: "Kutipan filosofis musik...",
      defaultValue:
        "Musik dimulai di saat kata-kata tak lagi sanggup mengucapkannya, dan cintaku padamu bernyanyi di saat alam semesta kehabisan bahasa.",
      section: "Warkah Solilokui Komposer",
    },
    {
      name: "composerSignatureTitle",
      label: "Sebutan Penutup Tanda Tangan Komposer",
      type: "text",
      placeholder: "Komposer yang Seluruh Detak Nadanya Beresonansi Untukmu,",
      defaultValue: "Komposer yang Seluruh Detak Nadanya Beresonansi Untukmu,",
      section: "Warkah Solilokui Komposer",
    },

    // Section 3: 4 Gerakan Simfoni Cinta (The 4 Movements)
    {
      name: "movement1Tempo",
      label: "Gerakan 1: Tempo & Tanda Birama",
      type: "text",
      placeholder: "Movement I: Allegro Vivace • 3/4 Time",
      defaultValue: "Movement I: Allegro Vivace • 3/4 Time",
      section: "4 Gerakan Simfoni Cinta",
    },
    {
      name: "movement1Title",
      label: "Gerakan 1: Judul Bagian",
      type: "text",
      placeholder: "Detak Awal Resonansi Pertemuan",
      defaultValue: "Detak Awal Resonansi Pertemuan",
      section: "4 Gerakan Simfoni Cinta",
    },
    {
      name: "movement1Desc",
      label: "Gerakan 1: Narasi Kisah Musikal",
      type: "textarea",
      placeholder: "Uraikan kisah gerakan pertama...",
      defaultValue:
        "Petikan akord riang yang berderap cepat seperti jantung yang berdegup kencang saat mata kita pertama kali bersua. Nada-nada tinggi yang melompat lincah merekam debar bahagia saat kusadari bahwa duniaku tak akan pernah sama lagi.",
      section: "4 Gerakan Simfoni Cinta",
    },
    {
      name: "movement1Dynamic",
      label: "Gerakan 1: Dinamika Jiwa",
      type: "text",
      placeholder: "Crescendo di Gioia (Sukacita yang Terus Bertumbuh)",
      defaultValue: "Crescendo di Gioia (Sukacita yang Terus Bertumbuh)",
      section: "4 Gerakan Simfoni Cinta",
    },

    {
      name: "movement2Tempo",
      label: "Gerakan 2: Tempo & Tanda Birama",
      type: "text",
      placeholder: "Movement II: Andante Cantabile • 4/4 Time",
      defaultValue: "Movement II: Andante Cantabile • 4/4 Time",
      section: "4 Gerakan Simfoni Cinta",
    },
    {
      name: "movement2Title",
      label: "Gerakan 2: Judul Bagian",
      type: "text",
      placeholder: "Bisikan Harmoni Sunyi di Larut Malam",
      defaultValue: "Bisikan Harmoni Sunyi di Larut Malam",
      section: "4 Gerakan Simfoni Cinta",
    },
    {
      name: "movement2Desc",
      label: "Gerakan 2: Narasi Kisah Musikal",
      type: "textarea",
      placeholder: "Uraikan kisah gerakan kedua...",
      defaultValue:
        "Melodi lambat nan menghanyutkan dimainkan dalam keheningan solo cello dan piano. Momen saat kita saling membuka luka masa lalu dan kerapuhan jiwa, menyadari bahwa pelukan kita adalah tempat teraman untuk beristirahat.",
      section: "4 Gerakan Simfoni Cinta",
    },
    {
      name: "movement2Dynamic",
      label: "Gerakan 2: Dinamika Jiwa",
      type: "text",
      placeholder: "Pianissimo con Tenerezza (Kelembutan Penuh Ketulusan)",
      defaultValue: "Pianissimo con Tenerezza (Kelembutan Penuh Ketulusan)",
      section: "4 Gerakan Simfoni Cinta",
    },

    {
      name: "movement3Tempo",
      label: "Gerakan 3: Tempo & Tanda Birama",
      type: "text",
      placeholder: "Movement III: Scherzo con Brio • 6/8 Time",
      defaultValue: "Movement III: Scherzo con Brio • 6/8 Time",
      section: "4 Gerakan Simfoni Cinta",
    },
    {
      name: "movement3Title",
      label: "Gerakan 3: Judul Bagian",
      type: "text",
      placeholder: "Tawa & Gelak Canda Menembus Badai",
      defaultValue: "Tawa & Gelak Canda Menembus Badai",
      section: "4 Gerakan Simfoni Cinta",
    },
    {
      name: "movement3Desc",
      label: "Gerakan 3: Narasi Kisah Musikal",
      type: "textarea",
      placeholder: "Uraikan kisah gerakan ketiga...",
      defaultValue:
        "Irama dansa waltz penuh warna yang melambangkan hari-hari penuh tawa, lelucon receh di sore hari, dan kemampuan kita mengubah hari terberat sekalipun menjadi melodi riang yang patut disyukuri.",
      section: "4 Gerakan Simfoni Cinta",
    },
    {
      name: "movement3Dynamic",
      label: "Gerakan 3: Dinamika Jiwa",
      type: "text",
      placeholder: "Leggiero e Brillante (Ringan, Hangat, & Bercahaya)",
      defaultValue: "Leggiero e Brillante (Ringan, Hangat, & Bercahaya)",
      section: "4 Gerakan Simfoni Cinta",
    },

    {
      name: "movement4Tempo",
      label: "Gerakan 4: Tempo & Tanda Birama",
      type: "text",
      placeholder: "Movement IV: Finale Maestoso • All'Unisono",
      defaultValue: "Movement IV: Finale Maestoso • All'Unisono",
      section: "4 Gerakan Simfoni Cinta",
    },
    {
      name: "movement4Title",
      label: "Gerakan 4: Judul Bagian",
      type: "text",
      placeholder: "Akord Puncak Perjanjian Keabadian",
      defaultValue: "Akord Puncak Perjanjian Keabadian",
      section: "4 Gerakan Simfoni Cinta",
    },
    {
      name: "movement4Desc",
      label: "Gerakan 4: Narasi Kisah Musikal",
      type: "textarea",
      placeholder: "Uraikan kisah gerakan keempat...",
      defaultValue:
        "Puncak simfoni di mana seluruh instrumen berdentang serentak dalam satu harmoni agung. Menegaskan komitmen bahwa cinta kita tidak akan pernah memudar oleh waktu, melainkan bergaung abadi melintasi dimensi semesta.",
      section: "4 Gerakan Simfoni Cinta",
    },
    {
      name: "movement4Dynamic",
      label: "Gerakan 4: Dinamika Jiwa",
      type: "text",
      placeholder: "Fortissimo Sforzando (Kekuatan Cinta Paling Kokoh)",
      defaultValue: "Fortissimo Sforzando (Kekuatan Cinta Paling Kokoh)",
      section: "4 Gerakan Simfoni Cinta",
    },

    // Section 4: 4 Instrumen Harmoni Jiwa
    {
      name: "instrument1Name",
      label: "Instrumen 1: Nama Instrumen",
      type: "text",
      placeholder: "The Concert Grand Piano (Piano Sayap Emas)",
      defaultValue: "The Concert Grand Piano (Piano Sayap Emas)",
      section: "4 Instrumen Harmoni Jiwa",
    },
    {
      name: "instrument1Role",
      label: "Instrumen 1: Peran Harmoni",
      type: "text",
      placeholder: "Pondasi Harmoni & Rumah Seluruh Nada Jiwa",
      defaultValue: "Pondasi Harmoni & Rumah Seluruh Nada Jiwa",
      section: "4 Instrumen Harmoni Jiwa",
    },
    {
      name: "instrument1Desc",
      label: "Instrumen 1: Filosofi",
      type: "textarea",
      placeholder: "Filosofi instrumen...",
      defaultValue:
        "Tuts gading dan kayu mahoni yang menopang seluruh dinamika simfoni cinta kita. Di atas tuts ini seluruh rasa sedih, bahagia, dan rindu menemukan nadanya yang paling jujur.",
      section: "4 Instrumen Harmoni Jiwa",
    },

    {
      name: "instrument2Name",
      label: "Instrumen 2: Nama Instrumen",
      type: "text",
      placeholder: "The Stradivarius Cello (Selo Akustik Hangat)",
      defaultValue: "The Stradivarius Cello (Selo Akustik Hangat)",
      section: "4 Instrumen Harmoni Jiwa",
    },
    {
      name: "instrument2Role",
      label: "Instrumen 2: Peran Harmoni",
      type: "text",
      placeholder: "Resonansi Dekapan & Ketenangan Batin",
      defaultValue: "Resonansi Dekapan & Ketenangan Batin",
      section: "4 Instrumen Harmoni Jiwa",
    },
    {
      name: "instrument2Desc",
      label: "Instrumen 2: Filosofi",
      type: "textarea",
      placeholder: "Filosofi instrumen...",
      defaultValue:
        "Gesekan senar bas yang dalam dan hangat, bagaikan dekapan lengan yang selalu siap menyambut kepulanganmu di kala dunia luar terasa begitu dingin dan melelahkan.",
      section: "4 Instrumen Harmoni Jiwa",
    },

    {
      name: "instrument3Name",
      label: "Instrumen 3: Nama Instrumen",
      type: "text",
      placeholder: "The Concert Harp (Harpa Kristal Langit)",
      defaultValue: "The Concert Harp (Harpa Kristal Langit)",
      section: "4 Instrumen Harmoni Jiwa",
    },
    {
      name: "instrument3Role",
      label: "Instrumen 3: Peran Harmoni",
      type: "text",
      placeholder: "Petikan Doa Suci & Kemilau Impian Masa Depan",
      defaultValue: "Petikan Doa Suci & Kemilau Impian Masa Depan",
      section: "4 Instrumen Harmoni Jiwa",
    },
    {
      name: "instrument3Desc",
      label: "Instrumen 3: Filosofi",
      type: "textarea",
      placeholder: "Filosofi instrumen...",
      defaultValue:
        "Untaian dawai emas yang dipetik perlahan menghasilkan gemerlap nada bagai bintang jatuh. Menjadi simbol doa dan impian indah yang kita gantungkan bersama di langit masa depan.",
      section: "4 Instrumen Harmoni Jiwa",
    },

    {
      name: "instrument4Name",
      label: "Instrumen 4: Nama Instrumen",
      type: "text",
      placeholder: "The Silver Concert Flute (Seruling Perak)",
      defaultValue: "The Silver Concert Flute (Seruling Perak)",
      section: "4 Instrumen Harmoni Jiwa",
    },
    {
      name: "instrument4Role",
      label: "Instrumen 4: Peran Harmoni",
      type: "text",
      placeholder: "Embusan Angin Kesejukan yang Meredakan Gundah",
      defaultValue: "Embusan Angin Kesejukan yang Meredakan Gundah",
      section: "4 Instrumen Harmoni Jiwa",
    },
    {
      name: "instrument4Desc",
      label: "Instrumen 4: Filosofi",
      type: "textarea",
      placeholder: "Filosofi instrumen...",
      defaultValue:
        "Tiupan melodi perak yang melayang ringan di udara, mengingatkanku pada hembusan nafasmu saat tertidur lelap di pundakku, membawa kedamaian mutlak bagi sanubariku.",
      section: "4 Instrumen Harmoni Jiwa",
    },

    // Section 5: Metrik Akustik & Piagam Harmoni Abadi
    {
      name: "tuningFrequency",
      label: "Frekuensi Penyelarasan (Tuning Pitch)",
      type: "text",
      placeholder: "432 Hz • Natural Harmonic Resonance of Love",
      defaultValue: "432 Hz • Natural Harmonic Resonance of Love",
      section: "Metrik Akustik & Piagam",
    },
    {
      name: "dynamicRange",
      label: "Jangkauan Dinamika Emosi",
      type: "text",
      placeholder: "Pianissimo (Bisikan Rindu) hingga Fortissimo (Pelukan Utuh)",
      defaultValue: "Pianissimo (Bisikan Rindu) hingga Fortissimo (Pelukan Utuh)",
      section: "Metrik Akustik & Piagam",
    },
    {
      name: "acousticResonance",
      label: "Ruang Resonansi Jiwa",
      type: "text",
      placeholder: "Dua Hati yang Saling Memahami Tanpa Butuh Banyak Kata",
      defaultValue: "Dua Hati yang Saling Memahami Tanpa Butuh Banyak Kata",
      section: "Metrik Akustik & Piagam",
    },
    {
      name: "codaStatus",
      label: "Status Koda Penutup",
      type: "text",
      placeholder: "Da Capo al Infinito • Nada Abadi Tanpa Garis Akhir",
      defaultValue: "Da Capo al Infinito • Nada Abadi Tanpa Garis Akhir",
      section: "Metrik Akustik & Piagam",
    },
    {
      name: "covenantTitle",
      label: "Judul Piagam Sumpah Harmoni",
      type: "text",
      placeholder: "The Composer's Sacred Covenant (Ikrar Harmoni Abadi)",
      defaultValue: "The Composer's Sacred Covenant (Ikrar Harmoni Abadi)",
      section: "Metrik Akustik & Piagam",
    },
    {
      name: "covenantText",
      label: "Naskah Piagam Sumpah Maestro",
      type: "textarea",
      placeholder: "Tuliskan naskah sumpah...",
      defaultValue:
        "Di hadapan keindahan seni nada dan di bawah naungan harmoni alam semesta, aku berikrar untuk senantiasa menyelaraskan detak jantungku dengan irama langkahmu, tidak akan pernah membiarkan sumbangnya amarah merusak nada kasih kita, dan akan terus memainkan lagu kesetiaan ini hingga nafas terakhirku berlabuh.",
      section: "Metrik Akustik & Piagam",
    },

    // Section 6: Dentang Akord Penutup & Melodi Simfoni
    {
      name: "cadenceButtonText",
      label: "Teks Tombol Akord Penutup",
      type: "text",
      placeholder: "Dentangkan Akord Cinta Terakhir (Play Final Cadence)",
      defaultValue: "Dentangkan Akord Cinta Terakhir (Play Final Cadence)",
      section: "Akord Penutup & Melodi",
    },
    {
      name: "secretCodaMessage",
      label: "Pesan Rahasia Koda Musik (Secret Musical Coda)",
      type: "textarea",
      placeholder: "Pesan rahasia terdalam...",
      defaultValue:
        "Jika suatu saat seluruh partitur di dunia terbakar dan hening menyelimuti bumi, dengarkanlah detak dadaku saat kau memelukku: di sanalah melodi namamu akan tetap berdentang abadi.",
      section: "Akord Penutup & Melodi",
    },
    {
      name: "scoreClosingQuote",
      label: "Kutipan Penutup Partitur",
      type: "text",
      placeholder: "Finis coronat opus • Melodi ini selesai ditulis, namun cinta kita tak akan pernah berakhir.",
      defaultValue: "Finis coronat opus • Melodi ini selesai ditulis, namun cinta kita tak akan pernah berakhir.",
      section: "Akord Penutup & Melodi",
    },

    // Theme & Music
    {
      name: "primaryColor",
      label: "Warna Utama (Candlelight Amber Gold)",
      type: "color",
      defaultValue: "#d4af37",
      section: "Pengaturan Tampilan & Musik",
    },
    {
      name: "secondaryColor",
      label: "Warna Sekunder (Nocturne Warm Cello)",
      type: "color",
      defaultValue: "#b45309",
      section: "Pengaturan Tampilan & Musik",
    },
    {
      name: "accentColor",
      label: "Warna Aksen (Velvet Concert Hall Mahogany)",
      type: "color",
      defaultValue: "#1a100c",
      section: "Pengaturan Tampilan & Musik",
    },
    {
      name: "musicTrack",
      label: "URL Musik Latar (Simfoni Piano & Selo Klasik)",
      type: "text",
      placeholder: "https://cdn.pixabay.com/download/audio/...",
      defaultValue: "https://cdn.pixabay.com/download/audio/2022/03/15/audio_c89b7b9cf4.mp3?filename=celestial-music-box-waltz-10928.mp3",
      section: "Pengaturan Tampilan & Musik",
    },
  ],
  sample: {
    opusNo: "OPUS N°24 IN C-SHARP MINOR",
    scoreTitle: "L'AMOUR ÉTERNEL: CONCERTO DI DUE ANIME",
    tempoMarking: "Adagio con Amore e Molto Espressivo (♩ = 60)",
    keySignature: "4 Sharps (F# - C# - G# - D#) • Simfoni Empat Musim Jiwa",
    recipientName: "Éléonore Vivienne de Chantal",
    senderName: "Maestro Julian de Saint-Germain",
    dedicationText: "Dédié avec toute la dévotion de mon âme à ma muse éternelle",
    musePhotoUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=80",
    pianoScorePhotoUrl: "https://images.unsplash.com/photo-1520523839898-50712825e617?auto=format&fit=crop&w=1200&q=80",
    soliloquyTitle: "Solilokui Malam di Balik Tuts Grand Piano",
    soliloquyTime: "Tengah Malam • Pukul 02:15 di Bawah Temaram Lilin Salon Musik",
    mainMessage:
      "Éléonore yang teramat kucintai,\n\nSeorang komposer menghabiskan seluruh umurnya merangkai sunyi menjadi nada, mencari frekuensi yang mampu menembus batas waktu di antara tuts tuts gading hitam dan putih. Namun malam ini, di tengah heningnya salon musik ini saat lilin perlahan meleleh ke cawannya, aku menyadari sebuah kepastian yang mutlak: sebelum mengenalmu, seluruh musik yang kutulis hanyalah bunyi hampa yang meratapi kesepian jiwanya sendiri.\n\nKehadiranmu mengubah setiap denyut nadiku menjadi melodi yang bernyawa. Suaramu saat berbisik lembut adalah nada Adagio yang paling menenangkan badai di kepalaku; tawa renyahmu adalah irama Scherzo yang memancarkan seribu percik cahaya ke dalam kegelapan; dan tatap matamu adalah akord Maestoso yang mengunci seluruh kesetiaanku dalam satu harmoni suci.\n\nPartitur Opus ini kutulis bukan dengan tinta biasa, melainkan dengan getaran rasa syukur yang tak bertepi. Selama nafasku masih berhembus, setiap nada dalam hidupku akan selalu digubah untuk memuliakan cintamu, menjaga senyumanmu, dan memastikan bahwa kita berdua tidak akan pernah berjalan sumbang di panggung semesta ini.",
    musicalAxiom:
      "Musik dimulai di saat kata-kata tak lagi sanggup mengucapkannya, dan cintaku padamu bernyanyi di saat alam semesta kehabisan bahasa.",
    composerSignatureTitle: "Komposer yang Seluruh Detak Nadanya Beresonansi Untukmu,",
    movement1Tempo: "Movement I: Allegro Vivace • 3/4 Time",
    movement1Title: "Detak Awal Resonansi Pertemuan",
    movement1Desc:
      "Petikan akord riang yang berderap cepat seperti jantung yang berdegup kencang saat mata kita pertama kali bersua. Nada-nada tinggi yang melompat lincah merekam debar bahagia saat kusadari bahwa duniaku tak akan pernah sama lagi.",
    movement1Dynamic: "Crescendo di Gioia (Sukacita yang Terus Bertumbuh)",
    movement2Tempo: "Movement II: Andante Cantabile • 4/4 Time",
    movement2Title: "Bisikan Harmoni Sunyi di Larut Malam",
    movement2Desc:
      "Melodi lambat nan menghanyutkan dimainkan dalam keheningan solo cello dan piano. Momen saat kita saling membuka luka masa lalu dan kerapuhan jiwa, menyadari bahwa pelukan kita adalah tempat teraman untuk beristirahat.",
    movement2Dynamic: "Pianissimo con Tenerezza (Kelembutan Penuh Ketulusan)",
    movement3Tempo: "Movement III: Scherzo con Brio • 6/8 Time",
    movement3Title: "Tawa & Gelak Canda Menembus Badai",
    movement3Desc:
      "Irama dansa waltz penuh warna yang melambangkan hari-hari penuh tawa, lelucon receh di sore hari, dan kemampuan kita mengubah hari terberat sekalipun menjadi melodi riang yang patut disyukuri.",
    movement3Dynamic: "Leggiero e Brillante (Ringan, Hangat, & Bercahaya)",
    movement4Tempo: "Movement IV: Finale Maestoso • All'Unisono",
    movement4Title: "Akord Puncak Perjanjian Keabadian",
    movement4Desc:
      "Puncak simfoni di mana seluruh instrumen berdentang serentak dalam satu harmoni agung. Menegaskan komitmen bahwa cinta kita tidak akan pernah memudar oleh waktu, melainkan bergaung abadi melintasi dimensi semesta.",
    movement4Dynamic: "Fortissimo Sforzando (Kekuatan Cinta Paling Kokoh)",
    instrument1Name: "The Concert Grand Piano (Piano Sayap Emas)",
    instrument1Role: "Pondasi Harmoni & Rumah Seluruh Nada Jiwa",
    instrument1Desc:
      "Tuts gading dan kayu mahoni yang menopang seluruh dinamika simfoni cinta kita. Di atas tuts ini seluruh rasa sedih, bahagia, dan rindu menemukan nadanya yang paling jujur.",
    instrument2Name: "The Stradivarius Cello (Selo Akustik Hangat)",
    instrument2Role: "Resonansi Dekapan & Ketenangan Batin",
    instrument2Desc:
      "Gesekan senar bas yang dalam dan hangat, bagaikan dekapan lengan yang selalu siap menyambut kepulanganmu di kala dunia luar terasa begitu dingin dan melelahkan.",
    instrument3Name: "The Concert Harp (Harpa Kristal Langit)",
    instrument3Role: "Petikan Doa Suci & Kemilau Impian Masa Depan",
    instrument3Desc:
      "Untaian dawai emas yang dipetik perlahan menghasilkan gemerlap nada bagai bintang jatuh. Menjadi simbol doa dan impian indah yang kita gantungkan bersama di langit masa depan.",
    instrument4Name: "The Silver Concert Flute (Seruling Perak)",
    instrument4Role: "Embusan Angin Kesejukan yang Meredakan Gundah",
    instrument4Desc:
      "Tiupan melodi perak yang melayang ringan di udara, mengingatkanku pada hembusan nafasmu saat tertidur lelap di pundakku, membawa kedamaian mutlak bagi sanubariku.",
    tuningFrequency: "432 Hz • Natural Harmonic Resonance of Love",
    dynamicRange: "Pianissimo (Bisikan Rindu) hingga Fortissimo (Pelukan Utuh)",
    acousticResonance: "Dua Hati yang Saling Memahami Tanpa Butuh Banyak Kata",
    codaStatus: "Da Capo al Infinito • Nada Abadi Tanpa Garis Akhir",
    covenantTitle: "The Composer's Sacred Covenant (Ikrar Harmoni Abadi)",
    covenantText:
      "Di hadapan keindahan seni nada dan di bawah naungan harmoni alam semesta, aku berikrar untuk senantiasa menyelaraskan detak jantungku dengan irama langkahmu, tidak akan pernah membiarkan sumbangnya amarah merusak nada kasih kita, dan akan terus memainkan lagu kesetiaan ini hingga nafas terakhirku berlabuh.",
    cadenceButtonText: "Dentangkan Akord Cinta Terakhir (Play Final Cadence)",
    secretCodaMessage:
      "Jika suatu saat seluruh partitur di dunia terbakar dan hening menyelimuti bumi, dengarkanlah detak dadaku saat kau memelukku: di sanalah melodi namamu akan tetap berdentang abadi.",
    scoreClosingQuote: "Finis coronat opus • Melodi ini selesai ditulis, namun cinta kita tak akan pernah berakhir.",
    primaryColor: "#d4af37",
    secondaryColor: "#b45309",
    accentColor: "#1a100c",
    musicTrack: "https://cdn.pixabay.com/download/audio/2022/03/15/audio_c89b7b9cf4.mp3?filename=celestial-music-box-waltz-10928.mp3",
  },
};
