import type { TemplateMeta } from "../types";

export const parfumDamourTemplate: TemplateMeta = {
  slug: "parfum-damour",
  name: "L'Atelier des Parfums",
  category: "Surat Romantis",
  description:
    "Surat cinta mewah bertema rumah parfum Prancis (French Haute Parfumerie). Menampilkan sertifikat botol parfum kristal bespoke, jurnal rahasia peracik wewangian, piramida aroma 3 tingkat (Top, Heart, and Base Notes), 4 botol kenangan aroma berharga (Olfactory Snapshots), metrik karakteristik sillage dan daya tahan abadi, serta tombol interaktif semprotan kabut emas beraroma cinta dengan alunan musik waltz Paris yang memabukkan.",
  tagline: "L'Atelier des Parfums: Meramu Aroma Cintamu Menjadi Mahakarya Abadi",
  cardAccent: "border-amber-400/40 bg-gradient-to-br from-[#120a0f] via-[#1a0f16] to-[#24141e] text-amber-200",
  highlights: [
    "Konsep French Haute Parfumerie: Menjadikan Cintamu Sebagai Racikan Extrait de Parfum",
    "Sertifikat Botol Flacon Kristal & Etiket Khusus Maison de Lettera Paris",
    "Surat Jurnal Rahasia Perfumer (The Perfumer's Private Journal) Berbingkai Emas",
    "Piramida Aroma 3 Tingkat (Top, Heart & Base Notes) yang Sarat Filosofi",
    "4 Botol Kenangan Aroma (Olfactory Snapshots) yang Mengabadikan Setiap Momen Indah",
    "Interaksi Semprotan Kabut Aroma Emas (Interactive Atomizer Spritz) & Melodi Waltz Paris",
  ],
  fields: [
    // Section 1: Etiket Botol Flacon & Sertifikat
    {
      name: "recipientName",
      label: "Nama Sang Kekasih (The Ineffable Muse)",
      type: "text",
      placeholder: "Aurelia Genevieve",
      required: true,
      isRecipient: true,
      section: "Etiket Botol Flacon",
    },
    {
      name: "senderName",
      label: "Nama Peracik (The Master Perfumer)",
      type: "text",
      placeholder: "Julian de Valois",
      required: true,
      section: "Etiket Botol Flacon",
    },
    {
      name: "flaconBatchNo",
      label: "Nomor Seri Formula Botol",
      type: "text",
      placeholder: "N°07-AMOUR-ETERNEL",
      defaultValue: "N°07-AMOUR-ETERNEL",
      section: "Etiket Botol Flacon",
    },
    {
      name: "perfumeName",
      label: "Nama Mahakarya Parfum",
      type: "text",
      placeholder: "L'Éternel Rendez-Vous",
      defaultValue: "L'Éternel Rendez-Vous",
      section: "Etiket Botol Flacon",
    },
    {
      name: "perfumeConcentration",
      label: "Konsentrasi Racikan",
      type: "text",
      placeholder: "Extrait de Parfum • 100% Pure Devotion",
      defaultValue: "Extrait de Parfum • 100% Pure Devotion",
      section: "Etiket Botol Flacon",
    },
    {
      name: "formulationDate",
      label: "Tanggal Formulasi",
      type: "text",
      placeholder: "Malam Saat Jiwa Ini Terpikat Selamanya",
      defaultValue: "Malam Saat Jiwa Ini Terpikat Selamanya",
      section: "Etiket Botol Flacon",
    },
    {
      name: "atelierLocation",
      label: "Lokasi Rumah Parfum",
      type: "text",
      placeholder: "Atelier de Lettera • Place Vendôme, Paris",
      defaultValue: "Atelier de Lettera • Place Vendôme, Paris",
      section: "Etiket Botol Flacon",
    },
    {
      name: "dedicationQuote",
      label: "Dedikasi Khusus untuk Sang Muse",
      type: "textarea",
      placeholder: "Kalimat dedikasi singkat di etiket botol...",
      defaultValue:
        "Untuk jiwa yang kehadirannya adalah wewangian terindah yang pernah dihirup oleh semesta. Tak ada bunga di taman Versailles yang mampu menandingi kehangatan aromamu.",
      section: "Etiket Botol Flacon",
    },

    // Section 2: Jurnal Rahasia Perfumer
    {
      name: "letterTitle",
      label: "Judul Surat Jurnal Rahasia",
      type: "text",
      placeholder: "Formulasi Rahasia di Balik Setiap Detak Jantungku",
      defaultValue: "Formulasi Rahasia di Balik Setiap Detak Jantungku",
      section: "Jurnal Rahasia Perfumer",
    },
    {
      name: "letterDate",
      label: "Tanggal Surat Ditulis",
      type: "text",
      placeholder: "Paris, Di Bawah Cahaya Rembulan & Semerbak Melati",
      defaultValue: "Paris, Di Bawah Cahaya Rembulan & Semerbak Melati",
      section: "Jurnal Rahasia Perfumer",
    },
    {
      name: "mainMessage",
      label: "Isi Surat Cinta & Refleksi Peracik",
      type: "textarea",
      placeholder: "Tuliskan surat cinta romantis yang menggambarkan keindahan kehadirannya...",
      defaultValue:
        "Aurelia yang teramat kucintai,\n\nMereka berkata bahwa penciuman adalah pintu memori manusia yang paling murni dan tak terbantahkan. Maka malam ini, di tengah heningnya ruang peracikan wewangian ini, aku menyadari bahwa seluruh hidupku sebelum bertemu denganmu hanyalah halaman hampa tanpa aroma.\n\nSetiap kali kamu mendekat, udara di sekitarku seketika berubah. Ada aroma kelembutan yang tidak bisa diracik dari kelopak mawar termahal di Grasse sekalipun; ada kehangatan yang tak mampu ditiru oleh amber dan cendana paling langka. Kehadiranmu adalah harmoni sempurna antara ketenangan fajar dan misteri bintang malam.\n\nBotol ini kuciptakan bukan untuk menyaingi keindahanmu, melainkan sebagai tempatku menyimpan setiap desah tawamu, setiap tatapan matamu yang teduh, dan setiap janji bisu yang kita rajut di bawah langit malam. Selama cairan emas ini bernapas, cintaku padamu akan terus mengalir, tak lekang oleh waktu, dan selalu menemukan jalan kembali ke pelukanmu.",
      section: "Jurnal Rahasia Perfumer",
    },
    {
      name: "letterSignoff",
      label: "Kalimat Penutup Surat",
      type: "text",
      placeholder: "Dengan seluruh aroma rindu yang tak pernah pudar,",
      defaultValue: "Dengan seluruh aroma rindu yang tak pernah pudar,",
      section: "Jurnal Rahasia Perfumer",
    },

    // Section 3: Piramida Aroma 3 Tingkat
    // Top Notes
    {
      name: "topNote1Name",
      label: "Top Note 1: Nama Elemen",
      type: "text",
      placeholder: "Bergamot of First Glimpse",
      defaultValue: "Bergamot of First Glimpse",
      section: "Piramida Aroma",
    },
    {
      name: "topNote1Desc",
      label: "Top Note 1: Makna Romantis",
      type: "text",
      placeholder: "Kesegaran debaran pertama saat mata kita bersitatap.",
      defaultValue: "Kesegaran debaran pertama saat mata kita bersitatap.",
      section: "Piramida Aroma",
    },
    {
      name: "topNote2Name",
      label: "Top Note 2: Nama Elemen",
      type: "text",
      placeholder: "Sparkling Pear of Sweet Laughter",
      defaultValue: "Sparkling Pear of Sweet Laughter",
      section: "Piramida Aroma",
    },
    {
      name: "topNote2Desc",
      label: "Top Note 2: Makna Romantis",
      type: "text",
      placeholder: "Manisnya tawa renyahmu yang selalu mencairkan segala gundah duniaku.",
      defaultValue: "Manisnya tawa renyahmu yang selalu mencairkan segala gundah duniaku.",
      section: "Piramida Aroma",
    },
    {
      name: "topNote3Name",
      label: "Top Note 3: Nama Elemen",
      type: "text",
      placeholder: "Pink Pepper of Electric Touch",
      defaultValue: "Pink Pepper of Electric Touch",
      section: "Piramida Aroma",
    },
    {
      name: "topNote3Desc",
      label: "Top Note 3: Makna Romantis",
      type: "text",
      placeholder: "Percikan kehangatan elektrik saat jemari kita pertama kali bertaut erat.",
      defaultValue: "Percikan kehangatan elektrik saat jemari kita pertama kali bertaut erat.",
      section: "Piramida Aroma",
    },

    // Heart Notes
    {
      name: "heartNote1Name",
      label: "Heart Note 1: Nama Elemen",
      type: "text",
      placeholder: "Damask Rose of Vulnerable Whispers",
      defaultValue: "Damask Rose of Vulnerable Whispers",
      section: "Piramida Aroma",
    },
    {
      name: "heartNote1Desc",
      label: "Heart Note 1: Makna Romantis",
      type: "text",
      placeholder: "Mekarnya kejujuran saat kita saling menceritakan kerapuhan hati tanpa takut dihakimi.",
      defaultValue: "Mekarnya kejujuran saat kita saling menceritakan kerapuhan hati tanpa takut dihakimi.",
      section: "Piramida Aroma",
    },
    {
      name: "heartNote2Name",
      label: "Heart Note 2: Nama Elemen",
      type: "text",
      placeholder: "Midnight Jasmine of Safe Embraces",
      defaultValue: "Midnight Jasmine of Safe Embraces",
      section: "Piramida Aroma",
    },
    {
      name: "heartNote2Desc",
      label: "Heart Note 2: Makna Romantis",
      type: "text",
      placeholder: "Ketenangan semerbak saat kepalamu bersandar nyaman di bahuku di ujung hari yang lelah.",
      defaultValue: "Ketenangan semerbak saat kepalamu bersandar nyaman di bahuku di ujung hari yang lelah.",
      section: "Piramida Aroma",
    },
    {
      name: "heartNote3Name",
      label: "Heart Note 3: Nama Elemen",
      type: "text",
      placeholder: "French Lavender of Peaceful Solace",
      defaultValue: "French Lavender of Peaceful Solace",
      section: "Piramida Aroma",
    },
    {
      name: "heartNote3Desc",
      label: "Heart Note 3: Makna Romantis",
      type: "text",
      placeholder: "Rasa damai tak terkatakan saat mengetahui bahwa rumah sejatiku adalah dirimu.",
      defaultValue: "Rasa damai tak terkatakan saat mengetahui bahwa rumah sejatiku adalah dirimu.",
      section: "Piramida Aroma",
    },

    // Base Notes
    {
      name: "baseNote1Name",
      label: "Base Note 1: Nama Elemen",
      type: "text",
      placeholder: "Warm Amber of Unshakable Devotion",
      defaultValue: "Warm Amber of Unshakable Devotion",
      section: "Piramida Aroma",
    },
    {
      name: "baseNote1Desc",
      label: "Base Note 1: Makna Romantis",
      type: "text",
      placeholder: "Bara kesetiaan yang mengakar kuat di palung jiwaku, tak pernah pudar oleh waktu.",
      defaultValue: "Bara kesetiaan yang mengakar kuat di palung jiwaku, tak pernah pudar oleh waktu.",
      section: "Piramida Aroma",
    },
    {
      name: "baseNote2Name",
      label: "Base Note 2: Nama Elemen",
      type: "text",
      placeholder: "Cedarwood of Shared Future Dreams",
      defaultValue: "Cedarwood of Shared Future Dreams",
      section: "Piramida Aroma",
    },
    {
      name: "baseNote2Desc",
      label: "Base Note 2: Makna Romantis",
      type: "text",
      placeholder: "Kekokohan pilar mimpi rumah tangga dan masa depan yang kita bangun berdampingan.",
      defaultValue: "Kekokohan pilar mimpi rumah tangga dan masa depan yang kita bangun berdampingan.",
      section: "Piramida Aroma",
    },
    {
      name: "baseNote3Name",
      label: "Base Note 3: Nama Elemen",
      type: "text",
      placeholder: "Tahitian Vanilla of Sweet Forever",
      defaultValue: "Tahitian Vanilla of Sweet Forever",
      section: "Piramida Aroma",
    },
    {
      name: "baseNote3Desc",
      label: "Base Note 3: Makna Romantis",
      type: "text",
      placeholder: "Manisnya janji untuk terus menua bersama hingga hela napas terakhir.",
      defaultValue: "Manisnya janji untuk terus menua bersama hingga hela napas terakhir.",
      section: "Piramida Aroma",
    },

    // Section 4: 4 Botol Kenangan Aroma (Olfactory Snapshots)
    {
      name: "vial1Title",
      label: "Vial 1: Nama Kenangan",
      type: "text",
      placeholder: "Rainy Wool & Warm Coffee",
      defaultValue: "Rainy Wool & Warm Coffee",
      section: "4 Botol Kenangan",
    },
    {
      name: "vial1Season",
      label: "Vial 1: Momen / Waktu",
      type: "text",
      placeholder: "Autumn Evening • Senja Pertama di Bawah Payung",
      defaultValue: "Autumn Evening • Senja Pertama di Bawah Payung",
      section: "4 Botol Kenangan",
    },
    {
      name: "vial1Memory",
      label: "Vial 1: Narasi Kenangan",
      type: "textarea",
      placeholder: "Ceritakan kenangan...",
      defaultValue:
        "Saat kita berdesakan di bawah satu payung kecil di tengah rintik hujan kota, aroma mantel wol basah dan secangkir kopi panas yang kita bagi dua.",
      section: "4 Botol Kenangan",
    },
    {
      name: "vial1ScentNotes",
      label: "Vial 1: Jejak Aroma",
      type: "text",
      placeholder: "Petrichor, Steamed Milk, Espresso & Wool",
      defaultValue: "Petrichor, Steamed Milk, Espresso & Wool",
      section: "4 Botol Kenangan",
    },

    {
      name: "vial2Title",
      label: "Vial 2: Nama Kenangan",
      type: "text",
      placeholder: "Sunlit Linen & Morning Whispers",
      defaultValue: "Sunlit Linen & Morning Whispers",
      section: "4 Botol Kenangan",
    },
    {
      name: "vial2Season",
      label: "Vial 2: Momen / Waktu",
      type: "text",
      placeholder: "Sunday Dawn • Keheningan Pagi Tanpa Tergesa",
      defaultValue: "Sunday Dawn • Keheningan Pagi Tanpa Tergesa",
      section: "4 Botol Kenangan",
    },
    {
      name: "vial2Memory",
      label: "Vial 2: Narasi Kenangan",
      type: "textarea",
      placeholder: "Ceritakan kenangan...",
      defaultValue:
        "Cahaya matahari pagi yang menerobos tirai tipis, menyinari rambutmu yang terurai. Kita hanya diam menikmati teh hangat dan ketenangan yang sempurna.",
      section: "4 Botol Kenangan",
    },
    {
      name: "vial2ScentNotes",
      label: "Vial 2: Jejak Aroma",
      type: "text",
      placeholder: "White Tea, Crisp Cotton, Chamomile & Honey",
      defaultValue: "White Tea, Crisp Cotton, Chamomile & Honey",
      section: "4 Botol Kenangan",
    },

    {
      name: "vial3Title",
      label: "Vial 3: Nama Kenangan",
      type: "text",
      placeholder: "Midnight Ocean Breeze & Starlight",
      defaultValue: "Midnight Ocean Breeze & Starlight",
      section: "4 Botol Kenangan",
    },
    {
      name: "vial3Season",
      label: "Vial 3: Momen / Waktu",
      type: "text",
      placeholder: "Midsummer Night • Liburan Pertama ke Pesisir",
      defaultValue: "Midsummer Night • Liburan Pertama ke Pesisir",
      section: "4 Botol Kenangan",
    },
    {
      name: "vial3Memory",
      label: "Vial 3: Narasi Kenangan",
      type: "textarea",
      placeholder: "Ceritakan kenangan...",
      defaultValue:
        "Duduk di dermaga kayu sambil mencelupkan kaki ke air laut yang sejuk, menatap langit bertabur bintang sambil bertukar rahasia masa kecil.",
      section: "4 Botol Kenangan",
    },
    {
      name: "vial3ScentNotes",
      label: "Vial 3: Jejak Aroma",
      type: "text",
      placeholder: "Sea Salt, Driftwood, Coastal Sage & Night Sky",
      defaultValue: "Sea Salt, Driftwood, Coastal Sage & Night Sky",
      section: "4 Botol Kenangan",
    },

    {
      name: "vial4Title",
      label: "Vial 4: Nama Kenangan",
      type: "text",
      placeholder: "Sweet Brioche & Twilight Stroll",
      defaultValue: "Sweet Brioche & Twilight Stroll",
      section: "4 Botol Kenangan",
    },
    {
      name: "vial4Season",
      label: "Vial 4: Momen / Waktu",
      type: "text",
      placeholder: "Spring Dusk • Menyusuri Lorong Kota Berdua",
      defaultValue: "Spring Dusk • Menyusuri Lorong Kota Berdua",
      section: "4 Botol Kenangan",
    },
    {
      name: "vial4Memory",
      label: "Vial 4: Narasi Kenangan",
      type: "textarea",
      placeholder: "Ceritakan kenangan...",
      defaultValue:
        "Berjalan bergandengan tangan tanpa tujuan jelas, mencium aroma toko kue mentega yang baru matang, dan tertawa karena es krim yang menetes di jarimu.",
      section: "4 Botol Kenangan",
    },
    {
      name: "vial4ScentNotes",
      label: "Vial 4: Jejak Aroma",
      type: "text",
      placeholder: "Golden Brioche, Vanilla Bean, Roasted Almond & Sugar",
      defaultValue: "Golden Brioche, Vanilla Bean, Roasted Almond & Sugar",
      section: "4 Botol Kenangan",
    },

    // Section 5: Karakteristik & Metrik Daya Tahan
    {
      name: "sillageRating",
      label: "Sillage (Jejak Keharuman Jiwa)",
      type: "text",
      placeholder: "Enormous • Jejak kehangatanmu memenuhi setiap sudut relung jiwaku",
      defaultValue: "Enormous • Jejak kehangatanmu memenuhi setiap sudut relung jiwaku",
      section: "Metrik Karakteristik",
    },
    {
      name: "longevityRating",
      label: "Longevity (Daya Tahan Cinta)",
      type: "text",
      placeholder: "Eternal • Bertahan melampaui usia dan waktu",
      defaultValue: "Eternal • Bertahan melampaui usia dan waktu",
      section: "Metrik Karakteristik",
    },
    {
      name: "seasonality",
      label: "Kesesuaian Musim",
      type: "text",
      placeholder: "All Seasons • Mekar di musim semi, menenangkan di musim gugur, menghangatkan di musim dingin",
      defaultValue: "All Seasons • Mekar di musim semi, menenangkan di musim gugur, menghangatkan di musim dingin",
      section: "Metrik Karakteristik",
    },
    {
      name: "signatureAccord",
      label: "Signature Accord Utama",
      type: "text",
      placeholder: "Pure Irreplaceable Love • Cinta Sejati yang Tak Tergantikan",
      defaultValue: "Pure Irreplaceable Love • Cinta Sejati yang Tak Tergantikan",
      section: "Metrik Karakteristik",
    },

    // Section 6: Warna, Suasana, Tombol Semprotan & Musik
    {
      name: "spritzButtonText",
      label: "Teks Tombol Semprotan Aroma",
      type: "text",
      placeholder: "Semprotkan Parfum Cinta",
      defaultValue: "Semprotkan Parfum Cinta",
      section: "Suasana & Musik",
    },
    {
      name: "spritzSuccessMessage",
      label: "Pesan Interaksi Semprotan Sukses",
      type: "text",
      placeholder: "Kabut wewangian emas merebak... memenuhi semesta dengan aroma kasihmu.",
      defaultValue: "Kabut wewangian emas merebak... memenuhi semesta dengan aroma kasihmu.",
      section: "Suasana & Musik",
    },
    {
      name: "primaryColor",
      label: "Warna Emas Sampanye (Champagne Gold)",
      type: "color",
      defaultValue: "#e6c587",
      section: "Suasana & Musik",
    },
    {
      name: "secondaryColor",
      label: "Warna Mawar Anggun (Dusty Rose)",
      type: "color",
      defaultValue: "#d47a88",
      section: "Suasana & Musik",
    },
    {
      name: "accentColor",
      label: "Warna Kristal Flacon (Crystal Amber)",
      type: "color",
      defaultValue: "#f59e0b",
      section: "Suasana & Musik",
    },
    {
      name: "musicTrack",
      label: "URL Musik Latar Waltz Paris (Opsional)",
      type: "text",
      placeholder: "https://example.com/audio/paris-romance-waltz.mp3",
      defaultValue: "https://cdn.pixabay.com/download/audio/2022/11/06/audio_c350170a7b.mp3?filename=paris-romance-waltz-125439.mp3",
      section: "Suasana & Musik",
    },
  ],
  sample: {
    recipientName: "Aurelia Genevieve",
    senderName: "Julian de Valois",
    flaconBatchNo: "N°07-AMOUR-ETERNEL",
    perfumeName: "L'Éternel Rendez-Vous",
    perfumeConcentration: "Extrait de Parfum • 100% Pure Devotion",
    formulationDate: "Malam Saat Jiwa Ini Terpikat Selamanya",
    atelierLocation: "Atelier de Lettera • Place Vendôme, Paris",
    dedicationQuote:
      "Untuk jiwa yang kehadirannya adalah wewangian terindah yang pernah dihirup oleh semesta. Tak ada bunga di taman Versailles yang mampu menandingi kehangatan aromamu.",
    letterTitle: "Formulasi Rahasia di Balik Setiap Detak Jantungku",
    letterDate: "Paris, Di Bawah Cahaya Rembulan & Semerbak Melati",
    mainMessage:
      "Aurelia yang teramat kucintai,\n\nMereka berkata bahwa penciuman adalah pintu memori manusia yang paling murni dan tak terbantahkan. Maka malam ini, di tengah heningnya ruang peracikan wewangian ini, aku menyadari bahwa seluruh hidupku sebelum bertemu denganmu hanyalah halaman hampa tanpa aroma.\n\nSetiap kali kamu mendekat, udara di sekitarku seketika berubah. Ada aroma kelembutan yang tidak bisa diracik dari kelopak mawar termahal di Grasse sekalipun; ada kehangatan yang tak mampu ditiru oleh amber dan cendana paling langka. Kehadiranmu adalah harmoni sempurna antara ketenangan fajar dan misteri bintang malam.\n\nBotol ini kuciptakan bukan untuk menyaingi keindahanmu, melainkan sebagai tempatku menyimpan setiap desah tawamu, setiap tatapan matamu yang teduh, dan setiap janji bisu yang kita rajut di bawah langit malam. Selama cairan emas ini bernapas, cintaku padamu akan terus mengalir, tak lekang oleh waktu, dan selalu menemukan jalan kembali ke pelukanmu.",
    letterSignoff: "Dengan seluruh aroma rindu yang tak pernah pudar,",
    topNote1Name: "Bergamot of First Glimpse",
    topNote1Desc: "Kesegaran debaran pertama saat mata kita bersitatap.",
    topNote2Name: "Sparkling Pear of Sweet Laughter",
    topNote2Desc: "Manisnya tawa renyahmu yang selalu mencairkan segala gundah duniaku.",
    topNote3Name: "Pink Pepper of Electric Touch",
    topNote3Desc: "Percikan kehangatan elektrik saat jemari kita pertama kali bertaut erat.",
    heartNote1Name: "Damask Rose of Vulnerable Whispers",
    heartNote1Desc: "Mekarnya kejujuran saat kita saling menceritakan kerapuhan hati tanpa takut dihakimi.",
    heartNote2Name: "Midnight Jasmine of Safe Embraces",
    heartNote2Desc: "Ketenangan semerbak saat kepalamu bersandar nyaman di bahuku di ujung hari yang lelah.",
    heartNote3Name: "French Lavender of Peaceful Solace",
    heartNote3Desc: "Rasa damai tak terkatakan saat mengetahui bahwa rumah sejatiku adalah dirimu.",
    baseNote1Name: "Warm Amber of Unshakable Devotion",
    baseNote1Desc: "Bara kesetiaan yang mengakar kuat di palung jiwaku, tak pernah pudar oleh waktu.",
    baseNote2Name: "Cedarwood of Shared Future Dreams",
    baseNote2Desc: "Kekokohan pilar mimpi rumah tangga dan masa depan yang kita bangun berdampingan.",
    baseNote3Name: "Tahitian Vanilla of Sweet Forever",
    baseNote3Desc: "Manisnya janji untuk terus menua bersama hingga hela napas terakhir.",
    vial1Title: "Rainy Wool & Warm Coffee",
    vial1Season: "Autumn Evening • Senja Pertama di Bawah Payung",
    vial1Memory:
      "Saat kita berdesakan di bawah satu payung kecil di tengah rintik hujan kota, aroma mantel wol basah dan secangkir kopi panas yang kita bagi dua.",
    vial1ScentNotes: "Petrichor, Steamed Milk, Espresso & Wool",
    vial2Title: "Sunlit Linen & Morning Whispers",
    vial2Season: "Sunday Dawn • Keheningan Pagi Tanpa Tergesa",
    vial2Memory:
      "Cahaya matahari pagi yang menerobos tirai tipis, menyinari rambutmu yang terurai. Kita hanya diam menikmati teh hangat dan ketenangan yang sempurna.",
    vial2ScentNotes: "White Tea, Crisp Cotton, Chamomile & Honey",
    vial3Title: "Midnight Ocean Breeze & Starlight",
    vial3Season: "Midsummer Night • Liburan Pertama ke Pesisir",
    vial3Memory:
      "Duduk di dermaga kayu sambil mencelupkan kaki ke air laut yang sejuk, menatap langit bertabur bintang sambil bertukar rahasia masa kecil.",
    vial3ScentNotes: "Sea Salt, Driftwood, Coastal Sage & Night Sky",
    vial4Title: "Sweet Brioche & Twilight Stroll",
    vial4Season: "Spring Dusk • Menyusuri Lorong Kota Berdua",
    vial4Memory:
      "Berjalan bergandengan tangan tanpa tujuan jelas, mencium aroma toko kue mentega yang baru matang, dan tertawa karena es krim yang menetes di jarimu.",
    vial4ScentNotes: "Golden Brioche, Vanilla Bean, Roasted Almond & Sugar",
    sillageRating: "Enormous • Jejak kehangatanmu memenuhi setiap sudut relung jiwaku",
    longevityRating: "Eternal • Bertahan melampaui usia dan waktu",
    seasonality: "All Seasons • Mekar di musim semi, menenangkan di musim gugur, menghangatkan di musim dingin",
    signatureAccord: "Pure Irreplaceable Love • Cinta Sejati yang Tak Tergantikan",
    spritzButtonText: "Semprotkan Parfum Cinta",
    spritzSuccessMessage: "Kabut wewangian emas merebak... memenuhi semesta dengan aroma kasihmu.",
    primaryColor: "#e6c587",
    secondaryColor: "#d47a88",
    accentColor: "#f59e0b",
    musicTrack: "https://cdn.pixabay.com/download/audio/2022/11/06/audio_c350170a7b.mp3?filename=paris-romance-waltz-125439.mp3",
  },
};
