import type { TemplateMeta } from "../types";

export const tourbillonLoveTemplate: TemplateMeta = {
  slug: "tourbillon-love",
  name: "L'Horlogerie de l'Amour",
  category: "Surat Romantis",
  description:
    "Surat cinta mewah bertema seni perakitan jam tangan mekanik Swiss (Swiss Haute Horlogerie & The Eternal Timepiece). Menampilkan sertifikat kaliber resmi Geneva Seal, surat cinta cetak biru di meja kerja perakit jam, 4 komplikasi mekanisme waktu cinta (Tourbillon, Moon Phase, Minute Repeater, Equation of Time), 4 tonggak detik waktu sakral presisi tinggi (Chronometer Milestones), metrik spesifikasi kaliber dan cadangan daya abadi, serta tombol interaktif memutar mahkota jam (Wind the Crown) dengan alunan musik kotak mekanik jam yang memikat.",
  tagline: "L'Horlogerie de l'Amour: Menyelaraskan Detak Waktu Kita Menjadi Mahakarya Abadi",
  cardAccent: "border-amber-400/40 bg-gradient-to-br from-[#0a0f18] via-[#101726] to-[#0c121e] text-amber-200",
  highlights: [
    "Konsep Swiss Haute Horlogerie: Menjadikan Waktu Cintamu Sebagai Mahakarya Grand Complication",
    "Sertifikat Kaliber Resmi Jenewa (Poinçon de Genève) & Etiket Pembuat Jam",
    "Surat Pengakuan di Meja Horologis (The Horologist's Drafting Dispatch)",
    "4 Komplikasi Mekanisme Waktu Cinta (Tourbillon, Moon Phase, Repeater, Equation of Time)",
    "4 Tonggak Detik Waktu Sakral (Chronometer Milestones) Presisi Tinggi",
    "Interaksi Memutar Mahkota Jam (Wind the Crown) & Melodi Kotak Musik Mekanis",
  ],
  fields: [
    // Section 1: Sertifikat Kaliber Jam & Geneva Seal
    {
      name: "recipientName",
      label: "Nama Sang Penguasa Waktu (The Keeper of My Seconds)",
      type: "text",
      placeholder: "Genevieve Vivienne",
      required: true,
      isRecipient: true,
      section: "Sertifikat Kaliber Jam",
    },
    {
      name: "senderName",
      label: "Nama Pembuat Jam (The Master Horologist)",
      type: "text",
      placeholder: "Alexandre de Montmirail",
      required: true,
      section: "Sertifikat Kaliber Jam",
    },
    {
      name: "calibreNo",
      label: "Nomor Seri Kaliber Mesin",
      type: "text",
      placeholder: "CALIBRE-ETERNAL-N°12",
      defaultValue: "CALIBRE-ETERNAL-N°12",
      section: "Sertifikat Kaliber Jam",
    },
    {
      name: "timepieceName",
      label: "Nama Mahakarya Jam",
      type: "text",
      placeholder: "The Grand Tourbillon of Two Hearts",
      defaultValue: "The Grand Tourbillon of Two Hearts",
      section: "Sertifikat Kaliber Jam",
    },
    {
      name: "certificationStandard",
      label: "Standar Sertifikasi Presisi",
      type: "text",
      placeholder: "Poinçon de Genève • Geneva Seal Quality Standard",
      defaultValue: "Poinçon de Genève • Geneva Seal Quality Standard",
      section: "Sertifikat Kaliber Jam",
    },
    {
      name: "manufactureLocation",
      label: "Lokasi Bengkel Horologi",
      type: "text",
      placeholder: "Manufacture de Lettera • Vallée de Joux, Switzerland",
      defaultValue: "Manufacture de Lettera • Vallée de Joux, Switzerland",
      section: "Sertifikat Kaliber Jam",
    },
    {
      name: "synchronizationDate",
      label: "Tanggal Sinkronisasi Detik Pertama",
      type: "text",
      placeholder: "Malam Saat Detak Jantung Kita Pertama Kali Selaras",
      defaultValue: "Malam Saat Detak Jantung Kita Pertama Kali Selaras",
      section: "Sertifikat Kaliber Jam",
    },
    {
      name: "dialEngravingQuote",
      label: "Grafir Emas pada Pelat Jam (Dial Engraving)",
      type: "textarea",
      placeholder: "Kutipan grafir di balik tutup kristal safir...",
      defaultValue:
        "Di antara miliaran putaran jarum jam di semesta, seluruh detik hidupku kini berdetak hanya untukmu. Waktu tak lagi berlalu; waktu kini tinggal bersamamu.",
      section: "Sertifikat Kaliber Jam",
    },

    // Section 2: Surat di Meja Horologis
    {
      name: "dispatchTitle",
      label: "Judul Surat di Meja Horologis",
      type: "text",
      placeholder: "Cetak Biru Waktu: Presisi Abadi di Setiap Detak Jantungku",
      defaultValue: "Cetak Biru Waktu: Presisi Abadi di Setiap Detak Jantungku",
      section: "Surat di Meja Horologis",
    },
    {
      name: "dispatchDate",
      label: "Waktu & Tempat Penulisan Surat",
      type: "text",
      placeholder: "Vallée de Joux, Di Tengah Bunyi Detak Mekanis Jam Meja",
      defaultValue: "Vallée de Joux, Di Tengah Bunyi Detak Mekanis Jam Meja",
      section: "Surat di Meja Horologis",
    },
    {
      name: "mainMessage",
      label: "Isi Surat Cinta Horologis",
      type: "textarea",
      placeholder: "Tuliskan isi surat cinta mendalam tentang waktu dan keabadian...",
      defaultValue:
        "Genevieve yang teramat kucintai,\n\nSeorang perakit jam menghabiskan seluruh usianya menatap roda-roda gigi renik melalui lensa kaca pembesar, berusaha menundukkan sesuatu yang paling angkuh di alam raya ini: sang waktu. Namun malam ini, di tengah heningnya bengkel kerja ini, aku menyadari bahwa sebelum mengenalmu, aku hanyalah perakit detik-detik hampa yang tak memiliki tujuan.\n\nKehadiranmu mengubah segalanya. Kamu adalah pegas utama yang memberi daya pada seluruh jiwaku; kamu adalah keseimbangan tourbillon yang menepis tarikan gravitasi duniawi agar hatiku selalu bergetar stabil dalam mencintaimu. Saat bersamamu, satu detik terasa mekar menjadi seribu bunga; dan saat merindukanmu, jarum jam seolah menolak bergerak karena enggan berjalan tanpamu.\n\nMahakarya jam ini kurakit dengan tangan gemetar penuh rasa syukur. Setiap komponen emas, setiap batu rubi penahan gesekan, dan setiap denting loncengnya kupersembahkan sebagai janji: bahwa selama bumi masih berputar pada porosnya, cintaku padamu tidak akan pernah mengalami perlambatan, tidak akan aus oleh gesekan masa, dan akan selalu tepat waktu memelukmu di setiap fajar kehidupan.",
      section: "Surat di Meja Horologis",
    },
    {
      name: "dispatchSignoff",
      label: "Kalimat Penutup Surat",
      type: "text",
      placeholder: "Dengan seluruh detik jiwa yang terus berputar untukmu,",
      defaultValue: "Dengan seluruh detik jiwa yang terus berputar untukmu,",
      section: "Surat di Meja Horologis",
    },

    // Section 3: 4 Komplikasi Mekanisme Waktu Cinta
    {
      name: "complication1Title",
      label: "Komplikasi 1: Nama Mekanisme",
      type: "text",
      placeholder: "The Perpetual Tourbillon (Penyeimbang Gravitasi Jiwa)",
      defaultValue: "The Perpetual Tourbillon (Penyeimbang Gravitasi Jiwa)",
      section: "4 Komplikasi Waktu",
    },
    {
      name: "complication1Subtitle",
      label: "Komplikasi 1: Fungsi Mekanis",
      type: "text",
      placeholder: "Penetralisir Efek Gravitasi Bumi pada Detak Jantung",
      defaultValue: "Penetralisir Efek Gravitasi Bumi pada Detak Jantung",
      section: "4 Komplikasi Waktu",
    },
    {
      name: "complication1Story",
      label: "Komplikasi 1: Filosofi Romantis",
      type: "textarea",
      placeholder: "Uraikan filosofi komplikasi ini...",
      defaultValue:
        "Sebagaimana sangkar tourbillon berputar 360 derajat untuk menetralkan tarikan gravitasi agar jam tetap berdetak akurat, demikianlah komitmenku untuk selalu berputar menjaga keseimbangan emosi dan ego agar keharmonisan kita tak pernah runtuh.",
      section: "4 Komplikasi Waktu",
    },
    {
      name: "complication1Meaning",
      label: "Komplikasi 1: Janji Waktu",
      type: "text",
      placeholder: "Janji presisi...",
      defaultValue: "Kestabilan rasa yang tak akan terpengaruh oleh pasang surut keadaan dunia.",
      section: "4 Komplikasi Waktu",
    },

    {
      name: "complication2Title",
      label: "Komplikasi 2: Nama Mekanisme",
      type: "text",
      placeholder: "The Astronomical Moon Phase (Fase Rembulan Kerinduan)",
      defaultValue: "The Astronomical Moon Phase (Fase Rembulan Kerinduan)",
      section: "4 Komplikasi Waktu",
    },
    {
      name: "complication2Subtitle",
      label: "Komplikasi 2: Fungsi Mekanis",
      type: "text",
      placeholder: "Penghitung Siklus 29,5 Hari Pasang Surut Kerinduan",
      defaultValue: "Penghitung Siklus 29,5 Hari Pasang Surut Kerinduan",
      section: "4 Komplikasi Waktu",
    },
    {
      name: "complication2Story",
      label: "Komplikasi 2: Filosofi Romantis",
      type: "textarea",
      placeholder: "Uraikan filosofi komplikasi ini...",
      defaultValue:
        "Piringan emas biru lapis lazuli yang melacak wajah bulan di langit malam. Di saat bulan sabit ataupun purnama sempurna, hatiku selalu tahu bahwa kita memandang langit yang sama, merawat kerinduan yang sama, dan menantikan fajar kepulangan yang sama.",
      section: "4 Komplikasi Waktu",
    },
    {
      name: "complication2Meaning",
      label: "Komplikasi 2: Janji Waktu",
      type: "text",
      placeholder: "Janji presisi...",
      defaultValue: "Rasa rindu yang setia menemani di setiap fase malam hingga matahari terbit.",
      section: "4 Komplikasi Waktu",
    },

    {
      name: "complication3Title",
      label: "Komplikasi 3: Nama Mekanisme",
      type: "text",
      placeholder: "The Acoustic Minute Repeater (Denting Lonceng Kejujuran)",
      defaultValue: "The Acoustic Minute Repeater (Denting Lonceng Kejujuran)",
      section: "4 Komplikasi Waktu",
    },
    {
      name: "complication3Subtitle",
      label: "Komplikasi 3: Fungsi Mekanis",
      type: "text",
      placeholder: "Lonceng Katedral Mini Pemukul Jam, Perempat, & Menit",
      defaultValue: "Lonceng Katedral Mini Pemukul Jam, Perempat, & Menit",
      section: "4 Komplikasi Waktu",
    },
    {
      name: "complication3Story",
      label: "Komplikasi 3: Filosofi Romantis",
      type: "textarea",
      placeholder: "Uraikan filosofi komplikasi ini...",
      defaultValue:
        "Dua palu baja yang memukul cincin gong emas menghasilkan denting merdu di dalam kegelapan. Mekanisme ini berbunyi setiap kali dua jiwa saling memanggil dalam doa, membuktikan bahwa kita tidak pernah benar-benar sendirian di dalam hening.",
      section: "4 Komplikasi Waktu",
    },
    {
      name: "complication3Meaning",
      label: "Komplikasi 3: Janji Waktu",
      type: "text",
      placeholder: "Janji presisi...",
      defaultValue: "Kehadiran batin yang selalu merespons setiap desah panggilan hatimu.",
      section: "4 Komplikasi Waktu",
    },

    {
      name: "complication4Title",
      label: "Komplikasi 4: Nama Mekanisme",
      type: "text",
      placeholder: "The Equation of Time (Persamaan Waktu Relatif)",
      defaultValue: "The Equation of Time (Persamaan Waktu Relatif)",
      section: "4 Komplikasi Waktu",
    },
    {
      name: "complication4Subtitle",
      label: "Komplikasi 4: Fungsi Mekanis",
      type: "text",
      placeholder: "Penyelarasan Waktu Matahari Sejati & Waktu Mekanis Hati",
      defaultValue: "Penyelarasan Waktu Matahari Sejati & Waktu Mekanis Hati",
      section: "4 Komplikasi Waktu",
    },
    {
      name: "complication4Story",
      label: "Komplikasi 4: Filosofi Romantis",
      type: "textarea",
      placeholder: "Uraikan filosofi komplikasi ini...",
      defaultValue:
        "Komplikasi paling langka yang mengukur selisih antara waktu jam dan waktu matahari nyata. Karena cinta memiliki hukum relativitasnya sendiri: satu jam bersamamu terasa berlalu dalam hitungan detik, dan satu hari tanpamu terasa bagai satu abad lamanya.",
      section: "4 Komplikasi Waktu",
    },
    {
      name: "complication4Meaning",
      label: "Komplikasi 4: Janji Waktu",
      type: "text",
      placeholder: "Janji presisi...",
      defaultValue: "Menghargai setiap detik keberadaanmu sebagai anugerah terbesar hidupku.",
      section: "4 Komplikasi Waktu",
    },

    // Section 4: 4 Tonggak Detik Waktu Sakral
    {
      name: "milestone1Time",
      label: "Tonggak 1: Waktu Presisi",
      type: "text",
      placeholder: "19:42:08 PM • Synchronized Heartbeat",
      defaultValue: "19:42:08 PM • Synchronized Heartbeat",
      section: "4 Tonggak Waktu Sakral",
    },
    {
      name: "milestone1Title",
      label: "Tonggak 1: Nama Momen",
      type: "text",
      placeholder: "Saat Jarum Detik Semesta Terhenti",
      defaultValue: "Saat Jarum Detik Semesta Terhenti",
      section: "4 Tonggak Waktu Sakral",
    },
    {
      name: "milestone1Story",
      label: "Tonggak 1: Narasi Detik Waktu",
      type: "textarea",
      placeholder: "Ceritakan detik waktu ini...",
      defaultValue:
        "Detik pertama saat mata kita saling bertemu di tengah riuhnya ruangan. Seluruh kebisingan kota seketika membisu, dan aku tahu jam hidupku baru saja dimulai.",
      section: "4 Tonggak Waktu Sakral",
    },
    {
      name: "milestone1Precision",
      label: "Tonggak 1: Tingkat Deviasi",
      type: "text",
      placeholder: "0.00 Detik Deviasi • Kemurnian Mutlak",
      defaultValue: "0.00 Detik Deviasi • Kemurnian Mutlak",
      section: "4 Tonggak Waktu Sakral",
    },

    {
      name: "milestone2Time",
      label: "Tonggak 2: Waktu Presisi",
      type: "text",
      placeholder: "02:15:34 AM • The Midnight Confession",
      defaultValue: "02:15:34 AM • The Midnight Confession",
      section: "4 Tonggak Waktu Sakral",
    },
    {
      name: "milestone2Title",
      label: "Tonggak 2: Nama Momen",
      type: "text",
      placeholder: "Bisikan di Luar Dimensi Jam",
      defaultValue: "Bisikan di Luar Dimensi Jam",
      section: "4 Tonggak Waktu Sakral",
    },
    {
      name: "milestone2Story",
      label: "Tonggak 2: Narasi Detik Waktu",
      type: "textarea",
      placeholder: "Ceritakan detik waktu ini...",
      defaultValue:
        "Larut malam saat kita saling membongkar dinding pertahanan diri di telepon, mengakui ketakutan dan kerapuhan tanpa rasa cemas akan ditinggalkan.",
      section: "4 Tonggak Waktu Sakral",
    },
    {
      name: "milestone2Precision",
      label: "Tonggak 2: Tingkat Deviasi",
      type: "text",
      placeholder: "+0.01 Detik Kehangatan Jiwa",
      defaultValue: "+0.01 Detik Kehangatan Jiwa",
      section: "4 Tonggak Waktu Sakral",
    },

    {
      name: "milestone3Time",
      label: "Tonggak 3: Waktu Presisi",
      type: "text",
      placeholder: "06:30:12 AM • The Golden Dawn Awakening",
      defaultValue: "06:30:12 AM • The Golden Dawn Awakening",
      section: "4 Tonggak Waktu Sakral",
    },
    {
      name: "milestone3Title",
      label: "Tonggak 3: Nama Momen",
      type: "text",
      placeholder: "Fajar Rumah Jiwa yang Abadi",
      defaultValue: "Fajar Rumah Jiwa yang Abadi",
      section: "4 Tonggak Waktu Sakral",
    },
    {
      name: "milestone3Story",
      label: "Tonggak 3: Narasi Detik Waktu",
      type: "textarea",
      placeholder: "Ceritakan detik waktu ini...",
      defaultValue:
        "Pagi tenang saat secangkir teh mengepul di meja, melihatmu tersenyum dengan rambut berantakan, menyadari bahwa aku tak lagi butuh mencari rumah di tempat lain.",
      section: "4 Tonggak Waktu Sakral",
    },
    {
      name: "milestone3Precision",
      label: "Tonggak 3: Tingkat Deviasi",
      type: "text",
      placeholder: "Kedamaian Fajar Sempurna",
      defaultValue: "Kedamaian Fajar Sempurna",
      section: "4 Tonggak Waktu Sakral",
    },

    {
      name: "milestone4Time",
      label: "Tonggak 4: Waktu Presisi",
      type: "text",
      placeholder: "23:59:60 PM • The Perpetual Leap Second",
      defaultValue: "23:59:60 PM • The Perpetual Leap Second",
      section: "4 Tonggak Waktu Sakral",
    },
    {
      name: "milestone4Title",
      label: "Tonggak 4: Nama Momen",
      type: "text",
      placeholder: "Detik Kabisat Cinta yang Menolak Berakhir",
      defaultValue: "Detik Kabisat Cinta yang Menolak Berakhir",
      section: "4 Tonggak Waktu Sakral",
    },
    {
      name: "milestone4Story",
      label: "Tonggak 4: Narasi Detik Waktu",
      type: "textarea",
      placeholder: "Ceritakan detik waktu ini...",
      defaultValue:
        "Satu detik ekstra yang disisipkan semesta sebelum hari berganti, waktu di mana aku selalu memperbarui janjiku untuk mencintaimu lebih dalam di hari esok.",
      section: "4 Tonggak Waktu Sakral",
    },
    {
      name: "milestone4Precision",
      label: "Tonggak 4: Tingkat Deviasi",
      type: "text",
      placeholder: "Keabadian Tanpa Batas Akhir",
      defaultValue: "Keabadian Tanpa Batas Akhir",
      section: "4 Tonggak Waktu Sakral",
    },

    // Section 5: Spesifikasi Mesin Kaliber & Metrik Daya
    {
      name: "powerReserve",
      label: "Cadangan Daya (Power Reserve)",
      type: "text",
      placeholder: "Infinite Hours • Ditenagai otomatis oleh detak cinta tanpa henti",
      defaultValue: "Infinite Hours • Ditenagai otomatis oleh detak cinta tanpa henti",
      section: "Spesifikasi Kaliber Mesin",
    },
    {
      name: "vibrationFrequency",
      label: "Frekuensi Getaran Kaliber",
      type: "text",
      placeholder: "28,800 VPH • Vibrations of Passion per Hour",
      defaultValue: "28,800 VPH • Vibrations of Passion per Hour",
      section: "Spesifikasi Kaliber Mesin",
    },
    {
      name: "jewelCount",
      label: "Batu Rubi Penahan Gesekan (Jewels)",
      type: "text",
      placeholder: "32 Sacred Jewels • Menghilangkan segala gesekan ego dalam hubungan",
      defaultValue: "32 Sacred Jewels • Menghilangkan segala gesekan ego dalam hubungan",
      section: "Spesifikasi Kaliber Mesin",
    },
    {
      name: "waterResistance",
      label: "Ketahanan Lingkungan (Water Resistance)",
      type: "text",
      placeholder: "Immersion Proof • Tahan dan kokoh menghadapi segala badai kehidupan",
      defaultValue: "Immersion Proof • Tahan dan kokoh menghadapi segala badai kehidupan",
      section: "Spesifikasi Kaliber Mesin",
    },

    // Section 6: Warna, Mahkota Jam & Musik Mekanik
    {
      name: "windButtonText",
      label: "Teks Tombol Pemutar Mahkota",
      type: "text",
      placeholder: "Putar Mahkota Jam Cinta",
      defaultValue: "Putar Mahkota Jam Cinta",
      section: "Mahkota Jam & Musik",
    },
    {
      name: "windSuccessMessage",
      label: "Pesan Interaksi Mahkota Diputar",
      type: "text",
      placeholder: "Roda gigi emas berputar merdu... daya cadangan cinta terisi penuh 100%!",
      defaultValue: "Roda gigi emas berputar merdu... daya cadangan cinta terisi penuh 100%!",
      section: "Mahkota Jam & Musik",
    },
    {
      name: "primaryColor",
      label: "Warna Emas Mawar (Polished Rose Gold)",
      type: "color",
      defaultValue: "#e0a96d",
      section: "Mahkota Jam & Musik",
    },
    {
      name: "secondaryColor",
      label: "Warna Jarum Baja Biru (Blued Steel)",
      type: "color",
      defaultValue: "#38bdf8",
      section: "Mahkota Jam & Musik",
    },
    {
      name: "accentColor",
      label: "Warna Kuningan Horologi (Horological Brass)",
      type: "color",
      defaultValue: "#d4af37",
      section: "Mahkota Jam & Musik",
    },
    {
      name: "musicTrack",
      label: "URL Musik Kotak Mekanik Jam / Harpsichord (Opsional)",
      type: "text",
      placeholder: "https://example.com/audio/mechanical-music-box.mp3",
      defaultValue: "https://cdn.pixabay.com/download/audio/2022/03/15/audio_c89b7b9cf4.mp3?filename=celestial-music-box-waltz-10928.mp3",
      section: "Mahkota Jam & Musik",
    },
  ],
  sample: {
    recipientName: "Genevieve Vivienne",
    senderName: "Alexandre de Montmirail",
    calibreNo: "CALIBRE-ETERNAL-N°12",
    timepieceName: "The Grand Tourbillon of Two Hearts",
    certificationStandard: "Poinçon de Genève • Geneva Seal Quality Standard",
    manufactureLocation: "Manufacture de Lettera • Vallée de Joux, Switzerland",
    synchronizationDate: "Malam Saat Detak Jantung Kita Pertama Kali Selaras",
    dialEngravingQuote:
      "Di antara miliaran putaran jarum jam di semesta, seluruh detik hidupku kini berdetak hanya untukmu. Waktu tak lagi berlalu; waktu kini tinggal bersamamu.",
    dispatchTitle: "Cetak Biru Waktu: Presisi Abadi di Setiap Detak Jantungku",
    dispatchDate: "Vallée de Joux, Di Tengah Bunyi Detak Mekanis Jam Meja",
    mainMessage:
      "Genevieve yang teramat kucintai,\n\nSeorang perakit jam menghabiskan seluruh usianya menatap roda-roda gigi renik melalui lensa kaca pembesar, berusaha menundukkan sesuatu yang paling angkuh di alam raya ini: sang waktu. Namun malam ini, di tengah heningnya bengkel kerja ini, aku menyadari bahwa sebelum mengenalmu, aku hanyalah perakit detik-detik hampa yang tak memiliki tujuan.\n\nKehadiranmu mengubah segalanya. Kamu adalah pegas utama yang memberi daya pada seluruh jiwaku; kamu adalah keseimbangan tourbillon yang menepis tarikan gravitasi duniawi agar hatiku selalu bergetar stabil dalam mencintaimu. Saat bersamamu, satu detik terasa mekar menjadi seribu bunga; dan saat merindukanmu, jarum jam seolah menolak bergerak karena enggan berjalan tanpamu.\n\nMahakarya jam ini kurakit dengan tangan gemetar penuh rasa syukur. Setiap komponen emas, setiap batu rubi penahan gesekan, dan setiap denting loncengnya kupersembahkan sebagai janji: bahwa selama bumi masih berputar pada porosnya, cintaku padamu tidak akan pernah mengalami perlambatan, tidak akan aus oleh gesekan masa, dan akan selalu tepat waktu memelukmu di setiap fajar kehidupan.",
    dispatchSignoff: "Dengan seluruh detik jiwa yang terus berputar untukmu,",
    complication1Title: "The Perpetual Tourbillon (Penyeimbang Gravitasi Jiwa)",
    complication1Subtitle: "Penetralisir Efek Gravitasi Bumi pada Detak Jantung",
    complication1Story:
      "Sebagaimana sangkar tourbillon berputar 360 derajat untuk menetralkan tarikan gravitasi agar jam tetap berdetak akurat, demikianlah komitmenku untuk selalu berputar menjaga keseimbangan emosi dan ego agar keharmonisan kita tak pernah runtuh.",
    complication1Meaning: "Kestabilan rasa yang tak akan terpengaruh oleh pasang surut keadaan dunia.",
    complication2Title: "The Astronomical Moon Phase (Fase Rembulan Kerinduan)",
    complication2Subtitle: "Penghitung Siklus 29,5 Hari Pasang Surut Kerinduan",
    complication2Story:
      "Piringan emas biru lapis lazuli yang melacak wajah bulan di langit malam. Di saat bulan sabit ataupun purnama sempurna, hatiku selalu tahu bahwa kita memandang langit yang sama, merawat kerinduan yang sama, dan menantikan fajar kepulangan yang sama.",
    complication2Meaning: "Rasa rindu yang setia menemani di setiap fase malam hingga matahari terbit.",
    complication3Title: "The Acoustic Minute Repeater (Denting Lonceng Kejujuran)",
    complication3Subtitle: "Lonceng Katedral Mini Pemukul Jam, Perempat, & Menit",
    complication3Story:
      "Dua palu baja yang memukul cincin gong emas menghasilkan denting merdu di dalam kegelapan. Mekanisme ini berbunyi setiap kali dua jiwa saling memanggil dalam doa, membuktikan bahwa kita tidak pernah benar-benar sendirian di dalam hening.",
    complication3Meaning: "Kehadiran batin yang selalu merespons setiap desah panggilan hatimu.",
    complication4Title: "The Equation of Time (Persamaan Waktu Relatif)",
    complication4Subtitle: "Penyelarasan Waktu Matahari Sejati & Waktu Mekanis Hati",
    complication4Story:
      "Komplikasi paling langka yang mengukur selisih antara waktu jam dan waktu matahari nyata. Karena cinta memiliki hukum relativitasnya sendiri: satu jam bersamamu terasa berlalu dalam hitungan detik, dan satu hari tanpanya terasa bagai satu abad lamanya.",
    complication4Meaning: "Menghargai setiap detik keberadaanmu sebagai anugerah terbesar hidupku.",
    milestone1Time: "19:42:08 PM • Synchronized Heartbeat",
    milestone1Title: "Saat Jarum Detik Semesta Terhenti",
    milestone1Story:
      "Detik pertama saat mata kita saling bertemu di tengah riuhnya ruangan. Seluruh kebisingan kota seketika membisu, dan aku tahu jam hidupku baru saja dimulai.",
    milestone1Precision: "0.00 Detik Deviasi • Kemurnian Mutlak",
    milestone2Time: "02:15:34 AM • The Midnight Confession",
    milestone2Title: "Bisikan di Luar Dimensi Jam",
    milestone2Story:
      "Larut malam saat kita saling membongkar dinding pertahanan diri di telepon, mengakui ketakutan dan kerapuhan tanpa rasa cemas akan ditinggalkan.",
    milestone2Precision: "+0.01 Detik Kehangatan Jiwa",
    milestone3Time: "06:30:12 AM • The Golden Dawn Awakening",
    milestone3Title: "Fajar Rumah Jiwa yang Abadi",
    milestone3Story:
      "Pagi tenang saat secangkir teh mengepul di meja, melihatmu tersenyum dengan rambut berantakan, menyadari bahwa aku tak lagi butuh mencari rumah di tempat lain.",
    milestone3Precision: "Kedamaian Fajar Sempurna",
    milestone4Time: "23:59:60 PM • The Perpetual Leap Second",
    milestone4Title: "Detik Kabisat Cinta yang Menolak Berakhir",
    milestone4Story:
      "Satu detik ekstra yang disisipkan semesta sebelum hari berganti, waktu di mana aku selalu memperbarui janjiku untuk mencintaimu lebih dalam di hari esok.",
    milestone4Precision: "Keabadian Tanpa Batas Akhir",
    powerReserve: "Infinite Hours • Ditenagai otomatis oleh detak cinta tanpa henti",
    vibrationFrequency: "28,800 VPH • Vibrations of Passion per Hour",
    jewelCount: "32 Sacred Jewels • Menghilangkan segala gesekan ego dalam hubungan",
    waterResistance: "Immersion Proof • Tahan dan kokoh menghadapi segala badai kehidupan",
    windButtonText: "Putar Mahkota Jam Cinta",
    windSuccessMessage: "Roda gigi emas berputar merdu... daya cadangan cinta terisi penuh 100%!",
    primaryColor: "#e0a96d",
    secondaryColor: "#38bdf8",
    accentColor: "#d4af37",
    musicTrack: "https://cdn.pixabay.com/download/audio/2022/03/15/audio_c89b7b9cf4.mp3?filename=celestial-music-box-waltz-10928.mp3",
  },
};
