import type { TemplateMeta } from "../types";
import {
  VINTAGE_LOVE_COLOR_PRESETS,
  BACKGROUND_COLOR_PRESETS,
  CARD_COLOR_PRESETS,
  TEXT_COLOR_PRESETS,
} from "../color-presets";

export const vintageLoveTemplate: TemplateMeta = {
  slug: "vintage-love",
  name: "Vintage Love Letter & Wax Seal",
  category: "Romansa",
  tagline:
    "Surat cinta klasik beramplop segel lilin — cap pos retro, kertas perkamen bertekstur, foto kenangan, dan catatan rahasia.",
  description:
    "Sebuah pengalaman berkirim surat cinta nostalgia yang abadi. Dilengkapi dengan amplop bersegel lilin interaktif, stempel cap pos personal dengan nama kota & tanggal kenangan, lembaran kertas perkamen hangat, kartu foto film klasik, catatan rahasia tersembunyi, dan pemutar musik romantis.",
  cardAccent: "bg-rose-50 text-rose-800 ring-1 ring-rose-300",
  highlights: [
    "Amplop vintage antik dengan animasi segel lilin (wax seal 3D)",
    "Cap stempel pos retro dengan tanggal & kota kenangan berdua",
    "Kertas perkamen klasik bertekstur dengan tipografi anggun",
    "Kartu foto kenangan berbingkai film analog",
    "Catatan rahasia interaktif (Secret Love Note) yang bisa dibuka",
    "Tiga butir janji cinta manis berbingkai ornamen",
    "Pemutar audio instrumen romantis berputar",
  ],
  fields: [
    // --- SECTION: IDENTITAS & CAP POS AMPLOP ---
    {
      name: "recipientName",
      label: "Nama kekasih (penerima)",
      type: "text",
      placeholder: "Adinda Kirana",
      required: true,
      maxLength: 60,
      isRecipient: true,
      section: "envelope",
    },
    {
      name: "senderName",
      label: "Nama kamu (pengirim)",
      type: "text",
      placeholder: "Bima Arya",
      required: true,
      maxLength: 60,
      section: "envelope",
    },
    {
      name: "postmarkCity",
      label: "Kota kenangan cap pos",
      type: "text",
      placeholder: "Bandung, Jawa Barat",
      maxLength: 50,
      helperText: "Nama kota tempat cinta bersemi atau kenangan berharga terukir.",
      section: "envelope",
    },
    {
      name: "postmarkDate",
      label: "Tanggal cap pos",
      type: "text",
      placeholder: "21 September 2024",
      maxLength: 40,
      section: "envelope",
    },
    {
      name: "sealInitials",
      label: "Inisial segel lilin",
      type: "text",
      placeholder: "B & A",
      maxLength: 10,
      helperText: "Inisial namamu dan pasangan di tengah segel lilin (misal: B & A atau ❤️).",
      section: "envelope",
    },

    {
      name: "stampPhotoUrl",
      label: "Foto pribadi untuk prangko amplop",
      type: "text",
      placeholder:
        "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=400&q=80",
      maxLength: 1000,
      helperText: "Foto mini pasangan yang akan tercetak di dalam prangko vintage amplop.",
      section: "envelope",
    },
    {
      name: "loveAnniversary",
      label: "Hari jadian / Perayaan cinta",
      type: "text",
      placeholder: "14 Februari 2022 • Hari Pertama Bertemu",
      maxLength: 60,
      section: "envelope",
    },

    // --- SECTION: SURAT UTAMA ---
    {
      name: "title",
      label: "Judul surat cinta",
      type: "text",
      placeholder: "Sebuah Warkat Kasih Dari Lubuk Hati",
      required: true,
      maxLength: 100,
      section: "letter",
    },
    {
      name: "salutation",
      label: "Salam pembuka mesra",
      type: "text",
      placeholder: "Kepada Pemilik Senyum yang Selalu Kurindukan,",
      required: true,
      maxLength: 100,
      section: "letter",
    },
    {
      name: "letterLocation",
      label: "Lokasi penulisan warkat",
      type: "text",
      placeholder: "Ditulis dari sudut kedai kopi kenangan kita",
      maxLength: 80,
      section: "letter",
    },
    {
      name: "message",
      label: "Isi surat cinta",
      type: "textarea",
      placeholder:
        "Tuliskan kata-kata puitis, rasa rindu, dan pengakuan cintamu di sini...\n\nPisahkan setiap paragraf dengan baris kosong untuk menjaga keindahan tata letak perkamen.",
      required: true,
      maxLength: 4000,
      rows: 10,
      section: "letter",
    },
    {
      name: "closingStatement",
      label: "Kalimat penutup",
      type: "text",
      placeholder: "Selamanya mengagumi dan menyayangimu,",
      maxLength: 100,
      section: "letter",
    },
    {
      name: "signature",
      label: "Tanda tangan pengirim",
      type: "text",
      placeholder: "Bima Arya",
      maxLength: 60,
      section: "letter",
    },

    // --- SECTION: JAM SAKU PENGHITUNG WAKTU (POCKET WATCH COUNTER) ---
    {
      name: "anniversaryDate",
      label: "Tanggal mulai hubungan (untuk jam saku)",
      type: "text",
      placeholder: "2022-02-14",
      maxLength: 30,
      helperText: "Format YYYY-MM-DD (misal: 2022-02-14) agar jam saku antik dapat menghitung total hari, jam, menit & detik cinta secara live.",
      section: "counter",
    },
    {
      name: "counterSubtitle",
      label: "Kutipan romantis jam saku",
      type: "text",
      placeholder: "Detik demi detik bersamamu adalah anugerah terindah",
      maxLength: 120,
      section: "counter",
    },

    // --- SECTION: PIRINGAN HITAM VINYL GRAMOFON ---
    {
      name: "vinylSongTitle",
      label: "Judul lagu piringan hitam",
      type: "text",
      placeholder: "Can't Help Falling in Love",
      maxLength: 80,
      section: "vinyl",
    },
    {
      name: "vinylArtist",
      label: "Penyanyi / Komponis nostalgia",
      type: "text",
      placeholder: "Elvis Presley • Side A Track 01",
      maxLength: 80,
      section: "vinyl",
    },
    {
      name: "vinylSideNote",
      label: "Catatan tepi piringan hitam",
      type: "text",
      placeholder: "Lagu yang selalu berputar di kepala setiap kali merindukanmu.",
      maxLength: 140,
      section: "vinyl",
    },

    // --- SECTION: TIKET KERETA / BIOSKOP KLASIK (VINTAGE TICKET) ---
    {
      name: "ticketOrigin",
      label: "Titik keberangkatan tiket (Origin)",
      type: "text",
      placeholder: "Hari Pertama Bertemu",
      maxLength: 50,
      section: "ticket",
    },
    {
      name: "ticketDestination",
      label: "Tujuan akhir tiket (Destination)",
      type: "text",
      placeholder: "Menua Bersama Selamanya",
      maxLength: 50,
      section: "ticket",
    },
    {
      name: "ticketDate",
      label: "Masa berlaku tiket",
      type: "text",
      placeholder: "Seumur Hidup & Tak Berujung",
      maxLength: 50,
      section: "ticket",
    },
    {
      name: "ticketSeat",
      label: "Nomor kursi / gerbong",
      type: "text",
      placeholder: "Gerbong Kasih No. 01 (VIP)",
      maxLength: 50,
      section: "ticket",
    },
    {
      name: "ticketNote",
      label: "Pesan khusus pada tiket",
      type: "text",
      placeholder: "Tiket sekali jalan menuju kebahagiaan abadi, berlaku tanpa batas masa.",
      maxLength: 160,
      section: "ticket",
    },

    // --- SECTION: WARTA BERITA CINTA (VINTAGE HERALD NEWSPAPER) ---
    {
      name: "newspaperHeadline",
      label: "Tajuk utama koran (Headline)",
      type: "text",
      placeholder: "WARGA GEMPAR: DUA HATI RESMI TERIKAT JANJI SUCI",
      maxLength: 100,
      section: "newspaper",
    },
    {
      name: "newspaperSub",
      label: "Sub-tajuk berita koran",
      type: "text",
      placeholder: "Edisi Khusus Romansa • Terbit untuk Mengabadikan Kisah Terindah",
      maxLength: 120,
      section: "newspaper",
    },
    {
      name: "newspaperDate",
      label: "Tanggal edisi koran",
      type: "text",
      placeholder: "Edisi Kenangan Abadi",
      maxLength: 60,
      section: "newspaper",
    },
    {
      name: "newspaperBody",
      label: "Isi artikel berita cinta",
      type: "textarea",
      placeholder:
        "Kabar bahagia mengudara ke seluruh pelosok. Dua insan yang ditakdirkan bersama telah mengukir komitmen suci. Setiap detik yang terlewati menjadi saksi betapa tulusnya cinta yang mereka bangun bersama...",
      maxLength: 1000,
      rows: 4,
      section: "newspaper",
    },

    // --- SECTION: JEJAK BABAK KASIH (4 CHAPTERS) ---
    {
      name: "chapter1Title",
      label: "Babak I - Judul",
      type: "text",
      placeholder: "Babak I: Pertemuan Pertama",
      maxLength: 80,
      section: "chronicles",
    },
    {
      name: "chapter1Year",
      label: "Babak I - Waktu / Tahun",
      type: "text",
      placeholder: "Awal Pertemuan",
      maxLength: 40,
      section: "chronicles",
    },
    {
      name: "chapter1Story",
      label: "Babak I - Kisah",
      type: "textarea",
      placeholder: "Hari di mana tatap mata kita pertama kali bersirobok...",
      maxLength: 300,
      rows: 2,
      section: "chronicles",
    },
    {
      name: "chapter2Title",
      label: "Babak II - Judul",
      type: "text",
      placeholder: "Babak II: Mengikat Rasa",
      maxLength: 80,
      section: "chronicles",
    },
    {
      name: "chapter2Year",
      label: "Babak II - Waktu / Tahun",
      type: "text",
      placeholder: "Hari Jadian",
      maxLength: 40,
      section: "chronicles",
    },
    {
      name: "chapter2Story",
      label: "Babak II - Kisah",
      type: "textarea",
      placeholder: "Saat dua hati akhirnya berani saling mengakui dan berjanji untuk melangkah beriringan...",
      maxLength: 300,
      rows: 2,
      section: "chronicles",
    },
    {
      name: "chapter3Title",
      label: "Babak III - Judul",
      type: "text",
      placeholder: "Babak III: Badai yang Kita Lewati",
      maxLength: 80,
      section: "chronicles",
    },
    {
      name: "chapter3Year",
      label: "Babak III - Waktu / Tahun",
      type: "text",
      placeholder: "Ujian & Kedewasaan",
      maxLength: 40,
      section: "chronicles",
    },
    {
      name: "chapter3Story",
      label: "Babak III - Kisah",
      type: "textarea",
      placeholder: "Tak selamanya jalan berdua bertabur bunga, namun setiap badai justru semakin memperkokoh kasih kita...",
      maxLength: 300,
      rows: 2,
      section: "chronicles",
    },
    {
      name: "chapter4Title",
      label: "Babak IV - Judul",
      type: "text",
      placeholder: "Babak IV: Janji Menua Bersama",
      maxLength: 80,
      section: "chronicles",
    },
    {
      name: "chapter4Year",
      label: "Babak IV - Waktu / Tahun",
      type: "text",
      placeholder: "Masa Depan & Abadi",
      maxLength: 40,
      section: "chronicles",
    },
    {
      name: "chapter4Story",
      label: "Babak IV - Kisah",
      type: "textarea",
      placeholder: "Kini hingga rambut memutih, tanganku akan tetap menggenggam tanganmu menatap hari esok...",
      maxLength: 300,
      rows: 2,
      section: "chronicles",
    },

    // --- SECTION: TELEGRAM KILAT MESIN TIK (TYPEWRITER TELEGRAM) ---
    {
      name: "telegramMessage",
      label: "Isi telegram kilat mesin tik",
      type: "textarea",
      placeholder:
        "BERITA KILAT STOP DUA HATI TELAH BERPADU STOP TIDAK ADA YANG BISA MEMISAHKAN KITA LAGI STOP SAYANG KAMU SELALU STOP",
      maxLength: 400,
      rows: 3,
      helperText: "Gunakan kata 'STOP' ala telegram antik kawat kilat untuk nuansa vintage yang autentik.",
      section: "telegram",
    },

    // --- SECTION: FOTO KENANGAN & PESAN RAHASIA ---
    {
      name: "photoUrl",
      label: "Tautan foto kenangan pertama (Film Frame 1)",
      type: "text",
      placeholder:
        "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=1000&q=80",
      maxLength: 1000,
      helperText: "Foto berdua dengan gaya klasik yang akan dibingkai seperti cetakan foto film.",
      section: "memories",
    },
    {
      name: "photoCaption",
      label: "Catatan kecil di bawah foto 1",
      type: "text",
      placeholder: "Momen pertama kali kita berbincang hingga senja berganti bintang.",
      maxLength: 140,
      section: "memories",
    },
    {
      name: "photo2Url",
      label: "Tautan foto kenangan kedua (Film Frame 2)",
      type: "text",
      placeholder:
        "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=1000&q=80",
      maxLength: 1000,
      helperText: "Foto kedua untuk melengkapi galeri film analog di lembaran surat.",
      section: "memories",
    },
    {
      name: "photo2Caption",
      label: "Catatan kecil di bawah foto 2",
      type: "text",
      placeholder: "Tawa lepas di tepi pantai saat kita berjanji untuk saling menjaga.",
      maxLength: 140,
      section: "memories",
    },
    {
      name: "secretNoteTitle",
      label: "Judul catatan rahasia",
      type: "text",
      placeholder: "Bisikan Rahasia untuk Hatimu ✨",
      maxLength: 80,
      section: "memories",
    },
    {
      name: "secretNoteContent",
      label: "Isi catatan rahasia tersembunyi",
      type: "textarea",
      placeholder:
        "Sebuah pesan manis yang hanya akan terbuka saat pasanganmu mengetuk/mengklik kartu rahasia ini...",
      maxLength: 600,
      rows: 4,
      section: "memories",
    },

    // --- SECTION: JANJI CINTA ---
    {
      name: "promisesTitle",
      label: "Judul seksi janji",
      type: "text",
      placeholder: "Tiga Janji Setia untuk Hari Esok",
      maxLength: 80,
      section: "promises",
    },
    {
      name: "promise1",
      label: "Janji 1",
      type: "text",
      placeholder: "Selalu mendengarkan ceritamu dengan penuh ketulusan di setiap hari lelahmu.",
      maxLength: 160,
      section: "promises",
    },
    {
      name: "promise2",
      label: "Janji 2",
      type: "text",
      placeholder: "Menjadi tempat pulang yang paling aman dan menghangatkan hatimu.",
      maxLength: 160,
      section: "promises",
    },
    {
      name: "promise3",
      label: "Janji 3",
      type: "text",
      placeholder: "Terus memilihmu dan mencintaimu dalam setiap babak perjalanan kita.",
      maxLength: 160,
      section: "promises",
    },

    // --- SECTION: TEMA & MUSIK ---
    {
      name: "primaryColor",
      label: "Warna segel lilin & ornamen aksen",
      type: "color",
      defaultValue: "#781d2f",
      helperText: "Warna stempel segel lilin 3D, cap pos retro, dan garis hiasan klasik.",
      colorPresets: VINTAGE_LOVE_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "backgroundColor",
      label: "Warna latar belakang halaman",
      type: "color",
      defaultValue: "#f6f1ea",
      helperText: "Warna kanvas di luar lembaran amplop.",
      colorPresets: BACKGROUND_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "cardColor",
      label: "Warna kertas perkamen",
      type: "color",
      defaultValue: "#fffdf9",
      helperText: "Warna lembaran kertas surat klasik.",
      colorPresets: CARD_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "textColor",
      label: "Warna teks judul & cap",
      type: "color",
      defaultValue: "#3e1b24",
      helperText: "Warna judul dan salam pembuka.",
      colorPresets: TEXT_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "bodyTextColor",
      label: "Warna teks isi surat",
      type: "color",
      defaultValue: "#4a3b32",
      helperText: "Warna paragraf tulisan surat perkamen.",
      colorPresets: TEXT_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "musicTitle",
      label: "Judul audio pengiring (opsional)",
      type: "text",
      placeholder: "Romantic Music Box & Cello",
      maxLength: 80,
      section: "theme",
    },
    {
      name: "bgMusicUrl",
      label: "Tautan audio pengiring (.mp3)",
      type: "text",
      placeholder: "https://cdn.pixabay.com/download/audio/2022/05/16/audio_c0c1b72e04.mp3",
      maxLength: 1000,
      helperText: "Tautan langsung ke file audio mp3 romantis klasik.",
      section: "theme",
    },
  ],
  sample: {
    recipientName: "Adinda Kirana",
    senderName: "Bima Arya",
    postmarkCity: "Bandung, Jawa Barat",
    postmarkDate: "21 September 2024",
    sealInitials: "B & A",
    stampPhotoUrl:
      "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=400&q=80",
    loveAnniversary: "14 Februari 2022 • Hari Pertama Bertemu",
    title: "Sebuah Warkat Kasih Dari Lubuk Hati",
    salutation: "Kepada Pemilik Senyum yang Selalu Kurindukan,",
    letterLocation: "Ditulis dari sudut kedai kopi kenangan kita",
    message:
      "Dinda,\n\nAda rasa hangat yang selalu merayap ke dadaku setiap kali mengingat caramu tertawa. Di antara miliaran manusia yang berjalan di bumi, bertemu dan berjalan bersamamu adalah kebetulan terindah yang paling kusyukuri dalam hidup.\n\nSurat ini kutulis bukan hanya untuk merayakan hari-hari manis yang telah kita lewati, namun juga sebagai pengingat abadi bahwa di setiap langkah esok, ada sepasang mata yang selalu bangga melihatmu dan hati yang selalu mendoakan bahagiamu.\n\nTerima kasih telah menjadi rumah tempatku pulang, dan pelita di kala malam terasa gelap. Aku mencintaimu lebih dari apa yang sanggup dirangkum oleh kata-kata.",
    closingStatement: "Selamanya mengagumi dan menyayangimu,",
    signature: "Bima Arya",

    // Sample data fitur tambahan mewah:
    anniversaryDate: "2022-02-14",
    counterSubtitle: "Detik demi detik bersamamu adalah anugerah terindah",

    vinylSongTitle: "Can't Help Falling in Love",
    vinylArtist: "Elvis Presley • Side A Track 01",
    vinylSideNote: "Lagu yang selalu berputar di kepala setiap kali merindukanmu.",

    ticketOrigin: "Pertemuan Pertama di Braga",
    ticketDestination: "Menua Bersama Selamanya",
    ticketDate: "Seumur Hidup & Tak Berujung",
    ticketSeat: "Gerbong Kasih No. 01 (VIP)",
    ticketNote: "Tiket sekali jalan menuju kebahagiaan abadi, berlaku tanpa batas masa.",

    newspaperHeadline: "WARGA GEMPAR: DUA HATI RESMI TERIKAT JANJI SUCI",
    newspaperSub: "Edisi Khusus Romansa • Terbit untuk Mengabadikan Kisah Terindah",
    newspaperDate: "Edisi Kenangan Abadi No. 781",
    newspaperBody:
      "Kabar bahagia mengudara ke seluruh pelosok. Dua insan yang ditakdirkan bersama telah mengukir komitmen suci. Setiap detik yang terlewati menjadi saksi betapa tulusnya cinta yang mereka bangun bersama. Menurut saksi mata, senyum bahagia keduanya merebak bagai musim semi abadi.",

    chapter1Title: "Babak I: Pertemuan Pertama",
    chapter1Year: "14 Februari 2022",
    chapter1Story:
      "Hari di mana tatap mata kita pertama kali bersirobok di kedai kopi itu. Senyum manismu seketika mengubah duniaku menjadi jauh lebih hangat dan berwarna.",

    chapter2Title: "Babak II: Mengikat Janji Kasih",
    chapter2Year: "21 September 2022",
    chapter2Story:
      "Di bawah temaram lampu kota, dua hati akhirnya berani saling mengakui dan berjanji untuk saling menggenggam tangan dalam setiap langkah ke depan.",

    chapter3Title: "Babak III: Badai yang Kita Lewati",
    chapter3Year: "Tahun 2023",
    chapter3Story:
      "Tak selamanya langit cerah, namun setiap kerikil dan badai justru membuktikan betapa kokohnya bahu kita untuk saling bersandar.",

    chapter4Title: "Babak IV: Menua Bersama",
    chapter4Year: "Hari Ini & Selamanya",
    chapter4Story:
      "Kini hingga rambut memutih dan langkah melambat, tanganku akan tetap erat menggenggam tanganmu dengan cinta yang tak pernah berkurang sedikit pun.",

    telegramMessage:
      "BERITA KILAT STOP DUA HATI TELAH RESMI BERPADU STOP TIDAK ADA YANG BISA MEMISAHKAN KITA LAGI STOP TERIMA KASIH TELAH MEMILIHKU STOP SAYANG KAMU SELALU STOP",

    photoUrl:
      "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=1000&q=80",
    photoCaption: "Kenangan senja saat kita berjanji untuk saling menjaga selamanya.",
    photo2Url:
      "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=1000&q=80",
    photo2Caption: "Tawa lepas di tepi pantai saat kita menyusuri ombak berdua.",
    secretNoteTitle: "Bisikan Rahasia untuk Hatimu ✨",
    secretNoteContent:
      "Jika suatu saat dunia terasa terlalu bising dan melelahkan, ingatlah bahwa kamu tidak pernah sendirian. Genggam tanganku, dan kita akan lalui semuanya bersama-sama.",
    promisesTitle: "Tiga Janji Setia untuk Hari Esok",
    promise1: "Selalu mendengarkan ceritamu dengan penuh ketulusan di setiap hari lelahmu.",
    promise2: "Menjadi tempat pulang yang paling aman dan menghangatkan hatimu.",
    promise3: "Terus memilihmu dan mencintaimu dalam setiap babak perjalanan kita.",
    primaryColor: "#781d2f",
    backgroundColor: "#f6f1ea",
    cardColor: "#fffdf9",
    textColor: "#3e1b24",
    bodyTextColor: "#4a3b32",
    musicTitle: "",
    bgMusicUrl: "",
  },
};
