import type { TemplateMeta } from "../types";
import {
  VINTAGE_LOVE_COLOR_PRESETS,
  BACKGROUND_COLOR_PRESETS,
  CARD_COLOR_PRESETS,
  TEXT_COLOR_PRESETS,
} from "../color-presets";

export const vintageLoveTemplate: TemplateMeta = {
  slug: "vintage-love",
  name: "Vintage Love Letter & Wax Seal",
  category: "Romansa",
  tagline:
    "Surat cinta klasik beramplop segel lilin — cap pos retro, kertas perkamen bertekstur, foto kenangan, dan catatan rahasia.",
  description:
    "Sebuah pengalaman berkirim surat cinta nostalgia yang abadi. Dilengkapi dengan amplop bersegel lilin interaktif, stempel cap pos personal dengan nama kota & tanggal kenangan, lembaran kertas perkamen hangat, kartu foto film klasik, catatan rahasia tersembunyi, dan pemutar musik romantis.",
  cardAccent: "bg-rose-50 text-rose-800 ring-1 ring-rose-300",
  highlights: [
    "Amplop vintage antik dengan animasi segel lilin (wax seal 3D)",
    "Cap stempel pos retro dengan tanggal & kota kenangan berdua",
    "Kertas perkamen klasik bertekstur dengan tipografi anggun",
    "Kartu foto kenangan berbingkai film analog",
    "Catatan rahasia interaktif (Secret Love Note) yang bisa dibuka",
    "Tiga butir janji cinta manis berbingkai ornamen",
    "Pemutar audio instrumen romantis berputar",
  ],
  fields: [
    // --- SECTION: IDENTITAS & CAP POS AMPLOP ---
    {
      name: "recipientName",
      label: "Nama kekasih (penerima)",
      type: "text",
      placeholder: "Adinda Kirana",
      required: true,
      maxLength: 60,
      isRecipient: true,
      section: "envelope",
    },
    {
      name: "senderName",
      label: "Nama kamu (pengirim)",
      type: "text",
      placeholder: "Bima Arya",
      required: true,
      maxLength: 60,
      section: "envelope",
    },
    {
      name: "postmarkCity",
      label: "Kota kenangan cap pos",
      type: "text",
      placeholder: "Bandung, Jawa Barat",
      maxLength: 50,
      helperText: "Nama kota tempat cinta bersemi atau kenangan berharga terukir.",
      section: "envelope",
    },
    {
      name: "postmarkDate",
      label: "Tanggal cap pos",
      type: "text",
      placeholder: "21 September 2024",
      maxLength: 40,
      section: "envelope",
    },
    {
      name: "sealInitials",
      label: "Inisial segel lilin",
      type: "text",
      placeholder: "B & A",
      maxLength: 10,
      helperText: "Inisial namamu dan pasangan di tengah segel lilin (misal: B & A atau ❤️).",
      section: "envelope",
    },

    {
      name: "stampPhotoUrl",
      label: "Foto pribadi untuk prangko amplop",
      type: "text",
      placeholder:
        "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=400&q=80",
      maxLength: 1000,
      helperText: "Foto mini pasangan yang akan tercetak di dalam prangko vintage amplop.",
      section: "envelope",
    },
    {
      name: "loveAnniversary",
      label: "Hari jadian / Perayaan cinta",
      type: "text",
      placeholder: "14 Februari 2022 • Hari Pertama Bertemu",
      maxLength: 60,
      section: "envelope",
    },

    // --- SECTION: SURAT UTAMA ---
    {
      name: "title",
      label: "Judul surat cinta",
      type: "text",
      placeholder: "Sebuah Warkat Kasih Dari Lubuk Hati",
      required: true,
      maxLength: 100,
      section: "letter",
    },
    {
      name: "salutation",
      label: "Salam pembuka mesra",
      type: "text",
      placeholder: "Kepada Pemilik Senyum yang Selalu Kurindukan,",
      required: true,
      maxLength: 100,
      section: "letter",
    },
    {
      name: "letterLocation",
      label: "Lokasi penulisan warkat",
      type: "text",
      placeholder: "Ditulis dari sudut kedai kopi kenangan kita",
      maxLength: 80,
      section: "letter",
    },
    {
      name: "message",
      label: "Isi surat cinta",
      type: "textarea",
      placeholder:
        "Tuliskan kata-kata puitis, rasa rindu, dan pengakuan cintamu di sini...\n\nPisahkan setiap paragraf dengan baris kosong untuk menjaga keindahan tata letak perkamen.",
      required: true,
      maxLength: 4000,
      rows: 10,
      section: "letter",
    },
    {
      name: "closingStatement",
      label: "Kalimat penutup",
      type: "text",
      placeholder: "Selamanya mengagumi dan menyayangimu,",
      maxLength: 100,
      section: "letter",
    },
    {
      name: "signature",
      label: "Tanda tangan pengirim",
      type: "text",
      placeholder: "Bima Arya",
      maxLength: 60,
      section: "letter",
    },

    // --- SECTION: FOTO KENANGAN & PESAN RAHASIA ---
    {
      name: "photoUrl",
      label: "Tautan foto kenangan pertama (Film Frame 1)",
      type: "text",
      placeholder:
        "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=1000&q=80",
      maxLength: 1000,
      helperText: "Foto berdua dengan gaya klasik yang akan dibingkai seperti cetakan foto film.",
      section: "memories",
    },
    {
      name: "photoCaption",
      label: "Catatan kecil di bawah foto 1",
      type: "text",
      placeholder: "Momen pertama kali kita berbincang hingga senja berganti bintang.",
      maxLength: 140,
      section: "memories",
    },
    {
      name: "photo2Url",
      label: "Tautan foto kenangan kedua (Film Frame 2)",
      type: "text",
      placeholder:
        "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=1000&q=80",
      maxLength: 1000,
      helperText: "Foto kedua untuk melengkapi galeri film analog di lembaran surat.",
      section: "memories",
    },
    {
      name: "photo2Caption",
      label: "Catatan kecil di bawah foto 2",
      type: "text",
      placeholder: "Tawa lepas di tepi pantai saat kita berjanji untuk saling menjaga.",
      maxLength: 140,
      section: "memories",
    },
    {
      name: "secretNoteTitle",
      label: "Judul catatan rahasia",
      type: "text",
      placeholder: "Bisikan Rahasia untuk Hatimu ✨",
      maxLength: 80,
      section: "memories",
    },
    {
      name: "secretNoteContent",
      label: "Isi catatan rahasia tersembunyi",
      type: "textarea",
      placeholder:
        "Sebuah pesan manis yang hanya akan terbuka saat pasanganmu mengetuk/mengklik kartu rahasia ini...",
      maxLength: 600,
      rows: 4,
      section: "memories",
    },

    // --- SECTION: JANJI CINTA ---
    {
      name: "promisesTitle",
      label: "Judul seksi janji",
      type: "text",
      placeholder: "Tiga Janji Setia untuk Hari Esok",
      maxLength: 80,
      section: "promises",
    },
    {
      name: "promise1",
      label: "Janji 1",
      type: "text",
      placeholder: "Selalu mendengarkan ceritamu dengan penuh ketulusan di setiap hari lelahmu.",
      maxLength: 160,
      section: "promises",
    },
    {
      name: "promise2",
      label: "Janji 2",
      type: "text",
      placeholder: "Menjadi tempat pulang yang paling aman dan menghangatkan hatimu.",
      maxLength: 160,
      section: "promises",
    },
    {
      name: "promise3",
      label: "Janji 3",
      type: "text",
      placeholder: "Terus memilihmu dan mencintaimu dalam setiap babak perjalanan kita.",
      maxLength: 160,
      section: "promises",
    },

    // --- SECTION: TEMA & MUSIK ---
    {
      name: "primaryColor",
      label: "Warna segel lilin & ornamen aksen",
      type: "color",
      defaultValue: "#781d2f",
      helperText: "Warna stempel segel lilin 3D, cap pos retro, dan garis hiasan klasik.",
      colorPresets: VINTAGE_LOVE_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "backgroundColor",
      label: "Warna latar belakang halaman",
      type: "color",
      defaultValue: "#f6f1ea",
      helperText: "Warna kanvas di luar lembaran amplop.",
      colorPresets: BACKGROUND_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "cardColor",
      label: "Warna kertas perkamen",
      type: "color",
      defaultValue: "#fffdf9",
      helperText: "Warna lembaran kertas surat klasik.",
      colorPresets: CARD_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "textColor",
      label: "Warna teks judul & cap",
      type: "color",
      defaultValue: "#3e1b24",
      helperText: "Warna judul dan salam pembuka.",
      colorPresets: TEXT_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "bodyTextColor",
      label: "Warna teks isi surat",
      type: "color",
      defaultValue: "#4a3b32",
      helperText: "Warna paragraf tulisan surat perkamen.",
      colorPresets: TEXT_COLOR_PRESETS,
      section: "theme",
    },
    {
      name: "musicTitle",
      label: "Judul audio pengiring (opsional)",
      type: "text",
      placeholder: "Romantic Music Box & Cello",
      maxLength: 80,
      section: "theme",
    },
    {
      name: "bgMusicUrl",
      label: "Tautan audio pengiring (.mp3)",
      type: "text",
      placeholder: "https://cdn.pixabay.com/download/audio/2022/05/16/audio_c0c1b72e04.mp3",
      maxLength: 1000,
      helperText: "Tautan langsung ke file audio mp3 romantis klasik.",
      section: "theme",
    },
  ],
  sample: {
    recipientName: "Adinda Kirana",
    senderName: "Bima Arya",
    postmarkCity: "Bandung, Jawa Barat",
    postmarkDate: "21 September 2024",
    sealInitials: "B & A",
    stampPhotoUrl:
      "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=400&q=80",
    loveAnniversary: "14 Februari 2022 • Hari Pertama Bertemu",
    title: "Sebuah Warkat Kasih Dari Lubuk Hati",
    salutation: "Kepada Pemilik Senyum yang Selalu Kurindukan,",
    letterLocation: "Ditulis dari sudut kedai kopi kenangan kita",
    message:
      "Dinda,\n\nAda rasa hangat yang selalu merayap ke dadaku setiap kali mengingat caramu tertawa. Di antara miliaran manusia yang berjalan di bumi, bertemu dan berjalan bersamamu adalah kebetulan terindah yang paling kusyukuri dalam hidup.\n\nSurat ini kutulis bukan hanya untuk merayakan hari-hari manis yang telah kita lewati, namun juga sebagai pengingat abadi bahwa di setiap langkah esok, ada sepasang mata yang selalu bangga melihatmu dan hati yang selalu mendoakan bahagiamu.\n\nTerima kasih telah menjadi rumah tempatku pulang, dan pelita di kala malam terasa gelap. Aku mencintaimu lebih dari apa yang sanggup dirangkum oleh kata-kata.",
    closingStatement: "Selamanya mengagumi dan menyayangimu,",
    signature: "Bima Arya",
    photoUrl:
      "https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=1000&q=80",
    photoCaption: "Kenangan senja saat kita berjanji untuk saling menjaga selamanya.",
    photo2Url:
      "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=1000&q=80",
    photo2Caption: "Tawa lepas di tepi pantai saat kita menyusuri ombak berdua.",
    secretNoteTitle: "Bisikan Rahasia untuk Hatimu ✨",
    secretNoteContent:
      "Jika suatu saat dunia terasa terlalu bising dan melelahkan, ingatlah bahwa kamu tidak pernah sendirian. Genggam tanganku, dan kita akan lalui semuanya bersama-sama.",
    promisesTitle: "Tiga Janji Setia untuk Hari Esok",
    promise1: "Selalu mendengarkan ceritamu dengan penuh ketulusan di setiap hari lelahmu.",
    promise2: "Menjadi tempat pulang yang paling aman dan menghangatkan hatimu.",
    promise3: "Terus memilihmu dan mencintaimu dalam setiap babak perjalanan kita.",
    primaryColor: "#781d2f",
    backgroundColor: "#f6f1ea",
    cardColor: "#fffdf9",
    textColor: "#3e1b24",
    bodyTextColor: "#4a3b32",
    musicTitle: "Romantic Music Box & Cello",
    bgMusicUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
  },
};
